[RRepo](tausackhn)twlived
Success: no issues found in 10 source files

[RRepo](OpenWeavers)openanalysis
Success: no issues found in 9 source files

[RRepo](klingtnet)klingt.net
Success: no issues found in 1 source file

[RRepo](deeppunster)RegEx101
Success: no issues found in 1 source file

[RRepo](lamenezes)simple-model
(lamenezes)simple-model/setup.py:17: error: Need type annotation for 'user_options' (hint: "user_options: List[<type>] = ...")  [var-annotated]
(lamenezes)simple-model/tests/test_builder.py:6: error: Module 'simple_model' has no attribute 'Model'  [attr-defined]
(lamenezes)simple-model/tests/test_builder.py:6: error: Module 'simple_model' has no attribute 'to_dict'  [attr-defined]
(lamenezes)simple-model/tests/test_converters.py:5: error: Module 'simple_model' has no attribute 'Model'  [attr-defined]
(lamenezes)simple-model/tests/test_converters.py:5: error: Module 'simple_model' has no attribute 'to_dict'  [attr-defined]
Found 5 errors in 3 files (checked 14 source files)

[RRepo](joereynolds)Mr-Figs
(joereynolds)Mr-Figs/src/save.py:9: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(joereynolds)Mr-Figs/src/save.py:20: error: Method must have at least one argument  [misc]
Found 2 errors in 1 file (checked 34 source files)

[RRepo](janelia-flyem)gala
(janelia-flyem)gala/gala/test_package.py:147: error: inconsistent use of tabs and spaces in indentation  [syntax]
Found 1 error in 1 file (checked 23 source files)

[RRepo](davidenunes)tensorx
(davidenunes)tensorx/tensorx/callbacks.py:19: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(davidenunes)tensorx/tensorx/callbacks.py:371: error: Incompatible types in assignment (expression has type "Iterator[Any]", variable has type "List[Any]")  [assignment]

[RRepo](thomasperrot)MTGTrader
(thomasperrot)MTGTrader/mtg/stats/tests/test_crawl_mkm.py:1: error: Relative import climbs too many namespaces  [misc]
(thomasperrot)MTGTrader/mtg/config/celery.py:11: error: Module 'celery' has no attribute 'Celery'  [attr-defined]
(thomasperrot)MTGTrader/mtg/config/celery.py:11: error: Module 'celery' has no attribute 'shared_task'  [attr-defined]
(thomasperrot)MTGTrader/mtg/tournaments/serializers.py:53: error: Need type annotation for 'card_types' (hint: "card_types: Set[<type>] = ...")  [var-annotated]
(thomasperrot)MTGTrader/mtg/tournaments/tests/test_crawl_tournaments.py:8: error: Relative import climbs too many namespaces  [misc]
(thomasperrot)MTGTrader/mtg/tournaments/models.py:82: error: Need type annotation for 'played_cards'  [var-annotated]
(thomasperrot)MTGTrader/mtg/stats/utils.py:52: error: Need type annotation for 'card_id_to_usages'  [var-annotated]
(thomasperrot)MTGTrader/mtg/stats/utils.py:134: error: Incompatible return value type (got "List[float]", expected "float")  [return-value]
(thomasperrot)MTGTrader/mtg/tournaments/tasks.py:17: error: Module 'celery' has no attribute 'group'  [attr-defined]
(thomasperrot)MTGTrader/mtg/tournaments/tasks.py:104: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(thomasperrot)MTGTrader/mtg/tournaments/tasks.py:140: error: Item "None" of "Optional[Match[str]]" has no attribute "groupdict"  [union-attr]
Found 11 errors in 7 files (checked 9 source files)

[RRepo](domino14)Webolith
(domino14)Webolith/scripts/digoceanssh.py:26: error: Missing parentheses in call to 'print'. Did you mean print("************")?  [syntax]
Found 1 error in 1 file (checked 51 source files)

[RRepo](mRokita)DPLib
(mRokita)DPLib/examples/message_on_elim.py:23: error: Need type annotation for 'spawnkills' (hint: "spawnkills: Dict[<type>, <type>] = ...")  [var-annotated]
(mRokita)DPLib/examples/message_on_elim.py:24: error: Need type annotation for 'spawnkill_last_times' (hint: "spawnkill_last_times: Dict[<type>, <type>] = ...")  [var-annotated]
(mRokita)DPLib/examples/spawnkill_kick.py:23: error: Need type annotation for 'spawnkills' (hint: "spawnkills: Dict[<type>, <type>] = ...")  [var-annotated]
(mRokita)DPLib/examples/spawnkill_kick.py:24: error: Need type annotation for 'spawnkill_last_times' (hint: "spawnkill_last_times: Dict[<type>, <type>] = ...")  [var-annotated]
(mRokita)DPLib/examples/server_manager.py:89: error: Missing return statement  [return]
(mRokita)DPLib/examples/server_manager.py:94: error: Return value expected  [return-value]
(mRokita)DPLib/examples/server_manager.py:96: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
Found 7 errors in 3 files (checked 9 source files)

[RRepo](HPAC)matchpy
(HPAC)matchpy/matchpy/matching/_common.py:7: error: Relative import climbs too many namespaces  [misc]
(HPAC)matchpy/matchpy/matching/_common.py:8: error: Relative import climbs too many namespaces  [misc]
(HPAC)matchpy/matchpy/matching/_common.py:9: error: Relative import climbs too many namespaces  [misc]
(HPAC)matchpy/matchpy/matching/_common.py:98: error: Need type annotation for 'sequence_variable_infos' (hint: "sequence_variable_infos: Dict[<type>, <type>] = ...")  [var-annotated]
(HPAC)matchpy/matchpy/matching/_common.py:100: error: Need type annotation for 'fixed_variable_infos' (hint: "fixed_variable_infos: Dict[<type>, <type>] = ...")  [var-annotated]
(HPAC)matchpy/matchpy/expressions/functions.py:165: error: Name '_' already defined on line 151  [no-redef]
(HPAC)matchpy/matchpy/functions.py:79: error: Need type annotation for 'new_operands' (hint: "new_operands: List[<type>] = ...")  [var-annotated]
(HPAC)matchpy/matchpy/functions.py:214: error: Incompatible default for argument "max_count" (default has type "float", argument has type "int")  [assignment]
(HPAC)matchpy/docs/conf.py:65: error: Module has no attribute "__version__"  [attr-defined]
(HPAC)matchpy/docs/conf.py:245: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]

[RRepo](cjlucas)rtorrent-python
(cjlucas)rtorrent-python/rtorrent/rpc/result.py:6: error: Bracketed expression "[...]" is not valid as a type  [misc]
(cjlucas)rtorrent-python/rtorrent/rpc/result.py:6: note: Did you mean "List[...]"?
(cjlucas)rtorrent-python/rtorrent/rpc/__init__.py:7: error: Need type annotation for '_rpc_methods' (hint: "_rpc_methods: Dict[<type>, <type>] = ...")  [var-annotated]
(cjlucas)rtorrent-python/rtorrent/rpc/__init__.py:46: error: Need type annotation for 'keys' (hint: "keys: List[<type>] = ...")  [var-annotated]
(cjlucas)rtorrent-python/rtorrent/rpc/__init__.py:47: error: Need type annotation for 'args' (hint: "args: List[<type>] = ...")  [var-annotated]
(cjlucas)rtorrent-python/rtorrent/file.py:24: error: Incompatible types in assignment (expression has type "Type[FileMetadata]", base class "BaseMulticallBuilder" defined the type as "None")  [assignment]
(cjlucas)rtorrent-python/rtorrent/file.py:25: error: Incompatible types in assignment (expression has type "Type[File]", base class "BaseMulticallBuilder" defined the type as "None")  [assignment]
(cjlucas)rtorrent-python/rtorrent/file.py:26: error: Incompatible types in assignment (expression has type "str", base class "BaseMulticallBuilder" defined the type as "None")  [assignment]
(cjlucas)rtorrent-python/rtorrent/tracker.py:25: error: Incompatible types in assignment (expression has type "Type[TrackerMetadata]", base class "BaseMulticallBuilder" defined the type as "None")  [assignment]
(cjlucas)rtorrent-python/rtorrent/tracker.py:26: error: Incompatible types in assignment (expression has type "Type[Tracker]", base class "BaseMulticallBuilder" defined the type as "None")  [assignment]
(cjlucas)rtorrent-python/rtorrent/tracker.py:27: error: Incompatible types in assignment (expression has type "str", base class "BaseMulticallBuilder" defined the type as "None")  [assignment]
(cjlucas)rtorrent-python/rtorrent/torrent.py:50: error: Incompatible types in assignment (expression has type "Type[TorrentMetadata]", base class "BaseMulticallBuilder" defined the type as "None")  [assignment]
(cjlucas)rtorrent-python/rtorrent/torrent.py:51: error: Incompatible types in assignment (expression has type "Type[Torrent]", base class "BaseMulticallBuilder" defined the type as "None")  [assignment]
(cjlucas)rtorrent-python/rtorrent/torrent.py:52: error: Incompatible types in assignment (expression has type "str", base class "BaseMulticallBuilder" defined the type as "None")  [assignment]
(cjlucas)rtorrent-python/rtorrent/__init__.py:24: error: Bracketed expression "[...]" is not valid as a type  [misc]
(cjlucas)rtorrent-python/rtorrent/__init__.py:24: note: Did you mean "List[...]"?
Found 14 errors in 6 files (checked 13 source files)

[RRepo](Chadsr)NordVPN-NetworkManager
(Chadsr)NordVPN-NetworkManager/setup.py:3: error: Module 'nordnm' has no attribute '__version__'  [attr-defined]
(Chadsr)NordVPN-NetworkManager/setup.py:3: error: Module 'nordnm' has no attribute '__license__'  [attr-defined]
(Chadsr)NordVPN-NetworkManager/nordnm/benchmarking.py:1: error: Module 'nordnm' has no attribute 'nordnm'  [attr-defined]
(Chadsr)NordVPN-NetworkManager/nordnm/networkmanager.py:2: error: Module 'nordnm' has no attribute 'paths'  [attr-defined]
(Chadsr)NordVPN-NetworkManager/nordnm/__main__.py:3: error: Module 'nordnm' has no attribute 'nordnm'  [attr-defined]
Found 5 errors in 4 files (checked 8 source files)

[RRepo](gopythongo)gopythongo
(gopythongo)gopythongo/src/py/gopythongo/builders/__init__.py:174: error: Argument 1 to "test_gopythongo" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(gopythongo)gopythongo/src/py/gopythongo/stores/aptly.py:26: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(gopythongo)gopythongo/src/py/gopythongo/utils/__init__.py:35: error: Incompatible types in assignment (expression has type "None", variable has type "List[str]")  [assignment]
(gopythongo)gopythongo/src/py/gopythongo/versioners/parsers/regexparser.py:62: error: Item "None" of "Optional[Match[Any]]" has no attribute "groupdict"  [union-attr]
(gopythongo)gopythongo/src/py/gopythongo/versioners/parsers/semverparser.py:76: error: Item "None" of "Optional[Match[Any]]" has no attribute "group"  [union-attr]
(gopythongo)gopythongo/src/py/gopythongo/versioners/parsers/semverparser.py:95: error: Item "None" of "Optional[Match[Any]]" has no attribute "group"  [union-attr]
(gopythongo)gopythongo/src/py/gopythongo/versioners/parsers/semverparser.py:97: error: Item "None" of "Optional[Match[Any]]" has no attribute "group"  [union-attr]
(gopythongo)gopythongo/src/py/gopythongo/versioners/bumpversion.py:22: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(gopythongo)gopythongo/src/py/gopythongo/utils/debversion.py:132: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")  [assignment]
(gopythongo)gopythongo/src/py/gopythongo/utils/debversion.py:134: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")  [assignment]
(gopythongo)gopythongo/src/py/gopythongo/utils/debversion.py:135: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(gopythongo)gopythongo/src/py/gopythongo/utils/debversion.py:136: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(gopythongo)gopythongo/src/py/gopythongo/utils/debversion.py:142: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(gopythongo)gopythongo/src/py/gopythongo/utils/buildcontext.py:68: error: Incompatible types in assignment (expression has type "None", variable has type "Dict[str, Any]")  [assignment]
(gopythongo)gopythongo/src/py/gopythongo/utils/buildcontext.py:69: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(gopythongo)gopythongo/src/py/gopythongo/utils/buildcontext.py:70: error: Incompatible types in assignment (expression has type "None", variable has type "List[str]")  [assignment]
(gopythongo)gopythongo/src/py/gopythongo/versioners/parsers/pep440parser.py:78: error: Argument 1 to "_adapt" has incompatible type "Union[LegacyVersion, Version]"; expected "Version"  [arg-type]
(gopythongo)gopythongo/src/py/gopythongo/utils/template.py:75: error: Item "None" of "Optional[Match[str]]" has no attribute "start"  [union-attr]
(gopythongo)gopythongo/src/py/gopythongo/utils/template.py:76: error: Item "None" of "Optional[Match[str]]" has no attribute "start"  [union-attr]
(gopythongo)gopythongo/src/py/gopythongo/utils/template.py:95: error: Incompatible return value type (got "None", expected "ProcessedStringWithTemplates")  [return-value]
Found 20 errors in 10 files (checked 33 source files)

[RRepo](vmagamedov)grpclib
(vmagamedov)grpclib/docs/conf.py:21: error: Need type annotation for 'templates_path' (hint: "templates_path: List[<type>] = ...")  [var-annotated]
(vmagamedov)grpclib/grpclib/encoding/proto.py:7: error: Relative import climbs too many namespaces  [misc]
(vmagamedov)grpclib/grpclib/compat.py:23: error: Module 'contextlib' has no attribute 'nullcontext'  [attr-defined]
(vmagamedov)grpclib/grpclib/health/service.py:6: error: Relative import climbs too many namespaces  [misc]
(vmagamedov)grpclib/grpclib/health/service.py:7: error: Relative import climbs too many namespaces  [misc]
(vmagamedov)grpclib/grpclib/health/service.py:8: error: Relative import climbs too many namespaces  [misc]
(vmagamedov)grpclib/grpclib/health/service.py:16: error: Relative import climbs too many namespaces  [misc]
(vmagamedov)grpclib/grpclib/health/check.py:8: error: Relative import climbs too many namespaces  [misc]
(vmagamedov)grpclib/grpclib/health/check.py:9: error: Relative import climbs too many namespaces  [misc]
Found 9 errors in 5 files (checked 39 source files)

[RRepo](jacobbridges)veggiecron-server
(jacobbridges)veggiecron-server/src/scheduler/job_runners/_base.py:10: error: Relative import climbs too many namespaces  [misc]
(jacobbridges)veggiecron-server/src/scheduler/parser.py:9: error: Relative import climbs too many namespaces  [misc]
(jacobbridges)veggiecron-server/src/scheduler/parser.py:72: error: Unsupported operand types for + ("float" and "timedelta")  [operator]
(jacobbridges)veggiecron-server/src/scheduler/parser.py:72: error: Unsupported operand type for unary + ("Optional[int]")  [operator]
(jacobbridges)veggiecron-server/src/scheduler/parser.py:80: error: Unsupported operand types for + ("float" and "timedelta")  [operator]
(jacobbridges)veggiecron-server/src/scheduler/parser.py:80: error: Unsupported operand type for unary + ("Optional[int]")  [operator]
(jacobbridges)veggiecron-server/src/scheduler/parser.py:83: error: Unsupported operand types for + ("float" and "timedelta")  [operator]
(jacobbridges)veggiecron-server/src/scheduler/parser.py:83: error: Unsupported operand type for unary + ("Optional[int]")  [operator]
(jacobbridges)veggiecron-server/src/scheduler/parser.py:86: error: Unsupported operand types for + ("float" and "timedelta")  [operator]
(jacobbridges)veggiecron-server/src/scheduler/parser.py:86: error: Unsupported operand type for unary + ("Optional[int]")  [operator]
(jacobbridges)veggiecron-server/src/database/connection.py:15: error: Relative import climbs too many namespaces  [misc]
(jacobbridges)veggiecron-server/src/scheduler/job_runners/http.py:14: error: Relative import climbs too many namespaces  [misc]
(jacobbridges)veggiecron-server/src/scheduler/job_runners/http.py:15: error: Relative import climbs too many namespaces  [misc]
(jacobbridges)veggiecron-server/src/scheduler/job_scheduler.py:16: error: Relative import climbs too many namespaces  [misc]
(jacobbridges)veggiecron-server/src/scheduler/job_scheduler.py:17: error: Relative import climbs too many namespaces  [misc]
(jacobbridges)veggiecron-server/src/routes/register.py:12: error: Relative import climbs too many namespaces  [misc]
(jacobbridges)veggiecron-server/src/server.py:61: error: Argument 1 to "__init__" of "Application" has incompatible type "List[Tuple[str, Any]]"; expected "Optional[List[Union[Rule, List[Any], Tuple[Union[str, Matcher], Any], Tuple[Union[str, Matcher], Any, Dict[str, Any]], Tuple[Union[str, Matcher], Any, Dict[str, Any], str]]]]"  [arg-type]
(jacobbridges)veggiecron-server/src/server.py:61: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
(jacobbridges)veggiecron-server/src/server.py:61: note: Consider using "Sequence" instead, which is covariant
(jacobbridges)veggiecron-server/src/server.py:68: error: Need type annotation for 'work_queue'  [var-annotated]
Found 18 errors in 7 files (checked 12 source files)

[RRepo](jvermeir)kata

[RRepo](jamespeterschinner)async_v20
(jamespeterschinner)async_v20/async_v20/definitions/health_types.py:12: error: Unexpected keyword argument "contains" for "__init_subclass__" of "object"  [call-arg]
/usr/local/lib/python3.6/dist-packages/mypy/typeshed/stdlib/2and3/builtins.pyi:69: note: "__init_subclass__" of "object" defined here
(jamespeterschinner)async_v20/async_v20/definitions/health_types.py:24: error: Unexpected keyword argument "contains" for "__init_subclass__" of "object"  [call-arg]
/usr/local/lib/python3.6/dist-packages/mypy/typeshed/stdlib/2and3/builtins.pyi:69: note: "__init_subclass__" of "object" defined here
(jamespeterschinner)async_v20/async_v20/definitions/health_types.py:36: error: Unexpected keyword argument "contains" for "__init_subclass__" of "object"  [call-arg]
/usr/local/lib/python3.6/dist-packages/mypy/typeshed/stdlib/2and3/builtins.pyi:69: note: "__init_subclass__" of "object" defined here
(jamespeterschinner)async_v20/async_v20/definitions/health_types.py:49: error: Unexpected keyword argument "contains" for "__init_subclass__" of "object"  [call-arg]
/usr/local/lib/python3.6/dist-packages/mypy/typeshed/stdlib/2and3/builtins.pyi:69: note: "__init_subclass__" of "object" defined here
(jamespeterschinner)async_v20/async_v20/definitions/health_types.py:60: error: Unexpected keyword argument "contains" for "__init_subclass__" of "object"  [call-arg]
/usr/local/lib/python3.6/dist-packages/mypy/typeshed/stdlib/2and3/builtins.pyi:69: note: "__init_subclass__" of "object" defined here

[RRepo](kenkov)kovot
(kenkov)kovot/kovot/stream/mastodon.py:5: error: Module 'mastodon' has no attribute 'StreamListener'  [attr-defined]
(kenkov)kovot/kovot/stream/mastodon.py:5: error: Module 'mastodon' has no attribute 'MastodonError'; maybe "Mastodon"?  [attr-defined]
(kenkov)kovot/kovot/stream/mastodon.py:8: error: Module 'kovot' has no attribute 'Message'  [attr-defined]
(kenkov)kovot/kovot/stream/mastodon.py:8: error: Module 'kovot' has no attribute 'Response'  [attr-defined]
(kenkov)kovot/kovot/stream/mastodon.py:8: error: Module 'kovot' has no attribute 'Speaker'  [attr-defined]
(kenkov)kovot/kovot/stream/mastodon.py:39: error: Too few arguments for "Mastodon"  [call-arg]
(kenkov)kovot/kovot/stream/mastodon.py:40: error: Argument 1 to "Mastodon" has incompatible type "str"; expected "Logger"  [arg-type]
(kenkov)kovot/kovot/stream/mastodon.py:45: error: "Mastodon" has no attribute "account_verify_credentials"  [attr-defined]
(kenkov)kovot/kovot/stream/mastodon.py:47: error: Need type annotation for '_cached' (hint: "_cached: Dict[<type>, <type>] = ...")  [var-annotated]
(kenkov)kovot/kovot/stream/mastodon.py:51: error: "Mastodon" has no attribute "stream_user"  [attr-defined]
(kenkov)kovot/kovot/stream/mastodon.py:69: error: "Mastodon" has no attribute "status_post"  [attr-defined]
(kenkov)kovot/kovot/stream/mastodon.py:71: error: "Mastodon" has no attribute "status_post"  [attr-defined]
(kenkov)kovot/kovot/stream/mastodon.py:97: error: Argument 2 of "handle_starttag" is incompatible with supertype "HTMLParser"; supertype defines the argument type as "List[Tuple[str, Optional[str]]]"  [override]
(kenkov)kovot/kovot/stream/twitter.py:28: error: Bracketed expression "[...]" is not valid as a type  [misc]
(kenkov)kovot/kovot/stream/twitter.py:28: note: Did you mean "List[...]"?
(kenkov)kovot/kovot/stream/twitter.py:74: error: Missing return statement  [return]
(kenkov)kovot/kovot/stream/stdio.py:19: error: Missing return statement  [return]
(kenkov)kovot/test/test_bot.py:6: error: Module 'kovot' has no attribute 'Bot'  [attr-defined]
(kenkov)kovot/test/test_bot.py:7: error: Module 'kovot' has no attribute 'Response'  [attr-defined]
(kenkov)kovot/test/test_bot.py:8: error: Module 'kovot' has no attribute 'Message'  [attr-defined]
(kenkov)kovot/test/test_bot.py:9: error: Module 'kovot' has no attribute 'Speaker'  [attr-defined]

[RRepo](vrk-kpa)X-Road
(vrk-kpa)X-Road/src/systemtest/op-monitoring/zabbix_api/examples/zabbix/import_sample_host.py:117: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 14 source files)

[RRepo](shafferm)SCNIC
(shafferm)SCNIC/SCNIC/between_correls.py:23: error: Name 'spearmanr' already defined (possibly by an import)  [no-redef]
(shafferm)SCNIC/SCNIC/correlation_analysis.py:26: error: Name 'spearmanr' already defined (possibly by an import)  [no-redef]
Found 2 errors in 2 files (checked 20 source files)

[RRepo](FRC-1123)frc2017-1123
Success: no issues found in 31 source files

[RRepo](monarch-initiative)dipper
(monarch-initiative)dipper/dipper/sources/PostgreSQLSource.py:14: error: Need type annotation for 'files' (hint: "files: Dict[<type>, <type>] = ...")  [var-annotated]

[RRepo](craws)OpenAtlas
(craws)OpenAtlas/openatlas/views/types.py:31: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/views/types.py:50: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/views/types.py:51: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/views/types.py:67: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/views/types.py:82: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/views/types.py:114: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/views/types.py:135: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/__init__.py:39: error: Module 'openatlas.util' has no attribute 'filters'  [attr-defined]
(craws)OpenAtlas/openatlas/__init__.py:40: error: Module 'openatlas.views' has no attribute 'admin'  [attr-defined]
(craws)OpenAtlas/openatlas/__init__.py:40: error: Module 'openatlas.views' has no attribute 'ajax'  [attr-defined]
(craws)OpenAtlas/openatlas/__init__.py:40: error: Module 'openatlas.views' has no attribute 'involvement'  [attr-defined]
(craws)OpenAtlas/openatlas/__init__.py:40: error: Module 'openatlas.views' has no attribute 'login'  [attr-defined]
(craws)OpenAtlas/openatlas/views/types.py:31: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/views/types.py:50: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/views/types.py:51: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/views/types.py:67: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/views/types.py:82: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/views/types.py:114: error: Cannot determine type of 'app'  [has-type]
(craws)OpenAtlas/openatlas/views/types.py:135: error: Cannot determine type of 'app'  [has-type]
Found 19 errors in 2 files (checked 36 source files)

[RRepo](novioleo)crnn.mxnet
(novioleo)crnn.mxnet/generate_data/simple_generate_scene_text.py:69: error: Name 'label_file_path' is not defined  [name-defined]
(novioleo)crnn.mxnet/generate_data/simple_generate_scene_text.py:70: error: Name 'label_file_path' is not defined  [name-defined]
(novioleo)crnn.mxnet/generate_data/simple_generate_scene_text.py:71: error: Name 'label_file_path' is not defined  [name-defined]
(novioleo)crnn.mxnet/generate_data/simple_generate_scene_text.py:131: error: Name 'label_file_path' is not defined  [name-defined]
(novioleo)crnn.mxnet/generate_data/simple_generate_scene_text.py:146: error: Name 'label_file_path' is not defined  [name-defined]
(novioleo)crnn.mxnet/generate_data/simple_generate_scene_text.py:147: error: Name 'label_file_path' is not defined  [name-defined]
Found 6 errors in 1 file (checked 6 source files)

[RRepo](getsentry)zeus
(getsentry)zeus/tests/zeus/api/resources/test_job_artifacts.py:4: error: Module 'zeus.models' has no attribute 'Artifact'  [attr-defined]
(getsentry)zeus/tests/zeus/api/resources/test_build_details.py:1: error: Module 'zeus.models' has no attribute 'ItemStat'  [attr-defined]
(getsentry)zeus/tests/zeus/api/resources/test_repository_hooks.py:1: error: Module 'zeus.models' has no attribute 'Hook'  [attr-defined]
(getsentry)zeus/tests/zeus/api/resources/test_change_request_details.py:1: error: Module 'zeus.models' has no attribute 'ChangeRequest'  [attr-defined]
(getsentry)zeus/tests/zeus/api/resources/test_repository_details.py:1: error: Module 'zeus.models' has no attribute 'Repository'  [attr-defined]
(getsentry)zeus/tests/zeus/api/resources/test_hook_details.py:1: error: Module 'zeus.models' has no attribute 'Hook'  [attr-defined]
(getsentry)zeus/tests/zeus/api/resources/test_repository_change_requests.py:1: error: Module 'zeus.models' has no attribute 'ChangeRequest'  [attr-defined]
(getsentry)zeus/tests/zeus/models/test_artifact.py:1: error: Module 'zeus.models' has no attribute 'Artifact'  [attr-defined]
(getsentry)zeus/zeus/api/resources/repository_test_details.py:3: error: Module 'zeus.models' has no attribute 'Job'  [attr-defined]
(getsentry)zeus/zeus/api/resources/repository_test_details.py:3: error: Module 'zeus.models' has no attribute 'Repository'  [attr-defined]
(getsentry)zeus/zeus/api/resources/repository_test_details.py:3: error: Module 'zeus.models' has no attribute 'TestCase'  [attr-defined]
(getsentry)zeus/zeus/api/resources/repository_test_details.py:6: error: Relative import climbs too many namespaces  [misc]
(getsentry)zeus/zeus/api/resources/build_source.py:2: error: Module 'zeus.models' has no attribute 'Build'  [attr-defined]
(getsentry)zeus/zeus/api/resources/build_source.py:2: error: Module 'zeus.models' has no attribute 'Source'  [attr-defined]
(getsentry)zeus/zeus/api/resources/build_source.py:5: error: Relative import climbs too many namespaces  [misc]
(getsentry)zeus/zeus/api/resources/test_details.py:3: error: Module 'zeus.models' has no attribute 'TestCase'  [attr-defined]
(getsentry)zeus/zeus/api/resources/test_details.py:6: error: Relative import climbs too many namespaces  [misc]
(getsentry)zeus/zeus/api/resources/revision_source.py:2: error: Module 'zeus.models' has no attribute 'Source'  [attr-defined]
(getsentry)zeus/zeus/api/resources/revision_source.py:2: error: Module 'zeus.models' has no attribute 'Revision'  [attr-defined]
(getsentry)zeus/zeus/api/resources/revision_source.py:5: error: Relative import climbs too many namespaces  [misc]
(getsentry)zeus/zeus/utils/celery.py:66: error: Name 'json.JSONEncoder' is not defined  [name-defined]
(getsentry)zeus/zeus/exceptions.py:47: error: Missing return statement  [return]

[RRepo](openfisca)openfisca-survey-manager
(openfisca)openfisca-survey-manager/openfisca_survey_manager/scripts/build_collection.py:159: error: Too few arguments for "check_template_config_files"  [call-arg]
(openfisca)openfisca-survey-manager/openfisca_survey_manager/survey_collections.py:27: error: Need type annotation for 'surveys' (hint: "surveys: List[<type>] = ...")  [var-annotated]
(openfisca)openfisca-survey-manager/openfisca_survey_manager/calibration.py:24: error: Need type annotation for 'margins_by_variable' (hint: "margins_by_variable: Dict[<type>, <type>] = ...")  [var-annotated]
(openfisca)openfisca-survey-manager/openfisca_survey_manager/surveys.py:35: error: Need type annotation for 'informations' (hint: "informations: Dict[<type>, <type>] = ...")  [var-annotated]
(openfisca)openfisca-survey-manager/openfisca_survey_manager/surveys.py:38: error: Need type annotation for 'tables'  [var-annotated]
(openfisca)openfisca-survey-manager/openfisca_survey_manager/surveys.py:39: error: Need type annotation for 'tables_index' (hint: "tables_index: Dict[<type>, <type>] = ...")  [var-annotated]
Found 6 errors in 4 files (checked 29 source files)

[RRepo](FAForever)client
(FAForever)client/src/chat/channel_autojoiner.py:13: error: Value expression in dictionary comprehension has incompatible type "str"; expected type "List[str]"  [misc]
(FAForever)client/tests/fa/test_updater.py:3: error: Module 'fa' has no attribute 'updater'  [attr-defined]
(FAForever)client/tests/fa/test_featured.py:3: error: Module 'fa' has no attribute 'updater'  [attr-defined]
(FAForever)client/src/model/ircuser.py:55: error: Name 'player' already defined on line 45  [no-redef]
(FAForever)client/src/model/ircuser.py:55: error: "Callable[[IrcUser], Any]" has no attribute "setter"  [attr-defined]
(FAForever)client/src/model/player.py:122: error: Name 'currentGame' already defined on line 110  [no-redef]
(FAForever)client/src/model/player.py:122: error: "Callable[[Player], Any]" has no attribute "setter"  [attr-defined]
(FAForever)client/src/model/chat/chatter.py:42: error: Name 'player' already defined on line 32  [no-redef]
(FAForever)client/src/model/chat/chatter.py:42: error: "Callable[[Chatter], Any]" has no attribute "setter"  [attr-defined]

[RRepo](brettcannon)gidgethub
Success: no issues found in 3 source files

[RRepo](ibarbech)learnbot
(ibarbech)learnbot/learnbot_dsl/Clients/EBO.py:19: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 19 source files)

[RRepo](mathieui)unha2

[RRepo](Prototype-X)Zabbix-Network-Weathermap
(Prototype-X)Zabbix-Network-Weathermap/mapping.py:15: error: Need type annotation for '_instances' (hint: "_instances: Dict[<type>, <type>] = ...")  [var-annotated]
(Prototype-X)Zabbix-Network-Weathermap/converter.py:18: error: Need type annotation for '_instances' (hint: "_instances: Dict[<type>, <type>] = ...")  [var-annotated]
(Prototype-X)Zabbix-Network-Weathermap/converter.py:230: error: Need type annotation for 'cfg_order'  [var-annotated]
(Prototype-X)Zabbix-Network-Weathermap/converter.py:246: error: "object" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
(Prototype-X)Zabbix-Network-Weathermap/converter.py:257: error: "object" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
(Prototype-X)Zabbix-Network-Weathermap/converter.py:272: error: "object" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
Found 6 errors in 2 files (checked 6 source files)

[RRepo](Digiography)blender_addon_pbr

[RRepo](cliffano)swaggy-jenkins

[RRepo](georgepsarakis)pitch
(georgepsarakis)pitch/pitch/plugins/common.py:34: error: Incompatible types in assignment (expression has type "str", base class "BasePlugin" defined the type as "None")  [assignment]
(georgepsarakis)pitch/pitch/interpreter/command.py:49: error: Incompatible types in assignment (expression has type "str", base class "ControlFlowStatement" defined the type as "None")  [assignment]
(georgepsarakis)pitch/pitch/interpreter/command.py:50: error: Incompatible types in assignment (expression has type "str", base class "ControlFlowStatement" defined the type as "None")  [assignment]
(georgepsarakis)pitch/pitch/interpreter/command.py:80: error: Incompatible types in assignment (expression has type "str", base class "ControlFlowStatement" defined the type as "None")  [assignment]
(georgepsarakis)pitch/pitch/interpreter/command.py:103: error: Incompatible types in assignment (expression has type "str", base class "ControlFlowStatement" defined the type as "None")  [assignment]
(georgepsarakis)pitch/pitch/structures.py:119: error: "str" not callable  [operator]
Found 6 errors in 3 files (checked 14 source files)

[RRepo](rmorshea)spectate
(rmorshea)spectate/docs/source/conf.py:29: error: Module has no attribute "__version__"  [attr-defined]
(rmorshea)spectate/docs/source/conf.py:31: error: Module has no attribute "__version__"  [attr-defined]
(rmorshea)spectate/docs/source/conf.py:76: error: Need type annotation for 'exclude_patterns' (hint: "exclude_patterns: List[<type>] = ...")  [var-annotated]
(rmorshea)spectate/docs/source/conf.py:129: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
(rmorshea)spectate/tests/test_core.py:20: error: Name 'signature' already defined (possibly by an import)  [no-redef]
(rmorshea)spectate/spectate/mvc/events.py:59: error: Need type annotation for 'events' (hint: "events: List[<type>] = ...")  [var-annotated]
(rmorshea)spectate/spectate/mvc/events.py:71: error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "List[Any]")  [assignment]
(rmorshea)spectate/spectate/mvc/events.py:74: error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "List[Any]")  [assignment]
(rmorshea)spectate/spectate/mvc/base.py:24: error: Missing return statement  [return]
(rmorshea)spectate/spectate/mvc/base.py:148: error: Incompatible types in assignment (expression has type "Union[Callable[..., Any], str]", variable has type "None")  [assignment]
(rmorshea)spectate/spectate/mvc/base.py:162: error: Incompatible types in assignment (expression has type "Union[Callable[..., Any], str]", variable has type "None")  [assignment]
Found 11 errors in 4 files (checked 15 source files)

[RRepo](Wintellect)WintellectWebinars
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex07_viewmodels/pypi_vm/viewmodels/packages/package_details_viewmodel.py:17: error: Attribute 'latest_release' already defined on line 14  [no-redef]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex07_viewmodels/pypi_vm/viewmodels/packages/package_details_viewmodel.py:19: error: Item "None" of "Optional[Any]" has no attribute "major_ver"  [union-attr]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex07_viewmodels/pypi_vm/viewmodels/packages/package_details_viewmodel.py:20: error: Item "None" of "Optional[Any]" has no attribute "minor_ver"  [union-attr]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex07_viewmodels/pypi_vm/viewmodels/packages/package_details_viewmodel.py:21: error: Item "None" of "Optional[Any]" has no attribute "build_ver"  [union-attr]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex07_viewmodels/pypi_vm/viewmodels/cms/page_viewmodel.py:24: error: Argument 1 to "get" of "Mapping" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex05_migrations/pypi_org/data/db_session.py:33: error: "None" not callable  [misc]
(Wintellect)WintellectWebinars/2017-04-06 - Pythonic Code Through 5 Examples/tip5_slots/clses.py:11: error: "House" has no attribute "other"  [attr-defined]
(Wintellect)WintellectWebinars/2017-04-06 - Pythonic Code Through 5 Examples/tip5_slots/clses.py:13: error: "House" has no attribute "other"  [attr-defined]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex04_async_web/views/city_api.py:2: error: Module 'services' has no attribute 'weather_service'  [attr-defined]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex04_async_web/views/city_api.py:2: error: Module 'services' has no attribute 'sun_service'  [attr-defined]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex04_async_web/views/city_api.py:2: error: Module 'services' has no attribute 'location_service'  [attr-defined]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex08_docker/services/movie_svc/views/api_views.py:4: error: Module 'data' has no attribute 'db'  [attr-defined]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex08_docker/services/movie_svc/data/db.py:6: error: Need type annotation for '__movie_data' (hint: "__movie_data: Dict[<type>, <type>] = ...")  [var-annotated]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex08_docker/services/movie_svc/data/db.py:7: error: Need type annotation for '__genres'  [var-annotated]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex08_docker/services/movie_svc/data/db.py:8: error: Need type annotation for '__top_movies' (hint: "__top_movies: List[<type>] = ...")  [var-annotated]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex08_docker/services/movie_svc/data/db.py:38: error: Incompatible return value type (got "Optional[Any]", expected "List[Movie]")  [return-value]
(Wintellect)WintellectWebinars/2018-02-22-mongo-python-kennedy/code/bin/data_faker.py:6: error: Module 'data' has no attribute 'mongo_setup'  [attr-defined]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex05_migrations/pypi_org/bin/load_data.py:41: error: Need type annotation for 'imported' (hint: "imported: Set[<type>] = ...")  [var-annotated]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex05_migrations/pypi_org/bin/load_data.py:46: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex05_migrations/pypi_org/bin/load_data.py:76: error: Need type annotation for 'imported' (hint: "imported: Set[<type>] = ...")  [var-annotated]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex05_migrations/pypi_org/bin/load_data.py:81: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex05_migrations/pypi_org/bin/load_data.py:89: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex05_migrations/pypi_org/bin/load_data.py:181: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex05_migrations/pypi_org/bin/load_data.py:182: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex05_migrations/pypi_org/bin/load_data.py:195: error: Need type annotation for 'data' (hint: "data: Dict[<type>, <type>] = ...")  [var-annotated]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex05_migrations/pypi_org/bin/load_data.py:203: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")  [assignment]
(Wintellect)WintellectWebinars/2017-04-20-python-for-dotnet-kennedy/wintellect_demo/wintellect_demo/infrastructure/static_cache.py:22: error: Need type annotation for '__hash_lookup' (hint: "__hash_lookup: Dict[<type>, <type>] = ...")  [var-annotated]

[RRepo](arcyfelix)Courses
(arcyfelix)Courses/17-06-05-Machine-Learning-For-Trading/10_row_and_column_slicing.py:39: error: Slice index must be an integer or None  [misc]
(arcyfelix)Courses/17-06-05-Machine-Learning-For-Trading/10_row_and_column_slicing.py:47: error: Slice index must be an integer or None  [misc]
Found 2 errors in 1 file (checked 59 source files)

[RRepo](dmtucker)backlog
Success: no issues found in 9 source files

[RRepo](yasushi-saito)go-netdicom
Success: no issues found in 2 source files

[RRepo](scienceopen)lowtran
(scienceopen)lowtran/Wavelength2LowtranWavenumber.py:5: error: Module 'lowtran' has no attribute 'nm2lt7'  [attr-defined]
Found 1 error in 1 file (checked 15 source files)

[RRepo](lablup)sorna-common
(lablup)sorna-common/src/ai/backend/common/logging.py:20: error: Name 'logging.Handler' is not defined  [name-defined]
(lablup)sorna-common/src/ai/backend/common/logging.py:126: error: Name 'logging.LoggerAdapter' is not defined  [name-defined]
(lablup)sorna-common/src/ai/backend/common/identity.py:21: error: Module has no attribute "getLogger"; maybe "Logger"?  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/identity.py:24: error: Missing return statement  [return]
(lablup)sorna-common/src/ai/backend/common/identity.py:73: error: Incompatible return value type (got "None", expected "str")  [return-value]
(lablup)sorna-common/src/ai/backend/common/etcd.py:26: error: Module has no attribute "getLogger"; maybe "Logger"?  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/argparse.py:17: error: Incompatible types in assignment (expression has type "None", variable has type "local")  [assignment]
(lablup)sorna-common/src/ai/backend/common/argparse.py:27: error: Module has no attribute "ArgumentTypeError"  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/argparse.py:36: error: Module has no attribute "ArgumentTypeError"  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/argparse.py:39: error: Module has no attribute "ArgumentTypeError"  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/argparse.py:42: error: Module has no attribute "ArgumentTypeError"  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/argparse.py:45: error: Module has no attribute "ArgumentTypeError"  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/argparse.py:48: error: Module has no attribute "ArgumentTypeError"  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/argparse.py:49: error: Incompatible return value type (got "Tuple[int, ...]", expected "Tuple[int, int]")  [return-value]
(lablup)sorna-common/src/ai/backend/common/argparse.py:58: error: Module has no attribute "ArgumentTypeError"  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/argparse.py:68: error: Module has no attribute "ArgumentTypeError"  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/argparse.py:117: error: Module has no attribute "ArgumentTypeError"  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/argparse.py:132: error: Module has no attribute "ArgumentTypeError"  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/argparse.py:141: error: Module has no attribute "ArgumentTypeError"  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/argparse.py:151: error: Module has no attribute "ArgumentTypeError"  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/plugin.py:10: error: Module has no attribute "getLogger"; maybe "Logger"?  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/etcd_beta.py:20: error: Module has no attribute "getLogger"; maybe "Logger"?  [attr-defined]
(lablup)sorna-common/src/ai/backend/common/docker.py:50: error: Incompatible types in assignment (expression has type "None", variable has type "BasicAuth")  [assignment]
Found 23 errors in 7 files (checked 18 source files)

[RRepo](cyanogen)uchroma
(cyanogen)uchroma/uchroma/server/types.py:43: error: Need type annotation for 'LOGO'  [var-annotated]
(cyanogen)uchroma/uchroma/server/types.py:44: error: Need type annotation for 'BACKLIGHT'  [var-annotated]

[RRepo](DeNeutoy)deep_qa
Success: no issues found in 1 source file

[RRepo](datmellow)League.py
(datmellow)League.py/docs/conf.py:82: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(datmellow)League.py/docs/conf.py:97: error: Need type annotation for 'exclude_patterns' (hint: "exclude_patterns: List[<type>] = ...")  [var-annotated]
(datmellow)League.py/docs/conf.py:130: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
(datmellow)League.py/league/__init__.py:41: error: Name 'NullHandler' already defined (possibly by an import)  [no-redef]
(datmellow)League.py/league/riotDTO.py:77: error: Argument 1 to "len" has incompatible type "Optional[Any]"; expected "Sized"  [arg-type]
(datmellow)League.py/league/riotDTO.py:78: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(datmellow)League.py/league/riotDTO.py:79: error: Argument 1 to "len" has incompatible type "Optional[Any]"; expected "Sized"  [arg-type]
(datmellow)League.py/league/riotDTO.py:80: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(datmellow)League.py/league/summoner.py:95: error: Missing return statement  [return]
(datmellow)League.py/league/summoner.py:112: error: Incompatible return value type (got "None", expected "LiveMatch")  [return-value]
(datmellow)League.py/league/summoner.py:129: error: Incompatible return value type (got "None", expected "List[LeagueEntry]")  [return-value]
(datmellow)League.py/league/summoner.py:131: error: Missing return statement  [return]
(datmellow)League.py/league/summoner.py:150: error: Missing return statement  [return]
(datmellow)League.py/league/summoner.py:173: error: Missing return statement  [return]
(datmellow)League.py/league/summoner.py:187: error: Incompatible return value type (got "Dict[Any, Any]", expected "int")  [return-value]
(datmellow)League.py/league/summoner.py:189: error: Missing return statement  [return]
(datmellow)League.py/league/summoner.py:233: error: Missing return statement  [return]
(datmellow)League.py/league/summoner.py:288: error: Item "None" of "Optional[datetime]" has no attribute "timestamp"  [union-attr]
(datmellow)League.py/league/summoner.py:289: error: Item "None" of "Optional[datetime]" has no attribute "timestamp"  [union-attr]
(datmellow)League.py/league/http.py:260: error: Missing return statement  [return]
(datmellow)League.py/league/http.py:320: error: Missing return statement  [return]
Found 21 errors in 5 files (checked 12 source files)

[RRepo](repleo)bounca
(repleo)bounca/bounca/webapp/views.py:8: error: Relative import climbs too many namespaces  [misc]
(repleo)bounca/bounca/webapp/forms.py:8: error: Relative import climbs too many namespaces  [misc]
(repleo)bounca/bounca/webapp/forms.py:9: error: Relative import climbs too many namespaces  [misc]
(repleo)bounca/bounca/webapp/forms.py:10: error: Relative import climbs too many namespaces  [misc]
(repleo)bounca/bounca/webapp/forms.py:11: error: Relative import climbs too many namespaces  [misc]
(repleo)bounca/bounca/webapp/forms.py:12: error: Relative import climbs too many namespaces  [misc]
(repleo)bounca/bounca/x509_pki/models.py:16: error: Relative import climbs too many namespaces  [misc]
(repleo)bounca/bounca/api/serializers.py:8: error: Relative import climbs too many namespaces  [misc]
(repleo)bounca/bounca/templatetags/templatetags/version_tags.py:6: error: Module 'bounca' has no attribute 'VERSION'  [attr-defined]
(repleo)bounca/bounca/certificate_engine/ssl/key.py:11: error: Incompatible types in assignment (expression has type "None", variable has type "RSAPrivateKey")  [assignment]
(repleo)bounca/bounca/certificate_engine/ssl/key.py:45: error: "RSAPrivateKey" has no attribute "private_bytes"  [attr-defined]
(repleo)bounca/bounca/certificate_engine/ssl/key.py:60: error: Incompatible return value type (got "Key", expected "RSAPrivateKey")  [return-value]

[RRepo](aio-libs)aioredis
(aio-libs)aioredis/aioredis/sentinel/commands.py: error: Duplicate module named 'commands' (also at '/home/bew/archive/typed_project/(aio-libs)aioredis/aioredis/commands/__init__.py')  [misc]
Found 1 error in 1 file (checked 54 source files)

[RRepo](tfgraph)tfgraph
(tfgraph)tfgraph/docs/source/conf.py:78: error: Need type annotation for 'exclude_patterns' (hint: "exclude_patterns: List[<type>] = ...")  [var-annotated]
(tfgraph)tfgraph/docs/source/conf.py:111: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
(tfgraph)tfgraph/examples/example_import_datasets.py:18: error: Module has no attribute "DataSets"  [attr-defined]
(tfgraph)tfgraph/tfgraph/algorithms/pagerank/iterative_pagerank.py:6: error: Module 'tfgraph.algorithms.pagerank' has no attribute 'PageRank'  [attr-defined]
(tfgraph)tfgraph/tfgraph/algorithms/pagerank/iterative_pagerank.py:7: error: Module 'tfgraph.algorithms.pagerank' has no attribute 'TransitionResetMatrix'  [attr-defined]
(tfgraph)tfgraph/tfgraph/algorithms/pagerank/algebraic_pagerank.py:7: error: Module 'tfgraph.algorithms.pagerank' has no attribute 'PageRank'  [attr-defined]
(tfgraph)tfgraph/tfgraph/algorithms/pagerank/algebraic_pagerank.py:8: error: Module 'tfgraph.algorithms.pagerank' has no attribute 'TransitionMatrix'  [attr-defined]
Found 7 errors in 4 files (checked 35 source files)

[RRepo](golemfactory)golem
(golemfactory)golem/golem/interface/client/tasks.py: error: Duplicate module named 'tasks' (also at '/home/bew/archive/typed_project/(golemfactory)golem/scripts/node_integration_tests/tasks/__init__.py')  [misc]
Found 1 error in 1 file (checked 445 source files)

[RRepo](dileep-kishore)microbial-ai
(dileep-kishore)microbial-ai/microbial_ai/metabolism/dfba.py:13: error: Relative import climbs too many namespaces  [misc]
(dileep-kishore)microbial-ai/microbial_ai/metabolism/media.py:53: error: Argument 1 of "__eq__" is incompatible with supertype "object"; supertype defines the argument type as "object"  [override]
(dileep-kishore)microbial-ai/microbial_ai/metabolism/media.py:53: note: It is recommended for "__eq__" to work with arbitrary objects, for example:
(dileep-kishore)microbial-ai/microbial_ai/metabolism/media.py:53: note:     def __eq__(self, other: object) -> bool:
(dileep-kishore)microbial-ai/microbial_ai/metabolism/media.py:53: note:         if not isinstance(other, Component):
(dileep-kishore)microbial-ai/microbial_ai/metabolism/media.py:53: note:             return NotImplemented
(dileep-kishore)microbial-ai/microbial_ai/metabolism/media.py:53: note:         return <logic to compare two Component instances>
(dileep-kishore)microbial-ai/microbial_ai/io/model_table.py:23: error: Variable "model_table.Base" is not valid as a type  [valid-type]
(dileep-kishore)microbial-ai/microbial_ai/io/model_table.py:23: error: Invalid base class "Base"  [misc]
(dileep-kishore)microbial-ai/microbial_ai/io/model_table.py:72: error: Argument 1 of "__eq__" is incompatible with supertype "object"; supertype defines the argument type as "object"  [override]
(dileep-kishore)microbial-ai/microbial_ai/io/model_table.py:72: note: It is recommended for "__eq__" to work with arbitrary objects, for example:
(dileep-kishore)microbial-ai/microbial_ai/io/model_table.py:72: note:     def __eq__(self, other: object) -> bool:
(dileep-kishore)microbial-ai/microbial_ai/io/model_table.py:72: note:         if not isinstance(other, Model):
(dileep-kishore)microbial-ai/microbial_ai/io/model_table.py:72: note:             return NotImplemented
(dileep-kishore)microbial-ai/microbial_ai/io/model_table.py:72: note:         return <logic to compare two Model instances>
(dileep-kishore)microbial-ai/microbial_ai/metabolism/reaction.py:88: error: Argument 1 of "__eq__" is incompatible with supertype "object"; supertype defines the argument type as "object"  [override]
(dileep-kishore)microbial-ai/microbial_ai/metabolism/reaction.py:88: note: It is recommended for "__eq__" to work with arbitrary objects, for example:
(dileep-kishore)microbial-ai/microbial_ai/metabolism/reaction.py:88: note:     def __eq__(self, other: object) -> bool:
(dileep-kishore)microbial-ai/microbial_ai/metabolism/reaction.py:88: note:         if not isinstance(other, Reaction):
(dileep-kishore)microbial-ai/microbial_ai/metabolism/reaction.py:88: note:             return NotImplemented
(dileep-kishore)microbial-ai/microbial_ai/metabolism/reaction.py:88: note:         return <logic to compare two Reaction instances>
(dileep-kishore)microbial-ai/microbial_ai/metabolism/metabolite.py:58: error: Argument 1 of "__eq__" is incompatible with supertype "object"; supertype defines the argument type as "object"  [override]
(dileep-kishore)microbial-ai/microbial_ai/metabolism/metabolite.py:58: note: It is recommended for "__eq__" to work with arbitrary objects, for example:
(dileep-kishore)microbial-ai/microbial_ai/metabolism/metabolite.py:58: note:     def __eq__(self, other: object) -> bool:
(dileep-kishore)microbial-ai/microbial_ai/metabolism/metabolite.py:58: note:         if not isinstance(other, Metabolite):
(dileep-kishore)microbial-ai/microbial_ai/metabolism/metabolite.py:58: note:             return NotImplemented
(dileep-kishore)microbial-ai/microbial_ai/metabolism/metabolite.py:58: note:         return <logic to compare two Metabolite instances>
(dileep-kishore)microbial-ai/microbial_ai/metabolism/metabolite.py:178: error: Name 'ExReaction' is not defined  [name-defined]
(dileep-kishore)microbial-ai/microbial_ai/visualization/plot_results.py:111: error: Unsupported target for indexed assignment  [index]
(dileep-kishore)microbial-ai/microbial_ai/visualization/plot_results.py:112: error: Unsupported target for indexed assignment  [index]
(dileep-kishore)microbial-ai/microbial_ai/visualization/plot_results.py:182: error: Unsupported target for indexed assignment  [index]
(dileep-kishore)microbial-ai/microbial_ai/visualization/plot_results.py:183: error: Unsupported target for indexed assignment  [index]
(dileep-kishore)microbial-ai/microbial_ai/visualization/plot_results.py:250: error: Unsupported target for indexed assignment  [index]
(dileep-kishore)microbial-ai/microbial_ai/visualization/plot_results.py:251: error: Unsupported target for indexed assignment  [index]
(dileep-kishore)microbial-ai/microbial_ai/simulation/simulation.py:18: error: Relative import climbs too many namespaces  [misc]
(dileep-kishore)microbial-ai/microbial_ai/simulation/simulation.py:19: error: Relative import climbs too many namespaces  [misc]
(dileep-kishore)microbial-ai/microbial_ai/regulation/dqnregulator.py:67: error: Too many arguments for "Variable"  [call-arg]
(dileep-kishore)microbial-ai/microbial_ai/regulation/dqnregulator.py:67: error: Unexpected keyword argument "volatile" for "Variable"  [call-arg]
(dileep-kishore)microbial-ai/microbial_ai/regulation/dqnregulator.py:69: error: Too few arguments for "multinomial" of "Tensor"  [call-arg]
(dileep-kishore)microbial-ai/microbial_ai/regulation/dqnregulator.py:70: error: Argument 1 to "_decode_action" of "Regulator" has incompatible type "Tensor"; expected "int"  [arg-type]
(dileep-kishore)microbial-ai/microbial_ai/regulation/dqnregulator.py:108: error: Argument 1 of "update" is incompatible with supertype "Regulator"; supertype defines the argument type as "Dict[str, float]"  [override]
(dileep-kishore)microbial-ai/microbial_ai/regulation/dqnregulator.py:108: error: Argument 3 of "update" is incompatible with supertype "Regulator"; supertype defines the argument type as "Dict[str, float]"  [override]
(dileep-kishore)microbial-ai/microbial_ai/regulation/__init__.py:9: error: Name 'A3CRegulator' is not defined  [name-defined]
Found 23 errors in 9 files (checked 30 source files)

[RRepo](auDeep)auDeep
(auDeep)auDeep/audeep/backend/signal/spectral.py:47: error: Syntax error in type annotation  [syntax]
(auDeep)auDeep/audeep/backend/signal/spectral.py:47: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(auDeep)auDeep/audeep/backend/signal/spectral.py:84: error: Syntax error in type annotation  [syntax]
(auDeep)auDeep/audeep/backend/signal/spectral.py:84: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(auDeep)auDeep/audeep/backend/signal/spectral.py:166: error: Argument 1 to "mel_filter_bank" has incompatible type "Optional[int]"; expected "int"  [arg-type]
(auDeep)auDeep/audeep/backend/signal/spectral.py:166: error: Argument 2 to "mel_filter_bank" has incompatible type "Optional[int]"; expected "int"  [arg-type]
(auDeep)auDeep/audeep/backend/models/frequency_autoencoder.py:89: error: "FrequencyAutoencoder" has no attribute "init_targets"  [attr-defined]
(auDeep)auDeep/audeep/backend/models/frequency_autoencoder.py:90: error: "FrequencyAutoencoder" has no attribute "init_encoder_inputs"; maybe "encoder_inputs" or "decoder_inputs"?  [attr-defined]
(auDeep)auDeep/audeep/backend/models/frequency_autoencoder.py:91: error: "FrequencyAutoencoder" has no attribute "init_encoder"  [attr-defined]
(auDeep)auDeep/audeep/backend/models/frequency_autoencoder.py:92: error: "FrequencyAutoencoder" has no attribute "init_representation"; maybe "representation"?  [attr-defined]
(auDeep)auDeep/audeep/backend/models/frequency_autoencoder.py:93: error: "FrequencyAutoencoder" has no attribute "init_decoder_inputs"; maybe "decoder_inputs" or "encoder_inputs"?  [attr-defined]
(auDeep)auDeep/audeep/backend/models/frequency_autoencoder.py:94: error: "FrequencyAutoencoder" has no attribute "init_decoder"  [attr-defined]
(auDeep)auDeep/audeep/backend/models/frequency_autoencoder.py:95: error: "FrequencyAutoencoder" has no attribute "init_reconstruction"; maybe "reconstruction"?  [attr-defined]
(auDeep)auDeep/audeep/backend/models/frequency_autoencoder.py:96: error: "FrequencyAutoencoder" has no attribute "init_loss"  [attr-defined]
(auDeep)auDeep/audeep/backend/models/frequency_autoencoder.py:97: error: "FrequencyAutoencoder" has no attribute "init_optimizer"; maybe "optimizer"?  [attr-defined]
(auDeep)auDeep/audeep/backend/evaluation.py:99: error: Incompatible return value type (got "None", expected "float")  [return-value]
(auDeep)auDeep/audeep/backend/evaluation.py:115: error: Incompatible return value type (got "None", expected "float")  [return-value]
(auDeep)auDeep/audeep/backend/evaluation.py:130: error: Incompatible return value type (got "None", expected "float")  [return-value]
(auDeep)auDeep/audeep/backend/evaluation.py:146: error: Incompatible return value type (got "None", expected "float")  [return-value]
(auDeep)auDeep/audeep/backend/evaluation.py:290: error: Incompatible return value type (got "None", expected "float")  [return-value]
(auDeep)auDeep/audeep/backend/evaluation.py:305: error: Incompatible return value type (got "None", expected "float")  [return-value]
(auDeep)auDeep/audeep/backend/parsers/compare18_heartbeat.py:104: error: Need type annotation for 'inverse_label_map' (hint: "inverse_label_map: Dict[<type>, <type>] = ...")  [var-annotated]
(auDeep)auDeep/audeep/backend/parsers/compare18_heartbeat.py:104: error: Argument 1 to "dict" has incompatible type "Iterator[Iterator[_T]]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"  [arg-type]
(auDeep)auDeep/audeep/backend/parsers/compare18_heartbeat.py:104: error: Item "None" of "Optional[Mapping[str, int]]" has no attribute "items"  [union-attr]
(auDeep)auDeep/audeep/backend/parsers/compare19_cs.py:108: error: Need type annotation for 'inverse_label_map' (hint: "inverse_label_map: Dict[<type>, <type>] = ...")  [var-annotated]
(auDeep)auDeep/audeep/backend/parsers/compare19_cs.py:108: error: Argument 1 to "dict" has incompatible type "Iterator[Iterator[_T]]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"  [arg-type]
(auDeep)auDeep/audeep/backend/parsers/compare19_cs.py:108: error: Item "None" of "Optional[Mapping[str, int]]" has no attribute "items"  [union-attr]
(auDeep)auDeep/audeep/backend/parsers/compare19_cs.py:117: error: Incompatible types in assignment (expression has type "None", variable has type "int")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/compare18_crying.py:102: error: Need type annotation for 'inverse_label_map' (hint: "inverse_label_map: Dict[<type>, <type>] = ...")  [var-annotated]
(auDeep)auDeep/audeep/backend/parsers/compare18_crying.py:102: error: Argument 1 to "dict" has incompatible type "Iterator[Iterator[_T]]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"  [arg-type]
(auDeep)auDeep/audeep/backend/parsers/compare18_crying.py:102: error: Item "None" of "Optional[Mapping[str, int]]" has no attribute "items"  [union-attr]
(auDeep)auDeep/audeep/backend/parsers/compare18_crying.py:111: error: Incompatible types in assignment (expression has type "None", variable has type "float")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/meta.py:82: error: "None" has no attribute "num_instances"  [attr-defined]
(auDeep)auDeep/audeep/backend/parsers/meta.py:104: error: "None" has no attribute "num_folds"  [attr-defined]
(auDeep)auDeep/audeep/backend/parsers/meta.py:126: error: "None" has no attribute "label_map"  [attr-defined]
(auDeep)auDeep/audeep/backend/parsers/meta.py:149: error: Incompatible types in assignment (expression has type "bool", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/meta.py:152: error: Incompatible return value type (got "None", expected "bool")  [return-value]
(auDeep)auDeep/audeep/backend/parsers/meta.py:176: error: "None" has no attribute "parse"  [attr-defined]
(auDeep)auDeep/audeep/backend/parsers/dcase.py:112: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/dcase.py:115: error: Incompatible return value type (got "None", expected "Sequence[Any]")  [return-value]
(auDeep)auDeep/audeep/backend/parsers/urban_sound_8k.py:170: error: Incompatible types in assignment (expression has type "Dict[<nothing>, <nothing>]", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/urban_sound_8k.py:176: error: Unsupported right operand type for in ("None")  [operator]
(auDeep)auDeep/audeep/backend/parsers/urban_sound_8k.py:177: error: Unsupported target for indexed assignment  [index]
(auDeep)auDeep/audeep/backend/parsers/urban_sound_8k.py:178: error: Value of type "None" is not indexable  [index]
(auDeep)auDeep/audeep/backend/parsers/urban_sound_8k.py:180: error: Value of type "None" is not indexable  [index]
(auDeep)auDeep/audeep/backend/parsers/cross_validated.py:139: error: Need type annotation for 'classes' (hint: "classes: List[<type>] = ...")  [var-annotated]
(auDeep)auDeep/audeep/backend/parsers/cross_validated.py:151: error: Incompatible types in assignment (expression has type "Set[Any]", variable has type "List[Any]")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/cross_validated.py:153: error: Incompatible types in assignment (expression has type "Dict[Any, int]", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/cross_validated.py:176: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/cross_validated.py:180: error: Unsupported operand types for + ("None" and "int")  [operator]
(auDeep)auDeep/audeep/backend/parsers/cross_validated.py:180: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/cross_validated.py:183: error: Incompatible return value type (got "None", expected "int")  [return-value]
(auDeep)auDeep/audeep/backend/parsers/dcase18_task4.py:105: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/dcase18_task4.py:108: error: Incompatible return value type (got "None", expected "Sequence[Any]")  [return-value]
(auDeep)auDeep/audeep/backend/parsers/no_metadata.py:71: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/no_metadata.py:74: error: Incompatible return value type (got "None", expected "int")  [return-value]
(auDeep)auDeep/audeep/backend/parsers/partitioned.py:110: error: Need type annotation for 'classes' (hint: "classes: List[<type>] = ...")  [var-annotated]
(auDeep)auDeep/audeep/backend/parsers/partitioned.py:122: error: Incompatible types in assignment (expression has type "Set[Any]", variable has type "List[Any]")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/partitioned.py:124: error: Incompatible types in assignment (expression has type "Dict[Any, int]", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/partitioned.py:167: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/partitioned.py:173: error: Unsupported operand types for + ("None" and "int")  [operator]
(auDeep)auDeep/audeep/backend/parsers/partitioned.py:173: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/partitioned.py:176: error: Incompatible return value type (got "None", expected "int")  [return-value]
(auDeep)auDeep/audeep/backend/models/spectrogram_queue.py:63: error: "SpectrogramQueue" has no attribute "init_input_queue"; maybe "input_queue"?  [attr-defined]
(auDeep)auDeep/audeep/backend/preprocessing.py:102: error: Need type annotation for '_mel_fbanks' (hint: "_mel_fbanks: Dict[<type>, <type>] = ...")  [var-annotated]
(auDeep)auDeep/audeep/backend/preprocessing.py:103: error: Need type annotation for '_freq_points' (hint: "_freq_points: Dict[<type>, <type>] = ...")  [var-annotated]
(auDeep)auDeep/audeep/backend/preprocessing.py:109: error: Syntax error in type annotation  [syntax]
(auDeep)auDeep/audeep/backend/preprocessing.py:109: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(auDeep)auDeep/audeep/backend/preprocessing.py:235: error: Unsupported operand types for + ("None" and "int")  [operator]
(auDeep)auDeep/audeep/backend/preprocessing.py:235: note: Left operand is of type "Optional[int]"
(auDeep)auDeep/audeep/backend/preprocessing.py:236: error: Unsupported operand types for + ("None" and "int")  [operator]
(auDeep)auDeep/audeep/backend/preprocessing.py:236: note: Left operand is of type "Optional[int]"
(auDeep)auDeep/audeep/backend/parsers/esc.py:111: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/esc.py:114: error: Unsupported operand types for + ("None" and "int")  [operator]
(auDeep)auDeep/audeep/backend/parsers/esc.py:114: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/esc.py:117: error: Incompatible return value type (got "None", expected "int")  [return-value]
(auDeep)auDeep/audeep/backend/parsers/esc.py:162: error: Incompatible types in assignment (expression has type "Dict[<nothing>, <nothing>]", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/parsers/esc.py:167: error: Unsupported target for indexed assignment  [index]
(auDeep)auDeep/audeep/backend/data/upsample.py:44: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[Tuple[str, int]], Iterator[_T]]"  [arg-type]
(auDeep)auDeep/audeep/backend/data/upsample.py:44: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[Tuple[str, int]], Tuple[int, str]]"  [arg-type]
(auDeep)auDeep/audeep/backend/data/export.py:168: error: "object" has no attribute "append"  [attr-defined]
(auDeep)auDeep/audeep/backend/data/export.py:169: error: "object" has no attribute "append"  [attr-defined]
(auDeep)auDeep/audeep/backend/data/export.py:172: error: "object" has no attribute "append"  [attr-defined]
(auDeep)auDeep/audeep/backend/data/export.py:176: error: "object" has no attribute "append"  [attr-defined]
(auDeep)auDeep/audeep/backend/data/export.py:177: error: "object" has no attribute "append"  [attr-defined]
(auDeep)auDeep/audeep/backend/data/export.py:193: error: "object" has no attribute "append"  [attr-defined]
(auDeep)auDeep/audeep/backend/learners.py:190: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/learners.py:217: error: Incompatible types in assignment (expression has type "Path", variable has type "None")  [assignment]
(auDeep)auDeep/audeep/backend/learners.py:270: error: Need type annotation for 'predictions' (hint: "predictions: Dict[<type>, <type>] = ...")  [var-annotated]
(auDeep)auDeep/audeep/backend/learners.py:329: error: "None" has no attribute "fit"  [attr-defined]
(auDeep)auDeep/audeep/backend/formatters.py:218: error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "List[Tuple[str, int]]")  [assignment]
(auDeep)auDeep/audeep/backend/formatters.py:221: error: List comprehension has incompatible type List[object]; expected List[Tuple[str, int]]  [misc]
Found 87 errors in 20 files (checked 46 source files)

[RRepo](zrzka)blackmamba
(zrzka)blackmamba/blackmamba/lib/rope/base/utils/pycompat.py:11: error: Name 'unicode' is not defined  [name-defined]
(zrzka)blackmamba/blackmamba/lib/rope/base/utils/pycompat.py:34: error: Name 'basestring' is not defined  [name-defined]
(zrzka)blackmamba/blackmamba/lib/rope/base/utils/pycompat.py:36: error: Cannot assign multiple types to name "ast_arg_type" without an explicit "Type[...]" annotation  [misc]
(zrzka)blackmamba/blackmamba/lib/rope/base/utils/pycompat.py:36: error: Incompatible types in assignment (expression has type "Type[Name]", variable has type "Type[arg]")  [assignment]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:77: error: Argument 1 to "multi" has incompatible type "Callable[[SymbolTable, Any, Any], Any]"; expected "SymbolTable"  [arg-type]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:87: error: Argument 1 to "multi" has incompatible type "Callable[[SymbolTable, Any, Any], Any]"; expected "SymbolTable"  [arg-type]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:109: error: Argument 1 to "multi" has incompatible type "Callable[[SymbolTable, Any, Any], Any]"; expected "SymbolTable"  [arg-type]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:118: error: Argument 1 to "multi" has incompatible type "Callable[[SymbolTable, Any, Any], Any]"; expected "SymbolTable"  [arg-type]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:127: error: Incompatible types in assignment (expression has type "staticmethod", variable has type "Callable[[SymbolTable], Any]")  [assignment]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:144: error: Cannot determine type of 'U'  [has-type]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:144: error: Cannot determine type of 'S'  [has-type]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:144: error: Cannot determine type of 'X'  [has-type]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:266: error: Name 'evaluate' already defined on line 244  [no-redef]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:275: error: Name 'nud' already defined on line 239  [no-redef]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:291: error: Name 'led' already defined on line 250  [no-redef]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:307: error: Name 'evaluate' already defined on line 244  [no-redef]
(zrzka)blackmamba/blackmamba/lib/rope/base/oi/type_hinting/evaluate.py:313: error: Name 'evaluate' already defined on line 307  [no-redef]
(zrzka)blackmamba/blackmamba/lib/rope/base/evaluate.py:4: error: Module 'rope.base' has no attribute 'worder'  [attr-defined]
(zrzka)blackmamba/blackmamba/lib/flake8/exceptions.py:123: error: Incompatible types in assignment (expression has type "str", base class "MercurialHookAlreadyExists" defined the type as "None")  [assignment]
(zrzka)blackmamba/blackmamba/lib/flake8/exceptions.py:129: error: Incompatible types in assignment (expression has type "str", base class "MercurialHookAlreadyExists" defined the type as "None")  [assignment]
(zrzka)blackmamba/blackmamba/lib/flake8/__init__.py:16: error: Name 'NullHandler' already defined (possibly by an import)  [no-redef]
(zrzka)blackmamba/blackmamba/lib/rope/refactor/importutils/importinfo.py:188: error: Need type annotation for 'names_and_aliases' (hint: "names_and_aliases: List[<type>] = ...")  [var-annotated]
(zrzka)blackmamba/blackmamba/lib/rope/refactor/functionutils.py:4: error: Module 'rope.base' has no attribute 'worder'  [attr-defined]
(zrzka)blackmamba/blackmamba/lib/libpasteurize/fixes/feature_base.py:36: error: Need type annotation for 'mapping' (hint: "mapping: Dict[<type>, <type>] = ...")  [var-annotated]
(zrzka)blackmamba/blackmamba/lib/flake8/utils.py:17: error: Type signature has too few arguments  [syntax]

[RRepo](varqox)sim
Success: no issues found in 2 source files

[RRepo](scienceopen)pybashutils
(scienceopen)pybashutils/compare_binary.py:18: error: Argument 1 to "cmp" has incompatible type "Path"; expected "Union[bytes, str]"  [arg-type]
(scienceopen)pybashutils/compare_binary.py:18: error: Argument 2 to "cmp" has incompatible type "Path"; expected "Union[bytes, str]"  [arg-type]
(scienceopen)pybashutils/diffdir.py:17: error: Value of type variable "AnyStr" of "dircmp" cannot be "Path"  [type-var]
(scienceopen)pybashutils/diffdir.py:18: error: Argument 1 to "join" of "str" has incompatible type "List[Path]"; expected "Iterable[str]"  [arg-type]
(scienceopen)pybashutils/diffdir.py:19: error: Argument 1 to "join" of "str" has incompatible type "List[Path]"; expected "Iterable[str]"  [arg-type]
(scienceopen)pybashutils/diffdir.py:20: error: Argument 1 to "join" of "str" has incompatible type "List[Path]"; expected "Iterable[str]"  [arg-type]
(scienceopen)pybashutils/pybashutils/getIP.py:32: error: "Curl" has no attribute "URL"  [attr-defined]
(scienceopen)pybashutils/pybashutils/getIP.py:34: error: "Curl" has no attribute "WRITEDATA"  [attr-defined]
(scienceopen)pybashutils/meld_all.py:41: error: Argument 1 to "cmp" has incompatible type "Path"; expected "Union[bytes, str]"  [arg-type]
(scienceopen)pybashutils/meld_all.py:41: error: Argument 2 to "cmp" has incompatible type "Path"; expected "Union[bytes, str]"  [arg-type]
Found 10 errors in 4 files (checked 21 source files)

[RRepo](EarthLifeConsortium)elc_api
(EarthLifeConsortium)elc_api/swagger_server/models/taxonomy_inner.py:58: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(EarthLifeConsortium)elc_api/swagger_server/models/taxonomy_inner.py:81: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(EarthLifeConsortium)elc_api/swagger_server/models/error_model.py:7: error: Relative import climbs too many namespaces  [misc]
(EarthLifeConsortium)elc_api/swagger_server/models/error_model.py:68: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(EarthLifeConsortium)elc_api/swagger_server/models/error_model.py:93: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(EarthLifeConsortium)elc_api/swagger_server/models/error_model.py:118: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(EarthLifeConsortium)elc_api/swagger_server/models/error_model.py:143: error: Incompatible return value type (got "Optional[int]", expected "int")  [return-value]
(EarthLifeConsortium)elc_api/swagger_server/models/reference.py:7: error: Relative import climbs too many namespaces  [misc]
(EarthLifeConsortium)elc_api/swagger_server/models/reference.py:83: error: Incompatible return value type (got "Optional[List[str]]", expected "List[str]")  [return-value]
(EarthLifeConsortium)elc_api/swagger_server/models/reference.py:106: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(EarthLifeConsortium)elc_api/swagger_server/models/reference.py:129: error: Incompatible return value type (got "Optional[List[str]]", expected "List[str]")  [return-value]
(EarthLifeConsortium)elc_api/swagger_server/models/reference.py:152: error: Incompatible return value type (got "Optional[List[str]]", expected "List[str]")  [return-value]
(EarthLifeConsortium)elc_api/swagger_server/models/reference.py:175: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(EarthLifeConsortium)elc_api/swagger_server/models/reference.py:198: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(EarthLifeConsortium)elc_api/swagger_server/models/reference.py:221: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]

[RRepo](smlbiobot)SML-Cogs
(smlbiobot)SML-Cogs/challonge/challonge.py:108: error: Module has no attribute "tournaments"  [attr-defined]
(smlbiobot)SML-Cogs/challonge/challonge.py:131: error: Module has no attribute "tournaments"  [attr-defined]
(smlbiobot)SML-Cogs/challonge/challonge.py:139: error: Module has no attribute "api"  [attr-defined]
(smlbiobot)SML-Cogs/reactionpoll/reactionpoll.py:104: error: Name 'reactionpoll_add' already defined on line 76  [no-redef]
(smlbiobot)SML-Cogs/card/data/scripts/popdata.py:45: error: Need type annotation for 'card_elixir' (hint: "card_elixir: Dict[<type>, <type>] = ...")  [var-annotated]
(smlbiobot)SML-Cogs/card/data/scripts/popdata.py:60: error: Need type annotation for 'cpid_dict' (hint: "cpid_dict: Dict[<type>, <type>] = ...")  [var-annotated]
(smlbiobot)SML-Cogs/discordgram/discordgram.py:37: error: Need type annotation for 'SERVER_DEFAULTS'  [var-annotated]
(smlbiobot)SML-Cogs/ascii/ascii.py:98: error: Module has no attribute "loadFromUrl"  [attr-defined]
(smlbiobot)SML-Cogs/rolehist/rolehist.py:97: error: Need type annotation for 'prev_roles' (hint: "prev_roles: List[<type>] = ...")  [var-annotated]
(smlbiobot)SML-Cogs/userdata/userdata.py:212: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(smlbiobot)SML-Cogs/post/post.py:180: error: "TextIO" has no attribute "get"  [attr-defined]
(smlbiobot)SML-Cogs/post/post.py:181: error: "TextIO" has no attribute "get"  [attr-defined]
(smlbiobot)SML-Cogs/banned/banned.py:331: error: Not all arguments converted during string formatting  [str-format]
(smlbiobot)SML-Cogs/search/search.py:121: error: Module has no attribute "search"  [attr-defined]
(smlbiobot)SML-Cogs/search/search.py:123: error: Module has no attribute "get"  [attr-defined]
(smlbiobot)SML-Cogs/search/search.py:138: error: Module has no attribute "search_images"  [attr-defined]
(smlbiobot)SML-Cogs/search/search.py:140: error: Module has no attribute "get"  [attr-defined]
(smlbiobot)SML-Cogs/farmers/farmers.py:67: error: Module has no attribute "get"  [attr-defined]
(smlbiobot)SML-Cogs/farmers/farmers.py:84: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
Found 19 errors in 11 files (checked 53 source files)

[RRepo](superdesk)Live-Blog
(superdesk)Live-Blog/documentor/libraries/Sphinx-1.1.3-py3.2/sphinx/pycode/nodes.py:32: error: Incompatible types in assignment (expression has type "None", base class "object" defined the type as "Callable[[object], int]")  [assignment]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:102: error: Invalid type comment or annotation  [valid-type]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:102: note: Suggestion: use Iter[...] instead of Iter(...)
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:109: error: Invalid type comment or annotation  [valid-type]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:109: note: Suggestion: use Iter[...] instead of Iter(...)
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:116: error: Invalid type comment or annotation  [valid-type]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:116: note: Suggestion: use Iter[...] instead of Iter(...)
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:123: error: Invalid type comment or annotation  [valid-type]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:123: note: Suggestion: use Iter[...] instead of Iter(...)
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:130: error: Invalid type comment or annotation  [valid-type]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:130: note: Suggestion: use Iter[...] instead of Iter(...)
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:138: error: Invalid type comment or annotation  [valid-type]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:138: note: Suggestion: use Iter[...] instead of Iter(...)
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:144: error: Name 'BlogPost.Id' is not defined  [name-defined]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:150: error: Name 'BlogPost.Id' is not defined  [name-defined]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:156: error: Name 'BlogPost.Id' is not defined  [name-defined]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:162: error: Name 'BlogPost.Id' is not defined  [name-defined]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:168: error: Name 'BlogPost.Id' is not defined  [name-defined]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:174: error: Name 'BlogPost.Id' is not defined  [name-defined]
(superdesk)Live-Blog/plugins/livedesk/livedesk/api/blog_post.py:180: error: Name 'BlogPost.Id' is not defined  [name-defined]
(superdesk)Live-Blog/plugins/livedesk/livedesk/impl/blog_collaborator.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/livedesk/livedesk/impl/filter_blog.py:57: error: Incompatible types in assignment (expression has type "List[str]", base class "BlogFilterServiceAlchemyBase" defined the type as "Type[List[Any]]")  [assignment]
(superdesk)Live-Blog/plugins/livedesk/livedesk/impl/filter_blog.py:69: error: Incompatible types in assignment (expression has type "List[str]", base class "BlogFilterServiceAlchemyBase" defined the type as "Type[List[Any]]")  [assignment]
(superdesk)Live-Blog/plugins/superdesk-source/superdesk/source/impl/source.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-source/superdesk/source/impl/source.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-source/superdesk/source/impl/source.py:14: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-post/superdesk/post/impl/type.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-post/superdesk/post/impl/type.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-user/__plugin__/superdesk_user/upgrade.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-user/superdesk/user/impl/user_type.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-user/superdesk/user/impl/user_type.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive/superdesk/media_archive/impl/meta_info.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive/superdesk/media_archive/impl/meta_info.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive/superdesk/media_archive/impl/meta_info.py:14: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive/superdesk/media_archive/impl/meta_info.py:15: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive/superdesk/media_archive/impl/meta_info.py:16: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive/superdesk/media_archive/impl/query_criteria.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive/superdesk/media_archive/impl/meta_type.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-collaborator/superdesk/collaborator/impl/collaborator.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-collaborator/superdesk/collaborator/impl/collaborator.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-person/superdesk/person/impl/person.py:14: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-verification/__plugin__/superdesk_verification/populate_default_data.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-verification/superdesk/verification/impl/verification.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-verification/superdesk/verification/impl/verification.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-verification/superdesk/verification/impl/status.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-verification/superdesk/verification/impl/status.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-security/__plugin__/superdesk_security/acl.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-security/__plugin__/superdesk_security/acl.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive-image/__plugin__/media_archive_image/gui.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive-image/__plugin__/media_archive_image/actions.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive-image/__plugin__/media_archive_image/actions.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive-image/__plugin__/media_archive_image/actions.py:14: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive-image/__plugin__/media_archive_image/actions.py:15: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk/__plugin__/superdesk/db_superdesk.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk/__plugin__/superdesk/db_superdesk.py:27: error: Cannot determine type of 'database_url'  [has-type]
(superdesk)Live-Blog/sandbox/plugins/superdesk-article/superdesk/article/impl/article.py:11: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/documentor/libraries/Sphinx-1.1.3-py3.2/sphinx/locale/__init__.py:45: error: Incompatible types in assignment (expression has type "property", base class "UserString" defined the type as "str")  [assignment]
(superdesk)Live-Blog/documentor/libraries/Sphinx-1.1.3-py3.2/sphinx/locale/__init__.py:77: error: Name '__str__' already defined on line 74  [no-redef]
(superdesk)Live-Blog/documentor/libraries/Sphinx-1.1.3-py3.2/sphinx/locale/__init__.py:184: error: Need type annotation for 'translators' (hint: "translators: Dict[<type>, <type>] = ...")  [var-annotated]
(superdesk)Live-Blog/documentor/libraries/docutils-0.9.1-py3.2/docutils/parsers/rst/languages/__init__.py:15: error: Module 'docutils.utils' has no attribute 'normalize_language_tag'  [attr-defined]
(superdesk)Live-Blog/documentor/libraries/docutils-0.9.1-py3.2/docutils/parsers/rst/languages/__init__.py:17: error: Need type annotation for '_languages' (hint: "_languages: Dict[<type>, <type>] = ...")  [var-annotated]
(superdesk)Live-Blog/documentor/libraries/docutils-0.9.1-py3.2/docutils/languages/__init__.py:14: error: Module 'docutils.utils' has no attribute 'normalize_language_tag'  [attr-defined]
(superdesk)Live-Blog/documentor/libraries/docutils-0.9.1-py3.2/docutils/languages/__init__.py:16: error: Need type annotation for '_languages' (hint: "_languages: Dict[<type>, <type>] = ...")  [var-annotated]
(superdesk)Live-Blog/plugins/superdesk-post/superdesk/post/impl/post.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-post/superdesk/post/impl/post.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-post/superdesk/post/impl/post.py:14: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk/__plugin__/superdesk/service.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/distribution/libraries/Babel-1.0dev-py3.2/babel/compat.py:76: error: "Type[GNUTranslations]" has no attribute "ugettext"  [attr-defined]
(superdesk)Live-Blog/distribution/libraries/Babel-1.0dev-py3.2/babel/compat.py:77: error: "Type[GNUTranslations]" has no attribute "ungettext"  [attr-defined]
(superdesk)Live-Blog/distribution/libraries/Babel-1.0dev-py3.2/babel/localedata.py:25: error: Name 'threading' already defined (by an import)  [no-redef]
(superdesk)Live-Blog/distribution/libraries/Babel-1.0dev-py3.2/babel/localedata.py:30: error: Need type annotation for '_cache' (hint: "_cache: Dict[<type>, <type>] = ...")  [var-annotated]
(superdesk)Live-Blog/build-package/distribution/sunburnt/json.py:4: error: Name 'json.JSONEncoder' is not defined  [name-defined]
(superdesk)Live-Blog/build-package/distribution/sunburnt/json.py:37: error: Cannot resolve attribute "load" (possible cyclic definition)  [misc]
(superdesk)Live-Blog/build-package/distribution/sunburnt/json.py:37: error: Module has no attribute "load"; maybe "loads"?  [attr-defined]
(superdesk)Live-Blog/build-package/distribution/sunburnt/json.py:38: error: Cannot resolve attribute "loads" (possible cyclic definition)  [misc]
(superdesk)Live-Blog/build-package/distribution/sunburnt/json.py:38: error: Module has no attribute "loads"; maybe "load"?  [attr-defined]
(superdesk)Live-Blog/documentor/libraries/Sphinx-1.1.3-py3.2/sphinx/websupport/storage/sqlalchemy_db.py:26: error: Variable "sphinx.websupport.storage.sqlalchemy_db.Base" is not valid as a type  [valid-type]
(superdesk)Live-Blog/documentor/libraries/Sphinx-1.1.3-py3.2/sphinx/websupport/storage/sqlalchemy_db.py:26: error: Invalid base class "Base"  [misc]
(superdesk)Live-Blog/documentor/libraries/Sphinx-1.1.3-py3.2/sphinx/websupport/storage/sqlalchemy_db.py:104: error: Variable "sphinx.websupport.storage.sqlalchemy_db.Base" is not valid as a type  [valid-type]
(superdesk)Live-Blog/documentor/libraries/Sphinx-1.1.3-py3.2/sphinx/websupport/storage/sqlalchemy_db.py:104: error: Invalid base class "Base"  [misc]
(superdesk)Live-Blog/documentor/libraries/Sphinx-1.1.3-py3.2/sphinx/websupport/storage/sqlalchemy_db.py:120: error: Variable "sphinx.websupport.storage.sqlalchemy_db.Base" is not valid as a type  [valid-type]
(superdesk)Live-Blog/documentor/libraries/Sphinx-1.1.3-py3.2/sphinx/websupport/storage/sqlalchemy_db.py:120: error: Invalid base class "Base"  [misc]
(superdesk)Live-Blog/documentor/libraries/Sphinx-1.1.3-py3.2/sphinx/pycode/pgen2/pgen.py:5: error: Module 'sphinx.pycode.pgen2' has no attribute 'tokenize'  [attr-defined]
(superdesk)Live-Blog/plugins/frontline-inlet/frontline/inlet/core/imp/sms_sync.py:63: error: Need type annotation for 'syncThreads' (hint: "syncThreads: Dict[<type>, <type>] = ...")  [var-annotated]
(superdesk)Live-Blog/plugins/frontline-inlet/frontline/inlet/impl/inlet.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/livedesk-embed/__plugin__/livedesk_embed/populate.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/livedesk-embed/__plugin__/livedesk_embed/populate.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/livedesk-embed/__plugin__/livedesk_embed/theme_default.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive/superdesk/media_archive/impl/meta_data.py:12: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive/superdesk/media_archive/impl/meta_data.py:13: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive/superdesk/media_archive/impl/meta_data.py:14: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/media-archive/superdesk/media_archive/impl/meta_data.py:15: error: Relative import climbs too many namespaces  [misc]
(superdesk)Live-Blog/plugins/superdesk-security/superdesk/security/core/impl/processor/user_persistence_filter.py:241: error: Unsupported operand types for > ("List[PermissionFilter]" and "int")  [operator]
(superdesk)Live-Blog/plugins/superdesk-security/superdesk/security/impl/authentication.py:12: error: Relative import climbs too many namespaces  [misc]

[RRepo](jcchoiling)learningPython
(jcchoiling)learningPython/treehouse/pythonSeries/unittestbasic/moves.py:27: error: Incompatible types in assignment (expression has type "List[str]", base class "Move" defined the type as "None")  [assignment]
(jcchoiling)learningPython/treehouse/pythonSeries/unittestbasic/moves.py:28: error: Incompatible types in assignment (expression has type "List[str]", base class "Move" defined the type as "None")  [assignment]
(jcchoiling)learningPython/treehouse/pythonSeries/unittestbasic/moves.py:32: error: Incompatible types in assignment (expression has type "List[str]", base class "Move" defined the type as "None")  [assignment]
(jcchoiling)learningPython/treehouse/pythonSeries/unittestbasic/moves.py:33: error: Incompatible types in assignment (expression has type "List[str]", base class "Move" defined the type as "None")  [assignment]
(jcchoiling)learningPython/treehouse/pythonSeries/unittestbasic/moves.py:37: error: Incompatible types in assignment (expression has type "List[str]", base class "Move" defined the type as "None")  [assignment]
(jcchoiling)learningPython/treehouse/pythonSeries/unittestbasic/moves.py:38: error: Incompatible types in assignment (expression has type "List[str]", base class "Move" defined the type as "None")  [assignment]
(jcchoiling)learningPython/treehouse/pythonSeries/students.py:4: error: Name 'SqliteDatabase' is not defined  [name-defined]
(jcchoiling)learningPython/treehouse/pythonSeries/students.py:31: error: Name 'Model' is not defined  [name-defined]
(jcchoiling)learningPython/treehouse/pythonSeries/students.py:32: error: Name 'CharField' is not defined  [name-defined]
(jcchoiling)learningPython/treehouse/pythonSeries/students.py:33: error: Name 'IntegerField' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day07/practice/ex_obj-oriented_v1.py:24: error: "SQLHelper" has no attribute "hhost"  [attr-defined]
(jcchoiling)learningPython/s13/Day07/practice/ex_obj-oriented_v1.py:25: error: "SQLHelper" has no attribute "uusername"  [attr-defined]
(jcchoiling)learningPython/s13/Day07/practice/ex_obj-oriented_v1.py:26: error: "SQLHelper" has no attribute "pwd"  [attr-defined]
(jcchoiling)learningPython/s13/Day12/practice/sql8.py:14: error: Variable "sql8.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql8.py:14: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql8.py:23: error: Variable "sql8.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql8.py:23: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql5.py:46: error: Variable "sql5.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql5.py:46: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql5.py:57: error: Variable "sql5.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql5.py:57: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql5.py:64: error: Variable "sql5.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql5.py:64: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql3.py:26: error: Variable "sql3.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql3.py:26: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql3.py:33: error: Variable "sql3.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql3.py:33: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql3.py:40: error: Variable "sql3.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql3.py:40: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql6.py:20: error: Variable "sql6.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql6.py:20: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql6.py:32: error: Variable "sql6.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql6.py:32: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql6.py:42: error: Variable "sql6.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql6.py:42: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql2.py:48: error: Variable "sql2.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql2.py:48: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql2.py:60: error: Variable "sql2.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql2.py:60: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql2.py:70: error: Variable "sql2.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql2.py:70: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day08/practice/s11.py:7: error: "Foo" has no attribute "_Foo__name"  [attr-defined]
(jcchoiling)learningPython/s13/Day08/practice/s11.py:9: error: Name '' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day08/practice/s11.py:9: error: Name '' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day03/practice/lambda.py:7: error: Cannot infer type of lambda  [misc]
(jcchoiling)learningPython/s13/Day03/practice/lambda.py:7: error: Incompatible types in assignment (expression has type "Callable[[Any, Any], Any]", variable has type "Callable[[Any], Any]")  [assignment]
(jcchoiling)learningPython/s13/Day03/practice/lambda.py:12: error: Too many arguments  [call-arg]
(jcchoiling)learningPython/s13/Day03/practice/functionOps.py:124: error: "help" does not return a value  [func-returns-value]
(jcchoiling)learningPython/s13/Day05/practice/day5_ex1.py:5: error: Need type annotation for 'USER_INFO' (hint: "USER_INFO: Dict[<type>, <type>] = ...")  [var-annotated]
(jcchoiling)learningPython/s13/Day05/practice/day5_ex2.py:9: error: Need type annotation for 'USER_INFO' (hint: "USER_INFO: Dict[<type>, <type>] = ...")  [var-annotated]
(jcchoiling)learningPython/s13/Day04/practice/registerOps.py:67: error: Name 'alex' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day04/practice/registerOps.py:67: error: Name 'gmail' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day04/practice/registerOps.py:67: error: Name 'alex999' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day04/practice/registerOps.py:68: error: Name 'janice' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day04/practice/registerOps.py:68: error: Name 'gmail' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day04/practice/registerOps.py:68: error: Name 'janice123' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day04/practice/registerOps.py:69: error: Name 'peter' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day04/practice/registerOps.py:69: error: Name 'gamil' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day04/practice/registerOps.py:69: error: Name 'peter123' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day04/practice/registerOps.py:70: error: Name 'admin' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day04/practice/registerOps.py:70: error: Name 'gmail' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day04/practice/registerOps.py:70: error: Name 'admin123' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day04/practice/filterOps.py:126: error: Argument 1 to "join" of "str" has incompatible type "Tuple[object, object, object]"; expected "Iterable[str]"  [arg-type]
(jcchoiling)learningPython/s13/Day11/practice/f1.py:30: error: Name 'env' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day11/practice/f1.py:35: error: Name 'env' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day11/practice/f1.py:36: error: Name 'env' is not defined  [name-defined]
(jcchoiling)learningPython/books/pythonoop/design_pattern/ShapeFactory.py:26: error: "ShapeFactory" has no attribute "draw"  [attr-defined]
(jcchoiling)learningPython/books/pythonoop/design_pattern/ShapeFactory.py:29: error: "ShapeFactory" has no attribute "draw"  [attr-defined]
(jcchoiling)learningPython/books/pythonoop/design_pattern/ShapeFactory.py:32: error: "ShapeFactory" has no attribute "draw"  [attr-defined]
(jcchoiling)learningPython/books/pythonoop/design_pattern/ShapeFactory.py:35: error: "ShapeFactory" has no attribute "draw"  [attr-defined]
(jcchoiling)learningPython/books/pythonoop/design_pattern/ShapeFactory.py:38: error: "ShapeFactory" has no attribute "draw"  [attr-defined]
(jcchoiling)learningPython/books/pythonoop/SecretString.py:24: error: "SecretString" has no attribute "_SecretString__plain_string"  [attr-defined]
(jcchoiling)learningPython/books/learn-python-the-hard-way/ex24_More_Practise.py:37: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(jcchoiling)learningPython/s13/Day12/practice/sql4.py:47: error: Variable "sql4.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql4.py:47: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql4.py:54: error: Variable "sql4.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql4.py:54: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql4.py:60: error: Variable "sql4.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql4.py:60: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/practice/sql4.py:67: error: Variable "sql4.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/practice/sql4.py:67: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/SSHClient.py:24: error: Variable "SSHClient.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/SSHClient.py:24: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/SSHClient.py:33: error: Variable "SSHClient.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/SSHClient.py:33: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/SSHClient.py:47: error: Variable "SSHClient.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day12/SSHClient.py:47: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day12/SSHClient.py:179: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(jcchoiling)learningPython/s13/Day12/SSHClient.py:180: error: Unsupported operand types for - ("str" and "int")  [operator]
(jcchoiling)learningPython/s13/Day12/SSHClient.py:181: error: Unsupported operand types for - ("str" and "int")  [operator]
(jcchoiling)learningPython/s13/Day12/SSHClient.py:182: error: Unsupported operand types for - ("str" and "int")  [operator]
(jcchoiling)learningPython/s13/Day08/Person.py:8: error: Need type annotation for 'avatar_list' (hint: "avatar_list: List[<type>] = ...")  [var-annotated]
(jcchoiling)learningPython/s13/Day08/Person.py:15: error: Need type annotation for 'USER_INFO' (hint: "USER_INFO: Dict[<type>, <type>] = ...")  [var-annotated]
(jcchoiling)learningPython/s13/Day05/modules/core/shopping.py:13: error: Need type annotation for 'purchase_history' (hint: "purchase_history: List[<type>] = ...")  [var-annotated]
(jcchoiling)learningPython/books/learn-python-the-hard-way/ex26_correct_a_file.py:78: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(jcchoiling)learningPython/treehouse/pythonSeries/oobasic/characters.py:29: error: Too few arguments for "Thief"  [call-arg]
(jcchoiling)learningPython/treehouse/pythonSeries/diary.py:9: error: Name 'SqliteDatabase' is not defined  [name-defined]
(jcchoiling)learningPython/treehouse/pythonSeries/diary.py:12: error: Name 'Model' is not defined  [name-defined]
(jcchoiling)learningPython/treehouse/pythonSeries/diary.py:13: error: Name 'TextField' is not defined  [name-defined]
(jcchoiling)learningPython/treehouse/pythonSeries/diary.py:14: error: Name 'DateTimeField' is not defined  [name-defined]
(jcchoiling)learningPython/s13/Day05/modules/core/atm.py:15: error: Need type annotation for 'BANK' (hint: "BANK: Dict[<type>, <type>] = ...")  [var-annotated]
(jcchoiling)learningPython/s13/Day11/practice/s21.py:54: error: Name 'put' already defined on line 12  [no-redef]
(jcchoiling)learningPython/s13/Day13/core/models.py:17: error: Variable "models.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day13/core/models.py:17: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day13/core/models.py:25: error: Variable "models.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day13/core/models.py:25: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day13/core/models.py:35: error: Variable "models.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day13/core/models.py:35: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day13/core/models.py:52: error: Variable "models.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day13/core/models.py:52: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day13/core/models.py:69: error: Variable "models.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day13/core/models.py:69: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day13/core/models.py:76: error: Variable "models.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day13/core/models.py:76: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day13/core/models.py:91: error: Variable "models.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day13/core/models.py:91: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day13/practice/s3.py:24: error: Variable "s3.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day13/practice/s3.py:24: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day13/practice/s3.py:33: error: Variable "s3.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day13/practice/s3.py:33: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day13/practice/s3.py:48: error: Variable "s3.Base" is not valid as a type  [valid-type]
(jcchoiling)learningPython/s13/Day13/practice/s3.py:48: error: Invalid base class "Base"  [misc]
(jcchoiling)learningPython/s13/Day13/practice/s3.py:253: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(jcchoiling)learningPython/s13/Day13/practice/s3.py:254: error: Unsupported operand types for - ("str" and "int")  [operator]
(jcchoiling)learningPython/s13/Day13/practice/s3.py:255: error: Unsupported operand types for - ("str" and "int")  [operator]
(jcchoiling)learningPython/s13/Day13/practice/s3.py:256: error: Unsupported operand types for - ("str" and "int")  [operator]
(jcchoiling)learningPython/s13/Day09/practice/ftp_s1.py:46: error: Unexpected keyword argument "cmds" for "print"  [call-arg]
(jcchoiling)learningPython/s13/Day09/practice/ftp_s1.py:48: error: Module has no attribute "split"  [attr-defined]
(jcchoiling)learningPython/s13/Day09/practice/ftp_s1.py:51: error: Module has no attribute "lower"  [attr-defined]
(jcchoiling)learningPython/s13/Day09/practice/ftp_s1.py:54: error: Module has no attribute "lower"  [attr-defined]
(jcchoiling)learningPython/s13/Day09/practice/ftp_s1.py:56: error: Cannot call function of unknown type  [operator]
(jcchoiling)learningPython/s13/Day09/practice/ftp_s1.py:56: error: Module has no attribute "lower"  [attr-defined]
(jcchoiling)learningPython/s13/Day09/practice/ftp_s1.py:58: error: Cannot call function of unknown type  [operator]
(jcchoiling)learningPython/s13/Day09/practice/ftp_s1.py:58: error: Module has no attribute "lower"  [attr-defined]
(jcchoiling)learningPython/s13/Day11/practice/s13.py:16: error: Need type annotation for 'dic' (hint: "dic: Dict[<type>, <type>] = ...")  [var-annotated]
(jcchoiling)learningPython/s13/Day11/practice/s10.py:32: error: Need type annotation for 'li'  [var-annotated]
Found 136 errors in 33 files (checked 139 source files)

[RRepo](mzdhr)weather
(mzdhr)weather/weather.py:76: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(mzdhr)weather/weather.py:77: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(mzdhr)weather/weather.py:78: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(mzdhr)weather/weather.py:79: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(mzdhr)weather/weather.py:80: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(mzdhr)weather/weather.py:81: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(mzdhr)weather/weather.py:83: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(mzdhr)weather/weather.py:84: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(mzdhr)weather/weather.py:85: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
(mzdhr)weather/weather.py:87: error: Argument 1 to "time_converter" has incompatible type "Optional[Any]"; expected "int"  [arg-type]
(mzdhr)weather/weather.py:88: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]
Found 11 errors in 1 file (checked 1 source file)

[RRepo](scivision)soothing-sounds
Success: no issues found in 6 source files

[RRepo](elsehow)moneybot
(elsehow)moneybot/moneybot/utils.py:47: error: Unsupported operand types for - ("float" and "None")  [operator]
(elsehow)moneybot/moneybot/utils.py:47: note: Right operand is of type "Optional[float]"
(elsehow)moneybot/moneybot/utils.py:51: error: Argument 2 to "estimate_value" of "MarketState" has incompatible type "Optional[float]"; expected "float"  [arg-type]
(elsehow)moneybot/moneybot/utils.py:54: error: Unsupported operand types for + ("float" and "None")  [operator]
(elsehow)moneybot/moneybot/utils.py:54: note: Right operand is of type "Optional[float]"
(elsehow)moneybot/moneybot/market/adapters/__init__.py:39: error: Argument 1 to "MarketState" has incompatible type "None"; expected "Dict[str, Dict[str, float]]"  [arg-type]
(elsehow)moneybot/moneybot/market/adapters/__init__.py:41: error: Argument 3 to "MarketState" has incompatible type "None"; expected "datetime"  [arg-type]
(elsehow)moneybot/moneybot/market/adapters/poloniex.py:80: error: Argument 3 to "Order" has incompatible type "Optional[float]"; expected "float"  [arg-type]
Found 6 errors in 3 files (checked 20 source files)

[RRepo](tbaptista)pyafai
(tbaptista)pyafai/pyafai/objects.py:26: error: Module 'pyafai' has no attribute 'Object'; maybe "objects"?  [attr-defined]
(tbaptista)pyafai/examples/bouncer.py:38: error: Module has no attribute "World2D"  [attr-defined]
(tbaptista)pyafai/examples/bouncer.py:39: error: Module has no attribute "Display"  [attr-defined]
(tbaptista)pyafai/examples/grid_example.py:23: error: Name 'pyafai.Display' is not defined  [name-defined]
(tbaptista)pyafai/examples/braitenberg.py:34: error: Name 'pyafai.Object' is not defined  [name-defined]
(tbaptista)pyafai/examples/braitenberg.py:46: error: Name 'pyafai.Perception' is not defined  [name-defined]
(tbaptista)pyafai/examples/braitenberg.py:97: error: Name 'pyafai.Agent' is not defined  [name-defined]
(tbaptista)pyafai/examples/braitenberg.py:161: error: Name 'pyafai.World2D' is not defined  [name-defined]
(tbaptista)pyafai/examples/braitenberg.py:191: error: Name 'pyafai.Display' is not defined  [name-defined]
(tbaptista)pyafai/examples/random_walk.py:27: error: Name 'pyafai.Agent' is not defined  [name-defined]
(tbaptista)pyafai/examples/random_walk.py:48: error: Module has no attribute "World2D"  [attr-defined]
(tbaptista)pyafai/examples/random_walk.py:49: error: Module has no attribute "Display"  [attr-defined]
Found 12 errors in 5 files (checked 6 source files)

[RRepo](aio-libs)aiokafka
(aio-libs)aiokafka/aiokafka/abc.py:48: error: Module has no attribute "abstractmethod"  [attr-defined]
(aio-libs)aiokafka/aiokafka/abc.py:69: error: Module has no attribute "abstractmethod"  [attr-defined]

[RRepo](sorz)ssmanager
Success: no issues found in 3 source files

[RRepo](eirannejad)pyRevit
(eirannejad)pyRevit/pyrevitlib/rpw/utils/rlcompleter.py:36: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 142 source files)

[RRepo](JustArchi)program-y
(JustArchi)program-y/src/programy/utils/services/service.py:39: error: Need type annotation for 'services' (hint: "services: Dict[<type>, <type>] = ...")  [var-annotated]
(JustArchi)program-y/src/programy/dialog.py:43: error: Incompatible types in assignment (expression has type "str", variable has type "None")  [assignment]
(JustArchi)program-y/src/programy/dialog.py:160: error: Need type annotation for '_questions' (hint: "_questions: List[<type>] = ...")  [var-annotated]
(JustArchi)program-y/src/programy/bot.py:28: error: Need type annotation for '_conversations' (hint: "_conversations: Dict[<type>, <type>] = ...")  [var-annotated]
(JustArchi)program-y/src/test/aiml_tests/condition_tests/test_condition_aiml.py:79: error: Name 'test_condition_type3_variant1_default' already defined on line 74  [no-redef]
(JustArchi)program-y/src/test/aiml_tests/get_tests/test_get_aiml.py:46: error: Name 'test_name_get_with_topic' already defined on line 41  [no-redef]
(JustArchi)program-y/src/test/aiml_tests/datetime_tests/test_datetime_aiml.py:9: error: Module has no attribute "util"  [attr-defined]
(JustArchi)program-y/src/programy/brain.py:275: error: Incompatible return value type (got "None", expected "str")  [return-value]
(JustArchi)program-y/src/programy/clients/webchat/chatsrv.py:30: error: Need type annotation for 'api_keys' (hint: "api_keys: List[<type>] = ...")  [var-annotated]
Found 9 errors in 8 files (checked 271 source files)

[RRepo](StanczakDominik)PythonPIC
(StanczakDominik)PythonPIC/pythonpic/tests/test_LongitudinalSolver.py:6: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_FieldSolver.py:6: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_FieldSolver.py:7: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_density_profiles.py:6: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_density_profiles.py:7: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_density_profiles.py:10: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_species.py:4: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_pusher.py:11: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_pusher.py:12: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_pusher.py:13: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/visualization/static_plots.py:8: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/visualization/animation.py:13: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/configs/run_coldplasma.py:5: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/configs/run_wave.py:3: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/configs/run_wave.py:4: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/configs/run_wave.py:5: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/configs/run_beamplasma.py:5: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/configs/run_twostream.py:5: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/configs/run_twostream.py:6: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_plotting.py:8: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_plotting.py:9: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_plotting.py:10: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/tests/test_plotting.py:11: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/classes/simulation.py:12: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/classes/simulation.py:13: error: Relative import climbs too many namespaces  [misc]
(StanczakDominik)PythonPIC/pythonpic/visualization/time_snapshots.py:7: error: Relative import climbs too many namespaces  [misc]
Found 26 errors in 14 files (checked 29 source files)

[RRepo](WPIRoboticsProjects)GRIP-code-generation
Success: no issues found in 3 source files

[RRepo](jzadeh)Aktaion
(jzadeh)Aktaion/python/researchDev/Parse.py:3: error: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \uXXXX escape  [syntax]
Found 1 error in 1 file (checked 34 source files)

[RRepo](raphaelm)django-hierarkey
(raphaelm)django-hierarkey/hierarkey/proxy.py:32: error: Cannot determine type of '_cached_obj'  [has-type]
(raphaelm)django-hierarkey/hierarkey/proxy.py:33: error: Cannot determine type of '_write_cached_obj'  [has-type]
(raphaelm)django-hierarkey/hierarkey/proxy.py:46: error: Cannot determine type of '_cached_obj'  [has-type]
(raphaelm)django-hierarkey/hierarkey/proxy.py:52: error: Incompatible return value type (got "Optional[Any]", expected "Dict[str, Any]")  [return-value]
(raphaelm)django-hierarkey/hierarkey/proxy.py:55: error: Cannot determine type of '_write_cached_obj'  [has-type]
(raphaelm)django-hierarkey/hierarkey/proxy.py:66: error: Incompatible types in assignment (expression has type "None", variable has type "Dict[Any, Any]")  [assignment]
(raphaelm)django-hierarkey/hierarkey/proxy.py:119: error: "type" has no attribute "objects"  [attr-defined]
(raphaelm)django-hierarkey/hierarkey/proxy.py:173: error: Argument 2 to "_unserialize" of "HierarkeyProxy" has incompatible type "Optional[type]"; expected "type"  [arg-type]
Found 8 errors in 1 file (checked 6 source files)

[RRepo](fqxp)nete-gtk
(fqxp)nete-gtk/nete/gui/components/toolbar.py:12: error: Need type annotation for '__gsignals__'  [var-annotated]
(fqxp)nete-gtk/nete/gui/actions.py:2: error: Module 'nete.services' has no attribute 'ui_state_storage'  [attr-defined]
(fqxp)nete-gtk/nete/gui/actions.py:3: error: Module 'nete.gui.services' has no attribute 'config_storage'  [attr-defined]
(fqxp)nete-gtk/tests/nete/gui/services/test_config_storage.py:6: error: Module 'nete.gui.services' has no attribute 'config_storage'  [attr-defined]
(fqxp)nete-gtk/nete/gui/application.py:19: error: Module 'nete.gui.state' has no attribute 'initial_state'  [attr-defined]
Found 5 errors in 4 files (checked 39 source files)

[RRepo](mangaki)mangaki
(mangaki)mangaki/mangaki/mangaki/utils/profile.py:26: error: Need type annotation for 'counts'  [var-annotated]
(mangaki)mangaki/mangaki/mangaki/utils/profile.py:36: error: Unsupported right operand type for in ("object")  [operator]
(mangaki)mangaki/mangaki/mangaki/utils/profile.py:59: error: "str" has no attribute "slug"  [attr-defined]
(mangaki)mangaki/mangaki/mangaki/utils/profile.py:60: error: "str" has no attribute "slug"  [attr-defined]
(mangaki)mangaki/mangaki/mangaki/utils/profile.py:81: error: Need type annotation for 'ranking'  [var-annotated]
(mangaki)mangaki/mangaki/mangaki/utils/logging.py:1: error: Module 'logging' has no attribute 'Formatter'  [attr-defined]
(mangaki)mangaki/mangaki/mangaki/factories.py:35: error: Method must have at least one argument  [misc]
(mangaki)mangaki/mangaki/mangaki/utils/db.py:31: error: Incompatible return value type (got "List[Dict[str, Any]]", expected "List[str]")  [return-value]
(mangaki)mangaki/mangaki/mangaki/utils/archive_export.py:125: error: "object" not callable  [operator]
(mangaki)mangaki/mangaki/mangaki/settings.py:78: error: Incompatible types in assignment (expression has type Tuple[str, str, ... <16 more items>], variable has type Tuple[str, str, ... <15 more items>])  [assignment]
(mangaki)mangaki/mangaki/mangaki/settings.py:85: error: Incompatible types in assignment (expression has type "Tuple[str, ...]", variable has type "Tuple[str, str, str, str, str, str, str, str, str, str, str, str, str, str, str, str, str]")  [assignment]
(mangaki)mangaki/mangaki/mangaki/settings.py:101: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str, str, str, str, str]", variable has type "Tuple[str, str, str, str, str, str, str]")  [assignment]
(mangaki)mangaki/mangaki/mangaki/settings.py:120: error: Incompatible types in assignment (expression has type Tuple[str, str, ... <18 more items>], variable has type Tuple[str, str, ... <15 more items>])  [assignment]
(mangaki)mangaki/mangaki/mangaki/tasks.py:28: error: Incompatible types in assignment (expression has type "None", variable has type "ConnectionPool")  [assignment]
(mangaki)mangaki/mangaki/mangaki/tasks.py:30: error: Incompatible types in assignment (expression has type "None", variable has type "ConnectionPool")  [assignment]
(mangaki)mangaki/mangaki/mangaki/utils/vgmdb.py:11: error: Name 'unicode' is not defined  [name-defined]
Found 16 errors in 8 files (checked 84 source files)

[RRepo](wileykestner)falcon-sqlalchemy-demo
(wileykestner)falcon-sqlalchemy-demo/falcon_web_demo/postgres_people_repository.py:11: error: Variable "postgres_people_repository.Base" is not valid as a type  [valid-type]
(wileykestner)falcon-sqlalchemy-demo/falcon_web_demo/postgres_people_repository.py:11: error: Invalid base class "Base"  [misc]
Found 2 errors in 1 file (checked 14 source files)

[RRepo](meine-stadt-transparent)meine-stadt-transparent
(meine-stadt-transparent)meine-stadt-transparent/mainapp/models/consultation.py:29: error: Missing return statement  [return]
(meine-stadt-transparent)meine-stadt-transparent/mainapp/functions/minio.py:4: error: Module 'minio' has no attribute 'Minio'  [attr-defined]
(meine-stadt-transparent)meine-stadt-transparent/mainapp/views/utils.py:22: error: Need type annotation for 'geodata' (hint: "geodata: Dict[<type>, <type>] = ...")  [var-annotated]
(meine-stadt-transparent)meine-stadt-transparent/mainapp/tests/live/test_account.py:60: error: Argument 1 to "skip" has incompatible type "Callable[[AccountTest], Any]"; expected "str"  [arg-type]
(meine-stadt-transparent)meine-stadt-transparent/mainapp/tests/main/test_citytools.py:9: error: Argument 1 to "skip" has incompatible type "Type[TestCitytools]"; expected "str"  [arg-type]
(meine-stadt-transparent)meine-stadt-transparent/importer/tests/test_cli.py:81: error: Value of type variable "AnyStr" of "parse_qs" cannot be "object"  [type-var]
(meine-stadt-transparent)meine-stadt-transparent/importer/tests/test_cli.py:82: error: Unsupported right operand type for in ("object")  [operator]
(meine-stadt-transparent)meine-stadt-transparent/importer/functions.py:59: error: Need type annotation for 'externalized' (hint: "externalized: List[<type>] = ...")  [var-annotated]
(meine-stadt-transparent)meine-stadt-transparent/importer/loader.py:49: error: Need type annotation for 'empty_page'  [var-annotated]
(meine-stadt-transparent)meine-stadt-transparent/mainapp/functions/document_parsing.py:82: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
(meine-stadt-transparent)meine-stadt-transparent/mainapp/functions/document_parsing.py:96: error: Incompatible types in assignment (expression has type "bytes", variable has type "Optional[str]")  [assignment]
(meine-stadt-transparent)meine-stadt-transparent/mainapp/functions/document_parsing.py:159: error: Need type annotation for 'street_names' (hint: "street_names: List[<type>] = ...")  [var-annotated]
(meine-stadt-transparent)meine-stadt-transparent/mainapp/views/views.py:13: error: Module 'requests.utils' has no attribute 'quote'  [attr-defined]
Found 13 errors in 10 files (checked 99 source files)

[RRepo](potfur)strict-hint
(potfur)strict-hint/strict_hint/strict_hint.py:52: error: "None" has no attribute "parameters"  [attr-defined]
(potfur)strict-hint/strict_hint/strict_hint.py:57: error: "None" has no attribute "parameters"  [attr-defined]
(potfur)strict-hint/strict_hint/strict_hint.py:64: error: "None" has no attribute "parameters"  [attr-defined]
(potfur)strict-hint/strict_hint/strict_hint.py:82: error: "None" has no attribute "return_annotation"  [attr-defined]
(potfur)strict-hint/strict_hint/strict_hint.py:82: error: "None" has no attribute "empty"  [attr-defined]
(potfur)strict-hint/strict_hint/strict_hint.py:85: error: "None" has no attribute "return_annotation"  [attr-defined]
(potfur)strict-hint/strict_hint/strict_hint.py:88: error: "None" has no attribute "return_annotation"  [attr-defined]
(potfur)strict-hint/strict_hint/strict_hint.py:104: error: Missing return statement  [return]
(potfur)strict-hint/strict_hint/strict_hint.py:109: error: "_SpecialForm" has no attribute "__name__"  [attr-defined]
Found 9 errors in 1 file (checked 2 source files)

[RRepo](yinkaisheng)Python-UIAutomation-for-Windows
(yinkaisheng)Python-UIAutomation-for-Windows/demos/collapse_tree_item_under_cursor.py:30: error: Name 'Event' is not defined  [name-defined]
(yinkaisheng)Python-UIAutomation-for-Windows/demos/automation_calculator.py:151: error: Module has no attribute "sys"  [attr-defined]
(yinkaisheng)Python-UIAutomation-for-Windows/demos/automation_calculator.py:161: error: Module has no attribute "kbhit"  [attr-defined]
(yinkaisheng)Python-UIAutomation-for-Windows/demos/automation_devicemanager.py:101: error: Module has no attribute "kbhit"  [attr-defined]
(yinkaisheng)Python-UIAutomation-for-Windows/demos/expand_tree_item_under_cursor.py:60: error: Name 'Event' is not defined  [name-defined]
(yinkaisheng)Python-UIAutomation-for-Windows/demos/hide_window_with_hotkey.py:40: error: Name 'Event' is not defined  [name-defined]
(yinkaisheng)Python-UIAutomation-for-Windows/demos/automation_notepad.py:145: error: Module has no attribute "windll"  [attr-defined]
(yinkaisheng)Python-UIAutomation-for-Windows/demos/automation_help_demo.py:190: error: Module has no attribute "windll"  [attr-defined]
Found 8 errors in 7 files (checked 18 source files)

[RRepo](mdzhang)goodreads-api-client-python
(mdzhang)goodreads-api-client-python/setup.py:16: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(mdzhang)goodreads-api-client-python/setup.py:19: error: Incompatible types in assignment (expression has type "TextIO", variable has type "BinaryIO")  [assignment]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_user_status.py:1: error: Module 'goodreads_api_client.resources' has no attribute 'UserStatus'  [attr-defined]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_topic.py:1: error: Module 'goodreads_api_client.resources' has no attribute 'Topic'  [attr-defined]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_group.py:1: error: Module 'goodreads_api_client.resources' has no attribute 'Group'  [attr-defined]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_series.py:1: error: Module 'goodreads_api_client.resources' has no attribute 'Series'  [attr-defined]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_event.py:1: error: Module 'goodreads_api_client.resources' has no attribute 'Event'  [attr-defined]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_read_status.py:1: error: Module 'goodreads_api_client.resources' has no attribute 'ReadStatus'  [attr-defined]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_recommendation.py:1: error: Module 'goodreads_api_client.resources' has no attribute 'Recommendation'  [attr-defined]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_shelf.py:3: error: Module 'goodreads_api_client.resources' has no attribute 'Shelf'  [attr-defined]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_user.py:1: error: Module 'goodreads_api_client.resources' has no attribute 'User'  [attr-defined]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_book.py:1: error: Module 'goodreads_api_client.resources' has no attribute 'Book'  [attr-defined]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_comment.py:1: error: Module 'goodreads_api_client.resources' has no attribute 'Comment'  [attr-defined]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_author.py:3: error: Module 'goodreads_api_client.resources' has no attribute 'Author'  [attr-defined]
(mdzhang)goodreads-api-client-python/goodreads_api_client/tests/resources/test_review.py:1: error: Module 'goodreads_api_client.resources' has no attribute 'Review'  [attr-defined]
Found 15 errors in 14 files (checked 44 source files)

[RRepo](jasperges)pose_thumbnails
(jasperges)pose_thumbnails/pose_thumbnails/__init__.py:41: error: Cannot resolve name "creation" (possible cyclic definition)  [misc]
(jasperges)pose_thumbnails/pose_thumbnails/__init__.py:43: error: Module 'pose_thumbnails' has no attribute 'creation'  [attr-defined]
(jasperges)pose_thumbnails/setup.py:26: error: Module 'distutils.command.bdist' has no attribute 'bdist'  [attr-defined]
(jasperges)pose_thumbnails/setup.py:37: error: Item "None" of "Optional[Match[Any]]" has no attribute "group"  [union-attr]
Found 4 errors in 2 files (checked 4 source files)

[RRepo](Azure)azure-sdk-for-python
(Azure)azure-sdk-for-python/scripts/templates/_operations_mixin.py:14: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 7144 source files)

[RRepo](klieret)pyplot-hierarchical-pie
(klieret)pyplot-hierarchical-pie/hpie/path.py:13: error: Argument 2 to "__new__" of "tuple" has incompatible type "Iterable[str]"; expected "Iterable[_T_co]"  [arg-type]
(klieret)pyplot-hierarchical-pie/hpie/calc.py:32: error: Need type annotation for 'completed'  [var-annotated]
(klieret)pyplot-hierarchical-pie/hpie/calc.py:118: error: Need type annotation for 'angles' (hint: "angles: Dict[<type>, <type>] = ...")  [var-annotated]
(klieret)pyplot-hierarchical-pie/hpie/calc.py:138: error: Incompatible types in assignment (expression has type "None", variable has type "int")  [assignment]
(klieret)pyplot-hierarchical-pie/hpie/tests/test_path.py:5: error: Relative import climbs too many namespaces  [misc]
(klieret)pyplot-hierarchical-pie/hpie/tests/test_calc.py:5: error: Relative import climbs too many namespaces  [misc]
(klieret)pyplot-hierarchical-pie/hpie/tests/test_calc.py:6: error: Relative import climbs too many namespaces  [misc]
(klieret)pyplot-hierarchical-pie/hpie/tests/test_calc.py:17: error: Name 'Path' is not defined  [name-defined]
(klieret)pyplot-hierarchical-pie/hpie/tests/test_calc.py:24: error: Name 'Path' is not defined  [name-defined]
Found 9 errors in 4 files (checked 8 source files)

[RRepo](wdv4758h)python-everywhere
(wdv4758h)python-everywhere/setup.py:30: error: Need type annotation for 'exclude_from_packages' (hint: "exclude_from_packages: List[<type>] = ...")  [var-annotated]
(wdv4758h)python-everywhere/setup.py:31: error: Need type annotation for 'requires' (hint: "requires: List[<type>] = ...")  [var-annotated]
Found 2 errors in 1 file (checked 6 source files)

[RRepo](enkore)i3pystatus

[RRepo](redzej)graphene-permissions
Success: no issues found in 8 source files

[RRepo](StructuralNeurobiologyLab)SyConn
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:23: error: Relative import climbs too many namespaces  [misc]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:71: error: Argument 1 to "encode" of "str" has incompatible type "bytes"; expected "str"  [arg-type]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:162: error: Incompatible default for argument "shape" (default has type "Tuple[int, int, int, int, int]", argument has type "Tuple[int]")  [assignment]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:208: error: Need type annotation for 'data' (hint: "data: Dict[<type>, <type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:210: error: Incompatible types in assignment (expression has type "List[<nothing>]", variable has type "Dict[Any, Any]")  [assignment]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:219: error: "Dict[Union[str, Any], Any]" has no attribute "append"  [attr-defined]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:251: error: Item "List[Any]" of "Union[Dict[str, Any], List[Any]]" has no attribute "keys"  [union-attr]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:253: error: Invalid index type "Union[str, Any]" for "Union[Dict[str, Any], List[Any]]"; expected type "int"  [index]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:255: error: Invalid index type "Union[str, Any]" for "Union[Dict[str, Any], List[Any]]"; expected type "int"  [index]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:257: error: Argument 1 to "len" has incompatible type "Optional[List[str]]"; expected "Sized"  [arg-type]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:265: error: Value of type "Optional[List[str]]" is not indexable  [index]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:265: error: Invalid index type "int" for "Union[Dict[str, Any], List[Any]]"; expected type "str"  [index]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:268: error: Value of type "Optional[List[str]]" is not indexable  [index]
(StructuralNeurobiologyLab)SyConn/syconn/handler/compression.py:268: error: Invalid index type "int" for "Union[Dict[str, Any], List[Any]]"; expected type "str"  [index]
(StructuralNeurobiologyLab)SyConn/syconn/handler/multiviews.py:12: error: Relative import climbs too many namespaces  [misc]
(StructuralNeurobiologyLab)SyConn/syconn/handler/multiviews.py:15: error: Relative import climbs too many namespaces  [misc]
(StructuralNeurobiologyLab)SyConn/syconn/handler/multiviews.py:472: error: Need type annotation for 'ds_locs_encountered' (hint: "ds_locs_encountered: Dict[<type>, <type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/proc/skel_based_classifier_helper.py:11: error: Relative import climbs too many namespaces  [misc]
(StructuralNeurobiologyLab)SyConn/syconn/proc/skel_based_classifier_helper.py:12: error: Relative import climbs too many namespaces  [misc]
(StructuralNeurobiologyLab)SyConn/syconn/proc/skel_based_classifier_helper.py:13: error: Relative import climbs too many namespaces  [misc]
(StructuralNeurobiologyLab)SyConn/syconn/proc/image.py:20: error: Relative import climbs too many namespaces  [misc]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_tripletnet_local.py:28: error: Need type annotation for 'data_batch_args' (hint: "data_batch_args: Dict[<type>, <type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_tripletnet_local.py:29: error: Need type annotation for 'data_init_kwargs' (hint: "data_init_kwargs: Dict[<type>, <type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_gliaviews.py:28: error: Need type annotation for 'data_batch_args' (hint: "data_batch_args: Dict[<type>, <type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_gliaviews.py:46: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_gliaviews.py:47: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_celltype.py:28: error: Need type annotation for 'data_batch_args' (hint: "data_batch_args: Dict[<type>, <type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_celltype.py:46: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_celltype.py:47: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_tripletnet_SSV.py:29: error: Need type annotation for 'data_batch_args' (hint: "data_batch_args: Dict[<type>, <type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_axonviews.py:28: error: Need type annotation for 'data_batch_args' (hint: "data_batch_args: Dict[<type>, <type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/reps/views.py:11: error: Relative import climbs too many namespaces  [misc]
(StructuralNeurobiologyLab)SyConn/syconn/extraction/block_processing.py:12: error: Name 'pkl' already defined (possibly by an import)  [no-redef]
(StructuralNeurobiologyLab)SyConn/syconn/proc/depr_realignment_trafo.py:10: error: Name 'pkl' already defined (possibly by an import)  [no-redef]
(StructuralNeurobiologyLab)SyConn/syconn/proc/depr_realignment_trafo.py:17: error: Relative import climbs too many namespaces  [misc]
(StructuralNeurobiologyLab)SyConn/syconn/proc/depr_checking.py:10: error: Name 'pkl' already defined (possibly by an import)  [no-redef]
(StructuralNeurobiologyLab)SyConn/syconn/proc/depr_checking.py:14: error: Relative import climbs too many namespaces  [misc]
(StructuralNeurobiologyLab)SyConn/syconn/proc/depr_checking.py:15: error: Relative import climbs too many namespaces  [misc]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/miga.py:12: error: Name 'pkl' already defined (possibly by an import)  [no-redef]
(StructuralNeurobiologyLab)SyConn/scripts/WIP/timing_prediction.py:40: error: Name 'SuperSegmentationDataset' is not defined  [name-defined]
(StructuralNeurobiologyLab)SyConn/scripts/WIP/timing_prediction.py:58: error: Name 'SuperSegmentationObject' is not defined  [name-defined]
(StructuralNeurobiologyLab)SyConn/scripts/WIP/timing_prediction.py:81: error: Name 'np' is not defined  [name-defined]
(StructuralNeurobiologyLab)SyConn/scripts/WIP/timing_prediction.py:94: error: Name 'np' is not defined  [name-defined]
(StructuralNeurobiologyLab)SyConn/scripts/WIP/timing_prediction.py:107: error: Name 'np' is not defined  [name-defined]
(StructuralNeurobiologyLab)SyConn/scripts/WIP/timing_prediction.py:120: error: Name 'global_params' is not defined  [name-defined]
(StructuralNeurobiologyLab)SyConn/syconn/exec/exec_init.py:118: error: Incompatible types in assignment (expression has type "Dict[Any, None]", variable has type "Optional[Callable[..., Any]]")  [assignment]
(StructuralNeurobiologyLab)SyConn/syconn/exec/exec_init.py:120: error: Incompatible types in assignment (expression has type "List[int]", variable has type "Optional[Tuple[int, int, int]]")  [assignment]
(StructuralNeurobiologyLab)SyConn/syconn/exec/exec_init.py:132: error: Argument "args" to "Process" has incompatible type "List[Any]"; expected "Tuple[Any, ...]"  [arg-type]
(StructuralNeurobiologyLab)SyConn/syconn/exec/exec_init.py:156: error: Argument "args" to "Process" has incompatible type "List[Any]"; expected "Tuple[Any, ...]"  [arg-type]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_celltype_e3.py:87: error: Name 's' is not defined  [name-defined]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_celltype_e3.py:92: error: Module has no attribute "jit"  [attr-defined]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_celltype_e3.py:111: error: Need type annotation for 'val_metric_keys' (hint: "val_metric_keys: List[<type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_celltype_e3.py:112: error: Need type annotation for 'val_metric_vals' (hint: "val_metric_vals: List[<type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_gliaviews_e3.py:91: error: Need type annotation for 'val_metric_keys' (hint: "val_metric_keys: List[<type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_gliaviews_e3.py:92: error: Need type annotation for 'val_metric_vals' (hint: "val_metric_vals: List[<type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_axonviews_e3.py:91: error: Need type annotation for 'val_metric_keys' (hint: "val_metric_keys: List[<type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_axonviews_e3.py:92: error: Need type annotation for 'val_metric_vals' (hint: "val_metric_vals: List[<type>] = ...")  [var-annotated]
(StructuralNeurobiologyLab)SyConn/scripts/WIP/object_extraction_benchmark.py:90: error: Need type annotation for 'result_queue'  [var-annotated]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_axonseg.py:94: error: Module has no attribute "jit"  [attr-defined]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/cnn_atn.py:175: error: Incompatible types in assignment (expression has type "DataParallel[Any]", variable has type "D_net_gauss")  [assignment]
Found 60 errors in 22 files (checked 39 source files)

[RRepo](n8henrie)pycookiecheat
Success: no issues found in 2 source files

[RRepo](SexualHealthInnovations)callisto-core
(SexualHealthInnovations)callisto-core/callisto_core/wizard_builder/admin/inlines.py:46: error: "Callable[[QuestionInline, Any], Any]" has no attribute "allow_tags"  [attr-defined]
(SexualHealthInnovations)callisto-core/callisto_core/delivery/utils.py:9: error: Invalid type comment or annotation  [valid-type]
(SexualHealthInnovations)callisto-core/callisto_core/delivery/utils.py:14: error: Invalid type comment or annotation  [valid-type]
(SexualHealthInnovations)callisto-core/callisto_core/delivery/utils.py:24: error: "RecordDataUtil" has no attribute "old_data"  [attr-defined]
(SexualHealthInnovations)callisto-core/callisto_core/delivery/utils.py:25: error: "RecordDataUtil" has no attribute "new_data"  [attr-defined]
(SexualHealthInnovations)callisto-core/callisto_core/delivery/utils.py:27: error: "RecordDataUtil" has no attribute "new_data"  [attr-defined]
(SexualHealthInnovations)callisto-core/callisto_core/delivery/utils.py:58: error: "RecordDataUtil" has no attribute "new_data"  [attr-defined]
(SexualHealthInnovations)callisto-core/callisto_core/delivery/utils.py:71: error: "RecordDataUtil" has no attribute "new_data"  [attr-defined]
(SexualHealthInnovations)callisto-core/callisto_core/delivery/utils.py:84: error: Argument 1 to "_get_choices" of "RecordDataUtil" has incompatible type "Optional[Any]"; expected "List[Any]"  [arg-type]
(SexualHealthInnovations)callisto-core/callisto_core/delivery/utils.py:87: error: Missing return statement  [return]
(SexualHealthInnovations)callisto-core/callisto_core/utils/tenant_api.py:7: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SexualHealthInnovations)callisto-core/callisto_core/utils/tenant_api.py:7: note: Did you mean "List[...]"?
(SexualHealthInnovations)callisto-core/callisto_core/utils/tenant_api.py:8: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SexualHealthInnovations)callisto-core/callisto_core/utils/tenant_api.py:8: note: Did you mean "List[...]"?
(SexualHealthInnovations)callisto-core/callisto_core/delivery/migrations/0010_email_notification_data_migration.py:31: error: Need type annotation for 'database_operations' (hint: "database_operations: List[<type>] = ...")  [var-annotated]
(SexualHealthInnovations)callisto-core/callisto_core/delivery/migrations/0010_email_notification_data_migration.py:39: error: Need type annotation for 'state_operations' (hint: "state_operations: List[<type>] = ...")  [var-annotated]
(SexualHealthInnovations)callisto-core/callisto_core/delivery/migrations/0010_email_notification_data_migration.py:44: error: Need type annotation for 'operations' (hint: "operations: List[<type>] = ...")  [var-annotated]
(SexualHealthInnovations)callisto-core/callisto_core/celeryconfig/celery.py:6: error: Module 'celery' has no attribute 'Celery'  [attr-defined]
(SexualHealthInnovations)callisto-core/callisto_core/delivery/view_helpers.py:87: error: "_LegacyReportStorageHelper" has no attribute "storage_form_key"  [attr-defined]
(SexualHealthInnovations)callisto-core/callisto_core/accounts/tests/test_account_creation.py:17: error: Relative import climbs too many namespaces  [misc]
(SexualHealthInnovations)callisto-core/callisto_core/evaluation/management/commands/decrypt_eval_data.py:11: error: Relative import climbs too many namespaces  [misc]
Found 19 errors in 8 files (checked 48 source files)

[RRepo](anlar)prismriver-lyrics
(anlar)prismriver-lyrics/prismriver/preprocessor.py:4: error: Invalid type comment or annotation  [valid-type]
(anlar)prismriver-lyrics/prismriver/preprocessor.py:11: error: Invalid type comment or annotation  [valid-type]
Found 2 errors in 1 file (checked 69 source files)

[RRepo](SWE574-Nerds)friendly-eureka
(SWE574-Nerds)friendly-eureka/backend/eureka/post/services/ListoryService.py:7: error: Bracketed expression "[...]" is not valid as a type  [misc]
(SWE574-Nerds)friendly-eureka/backend/eureka/post/services/ListoryService.py:7: note: Did you mean "List[...]"?
(SWE574-Nerds)friendly-eureka/backend/eureka/api/dto/LoginForm.py:10: error: Name '__init__' already defined on line 5  [no-redef]
(SWE574-Nerds)friendly-eureka/backend/eureka/api/dto/LoginForm.py:16: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(SWE574-Nerds)friendly-eureka/backend/eureka/api/dto/LoginForm.py:24: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(SWE574-Nerds)friendly-eureka/backend/eureka/api/dto/RegisterForm.py:14: error: Name '__init__' already defined on line 9  [no-redef]
(SWE574-Nerds)friendly-eureka/backend/eureka/api/dto/RegisterForm.py:21: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(SWE574-Nerds)friendly-eureka/backend/eureka/api/dto/RegisterForm.py:29: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(SWE574-Nerds)friendly-eureka/backend/eureka/api/dto/RegisterForm.py:37: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
Found 8 errors in 3 files (checked 18 source files)

[RRepo](webyneter)python-humble-utils
(webyneter)python-humble-utils/tests/test_commands.py:62: error: Argument 1 has incompatible type "Tuple[Any, ...]"; expected "str"  [arg-type]
(webyneter)python-humble-utils/travis_pypi_setup.py:18: error: Module 'urllib' has no attribute 'urlopen'  [attr-defined]
Found 2 errors in 2 files (checked 6 source files)

[RRepo](IlyaGusev)rupo
(IlyaGusev)rupo/rupo/metre/pattern_analyzer.py:46: error: Incompatible return value type (got "None", expected "TreeNode")  [return-value]
(IlyaGusev)rupo/rupo/metre/pattern_analyzer.py:55: error: Incompatible return value type (got "None", expected "TreeNode")  [return-value]
(IlyaGusev)rupo/rupo/metre/pattern_analyzer.py:164: error: Argument 1 to "TreeNode" has incompatible type "None"; expected "TreeNode"  [arg-type]
(IlyaGusev)rupo/rupo/metre/pattern_analyzer.py:192: error: Argument 1 to "State" has incompatible type "None"; expected "TreeNode"  [arg-type]
(IlyaGusev)rupo/rupo/metre/pattern_analyzer.py:228: error: Need type annotation for 'variants' (hint: "variants: Set[<type>] = ...")  [var-annotated]
(IlyaGusev)rupo/rupo/metre/pattern_analyzer.py:260: error: Incompatible return value type (got "None", expected "TreeNode")  [return-value]

[RRepo](belbio)bel_api
(belbio)bel_api/tests/api/test_status.py:11: error: Need type annotation for 'payload' (hint: "payload: Dict[<type>, <type>] = ...")  [var-annotated]
(belbio)bel_api/api/services/edges.py:25: error: Missing return statement  [return]

[RRepo](jdanekrh)dispatch-console-tests
(jdanekrh)dispatch-console-tests/webdriver/page_objects.py:193: error: Incompatible types in assignment (expression has type "None", variable has type "int")  [assignment]

[RRepo](Beomi)irkshop
(Beomi)irkshop/irkshop/celery.py:3: error: Module 'celery' has no attribute 'Celery'  [attr-defined]
(Beomi)irkshop/irkshop/celery.py:3: error: Module 'celery' has no attribute 'Celery'  [attr-defined]
(Beomi)irkshop/irkshop/settings.py:32: error: Incompatible types in assignment (expression has type "None", variable has type "TextIO")  [assignment]

[RRepo](EuroPython)epcon
(EuroPython)epcon/conference/settings.py:142: error: Incompatible types in assignment (expression has type "Tuple[Tuple[str, str], Tuple[str, str]]", variable has type "Tuple[Tuple[str, str], Tuple[str, str], Tuple[str, str], Tuple[str, str]]")  [assignment]
(EuroPython)epcon/conference/talks.py:10: error: Module 'conference.forms' has no attribute 'TalkUpdateForm'  [attr-defined]
(EuroPython)epcon/conference/talks.py:10: error: Module 'conference.forms' has no attribute 'TalkSlidesForm'  [attr-defined]
(EuroPython)epcon/conference/cachef.py:14: error: All conditional function variants must have identical signatures  [misc]
(EuroPython)epcon/p3/management/commands/check_schedule.py:10: error: Relative import climbs too many namespaces  [misc]
(EuroPython)epcon/p3/management/commands/accepted_talks.py:8: error: Relative import climbs too many namespaces  [misc]
(EuroPython)epcon/p3/templatetags/sessions.py:11: error: Relative import climbs too many namespaces  [misc]

[RRepo](mlindauer)AutoFolio
(mlindauer)AutoFolio/autofolio/selector/classifiers/xgboost.py:141: error: Module has no attribute "DMatrix"  [attr-defined]
(mlindauer)AutoFolio/autofolio/selector/classifiers/xgboost.py:142: error: Module has no attribute "train"  [attr-defined]
(mlindauer)AutoFolio/autofolio/pre_solving/aspeed_schedule.py:83: error: Need type annotation for 'schedule' (hint: "schedule: List[<type>] = ...")  [var-annotated]
(mlindauer)AutoFolio/autofolio/pre_solving/aspeed_schedule.py:145: error: Need type annotation for 'schedule_dict' (hint: "schedule_dict: Dict[<type>, <type>] = ...")  [var-annotated]
(mlindauer)AutoFolio/autofolio/validation/validate.py:241: error: Name 'sys' is not defined  [name-defined]
(mlindauer)AutoFolio/scripts/plot_config.py:7: error: Argument 1 to "getfile" has incompatible type "Optional[FrameType]"; expected "Union[Module, Type[Any], MethodType, FunctionType, TracebackType, FrameType, CodeType, Callable[..., Any]]"  [arg-type]
Found 6 errors in 4 files (checked 15 source files)

[RRepo](thorrak)fermentrack
(thorrak)fermentrack/gravity/gravity_debug.py:48: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 36 source files)

[RRepo](RulersOfAsgard)ALAMO-worker
(RulersOfAsgard)ALAMO-worker/alamo_worker/plugins/graphite.py:55: error: Ellipses cannot accompany other argument types in function type signature  [syntax]
Found 1 error in 1 file (checked 47 source files)

[RRepo](cprogrammer1994)GLWindow
(cprogrammer1994)GLWindow/GLWindow/mock.py:13: error: Name 'Window' is not defined  [name-defined]
(cprogrammer1994)GLWindow/GLWindow/mock.py:18: error: Name 'Window' is not defined  [name-defined]
(cprogrammer1994)GLWindow/docs/conf.py:27: error: Need type annotation for 'exclude_patterns' (hint: "exclude_patterns: List[<type>] = ...")  [var-annotated]
(cprogrammer1994)GLWindow/docs/conf.py:39: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
(cprogrammer1994)GLWindow/GLWindow/__init__.py:22: error: Module 'GLWindow' has no attribute 'glwnd'  [attr-defined]
(cprogrammer1994)GLWindow/GLWindow/__init__.py:38: error: Module 'GLWindow' has no attribute 'keys'  [attr-defined]
Found 6 errors in 3 files (checked 3 source files)

[RRepo](kimjinyong)i2nsf-framework
(kimjinyong)i2nsf-framework/Hackathon-104/stack/openstack_server.py:10: error: inconsistent use of tabs and spaces in indentation  [syntax]
Found 1 error in 1 file (checked 45 source files)

