[RRepo](cyberkov)home-assistant-config
Success: no issues found in 1 source file

[RRepo](leonidumanskiy)scheduledtask
(leonidumanskiy)scheduledtask/scheduledtask/utils.py:5: error: Invalid type comment or annotation  [valid-type]
(leonidumanskiy)scheduledtask/scheduledtask/utils.py:24: error: Invalid type comment or annotation  [valid-type]
(leonidumanskiy)scheduledtask/scheduledtask/utils.py:43: error: Invalid type comment or annotation  [valid-type]
(leonidumanskiy)scheduledtask/scheduledtask/utils.py:54: error: Invalid type comment or annotation  [valid-type]
Found 4 errors in 1 file (checked 2 source files)

[RRepo](cedricbonhomme)Stegano
Success: no issues found in 15 source files

[RRepo](lbryio)lbrycrd

[RRepo](danthelion)pyet
Success: no issues found in 1 source file

[RRepo](padmec-reservoir)ELLIPTIc
(padmec-reservoir)ELLIPTIc/examples/DSL_Example/src/DSLImpl.py:88: error: Incompatible types in assignment (expression has type "str", variable has type "int")  [assignment]
(padmec-reservoir)ELLIPTIc/examples/DSL_Example/src/DSLImpl.py:107: error: Incompatible types in assignment (expression has type "str", variable has type "int")  [assignment]
(padmec-reservoir)ELLIPTIc/elliptic/Kernel/Expression.py:72: error: Unsupported left operand type for + ("Iterable[Any]")  [operator]
(padmec-reservoir)ELLIPTIc/elliptic/Kernel/DSL.py:65: error: Incompatible types in assignment (expression has type "None", variable has type Module)  [assignment]
(padmec-reservoir)ELLIPTIc/elliptic/Kernel/TreeBuilder.py:35: error: Incompatible types in assignment (expression has type "None", variable has type Module)  [assignment]
Found 5 errors in 4 files (checked 14 source files)

[RRepo](SectorLabs)django-localized-fields
(SectorLabs)django-localized-fields/localized_fields/value.py:27: error: Signature of "get" incompatible with supertype "Mapping"  [override]
(SectorLabs)django-localized-fields/localized_fields/value.py:69: error: Incompatible return value type (got "Tuple[str, List[Dict[str, Any]], Dict[<nothing>, <nothing>]]", expected "Dict[Any, Any]")  [return-value]
(SectorLabs)django-localized-fields/localized_fields/value.py:182: error: Incompatible types in assignment (expression has type "str", base class "LocalizedValue" defined the type as "None")  [assignment]
(SectorLabs)django-localized-fields/localized_fields/fields/char_field.py:1: error: Relative import climbs too many namespaces  [misc]
(SectorLabs)django-localized-fields/localized_fields/fields/char_field.py:3: error: Relative import climbs too many namespaces  [misc]
(SectorLabs)django-localized-fields/localized_fields/fields/integer_field.py:7: error: Relative import climbs too many namespaces  [misc]
(SectorLabs)django-localized-fields/localized_fields/fields/integer_field.py:8: error: Relative import climbs too many namespaces  [misc]
(SectorLabs)django-localized-fields/localized_fields/fields/integer_field.py:49: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")  [return-value]
(SectorLabs)django-localized-fields/localized_fields/fields/integer_field.py:89: error: Incompatible types in assignment (expression has type "None", target has type "int")  [assignment]
(SectorLabs)django-localized-fields/localized_fields/fields/text_field.py:1: error: Relative import climbs too many namespaces  [misc]
(SectorLabs)django-localized-fields/localized_fields/forms.py:29: error: Unsupported right operand type for in ("Union[bool, List[str]]")  [operator]
(SectorLabs)django-localized-fields/localized_fields/forms.py:46: error: Variable "forms.LocalizedFieldForm.value_class" is not valid as a type  [valid-type]
(SectorLabs)django-localized-fields/localized_fields/forms.py:61: error: Incompatible types in assignment (expression has type "str", variable has type "List[str]")  [assignment]

[RRepo](saurabh1e)SuperFlaskSeed
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:15: error: Need type annotation for 'filters' (hint: "filters: Dict[<type>, <type>] = ...")  [var-annotated]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:21: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:25: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:27: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:29: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:31: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:41: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:43: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:184: error: Invalid type comment or annotation  [valid-type]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:184: note: Suggestion: use Type[...] instead of Type(...)
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:205: error: Need type annotation for 'filters' (hint: "filters: Dict[<type>, <type>] = ...")  [var-annotated]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:211: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:215: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:217: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:219: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:221: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:227: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
(saurabh1e)SuperFlaskSeed/web/src/utils/resource.py:229: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[str]")  [assignment]
Found 17 errors in 1 file (checked 7 source files)

[RRepo](ulikoehler)UliEngineering
(ulikoehler)UliEngineering/tests/Electronics/TestTemperatureCoefficient.py:13: error: Assertion is always true, perhaps remove parentheses?  [misc]
(ulikoehler)UliEngineering/tests/Electronics/TestTemperatureCoefficient.py:19: error: Assertion is always true, perhaps remove parentheses?  [misc]
(ulikoehler)UliEngineering/tests/Electronics/TestVoltageDivider.py:43: error: Name 'test_feedback_voltage' already defined on line 38  [no-redef]
(ulikoehler)UliEngineering/tests/Physics/TestTemperature.py:41: error: Name 'InvalidUnitException' is not defined  [name-defined]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestFilter.py:105: error: Name 'NotComputedException' is not defined  [name-defined]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestFilter.py:110: error: Name 'NotComputedException' is not defined  [name-defined]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestFilter.py:115: error: Name 'FilterUnstableError' is not defined  [name-defined]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestFilter.py:126: error: Name 'NotComputedException' is not defined  [name-defined]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestFilter.py:206: error: Name 'FilterInvalidError' is not defined  [name-defined]
(ulikoehler)UliEngineering/UliEngineering/Electronics/PowerFactor.py:11: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/PowerFactor.py:11: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:18: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:18: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:49: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:49: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:85: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:85: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:90: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:90: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:106: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:106: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:122: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:122: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:138: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:138: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:154: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Crystal.py:154: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Inductors.py:12: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Inductors.py:12: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/MOSFET.py:12: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/MOSFET.py:12: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/MOSFET.py:35: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/MOSFET.py:35: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:19: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:19: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:27: error: Name 'parallel_resistors' is not defined  [name-defined]
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:29: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:29: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:38: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:38: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:50: error: Name 'current_through_resistor' is not defined  [name-defined]
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:92: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:92: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:101: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:101: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:110: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:110: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:132: error: Name 'parallel_resistors' is not defined  [name-defined]
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:134: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:134: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:155: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:155: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/VoltageDivider.py:171: error: Name 'parallel_resistors' is not defined  [name-defined]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Power.py:11: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Power.py:11: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Power.py:21: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Power.py:21: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Capacitors.py:9: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Capacitors.py:9: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Capacitors.py:27: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Capacitors.py:27: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Capacitors.py:39: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Capacitors.py:39: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Reactance.py:14: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Reactance.py:14: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Reactance.py:23: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Reactance.py:23: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/OpAmp.py:16: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/OpAmp.py:16: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/LED.py:39: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/LED.py:39: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/Frequency.py:13: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/Frequency.py:13: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/Frequency.py:27: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/Frequency.py:27: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/NTC.py:17: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/NTC.py:17: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/RF.py:14: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/RF.py:14: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/RF.py:30: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/RF.py:30: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/RF.py:47: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/RF.py:47: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/RF.py:65: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/RF.py:65: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/NoiseDensity.py:10: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/NoiseDensity.py:10: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/NoiseDensity.py:23: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/NoiseDensity.py:23: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:21: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:21: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:25: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:25: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:29: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:29: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:33: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:33: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:36: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:36: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:60: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:60: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:64: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/Temperature.py:64: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Math/Decibel.py:22: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Math/Decibel.py:22: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Math/Decibel.py:57: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Math/Decibel.py:57: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Math/Decibel.py:72: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Math/Decibel.py:72: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Math/Decibel.py:88: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Math/Decibel.py:88: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Math/Decibel.py:97: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Math/Decibel.py:97: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Math/Decibel.py:106: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Math/Decibel.py:106: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Length.py:50: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Length.py:50: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Length.py:58: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Length.py:58: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/tests/Math/TestGeometry.py:45: error: Name 'test_polygon_area_rectangle' already defined on line 37  [no-redef]
(ulikoehler)UliEngineering/tests/Utils/TestNumPy.py:67: error: Name 'test_ngrams2' already defined on line 54  [no-redef]
(ulikoehler)UliEngineering/tests/Utils/TestNumPy.py:102: error: Name 'test_timedelta64_resolution' already defined on line 91  [no-redef]
(ulikoehler)UliEngineering/tests/TestEngineerIO.py:165: error: Name 'test_exp_suffix_map' already defined on line 153  [no-redef]
(ulikoehler)UliEngineering/tests/TestEngineerIO.py:190: error: Name 'test_normalize_numeric_invalid' already defined on line 56  [no-redef]
(ulikoehler)UliEngineering/tests/TestEngineerIO.py:210: error: Name 'UnannotatedReturnValueError' is not defined  [name-defined]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:42: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:42: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:58: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:58: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:74: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:74: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:91: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:91: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:123: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:123: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:129: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:129: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:137: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:137: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:146: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Resistors.py:146: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Microstrip.py:37: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Microstrip.py:37: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Electronics/Microstrip.py:81: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Electronics/Microstrip.py:81: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/RTD.py:39: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/RTD.py:39: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/RTD.py:50: error: Unsupported operand types for > ("float" and "Number")  [operator]
(ulikoehler)UliEngineering/UliEngineering/Physics/RTD.py:56: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/RTD.py:56: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/SignalProcessing/Simulation.py:61: error: Incompatible types in assignment (expression has type "Callable[[VarArg(Any), KwArg(Any)], Any]", variable has type "partial[Any]")  [assignment]
(ulikoehler)UliEngineering/UliEngineering/SignalProcessing/Simulation.py:62: error: Incompatible types in assignment (expression has type "Callable[[VarArg(Any), KwArg(Any)], Any]", variable has type "partial[Any]")  [assignment]
(ulikoehler)UliEngineering/UliEngineering/SignalProcessing/Simulation.py:63: error: Incompatible types in assignment (expression has type "Callable[[VarArg(Any), KwArg(Any)], Any]", variable has type "partial[Any]")  [assignment]
(ulikoehler)UliEngineering/UliEngineering/SignalProcessing/Simulation.py:64: error: Incompatible types in assignment (expression has type "Callable[[VarArg(Any), KwArg(Any)], Any]", variable has type "partial[Any]")  [assignment]
(ulikoehler)UliEngineering/UliEngineering/Physics/JohnsonNyquistNoise.py:27: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/JohnsonNyquistNoise.py:27: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/UliEngineering/Physics/JohnsonNyquistNoise.py:40: error: Invalid type comment or annotation  [valid-type]
(ulikoehler)UliEngineering/UliEngineering/Physics/JohnsonNyquistNoise.py:40: note: Suggestion: use Unit[...] instead of Unit(...)
(ulikoehler)UliEngineering/tests/SignalProcessing/TestWindow.py:23: error: Name 'testWindowFunctor' already defined on line 12  [no-redef]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestSimulation.py:50: error: Name 'sine_wave' is not defined  [name-defined]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestSimulation.py:51: error: Name 'cosine_wave' is not defined  [name-defined]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestSimulation.py:52: error: Name 'square_wave' is not defined  [name-defined]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestSimulation.py:53: error: Name 'triangle_wave' is not defined  [name-defined]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestSimulation.py:54: error: Name 'sawtooth' is not defined  [name-defined]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestSimulation.py:55: error: Name 'inverse_sawtooth' is not defined  [name-defined]
Found 98 errors in 31 files (checked 101 source files)

[RRepo](flopp)unicode-explorer
Success: no issues found in 4 source files

[RRepo](jamesacampbell)python-examples
(jamesacampbell)python-examples/tor-example.py:29: error: Cannot assign to a type  [misc]
(jamesacampbell)python-examples/tor-example.py:48: error: Module has no attribute "error"  [attr-defined]
(jamesacampbell)python-examples/scrape_twitter-example.py:41: error: Need type annotation for 'diction' (hint: "diction: List[<type>] = ...")  [var-annotated]
(jamesacampbell)python-examples/scrape_twitter-example.py:42: error: Need type annotation for 'subset' (hint: "subset: List[<type>] = ...")  [var-annotated]
(jamesacampbell)python-examples/stem_tor-example.py:16: error: Cannot find replacement for positional format specifier 1  [str-format]
(jamesacampbell)python-examples/flask-example.py:40: error: Missing return statement  [return]
Found 6 errors in 4 files (checked 26 source files)

[RRepo](Techcable)DiffUtils
(Techcable)DiffUtils/diffutils/__main__.py:46: error: Incompatible types in assignment (expression has type "IO[Any]", variable has type "TextIO")  [assignment]
(Techcable)DiffUtils/diffutils/__main__.py:62: error: Incompatible types in assignment (expression has type "None", variable has type "List[str]")  [assignment]
(Techcable)DiffUtils/diffutils/__main__.py:71: error: Incompatible types in assignment (expression has type "IO[Any]", variable has type "TextIO")  [assignment]
(Techcable)DiffUtils/diffutils/core.py:120: error: Incompatible types in assignment (expression has type "Type[DeleteDelta]", variable has type "Type[ChangeDelta]")  [assignment]
(Techcable)DiffUtils/diffutils/core.py:122: error: Incompatible types in assignment (expression has type "Type[InsertDelta]", variable has type "Type[ChangeDelta]")  [assignment]
(Techcable)DiffUtils/diffutils/_myers.py:23: error: Module 'typing' has no attribute 'T'  [attr-defined]
(Techcable)DiffUtils/diffutils/_myers.py:93: error: "list" is not subscriptable, use "typing.List" instead  [misc]
(Techcable)DiffUtils/diffutils/_myers.py:104: error: Item "None" of "Optional[DiffNode]" has no attribute "i"  [union-attr]
(Techcable)DiffUtils/diffutils/_myers.py:105: error: Item "None" of "Optional[DiffNode]" has no attribute "i"  [union-attr]
(Techcable)DiffUtils/diffutils/_myers.py:108: error: Item "None" of "Optional[DiffNode]" has no attribute "i"  [union-attr]
(Techcable)DiffUtils/diffutils/_myers.py:129: error: Incompatible return value type (got "Optional[DiffNode]", expected "DiffNode")  [return-value]
(Techcable)DiffUtils/diffutils/_myers.py:149: error: "DiffNode" has no attribute "prev"  [attr-defined]
(Techcable)DiffUtils/diffutils/_myers.py:150: error: "DiffNode" has no attribute "prev"  [attr-defined]
(Techcable)DiffUtils/diffutils/_myers.py:156: error: "DiffNode" has no attribute "prev"  [attr-defined]
(Techcable)DiffUtils/diffutils/_myers.py:166: error: "DiffNode" has no attribute "prev"  [attr-defined]
(Techcable)DiffUtils/diffutils/engine.py:67: error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "List[Any]")  [assignment]
Found 16 errors in 4 files (checked 6 source files)

[RRepo](idaks)PW-explorer
(idaks)PW-explorer/PW_explorer/Custom_Visualization_Functions/four_colorability_visualization.py:4: error: Relative import climbs too many namespaces  [misc]
(idaks)PW-explorer/PW_explorer/Custom_Visualization_Functions/graphviz_meta_data_based_visualization.py:3: error: Relative import climbs too many namespaces  [misc]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Meta_Data_Parser/Antlr_Files/PWE_ASP_Meta_DataListener.py:9: error: Name 'ParseTreeListener' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Meta_Data_Parser/Antlr_Files/PWE_ASP_Meta_DataLexer.py:43: error: Name 'Lexer' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Meta_Data_Parser/Antlr_Files/PWE_ASP_Meta_DataLexer.py:45: error: Name 'ATNDeserializer' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Meta_Data_Parser/Antlr_Files/PWE_ASP_Meta_DataLexer.py:47: error: Name 'DFA' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Meta_Data_Parser/Antlr_Files/PWE_ASP_Meta_DataLexer.py:82: error: Name 'LexerATNSimulator' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Meta_Data_Parser/Antlr_Files/PWE_ASP_Meta_DataLexer.py:82: error: Name 'PredictionContextCache' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/DLV_Parser/Antlr_Files/DLV_OutListener.py:9: error: Name 'ParseTreeListener' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/DLV_Parser/Antlr_Files/DLV_OutLexer.py:47: error: Name 'Lexer' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/DLV_Parser/Antlr_Files/DLV_OutLexer.py:49: error: Name 'ATNDeserializer' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/DLV_Parser/Antlr_Files/DLV_OutLexer.py:51: error: Name 'DFA' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/DLV_Parser/Antlr_Files/DLV_OutLexer.py:86: error: Name 'LexerATNSimulator' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/DLV_Parser/Antlr_Files/DLV_OutLexer.py:86: error: Name 'PredictionContextCache' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/DLV_Parser/dlv_parser.py:5: error: Relative import climbs too many namespaces  [misc]
(idaks)PW-explorer/PW_explorer/Input_Parsers/DLV_Parser/dlv_parser.py:162: error: Need type annotation for 'rel_keys' (hint: "rel_keys: List[<type>] = ...")  [var-annotated]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Clingo_Parser/Antlr_Files/ClingoLexer.py:62: error: Name 'Lexer' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Clingo_Parser/Antlr_Files/ClingoLexer.py:64: error: Name 'ATNDeserializer' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Clingo_Parser/Antlr_Files/ClingoLexer.py:66: error: Name 'DFA' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Clingo_Parser/Antlr_Files/ClingoLexer.py:103: error: Name 'LexerATNSimulator' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Clingo_Parser/Antlr_Files/ClingoLexer.py:103: error: Name 'PredictionContextCache' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Clingo_Parser/Antlr_Files/ClingoListener.py:9: error: Name 'ParseTreeListener' is not defined  [name-defined]
(idaks)PW-explorer/PW_explorer/Input_Parsers/Clingo_Parser/clingo_parser.py:5: error: Relative import climbs too many namespaces  [misc]
(idaks)PW-explorer/PW_explorer/query.py:41: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(idaks)PW-explorer/PW_explorer/query.py:41: note: Possible overload variants:
(idaks)PW-explorer/PW_explorer/query.py:41: note:     def __getitem__(self, int) -> Any
(idaks)PW-explorer/PW_explorer/query.py:41: note:     def __getitem__(self, slice) -> List[Any]
(idaks)PW-explorer/PW_explorer/query.py:43: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(idaks)PW-explorer/PW_explorer/query.py:43: note: Possible overload variants:
(idaks)PW-explorer/PW_explorer/query.py:43: note:     def __getitem__(self, int) -> Any
(idaks)PW-explorer/PW_explorer/query.py:43: note:     def __getitem__(self, slice) -> List[Any]
(idaks)PW-explorer/PW_explorer/query.py:74: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(idaks)PW-explorer/PW_explorer/query.py:74: note: Possible overload variants:
(idaks)PW-explorer/PW_explorer/query.py:74: note:     def __getitem__(self, int) -> Any
(idaks)PW-explorer/PW_explorer/query.py:74: note:     def __getitem__(self, slice) -> List[Any]
(idaks)PW-explorer/PW_explorer/query.py:82: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(idaks)PW-explorer/PW_explorer/query.py:82: note: Possible overload variants:
(idaks)PW-explorer/PW_explorer/query.py:82: note:     def __getitem__(self, int) -> Any
(idaks)PW-explorer/PW_explorer/query.py:82: note:     def __getitem__(self, slice) -> List[Any]
(idaks)PW-explorer/PW_explorer/query.py:85: error: Incompatible types in assignment (expression has type "int", variable has type "List[List[Any]]")  [assignment]
(idaks)PW-explorer/PW_explorer/query.py:86: error: No overload variant of "__getitem__" of "list" matches argument type "List[List[Any]]"  [call-overload]
(idaks)PW-explorer/PW_explorer/query.py:86: note: Possible overload variants:
(idaks)PW-explorer/PW_explorer/query.py:86: note:     def __getitem__(self, int) -> Any
(idaks)PW-explorer/PW_explorer/query.py:86: note:     def __getitem__(self, slice) -> List[Any]
(idaks)PW-explorer/PW_explorer/query.py:103: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(idaks)PW-explorer/PW_explorer/query.py:103: note: Possible overload variants:
(idaks)PW-explorer/PW_explorer/query.py:103: note:     def __getitem__(self, int) -> Any
(idaks)PW-explorer/PW_explorer/query.py:103: note:     def __getitem__(self, slice) -> List[Any]
(idaks)PW-explorer/PW_explorer/query.py:114: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(idaks)PW-explorer/PW_explorer/query.py:114: note: Possible overload variants:
(idaks)PW-explorer/PW_explorer/query.py:114: note:     def __getitem__(self, int) -> Any
(idaks)PW-explorer/PW_explorer/query.py:114: note:     def __getitem__(self, slice) -> List[Any]
(idaks)PW-explorer/PW_explorer/query.py:116: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(idaks)PW-explorer/PW_explorer/query.py:116: note: Possible overload variants:
(idaks)PW-explorer/PW_explorer/query.py:116: note:     def __getitem__(self, int) -> Any
(idaks)PW-explorer/PW_explorer/query.py:116: note:     def __getitem__(self, slice) -> List[Any]
(idaks)PW-explorer/PW_explorer/query.py:134: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(idaks)PW-explorer/PW_explorer/query.py:134: note: Possible overload variants:
(idaks)PW-explorer/PW_explorer/query.py:134: note:     def __getitem__(self, int) -> Any
(idaks)PW-explorer/PW_explorer/query.py:134: note:     def __getitem__(self, slice) -> List[Any]
(idaks)PW-explorer/PW_explorer/query.py:155: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(idaks)PW-explorer/PW_explorer/query.py:155: note: Possible overload variants:
(idaks)PW-explorer/PW_explorer/query.py:155: note:     def __getitem__(self, int) -> Any
(idaks)PW-explorer/PW_explorer/query.py:155: note:     def __getitem__(self, slice) -> List[Any]
(idaks)PW-explorer/PW_explorer/query.py:160: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(idaks)PW-explorer/PW_explorer/query.py:160: note: Possible overload variants:
(idaks)PW-explorer/PW_explorer/query.py:160: note:     def __getitem__(self, int) -> Any
(idaks)PW-explorer/PW_explorer/query.py:160: note:     def __getitem__(self, slice) -> List[Any]
(idaks)PW-explorer/PW_explorer/query.py:193: error: Argument 3 to "freq" of "PWEQuery" has incompatible type "int"; expected "str"  [arg-type]
(idaks)PW-explorer/PW_explorer/dist_calc.py:22: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "Set[Any]")  [assignment]
(idaks)PW-explorer/PW_explorer/visualize.py:61: error: Incompatible types in assignment (expression has type "range", variable has type "Optional[List[Any]]")  [assignment]
(idaks)PW-explorer/PW_explorer/visualize.py:63: error: Argument 2 to "map" has incompatible type "Optional[List[Any]]"; expected "Iterable[Any]"  [arg-type]
(idaks)PW-explorer/PW_explorer/visualize.py:125: error: Incompatible types in assignment (expression has type "range", variable has type "Optional[List[Any]]")  [assignment]
(idaks)PW-explorer/PW_explorer/visualize.py:127: error: Value of type "Optional[List[Any]]" is not indexable  [index]
(idaks)PW-explorer/PW_explorer/run_dlv.py:26: error: Need type annotation for 'meta_data' (hint: "meta_data: Dict[<type>, <type>] = ...")  [var-annotated]
(idaks)PW-explorer/PW_explorer/run_dlv.py:41: error: Argument 1 to "map" has incompatible type "Callable[[bytes], str]"; expected "Callable[[bytes], bytes]"  [arg-type]
(idaks)PW-explorer/PW_explorer/run_dlv.py:41: error: Incompatible return value type (got "str", expected "bytes")  [return-value]
(idaks)PW-explorer/PW_explorer/run_clingo.py:15: error: Need type annotation for 'meta_data' (hint: "meta_data: Dict[<type>, <type>] = ...")  [var-annotated]
(idaks)PW-explorer/PW_explorer/run_clingo.py:31: error: Argument 1 to "map" has incompatible type "Callable[[bytes], str]"; expected "Callable[[bytes], bytes]"  [arg-type]
(idaks)PW-explorer/PW_explorer/run_clingo.py:31: error: Incompatible return value type (got "str", expected "bytes")  [return-value]
(idaks)PW-explorer/PW_explorer/export.py:169: error: Argument 1 to "append" of "list" has incompatible type "Tuple[int, int, Any]"; expected "Tuple[int, str, Any]"  [arg-type]
(idaks)PW-explorer/PW_explorer/export.py:173: error: Argument 2 to "insert" of "list" has incompatible type "str"; expected "Tuple[int, str, Any]"  [arg-type]
(idaks)PW-explorer/PW_explorer/export.py:221: error: Argument 1 to "append" of "list" has incompatible type "Tuple[int, int, Any]"; expected "Tuple[int, str, Any]"  [arg-type]
(idaks)PW-explorer/PW_explorer/export.py:225: error: Argument 2 to "insert" of "list" has incompatible type "str"; expected "Tuple[int, str, Any]"  [arg-type]
Found 51 errors in 16 files (checked 24 source files)

[RRepo](Debith)py3traits
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_property_in_instance.py:41: error: "ExampleClass" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_property_in_instance.py:46: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_property_in_instance.py:50: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_property_in_instance.py:51: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_property_in_instance.py:55: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_property_in_instance.py:56: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_method_in_class.py:40: error: "Type[ExampleClass]" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_method_in_class.py:48: error: "Type[ExampleClass]" has no attribute "static_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_method_in_class.py:50: error: "Type[ExampleClass]" has no attribute "class_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_method_in_class.py:52: error: "ExampleClass" has no attribute "class_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_method_in_class.py:54: error: "ExampleClass" has no attribute "instance_method"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:48: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:49: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:50: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:51: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:54: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:55: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:56: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:57: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:60: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:61: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:64: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:65: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:66: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/property_is_created_into_instance.py:67: error: "ExampleClass" has no attribute "all"  [attr-defined]
(Debith)py3traits/examples/function_is_composed_as_a_part_of_class.py:34: error: "Type[ExampleClass]" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/function_is_composed_as_a_part_of_class.py:38: error: "Type[ExampleClass]" has no attribute "new_static_function"  [attr-defined]
(Debith)py3traits/examples/function_is_composed_as_a_part_of_class.py:40: error: "Type[ExampleClass]" has no attribute "new_class_function"  [attr-defined]
(Debith)py3traits/examples/function_is_composed_as_a_part_of_class.py:42: error: "ExampleClass" has no attribute "new_class_function"  [attr-defined]
(Debith)py3traits/examples/function_is_composed_as_a_part_of_class.py:44: error: "ExampleClass" has no attribute "new_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_property_in_instance.py:40: error: "Type[ExampleClass]" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_property_in_instance.py:47: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_property_in_instance.py:51: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_property_in_instance.py:52: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_property_in_instance.py:56: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_property_in_instance.py:57: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_other_class.py:40: error: "ExampleClass" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_other_class.py:45: error: "ExampleClass" has no attribute "static_method"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_other_class.py:47: error: "ExampleClass" has no attribute "class_method"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_other_class.py:49: error: "ExampleClass" has no attribute "instance_method"  [attr-defined]
(Debith)py3traits/examples/extendable_function_class_vs_instance.py:26: error: "Type[MyExample]" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/extendable_function_class_vs_instance.py:34: error: "MyExample" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_other_class.py:45: error: "Type[ExampleClass]" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_other_class.py:51: error: "Type[ExampleClass]" has no attribute "static_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_other_class.py:53: error: "Type[ExampleClass]" has no attribute "class_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_other_class.py:55: error: "ExampleClass" has no attribute "class_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_other_class.py:57: error: "ExampleClass" has no attribute "instance_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_other_class.py:59: error: "ExampleClass" has no attribute "value"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_method_in_instance.py:41: error: "Type[ExampleClass]" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_method_in_instance.py:49: error: "Type[ExampleClass]" has no attribute "static_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_method_in_instance.py:51: error: "Type[ExampleClass]" has no attribute "class_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_method_in_instance.py:53: error: "ExampleClass" has no attribute "class_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_method_in_instance.py:55: error: "ExampleClass" has no attribute "instance_method"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_property_in_class.py:36: error: "ExampleClass" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_property_in_class.py:40: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_property_in_class.py:44: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_property_in_class.py:45: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_property_in_class.py:49: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_property_in_class.py:50: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/composition_in_alternative_syntax.py:49: error: "ExampleClass" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/composition_in_alternative_syntax.py:50: error: "ExampleClass" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/composition_in_alternative_syntax.py:53: error: "ExampleClass" has no attribute "modify_instance"  [attr-defined]
(Debith)py3traits/examples/composition_in_alternative_syntax.py:62: error: "ExampleClass" has no attribute "instance_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_methods_with_rename.py:42: error: "Type[ExampleClass]" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_methods_with_rename.py:50: error: "Type[ExampleClass]" has no attribute "renamed_static_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_methods_with_rename.py:52: error: "Type[ExampleClass]" has no attribute "renamed_class_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_methods_with_rename.py:54: error: "ExampleClass" has no attribute "renamed_class_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_methods_with_rename.py:56: error: "ExampleClass" has no attribute "renamed_instance_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_other_instance.py:43: error: "Type[ExampleClass]" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_other_instance.py:49: error: "Type[ExampleClass]" has no attribute "static_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_other_instance.py:51: error: "Type[ExampleClass]" has no attribute "class_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_other_instance.py:53: error: "ExampleClass" has no attribute "class_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_other_instance.py:55: error: "ExampleClass" has no attribute "instance_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_other_instance.py:57: error: "ExampleClass" has no attribute "value"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_other_instance.py:41: error: "ExampleClass" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_other_instance.py:46: error: "ExampleClass" has no attribute "static_method"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_other_instance.py:48: error: "ExampleClass" has no attribute "class_method"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_other_instance.py:50: error: "ExampleClass" has no attribute "instance_method"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_methods_with_rename.py:44: error: "ExampleClass" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_methods_with_rename.py:52: error: "ExampleClass" has no attribute "renamed_static_method"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_methods_with_rename.py:54: error: "ExampleClass" has no attribute "renamed_class_method"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_methods_with_rename.py:56: error: "ExampleClass" has no attribute "renamed_instance_method"  [attr-defined]
(Debith)py3traits/examples/function_is_composed_as_a_part_of_instance.py:35: error: "ExampleClass" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/function_is_composed_as_a_part_of_instance.py:40: error: "ExampleClass" has no attribute "new_static_function"  [attr-defined]
(Debith)py3traits/examples/function_is_composed_as_a_part_of_instance.py:42: error: "ExampleClass" has no attribute "new_class_function"  [attr-defined]
(Debith)py3traits/examples/function_is_composed_as_a_part_of_instance.py:44: error: "ExampleClass" has no attribute "new_method"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_property_in_class.py:35: error: "Type[ExampleClass]" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_property_in_class.py:42: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_property_in_class.py:46: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_property_in_class.py:47: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_property_in_class.py:51: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/class_is_composed_from_cherrypicked_property_in_class.py:52: error: "ExampleClass" has no attribute "trait_property"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_method_in_class.py:40: error: "ExampleClass" has no attribute "add_traits"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_method_in_class.py:46: error: "ExampleClass" has no attribute "instance_method"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_method_in_class.py:48: error: "ExampleClass" has no attribute "class_method"  [attr-defined]
(Debith)py3traits/examples/instance_is_composed_from_cherrypicked_method_in_class.py:50: error: "ExampleClass" has no attribute "static_method"  [attr-defined]
(Debith)py3traits/src/pytraits/core/primitives/instance_object.py:21: error: Relative import climbs too many namespaces  [misc]
(Debith)py3traits/src/pytraits/core/primitives/trait_object.py:19: error: Relative import climbs too many namespaces  [misc]
(Debith)py3traits/src/pytraits/core/primitives/class_object.py:22: error: Relative import climbs too many namespaces  [misc]
(Debith)py3traits/src/pytraits/core/composing/composer.py:40: error: Need type annotation for '__COMPOSERS' (hint: "__COMPOSERS: Dict[<type>, <type>] = ...")  [var-annotated]
(Debith)py3traits/src/pytraits/core/composing/traits.py:91: error: Variable "traits.Resolutions" is not valid as a type  [valid-type]
(Debith)py3traits/tests/unittest_typeconverted.py:72: error: Name 'test_handles_properly_tuple_arguments_with_type' already defined on line 65  [no-redef]
(Debith)py3traits/tests/unittest_typeconverted.py:91: error: Name 'missing_with_default' is not defined  [name-defined]
(Debith)py3traits/tests/unittest_typeconverted.py:107: error: Name 'missing_with_default' is not defined  [name-defined]
(Debith)py3traits/tests/unittest_typesafe.py:71: error: Name 'test_handles_properly_tuple_arguments_with_type' already defined on line 64  [no-redef]
(Debith)py3traits/tests/unittest_typesafe.py:90: error: Name 'missing_with_default' is not defined  [name-defined]
(Debith)py3traits/tests/unittest_typesafe.py:106: error: Name 'missing_with_default' is not defined  [name-defined]
(Debith)py3traits/tests/unittest_traits.py:26: error: Name 'test_does_not_need_preprosessing_for_multiple_trait_functions' already defined on line 22  [no-redef]
(Debith)py3traits/src/pytraits/support/inspector.py:141: error: Need type annotation for '__hooks'  [var-annotated]
(Debith)py3traits/src/pytraits/support/inspector.py:174: error: "Inspector" has no attribute "__inspect_arg"  [attr-defined]
(Debith)py3traits/src/pytraits/trait_composer.py:28: error: Variable "trait_composer.TraitTarget" is not valid as a type  [valid-type]
(Debith)py3traits/src/pytraits/trait_composer.py:60: error: "Tuple[Any, ...]" has no attribute "compose"  [attr-defined]
(Debith)py3traits/tests/unittest_compiler.py:5: error: Module 'utils' has no attribute 'for_examples'  [attr-defined]
(Debith)py3traits/tests/unittest_compiler.py:50: error: "Type[TestDummy]" has no attribute "_TestDummy__private_func"  [attr-defined]
(Debith)py3traits/tests/unittest_compiler.py:51: error: "Type[TestDummy]" has no attribute "_TestDummy__private_func"  [attr-defined]
(Debith)py3traits/tests/unittest_factory.py:10: error: Module 'utils' has no attribute 'for_examples'  [attr-defined]
(Debith)py3traits/tests/unittest_inspector.py:8: error: Module 'utils' has no attribute 'for_examples'  [attr-defined]
(Debith)py3traits/tests/unittest_inspector.py:96: error: Name 'test_isclass_checks_identifies_types_properly' already defined on line 92  [no-redef]
Found 118 errors in 31 files (checked 49 source files)

[RRepo](snakeleon)YouCompleteMe-x86
(snakeleon)YouCompleteMe-x86/third_party/ycmd/ycmd/tests/python/testdata/general_fallback/lang_python.py:13: error: Missing parentheses in call to 'print'. Did you mean print(abc)?  [syntax]
Found 1 error in 1 file (checked 240 source files)

[RRepo](dmlc)mxnet
(dmlc)mxnet/example/gluon/lstm_crf/lstm_crf.py:196: error: Need type annotation for 'word2idx' (hint: "word2idx: Dict[<type>, <type>] = ...")  [var-annotated]
(dmlc)mxnet/example/gluon/lstm_crf/lstm_crf.py:235: error: "float" has no attribute "asscalar"  [attr-defined]
(dmlc)mxnet/tests/python/gpu/test_gluon_transforms.py:30: error: Module 'common' has no attribute 'assertRaises'  [attr-defined]
(dmlc)mxnet/tests/python/gpu/test_gluon_transforms.py:30: error: Module 'common' has no attribute 'setup_module'  [attr-defined]
(dmlc)mxnet/tests/python/gpu/test_gluon_transforms.py:30: error: Module 'common' has no attribute 'with_seed'  [attr-defined]
(dmlc)mxnet/tests/python/gpu/test_gluon_transforms.py:30: error: Module 'common' has no attribute 'teardown'  [attr-defined]
(dmlc)mxnet/tests/python/unittest/test_gluon_data_vision.py:26: error: Module 'common' has no attribute 'assertRaises'  [attr-defined]
(dmlc)mxnet/tests/python/unittest/test_gluon_data_vision.py:26: error: Module 'common' has no attribute 'setup_module'  [attr-defined]
(dmlc)mxnet/tests/python/unittest/test_gluon_data_vision.py:26: error: Module 'common' has no attribute 'with_seed'  [attr-defined]
(dmlc)mxnet/tests/python/unittest/test_gluon_data_vision.py:26: error: Module 'common' has no attribute 'teardown'  [attr-defined]
(dmlc)mxnet/tests/python/unittest/test_autograd.py:23: error: Module 'common' has no attribute 'setup_module'  [attr-defined]
(dmlc)mxnet/tests/python/unittest/test_autograd.py:23: error: Module 'common' has no attribute 'with_seed'  [attr-defined]
(dmlc)mxnet/tests/python/unittest/test_autograd.py:23: error: Module 'common' has no attribute 'teardown'  [attr-defined]
(dmlc)mxnet/example/ssd/quantization.py:30: error: Module 'symbol' has no attribute 'symbol_builder'  [attr-defined]
(dmlc)mxnet/example/ssd/quantization.py:124: error: Need type annotation for 'excluded_sym_names' (hint: "excluded_sym_names: List[<type>] = ...")  [var-annotated]
(dmlc)mxnet/example/ssd/quantization.py:141: error: Incompatible types in assignment (expression has type "List[float]", variable has type "str")  [assignment]
(dmlc)mxnet/example/ssd/quantization.py:145: error: Name 'quantize_model' is not defined  [name-defined]
(dmlc)mxnet/example/ssd/quantization.py:158: error: Name 'quantize_model' is not defined  [name-defined]
(dmlc)mxnet/tests/python/unittest/test_metric.py:21: error: Module 'common' has no attribute 'with_seed'  [attr-defined]
(dmlc)mxnet/amalgamation/amalgamation.py:98: error: Need type annotation for 'sysheaders' (hint: "sysheaders: List[<type>] = ...")  [var-annotated]
(dmlc)mxnet/amalgamation/amalgamation.py:99: error: Need type annotation for 'history' (hint: "history: Set[<type>] = ...")  [var-annotated]
(dmlc)mxnet/amalgamation/amalgamation.py:170: error: "Callable[[Any, Any, Any], Any]" has no attribute "treeDepth"  [attr-defined]
(dmlc)mxnet/amalgamation/amalgamation.py:171: error: "Callable[[Any, Any, Any], Any]" has no attribute "fileCount"  [attr-defined]
(dmlc)mxnet/tools/pip/setup.py:42: error: "str" not callable  [operator]
(dmlc)mxnet/tools/pip/setup.py:147: error: "object" has no attribute "append"  [attr-defined]
(dmlc)mxnet/tools/pip/setup.py:148: error: "object" has no attribute "append"  [attr-defined]
(dmlc)mxnet/tools/pip/setup.py:149: error: "object" has no attribute "append"  [attr-defined]
(dmlc)mxnet/tools/pip/setup.py:154: error: "object" has no attribute "append"  [attr-defined]
(dmlc)mxnet/tools/pip/setup.py:155: error: "object" has no attribute "append"  [attr-defined]
(dmlc)mxnet/tools/pip/setup.py:156: error: "object" has no attribute "append"  [attr-defined]
(dmlc)mxnet/tools/pip/setup.py:160: error: "object" has no attribute "append"  [attr-defined]
(dmlc)mxnet/tools/pip/setup.py:163: error: "object" has no attribute "append"  [attr-defined]
(dmlc)mxnet/tools/pip/setup.py:165: error: "object" has no attribute "append"  [attr-defined]
(dmlc)mxnet/tools/pip/setup.py:170: error: "object" has no attribute "append"  [attr-defined]
(dmlc)mxnet/python/mxnet/ndarray/register.py:24: error: Relative import climbs too many namespaces  [misc]
(dmlc)mxnet/python/mxnet/ndarray/register.py:26: error: Relative import climbs too many namespaces  [misc]
(dmlc)mxnet/example/image-classification/train_imagenet.py:22: error: Module 'common' has no attribute 'find_mxnet'  [attr-defined]
(dmlc)mxnet/example/image-classification/train_imagenet.py:22: error: Module 'common' has no attribute 'data'  [attr-defined]
(dmlc)mxnet/example/image-classification/train_imagenet.py:63: error: Module has no attribute "get_symbol"  [attr-defined]
(dmlc)mxnet/tests/python/gpu/test_kvstore_gpu.py:27: error: Module 'common' has no attribute 'setup_module'  [attr-defined]
(dmlc)mxnet/tests/python/gpu/test_kvstore_gpu.py:27: error: Module 'common' has no attribute 'with_seed'  [attr-defined]
(dmlc)mxnet/tests/python/gpu/test_kvstore_gpu.py:27: error: Module 'common' has no attribute 'teardown'  [attr-defined]
(dmlc)mxnet/tests/python/unittest/test_gluon_data.py:26: error: Module 'common' has no attribute 'setup_module'  [attr-defined]
(dmlc)mxnet/tests/python/unittest/test_gluon_data.py:26: error: Module 'common' has no attribute 'with_seed'  [attr-defined]
(dmlc)mxnet/tests/python/unittest/test_gluon_data.py:26: error: Module 'common' has no attribute 'teardown'  [attr-defined]
(dmlc)mxnet/tests/python/unittest/test_gluon_data.py:150: error: Name 'Dataset' already defined (possibly by an import)  [no-redef]
(dmlc)mxnet/dev_menu.py:81: error: Incompatible return value type (got "List[str]", expected "str")  [return-value]
Found 47 errors in 13 files (checked 32 source files)

[RRepo](renskiy)fabricio
(renskiy)fabricio/tests/test_decorators.py:12: error: Name 'docker.Container' is not defined  [name-defined]
(renskiy)fabricio/tests/test_decorators.py:14: error: Module has no attribute "Image"  [attr-defined]
(renskiy)fabricio/examples/service/stack/fabfile.py:14: error: Module has no attribute "Stack"  [attr-defined]
(renskiy)fabricio/fabricio/utils.py:94: error: Incompatible types in assignment (expression has type "Callable[[Dict[_KT, _VT], _KT, _VT], None]", base class "object" defined the type as "Callable[[object, str, Any], None]")  [assignment]

[RRepo](wright-group)WrightTools
(wright-group)WrightTools/WrightTools/data/_variable.py:9: error: Relative import climbs too many namespaces  [misc]
(wright-group)WrightTools/tests/kit/ini.py:3: error: Module 'WrightTools.kit' has no attribute 'INI'  [attr-defined]
(wright-group)WrightTools/docs/conf.py:174: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
(wright-group)WrightTools/tests/data/from_PyCMDS.py:137: error: Name 'test_two_centers' already defined on line 124  [no-redef]
(wright-group)WrightTools/examples/colormaps.py:15: error: Module has no attribute "artists"  [attr-defined]
(wright-group)WrightTools/examples/colormaps.py:17: error: "DatasetContainer" has no attribute "v1p0p1_MoS2_TrEE_movie"  [attr-defined]
(wright-group)WrightTools/examples/colormaps.py:18: error: Module has no attribute "open"  [attr-defined]
(wright-group)WrightTools/examples/colormaps.py:40: error: Module has no attribute "artists"  [attr-defined]
(wright-group)WrightTools/examples/colormaps.py:42: error: Module has no attribute "artists"  [attr-defined]
(wright-group)WrightTools/examples/colormaps.py:48: error: Module has no attribute "artists"  [attr-defined]
(wright-group)WrightTools/examples/fill_types.py:17: error: Module has no attribute "artists"  [attr-defined]
(wright-group)WrightTools/examples/fill_types.py:19: error: Module has no attribute "artists"  [attr-defined]
(wright-group)WrightTools/examples/fill_types.py:22: error: "DatasetContainer" has no attribute "v0p2_d1_d2_diagonal"  [attr-defined]
(wright-group)WrightTools/examples/fill_types.py:23: error: Module has no attribute "data"  [attr-defined]
(wright-group)WrightTools/examples/fill_types.py:101: error: Module has no attribute "artists"  [attr-defined]
(wright-group)WrightTools/examples/fill_types.py:105: error: Module has no attribute "artists"  [attr-defined]
(wright-group)WrightTools/examples/label_delay_space.py:14: error: Module has no attribute "artists"  [attr-defined]
(wright-group)WrightTools/examples/label_delay_space.py:24: error: "DatasetContainer" has no attribute "d1_d2_000"  [attr-defined]
(wright-group)WrightTools/examples/label_delay_space.py:25: error: Module has no attribute "data"  [attr-defined]
(wright-group)WrightTools/examples/label_delay_space.py:31: error: Module has no attribute "diagrams"  [attr-defined]
(wright-group)WrightTools/examples/label_delay_space.py:37: error: "DatasetContainer" has no attribute "d1_d2_001"  [attr-defined]
(wright-group)WrightTools/examples/label_delay_space.py:38: error: Module has no attribute "data"  [attr-defined]
(wright-group)WrightTools/examples/label_delay_space.py:45: error: Module has no attribute "diagrams"  [attr-defined]
(wright-group)WrightTools/examples/label_delay_space.py:50: error: Module has no attribute "artists"  [attr-defined]
(wright-group)WrightTools/examples/label_delay_space.py:54: error: Module has no attribute "artists"  [attr-defined]
(wright-group)WrightTools/WrightTools/exceptions.py:73: error: Cannot resolve name "ValueError" (possible cyclic definition)  [misc]
(wright-group)WrightTools/WrightTools/exceptions.py:79: error: Cannot resolve name "FileExistsError" (possible cyclic definition)  [misc]
(wright-group)WrightTools/WrightTools/exceptions.py:88: error: Cannot resolve name "TypeError" (possible cyclic definition)  [misc]
Found 28 errors in 8 files (checked 110 source files)

[RRepo](apache)ignite
(apache)ignite/modules/platforms/python/docs/conf.py:91: error: Need type annotation for 'html_static_path' (hint: "html_static_path: List[<type>] = ...")  [var-annotated]
(apache)ignite/modules/platforms/python/docs/conf.py:112: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
(apache)ignite/modules/platforms/python/setup.py:55: error: Need type annotation for 'requirements'  [var-annotated]
(apache)ignite/modules/platforms/python/pyignite/api/result.py:16: error: Module 'pyignite.datatypes' has no attribute 'String'  [attr-defined]
(apache)ignite/modules/platforms/python/pyignite/api/result.py:34: error: Name 'Response' is not defined  [name-defined]
(apache)ignite/modules/platforms/python/pyignite/utils.py:74: error: Name 'Client' is not defined  [name-defined]
(apache)ignite/modules/platforms/python/pyignite/utils.py:104: error: Argument 1 to "ord" has incompatible type "Union[str, int]"; expected "Union[str, bytes]"  [arg-type]
(apache)ignite/modules/platforms/python/pyignite/utils.py:107: error: Unsupported operand types for + ("int" and "str")  [operator]
(apache)ignite/modules/platforms/python/pyignite/utils.py:107: note: Right operand is of type "Union[str, int]"
(apache)ignite/modules/platforms/python/pyignite/utils.py:118: error: Incompatible return value type (got "Union[str, int]", expected "int")  [return-value]
(apache)ignite/modules/platforms/python/pyignite/utils.py:118: error: Argument 1 to "hashcode" has incompatible type "Union[str, int]"; expected "Union[str, bytes]"  [arg-type]
(apache)ignite/modules/platforms/python/pyignite/utils.py:128: error: Incompatible return value type (got "Union[str, int]", expected "int")  [return-value]
(apache)ignite/modules/platforms/python/pyignite/utils.py:128: error: Item "int" of "Union[str, int]" has no attribute "lower"  [union-attr]
(apache)ignite/modules/platforms/python/pyignite/utils.py:139: error: Incompatible return value type (got "Union[int, Dict[Any, Any]]", expected "int")  [return-value]
(apache)ignite/modules/platforms/python/pyignite/utils.py:142: error: Name 'FNV1_OFFSET_BASIS' is not defined  [name-defined]
(apache)ignite/modules/platforms/python/pyignite/utils.py:143: error: Item "int" of "Union[int, Dict[Any, Any]]" has no attribute "keys"  [union-attr]
(apache)ignite/modules/platforms/python/pyignite/utils.py:146: error: Name 'FNV1_PRIME' is not defined  [name-defined]
(apache)ignite/modules/platforms/python/pyignite/utils.py:148: error: Name 'FNV1_PRIME' is not defined  [name-defined]
(apache)ignite/modules/platforms/python/pyignite/utils.py:150: error: Name 'FNV1_PRIME' is not defined  [name-defined]
(apache)ignite/modules/platforms/python/pyignite/utils.py:152: error: Name 'FNV1_PRIME' is not defined  [name-defined]
(apache)ignite/modules/platforms/python/tests/test_generic_object.py:16: error: Module 'pyignite' has no attribute 'GenericObjectMeta'  [attr-defined]
(apache)ignite/modules/platforms/python/tests/test_get_names.py:16: error: Module 'pyignite.api' has no attribute 'cache_create'  [attr-defined]
(apache)ignite/modules/platforms/python/tests/test_get_names.py:16: error: Module 'pyignite.api' has no attribute 'cache_get_names'  [attr-defined]
(apache)ignite/modules/platforms/python/tests/test_scan.py:16: error: Module 'pyignite.api' has no attribute 'scan'  [attr-defined]
(apache)ignite/modules/platforms/python/tests/test_scan.py:16: error: Module 'pyignite.api' has no attribute 'scan_cursor_get_page'  [attr-defined]
(apache)ignite/modules/platforms/python/tests/test_scan.py:16: error: Module 'pyignite.api' has no attribute 'resource_close'  [attr-defined]
(apache)ignite/modules/platforms/python/tests/test_scan.py:16: error: Module 'pyignite.api' has no attribute 'cache_put_all'  [attr-defined]

[RRepo](shobute)go-slack
(shobute)go-slack/goban.py:35: error: Missing return statement  [return]
(shobute)go-slack/goban.py:51: error: Need type annotation for 'votes' (hint: "votes: Dict[<type>, <type>] = ...")  [var-annotated]
(shobute)go-slack/goban.py:56: error: Argument 1 to "update" of "dict" has incompatible type "Dict[Tuple[int, int], None]"; expected "Mapping[str, str]"  [arg-type]
(shobute)go-slack/goban.py:148: error: Invalid index type "Optional[Tuple[int, int]]" for "Dict[Tuple[int, int], None]"; expected type "Tuple[int, int]"  [index]
(shobute)go-slack/goban.py:148: error: Incompatible types in assignment (expression has type "str", target has type "None")  [assignment]
(shobute)go-slack/goban.py:153: error: Invalid index type "Optional[Tuple[int, int]]" for "Dict[Tuple[int, int], None]"; expected type "Tuple[int, int]"  [index]
(shobute)go-slack/goban.py:174: error: Cannot access "__init__" directly  [misc]
(shobute)go-slack/goban.py:187: error: Invalid index type "Optional[Tuple[int, int]]" for "Dict[Tuple[int, int], None]"; expected type "Tuple[int, int]"  [index]
(shobute)go-slack/goban.py:194: error: Invalid index type "Optional[Tuple[int, int]]" for "Dict[Tuple[int, int], None]"; expected type "Tuple[int, int]"  [index]
(shobute)go-slack/goban.py:197: error: Incompatible return value type (got "int", expected "bool")  [return-value]
(shobute)go-slack/goban.py:200: error: Invalid index type "Optional[Tuple[int, int]]" for "Dict[Tuple[int, int], None]"; expected type "Tuple[int, int]"  [index]
(shobute)go-slack/goban.py:204: error: Invalid index type "Optional[Tuple[int, int]]" for "Dict[Tuple[int, int], None]"; expected type "Tuple[int, int]"  [index]
(shobute)go-slack/goban.py:210: error: Invalid index type "Optional[Tuple[int, int]]" for "Dict[Tuple[int, int], None]"; expected type "Tuple[int, int]"  [index]
(shobute)go-slack/goban.py:216: error: 'None' object is not iterable  [misc]
(shobute)go-slack/goban.py:248: error: 'None' object is not iterable  [misc]
(shobute)go-slack/goban.py:254: error: Invalid index type "None" for "Dict[str, Any]"; expected type "str"  [index]
(shobute)go-slack/goban.py:256: error: Invalid index type "None" for "Dict[str, Any]"; expected type "str"  [index]
(shobute)go-slack/gobot.py:27: error: Missing return statement  [return]
(shobute)go-slack/gobot.py:63: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(shobute)go-slack/gobot.py:97: error: Unsupported right operand type for in ("Optional[str]")  [operator]
(shobute)go-slack/gobot.py:105: error: Incompatible return value type (got "Optional[Match[str]]", expected "bool")  [return-value]
Found 21 errors in 2 files (checked 3 source files)

[RRepo](mrgambal)vulyk
(mrgambal)vulyk/vulyk/blueprints/gamification/core/foundations.py:68: error: Dict entry 5 has incompatible type "str": "bool"; expected "str": "str"  [dict-item]
(mrgambal)vulyk/tests/gamification/test_rule_models.py:7: error: Relative import climbs too many namespaces  [misc]
(mrgambal)vulyk/vulyk/blueprints/gamification/models/rules.py:7: error: Relative import climbs too many namespaces  [misc]
(mrgambal)vulyk/vulyk/blueprints/gamification/models/events.py:17: error: Relative import climbs too many namespaces  [misc]
(mrgambal)vulyk/vulyk/blueprints/gamification/models/events.py:220: error: Need type annotation for 'seen' (hint: "seen: Set[<type>] = ...")  [var-annotated]
(mrgambal)vulyk/vulyk/blueprints/gamification/models/rules.py:7: error: Relative import climbs too many namespaces  [misc]
(mrgambal)vulyk/tests/gamification/fixtures.py:10: error: Relative import climbs too many namespaces  [misc]
(mrgambal)vulyk/vulyk/ext/leaderboard.py:55: error: Need type annotation for 'top'  [var-annotated]
(mrgambal)vulyk/vulyk/ext/leaderboard.py:57: error: "append" of "list" does not return a value  [func-returns-value]
(mrgambal)vulyk/vulyk/ext/leaderboard.py:65: error: "type" has no attribute "objects"  [attr-defined]
(mrgambal)vulyk/vulyk/blueprints/gamification/core/parsing.py:29: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(mrgambal)vulyk/vulyk/blueprints/gamification/models/foundations.py:13: error: Relative import climbs too many namespaces  [misc]

[RRepo](akapur)pyiqfeed
Success: no issues found in 3 source files

[RRepo](adamcharnock)lightbus
(adamcharnock)lightbus/lightbus_experiments/potential_use_mixed.py:126: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 88 source files)

[RRepo](nooperpudd)quantbube
(nooperpudd)quantbube/quantbube/utils/functional.py:114: error: Incompatible types in assignment (expression has type "property", base class "object" defined the type as "Type[_T]")  [assignment]

[RRepo](phanrahan)magmathon
(phanrahan)magmathon/examples/uart/txmod.py:8: error: Invalid type comment or annotation  [valid-type]
(phanrahan)magmathon/examples/uart/txmod.py:8: note: Suggestion: use m.Bits[...] instead of m.Bits(...)
(phanrahan)magmathon/examples/uart/txmod.py:11: error: Invalid type comment or annotation  [valid-type]
(phanrahan)magmathon/examples/uart/txmod.py:11: note: Suggestion: use m.Bits[...] instead of m.Bits(...)
(phanrahan)magmathon/examples/uart/txmod.py:12: error: Invalid type comment or annotation  [valid-type]
(phanrahan)magmathon/examples/uart/txmod.py:12: note: Suggestion: use m.Bits[...] instead of m.Bits(...)
(phanrahan)magmathon/examples/uart/txmod.py:13: error: Invalid type comment or annotation  [valid-type]
(phanrahan)magmathon/examples/uart/txmod.py:13: note: Suggestion: use m.Bits[...] instead of m.Bits(...)
(phanrahan)magmathon/examples/uart/txmod.py:13: error: Syntax error in type annotation  [syntax]
(phanrahan)magmathon/examples/uart/txmod.py:13: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(phanrahan)magmathon/examples/coreir-tutorial/functionality.py:49: error: Name 'get_ipython' is not defined  [name-defined]
(phanrahan)magmathon/examples/coreir-tutorial/shift_register.py:29: error: Name 'get_ipython' is not defined  [name-defined]
(phanrahan)magmathon/examples/coreir-tutorial/full_adder.py:32: error: Name 'get_ipython' is not defined  [name-defined]
(phanrahan)magmathon/examples/coreir-tutorial/full_adder.py:39: error: Name 'get_ipython' is not defined  [name-defined]
(phanrahan)magmathon/examples/coreir-tutorial/adder.py:39: error: Name 'get_ipython' is not defined  [name-defined]
(phanrahan)magmathon/examples/coreir-tutorial/combinational.py:38: error: Name 'get_ipython' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:71: error: Name 'Circuit' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:73: error: Name 'In' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:73: error: Name 'Clock' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:73: error: Name 'Out' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:73: error: Name 'Bits' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:74: error: Name 'Out' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:74: error: Name 'Bits' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:108: error: Name 'Circuit' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:110: error: Name 'In' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:110: error: Name 'Bits' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:110: error: Name 'Clock' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:111: error: Name 'Out' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:111: error: Name 'Bits' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:132: error: Name 'Circuit' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:135: error: Name 'In' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:135: error: Name 'Bits' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:135: error: Name 'Clock' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:136: error: Name 'Out' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:136: error: Name 'Bits' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:157: error: Name 'Circuit' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:159: error: Name 'In' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:159: error: Name 'Bits' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:159: error: Name 'Out' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:172: error: Name 'Circuit' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:174: error: Name 'In' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:174: error: Name 'Bits' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:174: error: Name 'Out' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:192: error: Name 'Circuit' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:194: error: Name 'In' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:194: error: Name 'Bits' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:194: error: Name 'Out' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:224: error: Name 'Circuit' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:226: error: Name 'In' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:226: error: Name 'Bits' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:226: error: Name 'Clock' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:226: error: Name 'Out' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:243: error: Name 'Circuit' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:245: error: Name 'In' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:245: error: Name 'Clock' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:245: error: Name 'Out' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:245: error: Name 'Bits' is not defined  [name-defined]
(phanrahan)magmathon/projects/digits_recognition/modules.py:245: error: Name 'Bit' is not defined  [name-defined]
(phanrahan)magmathon/examples/coreir-tutorial/simple_alu.py:41: error: Name 'get_ipython' is not defined  [name-defined]
Found 54 errors in 8 files (checked 14 source files)

[RRepo](HBPNeurorobotics)BlenderRobotDesigner
(HBPNeurorobotics)BlenderRobotDesigner/resources/urdf_xml_validator.py:21: error: Missing parentheses in call to 'print'. Did you mean print('urdf_xml_validator.py -d <xsdfile> -l <xmlfile>')?  [syntax]
Found 1 error in 1 file (checked 24 source files)

[RRepo](MaT1g3R)Roboragi
(MaT1g3R)Roboragi/roboragi/data_controller/abc.py:1: error: Module 'abc' has no attribute 'ABCMeta'  [attr-defined]
(MaT1g3R)Roboragi/roboragi/data_controller/abc.py:1: error: Module 'abc' has no attribute 'abstractmethod'  [attr-defined]

[RRepo](lablup)sorna-client
(lablup)sorna-client/src/ai/backend/client/keypair.py:150: error: Incompatible types in assignment (expression has type "Union[int, str]", target has type "Optional[bool]")  [assignment]
(lablup)sorna-client/setup.py:35: error: Need type annotation for 'ci_requires' (hint: "ci_requires: List[<type>] = ...")  [var-annotated]
(lablup)sorna-client/setup.py:36: error: Unsupported operand types for + ("List[<nothing>]" and "List[str]")  [operator]
(lablup)sorna-client/src/ai/backend/client/compat.py:28: error: Module has no attribute "get_running_loop"; maybe "_get_running_loop" or "_set_running_loop"?  [attr-defined]
(lablup)sorna-client/src/ai/backend/client/compat.py:34: error: Module has no attribute "all_tasks"  [attr-defined]
(lablup)sorna-client/src/ai/backend/client/compat.py:75: error: Module has no attribute "run"  [attr-defined]
(lablup)sorna-client/src/ai/backend/client/vfolder.py:89: error: Item "str" of "Union[str, Path]" has no attribute "stat"  [union-attr]
(lablup)sorna-client/src/ai/backend/client/vfolder.py:99: error: Item "str" of "Union[str, Path]" has no attribute "relative_to"  [union-attr]
(lablup)sorna-client/src/ai/backend/client/vfolder.py:172: error: Item "MultipartReader" of "Union[MultipartReader, BodyPartReader]" has no attribute "filename"  [union-attr]
(lablup)sorna-client/src/ai/backend/client/vfolder.py:175: error: Item "MultipartReader" of "Union[MultipartReader, BodyPartReader]" has no attribute "read_chunk"  [union-attr]
(lablup)sorna-client/src/ai/backend/client/config.py:155: error: Incompatible return value type (got "List[Union[str, Any]]", expected "Tuple[str, ...]")  [return-value]
(lablup)sorna-client/src/ai/backend/client/__init__.py:5: error: Name 'exceptions' is not defined  [name-defined]
(lablup)sorna-client/src/ai/backend/client/__init__.py:6: error: Name 'session' is not defined  [name-defined]
(lablup)sorna-client/src/ai/backend/client/cli/proxy.py:26: error: Need type annotation for 'upstream_buffer'  [var-annotated]
Found 14 errors in 7 files (checked 33 source files)

[RRepo](tommz9)wrf_runner
(tommz9)wrf_runner/src/wrf_runner/linkgrib.py:66: error: Incompatible types in assignment (expression has type "Iterator[str]", variable has type "List[str]")  [assignment]
(tommz9)wrf_runner/src/wrf_runner/wps.py:61: error: Need type annotation for 'patch'  [var-annotated]
(tommz9)wrf_runner/src/wrf_runner/datasets/nam.py:8: error: Relative import climbs too many namespaces  [misc]
Found 3 errors in 3 files (checked 7 source files)

[RRepo](enchantner)python-zero
(enchantner)python-zero/lesson_2/sample.py:7: error: Argument 1 to "my_cool_function" has incompatible type "str"; expected "int"  [arg-type]
(enchantner)python-zero/lesson_2/sample.py:7: error: Argument 2 to "my_cool_function" has incompatible type "str"; expected "int"  [arg-type]
(enchantner)python-zero/lesson_7/async_bot.py:16: error: Need type annotation for 'likes' (hint: "likes: Set[<type>] = ...")  [var-annotated]
(enchantner)python-zero/lesson_7/async_bot.py:17: error: Need type annotation for 'dislikes' (hint: "dislikes: Set[<type>] = ...")  [var-annotated]
Found 4 errors in 2 files (checked 5 source files)

[RRepo](shlinx)cloudflare-ddns
Success: no issues found in 1 source file

[RRepo](DonaldWhyte)deep-learning-with-rnns
(DonaldWhyte)deep-learning-with-rnns/talk_creation_helpers/initial_code/text.py:212: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 10 source files)

[RRepo](berylTechnologies)redcap
(berylTechnologies)redcap/task_manager/admin.py:37: error: "Callable[[ServerAdmin, Any], Any]" has no attribute "short_description"  [attr-defined]
(berylTechnologies)redcap/task_manager/admin.py:38: error: "Callable[[ServerAdmin, Any], Any]" has no attribute "allow_tags"  [attr-defined]
(berylTechnologies)redcap/task_manager/admin.py:53: error: "Callable[[BuildTargetAdmin, Any], Any]" has no attribute "short_description"  [attr-defined]
(berylTechnologies)redcap/task_manager/admin.py:54: error: "Callable[[BuildTargetAdmin, Any], Any]" has no attribute "allow_tags"  [attr-defined]
(berylTechnologies)redcap/task_manager/admin.py:68: error: "Callable[[BuildGroupAdmin, Any], Any]" has no attribute "short_description"  [attr-defined]
(berylTechnologies)redcap/task_manager/admin.py:69: error: "Callable[[BuildGroupAdmin, Any], Any]" has no attribute "allow_tags"  [attr-defined]
(berylTechnologies)redcap/task_manager/rest.py:17: error: Name 'Client' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:23: error: Name 'Project' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:29: error: Name 'Playbook' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:35: error: Name 'ActionHistory' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:43: error: Name 'BuildTarget' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:61: error: Name 'BuildGroup' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:67: error: Name 'Server' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:83: error: Name 'Server' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:93: error: Name 'Project' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:98: error: Name 'Client' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:103: error: Name 'Playbook' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:108: error: Name 'ActionHistory' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:113: error: Name 'BuildTarget' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:125: error: Name 'build_target_execute_async' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:130: error: Name 'BuildGroup' is not defined  [name-defined]
(berylTechnologies)redcap/task_manager/rest.py:135: error: Name 'build_group_execute_async' is not defined  [name-defined]
(berylTechnologies)redcap/runner/executor.py:15: error: Invalid type comment or annotation  [valid-type]
(berylTechnologies)redcap/task_manager/models.py:72: error: Syntax error in type annotation  [syntax]
(berylTechnologies)redcap/task_manager/models.py:72: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(berylTechnologies)redcap/task_manager/models.py:102: error: Invalid type comment or annotation  [valid-type]
(berylTechnologies)redcap/task_manager/models.py:150: error: Invalid type comment or annotation  [valid-type]
(berylTechnologies)redcap/task_manager/models.py:150: error: Syntax error in type annotation  [syntax]
(berylTechnologies)redcap/task_manager/models.py:150: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(berylTechnologies)redcap/task_manager/models.py:243: error: Bracketed expression "[...]" is not valid as a type  [misc]
(berylTechnologies)redcap/task_manager/models.py:243: note: Did you mean "List[...]"?
(berylTechnologies)redcap/task_manager/models.py:251: error: Bracketed expression "[...]" is not valid as a type  [misc]
(berylTechnologies)redcap/task_manager/models.py:251: note: Did you mean "List[...]"?
(berylTechnologies)redcap/runner/execute_helpers.py:12: error: Bracketed expression "[...]" is not valid as a type  [misc]
(berylTechnologies)redcap/runner/execute_helpers.py:12: note: Did you mean "List[...]"?
(berylTechnologies)redcap/runner/execute_helpers.py:12: error: Syntax error in type annotation  [syntax]
(berylTechnologies)redcap/runner/execute_helpers.py:12: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(berylTechnologies)redcap/runner/execute_helpers.py:38: error: "append" of "list" does not return a value  [func-returns-value]
(berylTechnologies)redcap/runner/execute_helpers.py:39: error: "append" of "list" does not return a value  [func-returns-value]
(berylTechnologies)redcap/runner/execute_helpers.py:43: error: Bracketed expression "[...]" is not valid as a type  [misc]
(berylTechnologies)redcap/runner/execute_helpers.py:43: note: Did you mean "List[...]"?
(berylTechnologies)redcap/runner/execute_helpers.py:49: error: Need type annotation for 'res' (hint: "res: List[<type>] = ...")  [var-annotated]
(berylTechnologies)redcap/runner/execute_helpers.py:55: error: Syntax error in type annotation  [syntax]
(berylTechnologies)redcap/runner/execute_helpers.py:55: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(berylTechnologies)redcap/runner/execute_helpers.py:62: error: Need type annotation for 'output'  [var-annotated]
(berylTechnologies)redcap/messenger/messenger.py:47: error: Missing return statement  [return]
(berylTechnologies)redcap/messenger/messenger.py:47: error: Return type "Response" of "send" incompatible with return type "str" in supertype "Messenger"  [override]
Found 39 errors in 6 files (checked 11 source files)

[RRepo](EdmundMartin)SearchScraperAPI
Success: no issues found in 13 source files

[RRepo](smeenka)esp32
(smeenka)esp32/lolin32/stub/machine.py:29: error: inconsistent use of tabs and spaces in indentation  [syntax]
Found 1 error in 1 file (checked 38 source files)

[RRepo](changyuheng)pywinwifi
(changyuheng)pywinwifi/src/winwifi/main.py:14: error: Item "None" of "Optional[bytes]" has no attribute "decode"  [union-attr]
(changyuheng)pywinwifi/src/winwifi/main.py:57: error: Incompatible types in assignment (expression has type "int", variable has type "RawIOBase")  [assignment]
(changyuheng)pywinwifi/src/winwifi/main.py:59: error: Argument 1 to "write" has incompatible type "RawIOBase"; expected "int"  [arg-type]
(changyuheng)pywinwifi/src/winwifi/main.py:62: error: Argument 1 to "close" has incompatible type "RawIOBase"; expected "int"  [arg-type]
Found 4 errors in 1 file (checked 2 source files)

[RRepo](GoogleCloudPlatform)training-data-analyst
(GoogleCloudPlatform)training-data-analyst/courses/machine_learning/deepdive/06_structured/labs/serving/application/main.py:32: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 104 source files)

[RRepo](algorithm-ninja)territoriali-backend
(algorithm-ninja)territoriali-backend/utils/fix_header.py:33: error: Incompatible types in assignment (expression has type "List[List[str]]", variable has type "bytes")  [assignment]
(algorithm-ninja)territoriali-backend/utils/fix_header.py:36: error: Value of type "int" is not indexable  [index]
(algorithm-ninja)territoriali-backend/utils/fix_header.py:43: error: Incompatible types in assignment (expression has type "Set[int]", variable has type "List[int]")  [assignment]
(algorithm-ninja)territoriali-backend/utils/fix_header.py:89: error: Need type annotation for 'authors' (hint: "authors: Dict[<type>, <type>] = ...")  [var-annotated]
(algorithm-ninja)territoriali-backend/terry/handlers/base_handler.py:16: error: Relative import climbs too many namespaces  [misc]
(algorithm-ninja)territoriali-backend/terry/handlers/base_handler.py:17: error: Relative import climbs too many namespaces  [misc]
(algorithm-ninja)territoriali-backend/terry/handlers/base_handler.py:18: error: Relative import climbs too many namespaces  [misc]
(algorithm-ninja)territoriali-backend/terry/handlers/base_handler.py:19: error: Relative import climbs too many namespaces  [misc]
(algorithm-ninja)territoriali-backend/terry/handlers/base_handler.py:16: error: Relative import climbs too many namespaces  [misc]
(algorithm-ninja)territoriali-backend/terry/handlers/base_handler.py:17: error: Relative import climbs too many namespaces  [misc]
(algorithm-ninja)territoriali-backend/terry/handlers/base_handler.py:18: error: Relative import climbs too many namespaces  [misc]
(algorithm-ninja)territoriali-backend/terry/handlers/base_handler.py:19: error: Relative import climbs too many namespaces  [misc]
(algorithm-ninja)territoriali-backend/terry/contest_manager.py:35: error: Need type annotation for 'input_queue' (hint: "input_queue: Dict[<type>, <type>] = ...")  [var-annotated]
(algorithm-ninja)territoriali-backend/terry/contest_manager.py:36: error: Need type annotation for 'tasks' (hint: "tasks: Dict[<type>, <type>] = ...")  [var-annotated]

[RRepo](erdewit)ib_insync
(erdewit)ib_insync/ib_insync/contract.py:176: error: Unexpected keyword argument "secType" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:176: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:176: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:176: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:176: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "lastTradeDateOrContractMonth" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "strike" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "right" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "multiplier" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:205: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Unexpected keyword argument "lastTradeDateOrContractMonth" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Unexpected keyword argument "localSymbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Unexpected keyword argument "multiplier" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:234: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:257: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:257: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:257: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:257: error: Unexpected keyword argument "localSymbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:257: error: Unexpected keyword argument "multiplier" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:257: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:282: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:282: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:282: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:282: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:321: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:321: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:321: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:321: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:340: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:340: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:340: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:340: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:359: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:359: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:359: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:359: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Too many arguments for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "symbol" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "lastTradeDateOrContractMonth" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "strike" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "right" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "exchange" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "multiplier" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/ib_insync/contract.py:398: error: Unexpected keyword argument "currency" for "__init__" of "object"  [call-arg]
(erdewit)ib_insync/docs/conf.py:17: error: "None" has no attribute "split"  [attr-defined]
(erdewit)ib_insync/ib_insync/util.py:320: error: Unsupported operand types for < ("time" and "datetime")  [operator]
(erdewit)ib_insync/ib_insync/util.py:321: error: Unsupported operand types for + ("time" and "timedelta")  [operator]
(erdewit)ib_insync/ib_insync/util.py:321: error: Incompatible types in assignment (expression has type "timedelta", variable has type "time")  [assignment]
(erdewit)ib_insync/ib_insync/util.py:324: error: Incompatible types in "yield" (actual type "time", expected type "datetime")  [misc]
(erdewit)ib_insync/ib_insync/util.py:325: error: Unsupported operand types for + ("time" and "timedelta")  [operator]
(erdewit)ib_insync/ib_insync/util.py:325: error: Incompatible types in assignment (expression has type "timedelta", variable has type "time")  [assignment]
(erdewit)ib_insync/ib_insync/util.py:338: error: Unsupported left operand type for - ("time")  [operator]
(erdewit)ib_insync/ib_insync/util.py:354: error: Unsupported operand types for < ("time" and "datetime")  [operator]
(erdewit)ib_insync/ib_insync/util.py:355: error: Unsupported operand types for + ("time" and "timedelta")  [operator]
(erdewit)ib_insync/ib_insync/util.py:355: error: Incompatible types in assignment (expression has type "timedelta", variable has type "time")  [assignment]
(erdewit)ib_insync/ib_insync/util.py:358: error: Incompatible types in "yield" (actual type "time", expected type "datetime")  [misc]
(erdewit)ib_insync/ib_insync/util.py:359: error: Unsupported operand types for + ("time" and "timedelta")  [operator]
(erdewit)ib_insync/ib_insync/util.py:359: error: Incompatible types in assignment (expression has type "timedelta", variable has type "time")  [assignment]
(erdewit)ib_insync/ib_insync/util.py:368: error: Unsupported left operand type for - ("time")  [operator]
(erdewit)ib_insync/ib_insync/util.py:441: error: Name 'qApp' is not defined  [name-defined]
Found 66 errors in 3 files (checked 10 source files)

[RRepo](idobrusin)RocLang
(idobrusin)RocLang/RocDemo/roc_node/scripts/temp/inmoov_manipulator.py:26: error: inconsistent use of tabs and spaces in indentation  [syntax]
Found 1 error in 1 file (checked 16 source files)

[RRepo](google)pybadges
(google)pybadges/pybadges/precalculated_text_measurer.py:56: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(google)pybadges/pybadges/precalculated_text_measurer.py:57: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(google)pybadges/pybadges/__init__.py:100: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")  [assignment]
Found 3 errors in 2 files (checked 11 source files)

[RRepo](oser-cs)oser-website
(oser-cs)oser-website/dynamicforms/utils.py:6: error: Name 'File' is not defined  [name-defined]
(oser-cs)oser-website/visits/models.py:186: error: "Callable[[Visit], Any]" has no attribute "boolean"  [attr-defined]
(oser-cs)oser-website/visits/models.py:188: error: "Callable[[], Any]" has no attribute "short_description"  [attr-defined]
(oser-cs)oser-website/tests/utils/field_test.py:138: error: Need type annotation for 'METHODS' (hint: "METHODS: List[<type>] = ...")  [var-annotated]
(oser-cs)oser-website/tests/utils/field_test.py:239: error: Incompatible types in assignment (expression has type "str", base class "BaseTestFactory" defined the type as "None")  [assignment]
(oser-cs)oser-website/tests/utils/field_test.py:276: error: Incompatible types in assignment (expression has type "str", base class "BaseTestFactory" defined the type as "None")  [assignment]
(oser-cs)oser-website/tests/utils/field_test.py:298: error: Incompatible types in assignment (expression has type "str", base class "FieldTestFactory" defined the type as "None")  [assignment]
(oser-cs)oser-website/tests/utils/field_test.py:314: error: Incompatible types in assignment (expression has type "str", base class "FieldTestFactory" defined the type as "None")  [assignment]
(oser-cs)oser-website/tests/utils/field_test.py:347: error: Incompatible types in assignment (expression has type "str", base class "ModelTestFactory" defined the type as "None")  [assignment]
(oser-cs)oser-website/tests/utils/field_test.py:363: error: Incompatible types in assignment (expression has type "str", base class "ModelTestFactory" defined the type as "None")  [assignment]
(oser-cs)oser-website/mails/management/commands/sendnotification.py:3: error: Relative import climbs too many namespaces  [misc]
(oser-cs)oser-website/mails/management/commands/rendernotification.py:3: error: Relative import climbs too many namespaces  [misc]
(oser-cs)oser-website/visits/notifications.py:7: error: Module 'mails' has no attribute 'Notification'  [attr-defined]
(oser-cs)oser-website/tests/utils/mixins.py:21: error: Need type annotation for 'retrieve_kwargs' (hint: "retrieve_kwargs: Dict[<type>, <type>] = ...")  [var-annotated]
(oser-cs)oser-website/tests/test_core/test_address.py:5: error: Module 'tests.utils' has no attribute 'ModelTestCase'  [attr-defined]
(oser-cs)oser-website/tests/test_core/test_document.py:5: error: Module 'tests.utils' has no attribute 'ModelTestCase'  [attr-defined]

[RRepo](sonata-nfv)son-cli
(sonata-nfv)son-cli/src/son/access/models/models.py:60: error: Need type annotation for '_storage' (hint: "_storage: List[<type>] = ...")  [var-annotated]
(sonata-nfv)son-cli/src/son/validate/event.py:133: error: "Type[EventLogger]" has no attribute "manager"  [attr-defined]
Found 2 errors in 2 files (checked 26 source files)

[RRepo](missionpinball)mpf-docs
(missionpinball)mpf-docs/_doc_tools/build_events_reference_docs.py:250: error: Need type annotation for 'dont_delete_files' (hint: "dont_delete_files: List[<type>] = ...")  [var-annotated]
(missionpinball)mpf-docs/_doc_tools/build_machine_vars_reference_docs.py:7: error: Need type annotation for 'dont_delete_files' (hint: "dont_delete_files: List[<type>] = ...")  [var-annotated]
(missionpinball)mpf-docs/_doc_tools/build_player_vars_reference_docs.py:7: error: Need type annotation for 'dont_delete_files' (hint: "dont_delete_files: List[<type>] = ...")  [var-annotated]
(missionpinball)mpf-docs/_doc_tools/build_error_reference_docs.py:194: error: Need type annotation for 'dont_delete_files' (hint: "dont_delete_files: List[<type>] = ...")  [var-annotated]
(missionpinball)mpf-docs/_doc_tools/build_error_reference_docs.py:196: error: Name 'EventDocParser' is not defined  [name-defined]

[RRepo](SpiroGanas)MIMIC3py
(SpiroGanas)MIMIC3py/MIMIC3py/utilities.py:12: error: Name 'local_save_folder' is not defined  [name-defined]
(SpiroGanas)MIMIC3py/MIMIC3py/utilities.py:95: error: Name 'local_save_folder' is not defined  [name-defined]
(SpiroGanas)MIMIC3py/MIMIC3py/download.py:12: error: Name 'physionet_FILENAMES' is not defined  [name-defined]
(SpiroGanas)MIMIC3py/MIMIC3py/download.py:25: error: Name 'local_save_folder' is not defined  [name-defined]
(SpiroGanas)MIMIC3py/MIMIC3py/download.py:25: error: Name 'physionet_USERNAME' is not defined  [name-defined]
(SpiroGanas)MIMIC3py/MIMIC3py/download.py:25: error: Name 'physionet_PASSWORD' is not defined  [name-defined]
(SpiroGanas)MIMIC3py/MIMIC3py/download.py:69: error: Name 'physionet_FILENAMES' is not defined  [name-defined]
Found 7 errors in 2 files (checked 5 source files)

[RRepo](penguinolog)logwrap
(penguinolog)logwrap/setup.py:73: error: Name 'build_ext.build_ext' is not defined  [name-defined]
(penguinolog)logwrap/test/test_log_wrap_shared.py:23: error: Module 'logwrap' has no attribute 'log_wrap'  [attr-defined]
(penguinolog)logwrap/test/test_pretty_str.py:210: error: Not all arguments converted during string formatting  [str-format]
Found 3 errors in 3 files (checked 7 source files)

[RRepo](mlperf)training_results_v0.6
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/tvm/nnvm/amalgamation/amalgamation.py:65: error: Missing parentheses in call to 'print'. Did you mean print(line)?  [syntax]
Found 1 error in 1 file (checked 837 source files)

[RRepo](QQuick)Transcrypt
(QQuick)Transcrypt/transcrypt/demos/cyclejs_demo/component_demos/isolated_bmi_slider/components/labeled_slider.py:39: error: Name 'CycleIsolate' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/development/manual_tests/static_types/mod2/__init__.py:2: error: Incompatible return value type (got "int", expected "str")  [return-value]
(QQuick)Transcrypt/transcrypt/tutorials/baseline/bl_035_if_else_event/if_else_event.py:1: error: Name 'document' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/tutorials/baseline/bl_035_if_else_event/if_else_event.py:2: error: Name 'document' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/tutorials/baseline/bl_035_if_else_event/if_else_event.py:4: error: Name 'document' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/tutorials/baseline/bl_035_if_else_event/if_else_event.py:5: error: Name 'document' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/tutorials/static_typing/functions.py:7: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(QQuick)Transcrypt/transcrypt/tutorials/static_typing/functions.py:7: error: List item 1 has incompatible type "float"; expected "int"  [list-item]
(QQuick)Transcrypt/transcrypt/tutorials/static_typing/functions.py:7: error: List item 0 has incompatible type "float"; expected "int"  [list-item]
(QQuick)Transcrypt/transcrypt/tutorials/static_typing/functions.py:7: error: List item 2 has incompatible type "float"; expected "int"  [list-item]
(QQuick)Transcrypt/transcrypt/tutorials/static_typing/functions.py:16: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(QQuick)Transcrypt/transcrypt/tutorials/static_typing/functions.py:22: error: Argument "c" to "h" has incompatible type "str"; expected "complex"  [arg-type]
(QQuick)Transcrypt/transcrypt/tutorials/static_typing/functions.py:25: error: Argument 1 has incompatible type "str"; expected "List[List[int]]"  [arg-type]
(QQuick)Transcrypt/transcrypt/tutorials/static_typing/functions.py:28: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(QQuick)Transcrypt/transcrypt/demos/pong/pong.py:1: error: Name '__pragma__' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/pong/pong.py:3: error: Name '__pragma__' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/pong/pong.py:5: error: Name '__pragma__' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/pong/pong.py:15: error: "int" has no attribute "onkeydown"  [attr-defined]
(QQuick)Transcrypt/transcrypt/demos/pong/pong.py:48: error: Name '__pragma__' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/pong/pong.py:57: error: Name '__pragma__' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/three_demo/three_demo.py:4: error: Name 'window' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/three_demo/three_demo.py:7: error: Name 'window' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/three_demo/three_demo.py:8: error: Name 'document' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/parcel_demo/example/mymod2/main2.py:1: error: Relative import climbs too many namespaces  [misc]
(QQuick)Transcrypt/transcrypt/demos/parcel_demo/example/mymod2/main2.py:2: error: Relative import climbs too many namespaces  [misc]
(QQuick)Transcrypt/transcrypt/demos/react_demo/react_demo.py:16: error: Name 'React' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/react_demo/react_demo.py:21: error: Name 'this' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/react_demo/react_demo.py:23: error: Name 'setInterval' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/react_demo/react_demo.py:23: error: Name 'this' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/react_demo/react_demo.py:26: error: Name 'this' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/react_demo/react_demo.py:28: error: Name 'this' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/react_demo/react_demo.py:35: error: Name 'React' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/jquery_demo/jquery_demo.py:1: error: Name '__pragma__' is not defined  [name-defined]
(QQuick)Transcrypt/transcrypt/demos/d3js_demo/d3js_demo.py:73: error: Name 'window' is not defined  [name-defined]

[RRepo](DFO-Ocean-Navigator)Ocean-Data-Map-Project
(DFO-Ocean-Navigator)Ocean-Data-Map-Project/scripts/drifter_process.py:44: error: invalid token  [syntax]
Found 1 error in 1 file (checked 57 source files)

[RRepo](yokawasa)azure-functions-python-samples

[RRepo](the-c0d3r)pynmap
(the-c0d3r)pynmap/portscan.py:40: error: Missing parentheses in call to 'print'. Did you mean print(banner)?  [syntax]
Found 1 error in 1 file (checked 4 source files)

[RRepo](stoklund)portable-simd
(stoklund)portable-simd/simdspec.py:13: error: Incompatible types in assignment (expression has type "None", variable has type "Interpretation")  [assignment]
(stoklund)portable-simd/simdspec.py:62: error: Incompatible return value type (got "None", expected "Interpretation")  [return-value]
(stoklund)portable-simd/simdspec.py:183: error: Argument 5 to "Signature" has incompatible type "Optional[str]"; expected "str"  [arg-type]
Found 3 errors in 1 file (checked 2 source files)

[RRepo](mara)mara-app
(mara)mara-app/mara_app/monkey_patch.py:16: error: Invalid type comment or annotation  [valid-type]
(mara)mara-app/mara_app/config.py:7: error: Invalid type comment or annotation  [valid-type]
(mara)mara-app/mara_app/views.py:97: error: Bracketed expression "[...]" is not valid as a type  [misc]
(mara)mara-app/mara_app/views.py:97: note: Did you mean "List[...]"?
(mara)mara-app/mara_app/views.py:100: error: Bracketed expression "[...]" is not valid as a type  [misc]
(mara)mara-app/mara_app/views.py:100: note: Did you mean "List[...]"?
(mara)mara-app/mara_app/layout.py:26: error: Bracketed expression "[...]" is not valid as a type  [misc]
(mara)mara-app/mara_app/layout.py:26: note: Did you mean "List[...]"?
(mara)mara-app/mara_app/layout.py:38: error: Bracketed expression "[...]" is not valid as a type  [misc]
(mara)mara-app/mara_app/layout.py:38: note: Did you mean "List[...]"?
(mara)mara-app/mara_app/layout.py:53: error: Bracketed expression "[...]" is not valid as a type  [misc]
(mara)mara-app/mara_app/layout.py:53: note: Did you mean "List[...]"?
(mara)mara-app/mara_app/layout.py:94: error: Incompatible return value type (got "List[Any]", expected "str")  [return-value]
(mara)mara-app/mara_app/app.py:19: error: Bracketed expression "[...]" is not valid as a type  [misc]
(mara)mara-app/mara_app/app.py:19: note: Did you mean "List[...]"?
(mara)mara-app/mara_app/app.py:30: error: Argument 2 to "isinstance" has incompatible type "_SpecialForm"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"  [arg-type]
(mara)mara-app/mara_app/app.py:124: error: Invalid type comment or annotation  [valid-type]
Found 11 errors in 5 files (checked 5 source files)

[RRepo](PJB3005)MoMMI
(PJB3005)MoMMI/MoMMI/Modules/permissions.py:3: error: Module 'MoMMI' has no attribute 'MRoleType'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/permissions.py:3: error: Module 'MoMMI' has no attribute 'MChannel'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/permissions.py:3: error: Module 'MoMMI' has no attribute 'command'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/test_comms.py:2: error: Module 'MoMMI' has no attribute 'comm_event'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/test_comms.py:2: error: Module 'MoMMI' has no attribute 'MChannel'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/wiggle.py:3: error: Module 'MoMMI' has no attribute 'MChannel'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/wiggle.py:3: error: Module 'MoMMI' has no attribute 'command'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/testmerge.py:3: error: Module 'MoMMI' has no attribute 'command'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/testmerge.py:3: error: Module 'MoMMI' has no attribute 'MChannel'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/help.py:4: error: Module 'MoMMI' has no attribute 'MChannel'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/help.py:4: error: Module 'MoMMI' has no attribute 'command'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/gamenudge.py:3: error: Module 'MoMMI' has no attribute 'MChannel'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/gamenudge.py:3: error: Module 'MoMMI' has no attribute 'comm_event'  [attr-defined]
(PJB3005)MoMMI/MoMMI/Modules/gamenudge.py:3: error: Module 'MoMMI' has no attribute 'SnowflakeID'  [attr-defined]

[RRepo](yoeo)guesslang
(yoeo)guesslang/guesslang/__main__.py:11: error: Module 'guesslang' has no attribute 'Guess'  [attr-defined]
(yoeo)guesslang/guesslang/__main__.py:11: error: Module 'guesslang' has no attribute 'GuesslangError'  [attr-defined]
(yoeo)guesslang/guesslang/__main__.py:11: error: Module 'guesslang' has no attribute 'config_logging'  [attr-defined]
(yoeo)guesslang/docs/conf.py:146: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
(yoeo)guesslang/tests/test_guesslang_utils.py:7: error: Module 'guesslang' has no attribute 'GuesslangError'  [attr-defined]
(yoeo)guesslang/tests/test_guesslang_guess.py:7: error: Module 'guesslang' has no attribute 'GuesslangError'  [attr-defined]
Found 6 errors in 4 files (checked 15 source files)

[RRepo](Zoidster)BirbBot
Success: no issues found in 3 source files

[RRepo](ekaj2)rock_builder
Success: no issues found in 1 source file

[RRepo](osm-fr)osmose-backend
(osm-fr)osmose-backend/mapcss/generated/MapCSSListener.py:9: error: Name 'ParseTreeListener' is not defined  [name-defined]

[RRepo](DeflatedPickle)Quiver
(DeflatedPickle)Quiver/dialog.py:6: error: Module 'tkinter' has no attribute 'font'  [attr-defined]
(DeflatedPickle)Quiver/dialog.py:234: error: "__init__" gets multiple values for keyword argument "title"  [misc]
(DeflatedPickle)Quiver/dialog.py:234: error: "__init__" gets multiple values for keyword argument "transient"  [misc]
(DeflatedPickle)Quiver/dialog.py:234: error: "__init__" gets multiple values for keyword argument "geometry"  [misc]
Found 4 errors in 1 file (checked 8 source files)

[RRepo](Floens)uchan

[RRepo](AeonGames)AeonEngine
(AeonGames)AeonEngine/tools/blender/addons/io_animation_anm/export.py:96: error: Invalid type comment or annotation  [valid-type]
(AeonGames)AeonEngine/tools/blender/addons/io_animation_anm/export.py:96: note: Suggestion: use bpy.props.StringProperty[...] instead of bpy.props.StringProperty(...)
Found 1 error in 1 file (checked 2 source files)

[RRepo](facebook)fbthrift

[RRepo](FrancescoCeruti)linux-show-player
(FrancescoCeruti)linux-show-player/lisp/core/singleton.py:47: error: Unsupported dynamic base class "type"  [misc]
(FrancescoCeruti)linux-show-player/lisp/ui/styles/styles.py:30: error: Name 'scandir' already defined (possibly by an import)  [no-redef]
(FrancescoCeruti)linux-show-player/lisp/ui/styles/styles.py:35: error: Need type annotation for 'LiSPStyles' (hint: "LiSPStyles: Dict[<type>, <type>] = ...")  [var-annotated]

[RRepo](phodge)dotfiles
(phodge)dotfiles/homely_dev/HOMELY.py:4: error: Module 'HOMELY' has no attribute 'jerjerrod_addline'  [attr-defined]
(phodge)dotfiles/homely_dev/HOMELY.py:4: error: Module 'HOMELY' has no attribute 'mypips'  [attr-defined]
(phodge)dotfiles/homely_dev/HOMELY.py:4: error: Module 'HOMELY' has no attribute 'wantfull'  [attr-defined]
(phodge)dotfiles/homely_dev/HOMELY.py:4: error: Module 'HOMELY' has no attribute 'wantjerjerrod'  [attr-defined]
Found 4 errors in 1 file (checked 3 source files)

[RRepo](telminov)django-park-keeper
(telminov)django-park-keeper/parkkeeper/tests/test_models.py:6: error: Module 'parkkeeper' has no attribute 'factories'  [attr-defined]
(telminov)django-park-keeper/parkkeeper/tests/datatools/test_worker.py:9: error: Module 'parkkeeper' has no attribute 'factories'  [attr-defined]
(telminov)django-park-keeper/parkkeeper/tests/datatools/test_task.py:9: error: Module 'parkkeeper' has no attribute 'factories'  [attr-defined]
(telminov)django-park-keeper/parkkeeper/event.py:12: error: Incompatible types in assignment (expression has type "bytes", variable has type "str")  [assignment]
(telminov)django-park-keeper/parkkeeper/event.py:30: error: Missing return statement  [return]
(telminov)django-park-keeper/parkkeeper/event.py:37: error: "None" not callable  [misc]

[RRepo](funkyfuture)deck-chores
Success: no issues found in 10 source files

[RRepo](miyakogi)wdom
(miyakogi)wdom/wdom/server/__init__.py: error: Duplicate module named 'server' (also at '/home/bew/archive/typed_project/(miyakogi)wdom/docs/server.py')  [misc]
(miyakogi)wdom/wdom/server/__init__.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 47 source files)

[RRepo](Ultimaker)Uranium
(Ultimaker)Uranium/tests/benchmarks/MeshData/profile_reserve.py:6: error: Name 'profile' is not defined  [name-defined]
(Ultimaker)Uranium/tests/benchmarks/MeshData/profile_reserve.py:10: error: Name 'profile' is not defined  [name-defined]
(Ultimaker)Uranium/tests/benchmarks/MeshData/profile_calcnormals.py:6: error: Name 'profile' is not defined  [name-defined]
(Ultimaker)Uranium/tests/benchmarks/MeshData/profile_addvertex.py:6: error: Name 'profile' is not defined  [name-defined]
(Ultimaker)Uranium/tests/benchmarks/MeshData/profile_getbytearray.py:6: error: Name 'profile' is not defined  [name-defined]
(Ultimaker)Uranium/tests/benchmarks/Settings/BenchmarkSettingDefinition.py:45: error: List item 0 has incompatible type "Tuple[Dict[str, str], int]"; expected "Tuple[object, bool]"  [list-item]
(Ultimaker)Uranium/tests/benchmarks/Settings/BenchmarkSettingDefinition.py:46: error: List item 1 has incompatible type "Tuple[Dict[str, str], int]"; expected "Tuple[object, bool]"  [list-item]
(Ultimaker)Uranium/tests/benchmarks/Settings/BenchmarkSettingDefinition.py:47: error: List item 2 has incompatible type "Tuple[Dict[str, int], int]"; expected "Tuple[object, bool]"  [list-item]
(Ultimaker)Uranium/tests/benchmarks/Settings/BenchmarkSettingDefinition.py:48: error: List item 3 has incompatible type "Tuple[Dict[str, int], int]"; expected "Tuple[object, bool]"  [list-item]
(Ultimaker)Uranium/tests/benchmarks/Settings/BenchmarkSettingDefinition.py:49: error: List item 4 has incompatible type "Tuple[Dict[str, str], int]"; expected "Tuple[object, bool]"  [list-item]
(Ultimaker)Uranium/tests/benchmarks/Settings/BenchmarkSettingDefinition.py:50: error: List item 5 has incompatible type "Tuple[Dict[str, int], int]"; expected "Tuple[object, bool]"  [list-item]
(Ultimaker)Uranium/tests/benchmarks/Settings/BenchmarkSettingDefinition.py:51: error: List item 6 has incompatible type "Tuple[Dict[str, str], int]"; expected "Tuple[object, bool]"  [list-item]
(Ultimaker)Uranium/run_mypy.py:8: error: Incompatible default for argument "search_path" (default has type "Optional[str]", argument has type "str")  [assignment]
(Ultimaker)Uranium/run_mypy.py:20: error: Incompatible types in assignment (expression has type "Set[str]", variable has type "List[str]")  [assignment]
(Ultimaker)Uranium/plugins/Tools/ScaleTool/__init__.py:4: error: Module 'ScaleTool' has no attribute 'ScaleTool'  [attr-defined]
(Ultimaker)Uranium/plugins/Tools/TranslateTool/__init__.py:4: error: Module 'TranslateTool' has no attribute 'TranslateTool'  [attr-defined]
(Ultimaker)Uranium/scripts/pirate.py:77: error: Incompatible types in assignment (expression has type "Tuple[Any, Any]", target has type "str")  [assignment]
(Ultimaker)Uranium/UM/Math/Polygon.py:135: error: Argument 1 to "polygon2ShapelyPolygon" has incompatible type "Polygon.Polygon"; expected "UM.Math.Polygon.Polygon"  [arg-type]
(Ultimaker)Uranium/UM/Math/Polygon.py:136: error: Argument 1 to "polygon2ShapelyPolygon" has incompatible type "Polygon.Polygon"; expected "UM.Math.Polygon.Polygon"  [arg-type]
(Ultimaker)Uranium/UM/Math/Polygon.py:157: error: Argument 1 to "polygon2ShapelyPolygon" has incompatible type "Polygon.Polygon"; expected "UM.Math.Polygon.Polygon"  [arg-type]
(Ultimaker)Uranium/UM/Math/Polygon.py:158: error: Argument 1 to "polygon2ShapelyPolygon" has incompatible type "Polygon.Polygon"; expected "UM.Math.Polygon.Polygon"  [arg-type]
(Ultimaker)Uranium/UM/Math/Polygon.py:176: error: Argument 1 to "polygon2ShapelyPolygon" has incompatible type "Polygon.Polygon"; expected "UM.Math.Polygon.Polygon"  [arg-type]
(Ultimaker)Uranium/UM/Math/Polygon.py:177: error: Argument 1 to "polygon2ShapelyPolygon" has incompatible type "Polygon.Polygon"; expected "UM.Math.Polygon.Polygon"  [arg-type]
(Ultimaker)Uranium/tests/benchmarks/Math/profile_rayintersection.py:8: error: Name 'profile' is not defined  [name-defined]
(Ultimaker)Uranium/tests/benchmarks/Math/profile_rayintersection.py:13: error: Too many arguments for "AxisAlignedBox"  [call-arg]
(Ultimaker)Uranium/tests/benchmarks/Math/profile_rayintersection.py:13: error: Argument 1 to "AxisAlignedBox" has incompatible type "int"; expected "Vector"  [arg-type]
(Ultimaker)Uranium/tests/benchmarks/Math/profile_rayintersection.py:13: error: Argument 2 to "AxisAlignedBox" has incompatible type "int"; expected "Vector"  [arg-type]
(Ultimaker)Uranium/tests/Settings/ContainerTestPlugin/ContainerTestPlugin.py:104: error: Name 'Signal' is not defined  [name-defined]
(Ultimaker)Uranium/tests/TestPreferences.py:18: error: Need type annotation for 'test_newValues_data'  [var-annotated]
(Ultimaker)Uranium/UM/Qt/Bindings/OutputDeviceManagerProxy.py:11: error: Module 'UM.OutputDevice' has no attribute 'OutputDeviceError'  [attr-defined]

[RRepo](pypa)linehaul
(pypa)linehaul/tests/unit/protocol/test_line_receiver.py:25: error: Relative import climbs too many namespaces  [misc]
(pypa)linehaul/linehaul/events/parser.py:48: error: Cannot assign to a type  [misc]
(pypa)linehaul/linehaul/events/parser.py:48: error: Incompatible types in assignment (expression has type "NullValue", variable has type "Type[NullValue]")  [assignment]
(pypa)linehaul/linehaul/server.py:48: error: Missing return statement  [return]
(pypa)linehaul/linehaul/server.py:56: error: Return value expected  [return-value]
(pypa)linehaul/linehaul/server.py:60: error: Incompatible types in assignment (expression has type "str", variable has type "bytes")  [assignment]
Found 6 errors in 3 files (checked 15 source files)

[RRepo](wa1tnr)ainsuSPI
(wa1tnr)ainsuSPI/0-Distribution.d/circuitpython-master/cc3200/tools/uniflash.py:14: error: (unicode error) 'unicodeescape' codec can't decode bytes in position 100-101: truncated \uXXXX escape  [syntax]
Found 1 error in 1 file (checked 404 source files)

[RRepo](welbornprod)colr
(welbornprod)colr/colr/colr_docopt.py:134: error: Name 'docopt' already defined (possibly by an import)  [no-redef]
(welbornprod)colr/colr/colr_run.py:29: error: Item "None" of "Optional[str]" has no attribute "lower"  [union-attr]
(welbornprod)colr/examples/walk_dir.py:23: error: Module 'colr' has no attribute '__version__'  [attr-defined]
(welbornprod)colr/examples/walk_dir.py:32: error: Module 'colr' has no attribute 'AnimatedProgress'  [attr-defined]
(welbornprod)colr/examples/walk_dir.py:32: error: Module 'colr' has no attribute 'auto_disable'  [attr-defined]
(welbornprod)colr/examples/walk_dir.py:32: error: Module 'colr' has no attribute 'Bars'  [attr-defined]
(welbornprod)colr/examples/walk_dir.py:32: error: Module 'colr' has no attribute 'Colr'  [attr-defined]
(welbornprod)colr/examples/walk_dir.py:32: error: Module 'colr' has no attribute 'docopt'  [attr-defined]
(welbornprod)colr/examples/walk_dir.py:32: error: Module 'colr' has no attribute 'Frames'  [attr-defined]
(welbornprod)colr/examples/walk_dir.py:32: error: Module 'colr' has no attribute 'ProgressBar'  [attr-defined]
(welbornprod)colr/test/run_controls.py:23: error: Module 'colr' has no attribute 'Colr'  [attr-defined]
(welbornprod)colr/test/run_controls.py:23: error: Module 'colr' has no attribute 'docopt'  [attr-defined]
(welbornprod)colr/benchmark.py:23: error: Module 'colr' has no attribute 'AnimatedProgress'  [attr-defined]
(welbornprod)colr/benchmark.py:23: error: Module 'colr' has no attribute 'Colr'  [attr-defined]
(welbornprod)colr/benchmark.py:23: error: Module 'colr' has no attribute 'Frames'  [attr-defined]
(welbornprod)colr/benchmark.py:23: error: Module 'colr' has no attribute 'color'  [attr-defined]
(welbornprod)colr/benchmark.py:23: error: Module 'colr' has no attribute 'docopt'  [attr-defined]
(welbornprod)colr/test/test_colr_docopt.py:12: error: Module 'colr' has no attribute 'docopt'  [attr-defined]
(welbornprod)colr/test/test_colr_docopt.py:12: error: Module 'colr' has no attribute 'docopt_file'  [attr-defined]
(welbornprod)colr/test/test_colr_docopt.py:12: error: Module 'colr' has no attribute 'docopt_version'  [attr-defined]
(welbornprod)colr/test/test_trans.py:13: error: Module 'colr' has no attribute '__version__'  [attr-defined]
(welbornprod)colr/test/test_controls.py:13: error: Module 'colr' has no attribute '__version__'  [attr-defined]
(welbornprod)colr/test/test_controls.py:13: error: Module 'colr' has no attribute 'Colr'  [attr-defined]
(welbornprod)colr/test/test_preset.py:12: error: Module 'colr' has no attribute '__version__'  [attr-defined]
(welbornprod)colr/test/test_preset.py:12: error: Module 'colr' has no attribute 'Colr'  [attr-defined]
(welbornprod)colr/test/test_preset.py:12: error: Module 'colr' has no attribute 'Preset'  [attr-defined]
Found 26 errors in 9 files (checked 14 source files)

[RRepo](WoodNeck)tataru
(WoodNeck)tataru/cogs/utils/session.py:157: error: Need type annotation for 'fields' (hint: "fields: List[<type>] = ...")  [var-annotated]

[RRepo](tuna)fishroom
(tuna)fishroom/fishroom/plugins/pia.py:3: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/vote.py:3: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/vote.py:4: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/vote.py:5: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/xmpp.py:82: error: Cannot assign to a method  [assignment]
(tuna)fishroom/fishroom/xmpp.py:82: error: Incompatible types in assignment (expression has type "Callable[[Any, Any], Any]", variable has type "Callable[[Any], Any]")  [assignment]
(tuna)fishroom/fishroom/command.py:18: error: Need type annotation for 'command_handlers' (hint: "command_handlers: Dict[<type>, <type>] = ...")  [var-annotated]
(tuna)fishroom/fishroom/runner.py:57: error: Type of __all__ must be "Sequence[str]", not "List[Callable[[Iterable[Tuple[Callable[[Any], Any], Tuple[Any]]]], Any]]"  [misc]
(tuna)fishroom/fishroom/plugins/imglink.py:4: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/imglink.py:5: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/hualao.py:6: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/hualao.py:7: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/hualao.py:8: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/hualao.py:9: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/hualao.py:10: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/wechat.py:24: error: Need type annotation for 'wxRooms' (hint: "wxRooms: Dict[<type>, <type>] = ...")  [var-annotated]
(tuna)fishroom/fishroom/wechat.py:24: error: Need type annotation for 'wxRoomNicks' (hint: "wxRoomNicks: Dict[<type>, <type>] = ...")  [var-annotated]
(tuna)fishroom/fishroom/wechat.py:221: error: Cannot assign to a method  [assignment]
(tuna)fishroom/fishroom/wechat.py:221: error: Incompatible types in assignment (expression has type "Callable[[Any, Any], Any]", variable has type "Callable[[Any], Any]")  [assignment]
(tuna)fishroom/fishroom/matrix.py:141: error: Cannot assign to a method  [assignment]
(tuna)fishroom/fishroom/matrix.py:141: error: Incompatible types in assignment (expression has type "Callable[[Any, Any], Any]", variable has type "Callable[[Any], Any]")  [assignment]
(tuna)fishroom/fishroom/base.py:18: note: "send_photo" of "BaseBotInstance" defined here
(tuna)fishroom/fishroom/base.py:44: error: Incompatible return value type (got "object", expected "Tuple[str, str]")  [return-value]
(tuna)fishroom/fishroom/base.py:54: error: "None" has no attribute "lower"  [attr-defined]
(tuna)fishroom/fishroom/base.py:62: error: Unexpected keyword argument "sender" for "send_photo" of "BaseBotInstance"  [call-arg]
(tuna)fishroom/fishroom/base.py:94: error: Incompatible types in assignment (expression has type "str", base class "BaseBotInstance" defined the type as "None")  [assignment]
(tuna)fishroom/fishroom/plugins/ratelimit.py:5: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/ratelimit.py:6: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/IRC.py:200: error: Cannot assign to a method  [assignment]
(tuna)fishroom/fishroom/IRC.py:200: error: Incompatible types in assignment (expression has type "Callable[[Any, Any], Any]", variable has type "Callable[[Any], Any]")  [assignment]
(tuna)fishroom/fishroom/plugins/stats.py:7: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/stats.py:8: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/stats.py:9: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/stats.py:10: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/plugins/stats.py:11: error: Relative import climbs too many namespaces  [misc]
(tuna)fishroom/fishroom/db.py:5: error: Need type annotation for '__dbctx' (hint: "__dbctx: Dict[<type>, <type>] = ...")  [var-annotated]
(tuna)fishroom/fishroom/models.py:252: error: Incompatible types in assignment (expression has type "TextStyleSchema", variable has type "None")  [assignment]
(tuna)fishroom/fishroom/photostore.py:82: error: Incompatible return value type (got "None", expected "str")  [return-value]
(tuna)fishroom/fishroom/photostore.py:85: error: Incompatible return value type (got "None", expected "str")  [return-value]
(tuna)fishroom/fishroom/photostore.py:87: error: Incompatible return value type (got "None", expected "str")  [return-value]
(tuna)fishroom/fishroom/helpers.py:67: error: Incompatible return value type (got "Tuple[None, None]", expected "Tuple[bytes, str]")  [return-value]
(tuna)fishroom/fishroom/helpers.py:70: error: Incompatible return value type (got "Tuple[None, None]", expected "Tuple[bytes, str]")  [return-value]
(tuna)fishroom/fishroom/helpers.py:72: error: Incompatible return value type (got "Tuple[bytes, Optional[str]]", expected "Tuple[bytes, str]")  [return-value]
(tuna)fishroom/fishroom/textstore.py:57: error: Incompatible return value type (got "None", expected "str")  [return-value]
(tuna)fishroom/fishroom/textstore.py:62: error: Incompatible return value type (got "None", expected "str")  [return-value]
(tuna)fishroom/fishroom/textstore.py:80: error: Incompatible return value type (got "None", expected "str")  [return-value]
(tuna)fishroom/fishroom/textstore.py:85: error: Incompatible return value type (got "None", expected "str")  [return-value]

[RRepo](mattrberry)csgoSkinStatistics

[RRepo](cclauss)Ten-lines-or-less

[RRepo](jmcs)ecological
(jmcs)ecological/ecological/transform.py:14: error: Cannot assign to a type  [misc]
(jmcs)ecological/ecological/transform.py:14: error: Incompatible types in assignment (expression has type "None", variable has type "Type[GenericMeta]")  [assignment]
(jmcs)ecological/ecological/transform.py:23: error: Incompatible types in assignment (expression has type "object", variable has type "Type[deque[Any]]")  [assignment]
(jmcs)ecological/ecological/transform.py:23: error: Incompatible types in assignment (expression has type "object", variable has type "Type[Counter[Any]]")  [assignment]
(jmcs)ecological/ecological/transform.py:69: error: "type" has no attribute "__origin__"  [attr-defined]
(jmcs)ecological/ecological/transform.py:85: error: "type" has no attribute "__supertype__"  [attr-defined]
Found 6 errors in 1 file (checked 2 source files)

[RRepo](dainst)gazetteer
Success: no issues found in 3 source files

[RRepo](mirumee)django-prices-openexchangerates
(mirumee)django-prices-openexchangerates/django_prices_openexchangerates/management/commands/update_exchange_rates.py:3: error: Relative import climbs too many namespaces  [misc]
Found 1 error in 1 file (checked 5 source files)

[RRepo](lnmds)jose

[RRepo](tchellomello)home-assistant
(tchellomello)home-assistant/homeassistant/components/zha/core/registries.py:27: error: Need type annotation for 'DEVICE_CLASS' (hint: "DEVICE_CLASS: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/components/zha/core/registries.py:28: error: Need type annotation for 'SINGLE_INPUT_CLUSTER_DEVICE_CLASS' (hint: "SINGLE_INPUT_CLUSTER_DEVICE_CLASS: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/components/zha/core/registries.py:29: error: Need type annotation for 'SINGLE_OUTPUT_CLUSTER_DEVICE_CLASS' (hint: "SINGLE_OUTPUT_CLUSTER_DEVICE_CLASS: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/components/zha/core/registries.py:30: error: Need type annotation for 'SENSOR_TYPES' (hint: "SENSOR_TYPES: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/components/zha/core/registries.py:32: error: Need type annotation for 'BINARY_SENSOR_TYPES' (hint: "BINARY_SENSOR_TYPES: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/components/zha/core/registries.py:33: error: Need type annotation for 'REMOTE_DEVICE_TYPES' (hint: "REMOTE_DEVICE_TYPES: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/components/zha/core/registries.py:34: error: Need type annotation for 'CLUSTER_REPORT_CONFIGS' (hint: "CLUSTER_REPORT_CONFIGS: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/components/zha/core/registries.py:35: error: Need type annotation for 'CUSTOM_CLUSTER_MAPPINGS' (hint: "CUSTOM_CLUSTER_MAPPINGS: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/components/zha/core/registries.py:41: error: Need type annotation for 'BINARY_SENSOR_CLUSTERS' (hint: "BINARY_SENSOR_CLUSTERS: Set[<type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/components/zha/core/registries.py:42: error: Need type annotation for 'LIGHT_CLUSTERS' (hint: "LIGHT_CLUSTERS: Set[<type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/components/zha/core/registries.py:43: error: Need type annotation for 'SWITCH_CLUSTERS' (hint: "SWITCH_CLUSTERS: Set[<type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/components/device_tracker/config_entry.py:62: error: Incompatible return value type (got "None", expected "str")  [return-value]
(tchellomello)home-assistant/homeassistant/components/device_tracker/config_entry.py:67: error: Incompatible return value type (got "Type[NotImplementedError]", expected "float")  [return-value]
(tchellomello)home-assistant/homeassistant/components/device_tracker/config_entry.py:72: error: Incompatible return value type (got "Type[NotImplementedError]", expected "float")  [return-value]
(tchellomello)home-assistant/homeassistant/components/alexa/errors.py:38: error: Incompatible types in assignment (expression has type "str", base class "AlexaError" defined the type as "None")  [assignment]
(tchellomello)home-assistant/homeassistant/components/alexa/errors.py:39: error: Incompatible types in assignment (expression has type "str", base class "AlexaError" defined the type as "None")  [assignment]
(tchellomello)home-assistant/homeassistant/components/alexa/errors.py:51: error: Incompatible types in assignment (expression has type "str", base class "AlexaError" defined the type as "None")  [assignment]
(tchellomello)home-assistant/homeassistant/components/alexa/errors.py:52: error: Incompatible types in assignment (expression has type "str", base class "AlexaError" defined the type as "None")  [assignment]
(tchellomello)home-assistant/homeassistant/components/alexa/errors.py:58: error: Incompatible types in assignment (expression has type "str", base class "AlexaError" defined the type as "None")  [assignment]
(tchellomello)home-assistant/homeassistant/components/alexa/errors.py:59: error: Incompatible types in assignment (expression has type "str", base class "AlexaError" defined the type as "None")  [assignment]
(tchellomello)home-assistant/homeassistant/components/alexa/errors.py:65: error: Incompatible types in assignment (expression has type "str", base class "AlexaError" defined the type as "None")  [assignment]
(tchellomello)home-assistant/homeassistant/components/alexa/errors.py:66: error: Incompatible types in assignment (expression has type "str", base class "AlexaError" defined the type as "None")  [assignment]
(tchellomello)home-assistant/homeassistant/components/alexa/errors.py:90: error: Incompatible types in assignment (expression has type "str", base class "AlexaError" defined the type as "None")  [assignment]
(tchellomello)home-assistant/homeassistant/components/alexa/errors.py:91: error: Incompatible types in assignment (expression has type "str", base class "AlexaError" defined the type as "None")  [assignment]
(tchellomello)home-assistant/homeassistant/components/demo/fan.py:86: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
(tchellomello)home-assistant/tests/components/alexa/__init__.py:16: error: Need type annotation for 'entity_config' (hint: "entity_config: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/tests/components/auth/__init__.py:18: error: Need type annotation for 'EMPTY_CONFIG' (hint: "EMPTY_CONFIG: List[<type>] = ...")  [var-annotated]
(tchellomello)home-assistant/tests/helpers/test_deprecation.py:11: error: Decorated property not supported  [misc]
(tchellomello)home-assistant/tests/helpers/test_config_entry_flow.py:6: error: Module 'homeassistant' has no attribute 'data_entry_flow'  [attr-defined]
(tchellomello)home-assistant/tests/components/auth/test_mfa_setup_flow.py:2: error: Module 'homeassistant' has no attribute 'data_entry_flow'  [attr-defined]
(tchellomello)home-assistant/tests/auth/providers/test_command_line.py:9: error: Module 'homeassistant' has no attribute 'data_entry_flow'  [attr-defined]
(tchellomello)home-assistant/tests/auth/providers/test_legacy_api_password.py:4: error: Module 'homeassistant' has no attribute 'data_entry_flow'  [attr-defined]
(tchellomello)home-assistant/tests/test_data_entry_flow.py:5: error: Module 'homeassistant' has no attribute 'data_entry_flow'  [attr-defined]
(tchellomello)home-assistant/tests/test_main.py:4: error: Module 'homeassistant' has no attribute '__main__'  [attr-defined]
(tchellomello)home-assistant/docs/source/conf.py:156: error: Need type annotation for 'exclude_patterns' (hint: "exclude_patterns: List[<type>] = ...")  [var-annotated]
(tchellomello)home-assistant/docs/source/conf.py:334: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/components/config/config_entries.py:3: error: Module 'homeassistant' has no attribute 'data_entry_flow'  [attr-defined]
(tchellomello)home-assistant/homeassistant/components/homeassistant/scene.py:30: error: String literal expected as namedtuple() item  [misc]
(tchellomello)home-assistant/homeassistant/components/demo/calendar.py:30: error: Need type annotation for 'event' (hint: "event: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/helpers/deprecation.py:49: error: Item "None" of "Optional[Module]" has no attribute "__name__"  [union-attr]
(tchellomello)home-assistant/homeassistant/helpers/script.py:93: error: Need type annotation for '_async_listener' (hint: "_async_listener: List[<type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/helpers/script.py:94: error: Need type annotation for '_template_cache' (hint: "_template_cache: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/helpers/script.py:95: error: Need type annotation for '_config_cache' (hint: "_config_cache: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/homeassistant/helpers/script.py:142: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(tchellomello)home-assistant/homeassistant/components/auth/mfa_setup_flow.py:6: error: Module 'homeassistant' has no attribute 'data_entry_flow'  [attr-defined]
(tchellomello)home-assistant/homeassistant/util/json.py:53: error: Argument "cls" to "dumps" has incompatible type "Optional[JSONEncoder]"; expected "Optional[Type[JSONEncoder]]"  [arg-type]
(tchellomello)home-assistant/script/hassfest/zeroconf.py:23: error: Need type annotation for 'service_type_dict'  [var-annotated]
(tchellomello)home-assistant/script/hassfest/zeroconf.py:24: error: Need type annotation for 'homekit_dict' (hint: "homekit_dict: Dict[<type>, <type>] = ...")  [var-annotated]
(tchellomello)home-assistant/script/hassfest/zeroconf.py:77: error: Need type annotation for 'warned' (hint: "warned: Set[<type>] = ...")  [var-annotated]
(tchellomello)home-assistant/script/hassfest/ssdp.py:27: error: Need type annotation for 'data'  [var-annotated]
(tchellomello)home-assistant/script/translations_upload_merge.py:29: error: Incompatible types in assignment (expression has type "str", variable has type "Union[List[Any], Dict[Any, Any]]")  [assignment]
(tchellomello)home-assistant/script/translations_upload_merge.py:31: error: Argument 1 to "write" of "IO" has incompatible type "Union[List[Any], Dict[Any, Any]]"; expected "str"  [arg-type]
(tchellomello)home-assistant/script/translations_download_split.py:28: error: Incompatible types in assignment (expression has type "str", variable has type "Union[List[Any], Dict[Any, Any]]")  [assignment]
(tchellomello)home-assistant/script/translations_download_split.py:30: error: Argument 1 to "write" of "IO" has incompatible type "Union[List[Any], Dict[Any, Any]]"; expected "str"  [arg-type]

[RRepo](loopspace)microbit
(loopspace)microbit/enigma/enigma.py:51: error: Name 'pin12' is not defined  [name-defined]
(loopspace)microbit/enigma/enigma.py:51: error: Name 'pin13' is not defined  [name-defined]
(loopspace)microbit/enigma/enigma.py:51: error: Name 'pin14' is not defined  [name-defined]
(loopspace)microbit/enigma/enigma.py:51: error: Name 'pin15' is not defined  [name-defined]
(loopspace)microbit/enigma/enigma.py:51: error: Name 'pin16' is not defined  [name-defined]
(loopspace)microbit/enigma/enigma.py:66: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/enigma/enigma.py:69: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/enigma/enigma.py:70: error: Name 'sleep' is not defined  [name-defined]
(loopspace)microbit/enigma/enigma.py:71: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/lego/acrobot/acrobot_capacitor.py:9: error: Name 'pin1' is not defined  [name-defined]
(loopspace)microbit/lego/acrobot/acrobot_capacitor.py:21: error: Name 'pin1' is not defined  [name-defined]
(loopspace)microbit/lego/acrobot/acrobot.py:10: error: Name 'pin1' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:4: error: Name 'pin0' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:7: error: Name 'pin1' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:8: error: Name 'pin2' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:55: error: Name 'accelerometer' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:56: error: Name 'button_a' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:60: error: Name 'button_b' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:65: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:71: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:73: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:73: error: Name 'Image' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:74: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:78: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:82: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:82: error: Name 'Image' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:85: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:87: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:87: error: Name 'Image' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:88: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:92: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:96: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/minimove/main.py:96: error: Name 'Image' is not defined  [name-defined]
(loopspace)microbit/minimove/remove.py:11: error: Name 'pin0' is not defined  [name-defined]
(loopspace)microbit/minimove/remove.py:14: error: Name 'pin1' is not defined  [name-defined]
(loopspace)microbit/minimove/remove.py:15: error: Name 'pin2' is not defined  [name-defined]
(loopspace)microbit/minimove/remove.py:113: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/minimove/remove.py:113: error: Name 'Image' is not defined  [name-defined]
(loopspace)microbit/minimove/remove.py:120: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/minimove/remove.py:120: error: Name 'Image' is not defined  [name-defined]
(loopspace)microbit/minimove/remove.py:126: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/minimove/remove.py:126: error: Name 'Image' is not defined  [name-defined]
(loopspace)microbit/minimove/remove.py:130: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/minimove/remove.py:130: error: Name 'Image' is not defined  [name-defined]
(loopspace)microbit/ziphalo/test.py:167: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/ziphalo/test.py:170: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/ziphalo/gravity.py:12: error: Name 'pin0' is not defined  [name-defined]
(loopspace)microbit/ziphalo/gravity.py:15: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/gravity.py:24: error: Name 'accelerometer' is not defined  [name-defined]
(loopspace)microbit/ziphalo/gravity.py:25: error: Name 'accelerometer' is not defined  [name-defined]
(loopspace)microbit/ziphalo/gravity.py:26: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/gravity.py:27: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/gravity.py:30: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(loopspace)microbit/ziphalo/chase.py:13: error: Name 'pin0' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:16: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:17: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:19: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:20: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:31: error: Name 'button_b' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:32: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:34: error: Name 'button_a' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:37: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:38: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:39: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:43: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:44: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:51: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:53: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:58: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:67: error: Name 'accelerometer' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:68: error: Name 'accelerometer' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:69: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:70: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:73: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
(loopspace)microbit/ziphalo/chase.py:84: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:86: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:89: error: Incompatible types in assignment (expression has type "str", variable has type "int")  [assignment]
(loopspace)microbit/ziphalo/chase.py:89: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:90: error: Name 'display' is not defined  [name-defined]
(loopspace)microbit/ziphalo/chase.py:94: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/circuit.py:46: error: Name 'pin0' is not defined  [name-defined]
(loopspace)microbit/ziphalo/circuit.py:67: error: Name 'sleep' is not defined  [name-defined]
(loopspace)microbit/ziphalo/ball.py:41: error: Name 'pin0' is not defined  [name-defined]
(loopspace)microbit/ziphalo/ball.py:53: error: List item 0 has incompatible type "float"; expected "int"  [list-item]
(loopspace)microbit/ziphalo/ball.py:54: error: List item 0 has incompatible type "float"; expected "int"  [list-item]
(loopspace)microbit/ziphalo/ball.py:56: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/ball.py:57: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/ball.py:63: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/ball.py:64: error: Name 'running_time' is not defined  [name-defined]
(loopspace)microbit/ziphalo/ball.py:65: error: Name 'accelerometer' is not defined  [name-defined]
(loopspace)microbit/ziphalo/ball.py:66: error: Name 'accelerometer' is not defined  [name-defined]
(loopspace)microbit/ziphalo/ball.py:75: error: List item 0 has incompatible type "float"; expected "int"  [list-item]
(loopspace)microbit/ziphalo/ball.py:83: error: No overload variant of "__setitem__" of "list" matches argument types "int", "float"  [call-overload]
(loopspace)microbit/ziphalo/ball.py:83: note: Possible overload variants:
(loopspace)microbit/ziphalo/ball.py:83: note:     def __setitem__(self, int, int) -> None
(loopspace)microbit/ziphalo/ball.py:83: note:     def __setitem__(self, slice, Iterable[int]) -> None
(loopspace)microbit/ziphalo/ball.py:103: error: Incompatible types in assignment (expression has type "List[int]", variable has type "Set[int]")  [assignment]
(loopspace)microbit/lego/ev3.py:308: error: Cannot determine type of '_protocol'  [has-type]
(loopspace)microbit/lego/ev3.py:309: error: Cannot determine type of '_device'  [has-type]
(loopspace)microbit/lego/ev3.py:310: error: Cannot determine type of '_socket'  [has-type]
(loopspace)microbit/lego/ev3.py:367: error: Incompatible return value type (got "int", expected "bytes")  [return-value]
(loopspace)microbit/lego/ev3.py:520: error: Name 'av' is not defined  [name-defined]
(loopspace)microbit/lego/ev3.py:522: error: Name 'av' is not defined  [name-defined]
(loopspace)microbit/lego/ev3.py:524: error: Name 'av' is not defined  [name-defined]
(loopspace)microbit/lego/ev3.py:526: error: Name 'av' is not defined  [name-defined]
(loopspace)microbit/speed/speed_pc.py:6: error: Need type annotation for 'key'  [var-annotated]
(loopspace)microbit/speed/speed_pc.py:49: error: Module has no attribute "queue"  [attr-defined]
(loopspace)microbit/speed/speed_pc.py:50: error: Module has no attribute "queue"  [attr-defined]
(loopspace)microbit/speed/speed_pygame.py:29: error: Need type annotation for 'times' (hint: "times: List[<type>] = ...")  [var-annotated]
(loopspace)microbit/speed/speed_pygame.py:33: error: Need type annotation for 'scores' (hint: "scores: Dict[<type>, <type>] = ...")  [var-annotated]
(loopspace)microbit/speed/speed_pygame.py:46: error: Need type annotation for 'disqualified' (hint: "disqualified: List[<type>] = ...")  [var-annotated]
(loopspace)microbit/speed/speed_pygame.py:85: error: Module has no attribute "MICROBITEVENT"  [attr-defined]
(loopspace)microbit/lego/R3ptar.py:41: error: Module has no attribute "queue"  [attr-defined]
(loopspace)microbit/lego/edubot.py:21: error: Module has no attribute "queue"  [attr-defined]
(loopspace)microbit/lego/Track3r.py:32: error: Module has no attribute "queue"  [attr-defined]
Found 112 errors in 16 files (checked 26 source files)

[RRepo](evancasey)demeter
(evancasey)demeter/demeter/rl/env/gym.py:16: error: Name 'gym.Env' is not defined  [name-defined]
(evancasey)demeter/demeter/rl/env/gym.py:37: error: Name 'gym.Space' is not defined  [name-defined]
(evancasey)demeter/demeter/rl/env/gym.py:41: error: Name 'gym.Space' is not defined  [name-defined]
(evancasey)demeter/demeter/rl/actor_critic.py:43: error: Unsupported operand types for >= ("int" and "None")  [operator]
(evancasey)demeter/demeter/rl/actor_critic.py:43: note: Right operand is of type "Optional[int]"
(evancasey)demeter/demeter/rl/common/buffer.py:45: error: Item "None" of "Optional[Dict[str, Union[Any, Any, List[Any]]]]" has no attribute "items"  [union-attr]
(evancasey)demeter/demeter/rl/common/buffer.py:52: error: Item "None" of "Optional[Dict[str, Union[Any, Any, List[Any]]]]" has no attribute "items"  [union-attr]
(evancasey)demeter/demeter/rl/common/buffer.py:111: error: Missing return statement  [return]
(evancasey)demeter/demeter/rl/common/buffer.py:111: error: Function "buffer.TensorBuffer.slice" is not valid as a type  [valid-type]
(evancasey)demeter/demeter/rl/common/buffer.py:111: note: Perhaps you need "Callable[...]" or a callback protocol?
(evancasey)demeter/scripts/pix2pix_facade.py:104: error: Cannot assign to a method  [assignment]
(evancasey)demeter/scripts/pix2pix_facade.py:105: error: Cannot assign to a method  [assignment]
(evancasey)demeter/scripts/reinforce_cartpole.py:56: error: Module has no attribute "make"  [attr-defined]
(evancasey)demeter/scripts/reinforce_cartpole.py:65: error: Need type annotation for 'all_eps_rewards'  [var-annotated]
(evancasey)demeter/scripts/create_catdraw_tfrecords.py:47: error: Need type annotation for 'fnames_dedup'  [var-annotated]
(evancasey)demeter/scripts/pix2pix_catdraw.py:137: error: Cannot assign to a method  [assignment]
(evancasey)demeter/scripts/pix2pix_catdraw.py:138: error: Cannot assign to a method  [assignment]
(evancasey)demeter/scripts/dcgan_mnist.py:99: error: Cannot assign to a method  [assignment]
(evancasey)demeter/scripts/dcgan_mnist.py:100: error: Cannot assign to a method  [assignment]
Found 17 errors in 8 files (checked 20 source files)

[RRepo](DeflatedPickle)pkinter
(DeflatedPickle)pkinter/pkinter/center.py:12: error: Invalid type comment or annotation  [valid-type]
(DeflatedPickle)pkinter/pkinter/center.py:28: error: "Toplevel" has no attribute "master"  [attr-defined]
(DeflatedPickle)pkinter/pkinter/hyperlink.py:7: error: Module 'tkinter' has no attribute 'font'  [attr-defined]
(DeflatedPickle)pkinter/pkinter/entryspinbox.py:15: error: Name 'ttk.Spinbox' is not defined  [name-defined]
(DeflatedPickle)pkinter/pkinter_test.py:21: error: Module has no attribute "Toolbar"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:35: error: Module has no attribute "Statusbar"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:57: error: Module has no attribute "ToggledLabelFrame"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:65: error: Module has no attribute "LabeledSeparator"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:70: error: Module has no attribute "RoundingScale"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:75: error: Module has no attribute "EntryText"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:80: error: Module has no attribute "LimitedEntry"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:85: error: Module has no attribute "ColourPickerButton"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:90: error: Module has no attribute "EditableLabel"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:95: error: Module has no attribute "CollapsiblePane"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:103: error: Module has no attribute "Hyperlink"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:108: error: Module has no attribute "PageView"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:129: error: Module has no attribute "BoundButton"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:134: error: Module has no attribute "ValidEntry"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:139: error: Module has no attribute "ChoiceBook"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:156: error: Module has no attribute "PasswordEntry"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:161: error: Module has no attribute "InvalidEntry"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:166: error: Module has no attribute "ListBook"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:183: error: Module has no attribute "AccelLabel"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:188: error: Module has no attribute "InfoBar"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:193: error: Module has no attribute "LockButton"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:198: error: Module has no attribute "ToggleButton"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:203: error: Module has no attribute "ScaleSwitch"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:208: error: Module has no attribute "ButtonSwitch"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:213: error: Module has no attribute "FilePicker"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:218: error: Module has no attribute "DirectoryPicker"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:223: error: Module has no attribute "center_on_screen"  [attr-defined]
(DeflatedPickle)pkinter/pkinter_test.py:228: error: Module has no attribute "center_on_parent"  [attr-defined]
Found 32 errors in 4 files (checked 35 source files)

[RRepo](naturalness)sensibility
(naturalness)sensibility/sensibility/sentences.py:25: error: Module 'sensibility' has no attribute 'current_language'  [attr-defined]

[RRepo](benmoran56)esper
(benmoran56)esper/esper.py:63: error: "Processor" has no attribute "priority"  [attr-defined]
(benmoran56)esper/esper.py:64: error: Incompatible types in assignment (expression has type "World", variable has type "None")  [assignment]
(benmoran56)esper/esper.py:78: error: Missing return statement  [return]
(benmoran56)esper/esper.py:248: error: Incompatible types in "yield" (actual type "Tuple[Any, List[Any]]", expected type "Tuple[int, ...]")  [misc]
(benmoran56)esper/examples/benchmark.py:131: error: Need type annotation for 'results'  [var-annotated]
(benmoran56)esper/examples/benchmark.py:132: error: Need type annotation for 'result_times' (hint: "result_times: List[<type>] = ...")  [var-annotated]
(benmoran56)esper/examples/benchmark.py:185: error: Need type annotation for 'lines' (hint: "lines: List[<type>] = ...")  [var-annotated]
(benmoran56)esper/examples/benchmark_cache.py:117: error: Need type annotation for 'current_run' (hint: "current_run: List[<type>] = ...")  [var-annotated]
(benmoran56)esper/examples/pythonista_ios_example.py:7: error: Name 'SpriteNode' is not defined  [name-defined]
(benmoran56)esper/examples/pythonista_ios_example.py:32: error: Name 'Scene' is not defined  [name-defined]
(benmoran56)esper/examples/pythonista_ios_example.py:69: error: Name 'run' is not defined  [name-defined]
Found 11 errors in 4 files (checked 10 source files)

[RRepo](automl)RoBO
(automl)RoBO/experiments/fabolas/run_mtbo.py:83: error: Need type annotation for 'test_error' (hint: "test_error: List[<type>] = ...")  [var-annotated]
(automl)RoBO/experiments/fabolas/run_fabolas.py:144: error: Need type annotation for 'test_error' (hint: "test_error: List[<type>] = ...")  [var-annotated]
(automl)RoBO/experiments/bayesopt/run_direct_synthetic_funcs.py:86: error: Incompatible types in assignment (expression has type "List[Any]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_direct_synthetic_funcs.py:87: error: Incompatible types in assignment (expression has type "int", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_direct_synthetic_funcs.py:88: error: Incompatible types in assignment (expression has type "List[Optional[Any]]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_direct_synthetic_funcs.py:89: error: Incompatible types in assignment (expression has type "List[float]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_direct_synthetic_funcs.py:90: error: Incompatible types in assignment (expression has type "List[Any]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_direct_synthetic_funcs.py:91: error: Incompatible types in assignment (expression has type "List[Any]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_scipy_synthetic_funcs.py:89: error: Incompatible types in assignment (expression has type "List[Any]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_scipy_synthetic_funcs.py:90: error: Incompatible types in assignment (expression has type "int", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_scipy_synthetic_funcs.py:91: error: Incompatible types in assignment (expression has type "List[Optional[Any]]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_scipy_synthetic_funcs.py:92: error: Incompatible types in assignment (expression has type "List[float]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_scipy_synthetic_funcs.py:93: error: Incompatible types in assignment (expression has type "List[Any]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_scipy_synthetic_funcs.py:94: error: Incompatible types in assignment (expression has type "List[Any]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_mtbo_surrogate.py:56: error: Need type annotation for 'test_error' (hint: "test_error: List[<type>] = ...")  [var-annotated]
(automl)RoBO/experiments/bayesopt/run_cmaes_surrogate.py:88: error: Incompatible types in assignment (expression has type "List[List[Any]]", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_cmaes_surrogate.py:90: error: Incompatible types in assignment (expression has type "str", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_cmaes_surrogate.py:91: error: Incompatible types in assignment (expression has type "str", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_cmaes_surrogate.py:92: error: Incompatible types in assignment (expression has type "int", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_cmaes_surrogate.py:93: error: Incompatible types in assignment (expression has type "List[Optional[Any]]", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_cmaes_surrogate.py:94: error: Incompatible types in assignment (expression has type "List[float]", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_direct_surrogate.py:86: error: Incompatible types in assignment (expression has type "List[List[Any]]", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_direct_surrogate.py:88: error: Incompatible types in assignment (expression has type "str", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_direct_surrogate.py:89: error: Incompatible types in assignment (expression has type "str", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_direct_surrogate.py:90: error: Incompatible types in assignment (expression has type "int", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_direct_surrogate.py:91: error: Incompatible types in assignment (expression has type "List[Optional[Any]]", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_direct_surrogate.py:92: error: Incompatible types in assignment (expression has type "List[float]", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_scipy_surrogate.py:82: error: Incompatible types in assignment (expression has type "List[List[Any]]", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_scipy_surrogate.py:84: error: Incompatible types in assignment (expression has type "str", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_scipy_surrogate.py:85: error: Incompatible types in assignment (expression has type "str", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_scipy_surrogate.py:86: error: Incompatible types in assignment (expression has type "int", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_scipy_surrogate.py:87: error: Incompatible types in assignment (expression has type "List[Optional[Any]]", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_scipy_surrogate.py:88: error: Incompatible types in assignment (expression has type "List[float]", target has type "List[int]")  [assignment]
(automl)RoBO/experiments/bayesopt/run_cmaes_synthetic_funcs.py:87: error: Incompatible types in assignment (expression has type "List[Any]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_cmaes_synthetic_funcs.py:88: error: Incompatible types in assignment (expression has type "int", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_cmaes_synthetic_funcs.py:89: error: Incompatible types in assignment (expression has type "List[Optional[Any]]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_cmaes_synthetic_funcs.py:90: error: Incompatible types in assignment (expression has type "List[float]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_cmaes_synthetic_funcs.py:91: error: Incompatible types in assignment (expression has type "List[Any]", target has type "str")  [assignment]
(automl)RoBO/experiments/bayesopt/run_cmaes_synthetic_funcs.py:92: error: Incompatible types in assignment (expression has type "List[Any]", target has type "str")  [assignment]
Found 39 errors in 9 files (checked 83 source files)

[RRepo](damoti)shipmaster
Success: no issues found in 23 source files

[RRepo](wagtail)wagtail
(wagtail)wagtail/wagtail/search/backends/__init__.py: error: Duplicate module named 'backends' (also at '/home/bew/archive/typed_project/(wagtail)wagtail/wagtail/contrib/frontend_cache/backends.py')  [misc]
Found 1 error in 1 file (checked 196 source files)

[RRepo](crate)crate-admin
(crate)crate-admin/setup.py:39: error: Name 'Path' is not defined  [name-defined]
Found 1 error in 1 file (checked 1 source file)

[RRepo](kevinkahn)softconsole
(kevinkahn)softconsole/hubs/isy/isycodes.py:52: error: Need type annotation for 'AlertNodes' (hint: "AlertNodes: Dict[<type>, <type>] = ...")  [var-annotated]
(kevinkahn)softconsole/hubs/ha/domains/ignore.py:8: error: Need type annotation for 'IngoredEntities' (hint: "IngoredEntities: Dict[<type>, <type>] = ...")  [var-annotated]
(kevinkahn)softconsole/stores/weathprov/providerutils.py:7: error: Need type annotation for 'WeathProvs' (hint: "WeathProvs: Dict[<type>, <type>] = ...")  [var-annotated]
(kevinkahn)softconsole/stores/weathprov/providerutils.py:9: error: Need type annotation for 'TermShortener' (hint: "TermShortener: Dict[<type>, <type>] = ...")  [var-annotated]
(kevinkahn)softconsole/deprecated/ft5406.py:267: error: Name 'signal' is not defined  [name-defined]

[RRepo](muddyfish)PYKE
(muddyfish)PYKE/type/type_time.py:177: error: "Type[TypeTime]" has no attribute "default_time"  [attr-defined]

[RRepo](Jokiva)Computational-Physics
(Jokiva)Computational-Physics/lecture 14/Problem_3.py:74: error: No overload variant of "__getitem__" of "list" matches argument type "Tuple[slice, int]"  [call-overload]
(Jokiva)Computational-Physics/lecture 14/Problem_3.py:74: note: Possible overload variants:
(Jokiva)Computational-Physics/lecture 14/Problem_3.py:74: note:     def __getitem__(self, int) -> List[Any]
(Jokiva)Computational-Physics/lecture 14/Problem_3.py:74: note:     def __getitem__(self, slice) -> List[List[Any]]
(Jokiva)Computational-Physics/lecture 14/Problem_3.py:80: error: No overload variant of "__getitem__" of "list" matches argument type "Tuple[slice, int]"  [call-overload]
(Jokiva)Computational-Physics/lecture 14/Problem_3.py:80: note: Possible overload variants:
(Jokiva)Computational-Physics/lecture 14/Problem_3.py:80: note:     def __getitem__(self, int) -> Tuple[Any, Any]
(Jokiva)Computational-Physics/lecture 14/Problem_3.py:80: note:     def __getitem__(self, slice) -> List[Tuple[Any, Any]]
(Jokiva)Computational-Physics/lecture 8/cubic_spline.py:187: error: Too many arguments for "spline_function"  [call-arg]
(Jokiva)Computational-Physics/lecture 12/1c.py:7: error: Name 'f' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 12/1ab.py:6: error: Name 'f' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 11/1a.py:9: error: Name 'f' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 11/1a.py:13: error: Name 'g' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 10/simpson_err.py:8: error: Name 'f' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 10/romberg_err.py:8: error: Name 'f' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 10/trapezoidal_err.py:8: error: Name 'f' already defined (possibly by an import)  [no-redef]
Found 10 errors in 8 files (checked 29 source files)

[RRepo](hail-is)hail
(hail-is)hail/hail/src/test/resources/makeTestInfoScore.py:110: error: Missing parentheses in call to 'print'. Did you mean print(dx)?  [syntax]
Found 1 error in 1 file (checked 136 source files)

[RRepo](the-c0d3r)admin-finder
(the-c0d3r)admin-finder/lib/connection.py:21: error: Bracketed expression "[...]" is not valid as a type  [misc]
(the-c0d3r)admin-finder/lib/connection.py:21: note: Did you mean "List[...]"?
(the-c0d3r)admin-finder/lib/connection.py:62: error: Bracketed expression "[...]" is not valid as a type  [misc]
(the-c0d3r)admin-finder/lib/connection.py:62: note: Did you mean "List[...]"?
(the-c0d3r)admin-finder/lib/connection.py:71: error: Bracketed expression "[...]" is not valid as a type  [misc]
(the-c0d3r)admin-finder/lib/connection.py:71: note: Did you mean "List[...]"?
(the-c0d3r)admin-finder/lib/connection.py:105: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "Dict[Any, Any]")  [assignment]

[RRepo](nismod)smif
(nismod)smif/src/smif/data_layer/results.py:26: error: Attribute '_store' already defined on line 24  [no-redef]
(nismod)smif/tests/data_layer/test_config_store.py:33: error: Incompatible types in assignment (expression has type "int", target has type "str")  [assignment]
(nismod)smif/docs/conf.py:39: error: Argument 1 to "getfile" has incompatible type "Optional[FrameType]"; expected "Union[Module, Type[Any], MethodType, FunctionType, TracebackType, FrameType, CodeType, Callable[..., Any]]"  [arg-type]
(nismod)smif/docs/conf.py:182: error: Name 'version' already defined on line 123  [no-redef]
(nismod)smif/src/smif/cli/log.py:113: error: "Type[Logger]" has no attribute "profiling_start"  [attr-defined]
(nismod)smif/src/smif/cli/log.py:114: error: "Type[Logger]" has no attribute "profiling_stop"  [attr-defined]
(nismod)smif/src/smif/cli/log.py:115: error: "Type[Logger]" has no attribute "summary"  [attr-defined]
(nismod)smif/src/smif/cli/log.py:116: error: "Type[Logger]" has no attribute "_profile"  [attr-defined]
Found 8 errors in 4 files (checked 58 source files)

[RRepo](lkorigin)laniakea
(lkorigin)laniakea/src/laniakea/logging.py:32: error: Module has no attribute "basicConfig"  [attr-defined]
(lkorigin)laniakea/src/laniakea/logging.py:32: error: Module has no attribute "INFO"  [attr-defined]
(lkorigin)laniakea/src/mirk/mirk/config.py:34: error: Need type annotation for 'rooms' (hint: "rooms: List[<type>] = ...")  [var-annotated]
(lkorigin)laniakea/src/laniakea/db/base.py:26: error: Relative import climbs too many namespaces  [misc]
(lkorigin)laniakea/src/laniakea/localconfig.py:68: error: Need type annotation for 'endpoints_jobs' (hint: "endpoints_jobs: List[<type>] = ...")  [var-annotated]
(lkorigin)laniakea/src/laniakea/localconfig.py:69: error: Need type annotation for 'endpoints_submit' (hint: "endpoints_submit: List[<type>] = ...")  [var-annotated]
(lkorigin)laniakea/src/laniakea/localconfig.py:70: error: Need type annotation for 'endpoints_publish' (hint: "endpoints_publish: List[<type>] = ...")  [var-annotated]
(lkorigin)laniakea/src/laniakea/localconfig.py:72: error: Need type annotation for 'servers_jobs' (hint: "servers_jobs: List[<type>] = ...")  [var-annotated]
(lkorigin)laniakea/src/laniakea/localconfig.py:73: error: Need type annotation for 'servers_submit' (hint: "servers_submit: List[<type>] = ...")  [var-annotated]
(lkorigin)laniakea/src/laniakea/localconfig.py:74: error: Need type annotation for 'servers_publish' (hint: "servers_publish: List[<type>] = ...")  [var-annotated]
(lkorigin)laniakea/src/rubicon/rubicon/rubiconfig.py:34: error: Need type annotation for 'trusted_gpg_keyrings' (hint: "trusted_gpg_keyrings: List[<type>] = ...")  [var-annotated]
(lkorigin)laniakea/src/webswview/manage.py:19: error: Module 'lkswview' has no attribute 'create_app'  [attr-defined]
Found 12 errors in 6 files (checked 50 source files)

[RRepo](CenterForOpenScience)modular-file-renderer
(CenterForOpenScience)modular-file-renderer/mfr/extensions/utils.py:5: error: Module 'mfr.extensions' has no attribute 'settings'  [attr-defined]
(CenterForOpenScience)modular-file-renderer/mfr/core/provider.py:7: error: Module 'mfr.server' has no attribute 'settings'  [attr-defined]
(CenterForOpenScience)modular-file-renderer/tests/extensions/image/test_exporter.py:8: error: Module 'mfr.extensions.image' has no attribute 'ImageExporter'  [attr-defined]
(CenterForOpenScience)modular-file-renderer/tests/extensions/image/test_exporter.py:8: error: Module 'mfr.extensions.image' has no attribute 'settings'  [attr-defined]
(CenterForOpenScience)modular-file-renderer/tests/extensions/md/test_renderer.py:5: error: Module 'mfr.extensions.md' has no attribute 'MdRenderer'  [attr-defined]
(CenterForOpenScience)modular-file-renderer/mfr/core/remote_logging.py:7: error: Module 'mfr.server' has no attribute 'settings'  [attr-defined]

[RRepo](ChristianKuehnel)plantgateway
(ChristianKuehnel)plantgateway/plantgw/plantgw.py:26: error: Module 'plantgw' has no attribute '__version__'  [attr-defined]
(ChristianKuehnel)plantgateway/plantgw/plantgw.py:225: error: "None" has no attribute "publish"  [attr-defined]
(ChristianKuehnel)plantgateway/plantgw/plantgw.py:302: error: "None" has no attribute "publish"  [attr-defined]
Found 3 errors in 1 file (checked 2 source files)

[RRepo](mirceamironenco)GANs
Success: no issues found in 3 source files

[RRepo](MobSF)Mobile-Security-Framework-MobSF
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/binary_analysis.py:284: error: Missing return statement  [return]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/binary_analysis.py:304: error: Need type annotation for 'elf_an_dic' (hint: "elf_an_dic: Dict[<type>, <type>] = ...")  [var-annotated]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/binary_analysis.py:327: error: Value of type "Optional[Tuple[str, str, str]]" is not indexable  [index]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/binary_analysis.py:328: error: Value of type "Optional[Tuple[str, str, str]]" is not indexable  [index]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/binary_analysis.py:329: error: Value of type "Optional[Tuple[str, str, str]]" is not indexable  [index]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/comparer.py:42: error: Need type annotation for 'flat_results'  [var-annotated]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/comparer.py:114: error: Unsupported target for indexed assignment  [index]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/comparer.py:120: error: Unsupported target for indexed assignment  [index]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/comparer.py:126: error: Unsupported target for indexed assignment  [index]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/comparer.py:128: error: Unsupported target for indexed assignment  [index]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/comparer.py:160: error: Unsupported target for indexed assignment  [index]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/comparer.py:165: error: Unsupported target for indexed assignment  [index]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/comparer.py:170: error: Unsupported target for indexed assignment  [index]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/comparer.py:174: error: Unsupported target for indexed assignment  [index]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/comparer.py:178: error: Unsupported target for indexed assignment  [index]
(MobSF)Mobile-Security-Framework-MobSF/StaticAnalyzer/views/comparer.py:182: error: Unsupported target for indexed assignment  [index]
(MobSF)Mobile-Security-Framework-MobSF/install/windows/setup.py:21: error: Name 'urlrequest' already defined (by an import)  [no-redef]
Found 17 errors in 3 files (checked 38 source files)

