[RRepo](argaen)aiocache
(argaen)aiocache/aiocache/serializers/serializers.py:10: error: Name 'json' already defined (by an import)  [no-redef]
(argaen)aiocache/aiocache/serializers/serializers.py:99: error: Incompatible types in assignment (expression has type "None", base class "BaseSerializer" defined the type as "str")  [assignment]
(argaen)aiocache/tests/acceptance/test_serializers.py:7: error: Name 'json' already defined (by an import)  [no-redef]
(argaen)aiocache/tests/acceptance/test_serializers.py:11: error: Name 'pickle' already defined (possibly by an import)  [no-redef]
(argaen)aiocache/aiocache/backends/redis.py:53: error: Need type annotation for 'pools' (hint: "pools: Dict[<type>, <type>] = ...")  [var-annotated]
(argaen)aiocache/aiocache/backends/memory.py:12: error: Need type annotation for '_cache' (hint: "_cache: Dict[<type>, <type>] = ...")  [var-annotated]
(argaen)aiocache/aiocache/backends/memory.py:13: error: Need type annotation for '_handlers' (hint: "_handlers: Dict[<type>, <type>] = ...")  [var-annotated]
(argaen)aiocache/aiocache/lock.py:64: error: Need type annotation for '_EVENTS' (hint: "_EVENTS: Dict[<type>, <type>] = ...")  [var-annotated]
Found 8 errors in 5 files (checked 36 source files)

[RRepo](thismachinechills)pyscreencapture
(thismachinechills)pyscreencapture/screenshot/get_window_id.py:26: error: Invalid index type "Iterable[str]" for "Dict[str, Any]"; expected type "str"  [index]
(thismachinechills)pyscreencapture/screenshot/get_window_id.py:43: error: Incompatible types in "yield" (actual type "Tuple[Union[Any, int], Union[Any, int], Union[Any, int]]", expected type "Tuple[int, str, str]")  [misc]
(thismachinechills)pyscreencapture/screenshot/get_window_id.py:53: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(thismachinechills)pyscreencapture/screenshot/get_window_id.py:54: error: Argument 1 to "get_window_info" has incompatible type "str"; expected "int"  [arg-type]
(thismachinechills)pyscreencapture/screenshot/screencapture.py:32: error: Incompatible types in assignment (expression has type "str", variable has type "Optional[List[str]]")  [assignment]
Found 5 errors in 2 files (checked 2 source files)

[RRepo](City-of-Helsinki)linkedevents
(City-of-Helsinki)linkedevents/events/tests/test_signals.py:5: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_auth.py:5: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_models.py:5: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/auth.py:42: error: Unsupported dynamic base class "get_user_model"  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_api.py:11: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_api.py:12: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_api.py:13: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_permissions.py:6: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_permissions.py:7: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_events_search.py:11: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/conftest.py:28: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/renderers/docx.py:8: error: Module 'docx' has no attribute 'Document'  [attr-defined]
(City-of-Helsinki)linkedevents/linkedevents/settings.py:388: error: Need type annotation for 'AUTO_ENABLED_EXTENSIONS' (hint: "AUTO_ENABLED_EXTENSIONS: List[<type>] = ...")  [var-annotated]
Found 13 errors in 10 files (checked 62 source files)

[RRepo](trin5tensa)pigjar
(trin5tensa)pigjar/pigjar/payeesmenu.py:66: error: No overload variant of "fromkeys" of "dict" matches argument types "Tuple[str]", "str"  [call-overload]
(trin5tensa)pigjar/pigjar/payeesmenu.py:66: note: Possible overload variants:
(trin5tensa)pigjar/pigjar/payeesmenu.py:66: note:     def fromkeys() -> Dict[<nothing>, Any]
(trin5tensa)pigjar/pigjar/payeesmenu.py:66: note:     def [_S] fromkeys(value: _S) -> Dict[<nothing>, _S]
(trin5tensa)pigjar/pigjar/payeesmenu.py:77: error: Return value expected  [return-value]
(trin5tensa)pigjar/pigjar/payeesmenu.py:84: error: Return value expected  [return-value]
(trin5tensa)pigjar/pigjar/register.py:17: error: Module '__future__' has no attribute 'annotations'  [attr-defined]
(trin5tensa)pigjar/pigjar/observerpattern.py:94: error: Signature of "notify" incompatible with supertype "Observable"  [override]
(trin5tensa)pigjar/pigjar/pig.py:128: error: Incompatible types in assignment (expression has type "List[EventqItem]", target has type "Dict[Any, Any]")  [assignment]
(trin5tensa)pigjar/pigjar/pig.py:131: error: Incompatible types in assignment (expression has type "List[EventqItem]", target has type "Dict[Any, Any]")  [assignment]
(trin5tensa)pigjar/pigjar/pig.py:173: error: Name 'payee' is not defined  [name-defined]
(trin5tensa)pigjar/pigjar/pig.py:174: error: Name 'account' is not defined  [name-defined]
(trin5tensa)pigjar/pigjar/pig.py:248: error: The return type of a generator function should be "Generator" or one of its supertypes  [misc]
(trin5tensa)pigjar/pigjar/pig.py:269: error: Cannot infer type argument 1 of "heappush"  [misc]
(trin5tensa)pigjar/pigjar/cashflow.py:51: error: Incompatible types in assignment (expression has type "Tuple[None, None]", variable has type "Tuple[Decimal]")  [assignment]
(trin5tensa)pigjar/pigjar/cashflow.py:85: error: Unsupported target for indexed assignment  [index]
(trin5tensa)pigjar/pigjar/cashflow.py:86: error: Incompatible types in assignment (expression has type "Tuple[Any, Any]", variable has type "Tuple[Decimal]")  [assignment]
(trin5tensa)pigjar/pigjar/cashflow.py:110: error: No overload variant of "next" matches argument type "Tuple[Any, Decimal, Decimal]"  [call-overload]
(trin5tensa)pigjar/pigjar/cashflow.py:110: note: Possible overload variant:
(trin5tensa)pigjar/pigjar/cashflow.py:110: note:     def [_T] next(Iterator[_T]) -> _T
(trin5tensa)pigjar/pigjar/cashflow.py:110: note:     <1 more non-matching overload not shown>
(trin5tensa)pigjar/pigjar/cashflow.py:118: error: Unsupported target for indexed assignment  [index]
(trin5tensa)pigjar/pigjar/cashflow.py:119: error: Unsupported target for indexed assignment  [index]
(trin5tensa)pigjar/pigjar/cashflow.py:131: error: Need type annotation for 'spendq' (hint: "spendq: List[<type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/cashflow.py:132: error: Need type annotation for 'svgq' (hint: "svgq: List[<type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/impexp.py:95: error: Need type annotation for 'accounts_memo' (hint: "accounts_memo: Dict[<type>, <type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/impexp.py:96: error: Need type annotation for 'pigs_memo' (hint: "pigs_memo: Dict[<type>, <type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/impexp.py:97: error: Need type annotation for 'payees_memo' (hint: "payees_memo: Set[<type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/impexp.py:98: error: Need type annotation for 'assembler' (hint: "assembler: Dict[<type>, <type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/impexp.py:99: error: Need type annotation for 'clearances' (hint: "clearances: List[<type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/impexp.py:229: error: Incompatible types in assignment (expression has type "Tuple[Any, Any, Any, Decimal]", variable has type "str")  [assignment]
(trin5tensa)pigjar/pigjar/impexp.py:266: error: Incompatible return value type (got "Tuple[Any, Optional[Any], Optional[Any]]", expected "Tuple[bool, bool, bool]")  [return-value]
(trin5tensa)pigjar/pigjar/impexp.py:305: error: Incompatible return value type (got "Tuple[Any, Optional[bool], Any]", expected "Tuple[bool, bool, Any]")  [return-value]
(trin5tensa)pigjar/pigjar/test/test_payeesmenu.py:42: error: No overload variant of "fromkeys" of "dict" matches argument types "Tuple[str]", "str"  [call-overload]
(trin5tensa)pigjar/pigjar/test/test_payeesmenu.py:42: note: Possible overload variants:
(trin5tensa)pigjar/pigjar/test/test_payeesmenu.py:42: note:     def fromkeys() -> Dict[<nothing>, Any]
(trin5tensa)pigjar/pigjar/test/test_payeesmenu.py:42: note:     def [_S] fromkeys(value: _S) -> Dict[<nothing>, _S]
(trin5tensa)pigjar/pigjar/userhandlers.py:16: error: Module '__future__' has no attribute 'annotations'  [attr-defined]
(trin5tensa)pigjar/pigjar/userhandlers.py:34: error: Name 'tk' is not defined  [name-defined]
(trin5tensa)pigjar/pigjar/userhandlers.py:230: error: Name 'guipanes' is not defined  [name-defined]
(trin5tensa)pigjar/pigjar/userhandlers.py:235: error: Name 'guipanes' is not defined  [name-defined]
(trin5tensa)pigjar/pigjar/guimainwindow.py:125: error: Incompatible types in assignment (expression has type "Pattern[str]", variable has type "str")  [assignment]
(trin5tensa)pigjar/pigjar/guimainwindow.py:128: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(trin5tensa)pigjar/pigjar/guimainwindow.py:131: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(trin5tensa)pigjar/pigjar/guimainwindow.py:151: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(trin5tensa)pigjar/pigjar/guimainwindow.py:152: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(trin5tensa)pigjar/pigjar/guimainwindow.py:153: error: Argument 1 to "abs" has incompatible type "str"; expected "SupportsAbs[<nothing>]"  [arg-type]
(trin5tensa)pigjar/pigjar/guimainwindow.py:154: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(trin5tensa)pigjar/pigjar/guimainwindow.py:159: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(trin5tensa)pigjar/pigjar/guimainwindow.py:162: error: Numeric flags are only allowed for numeric types  [str-format]
(trin5tensa)pigjar/pigjar/guimainwindow.py:183: error: Argument 3 to "_place_menu_cascade" of "MainWindow" has incompatible type "Optional[Callable[..., Any]]"; expected "Callable[..., Any]"  [arg-type]
Found 42 errors in 9 files (checked 26 source files)

[RRepo](Berserker66)omnitool
(Berserker66)omnitool/omnitool/render_lib.py:4: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 30 source files)

[RRepo](deepmind)bsuite
(deepmind)bsuite/bsuite/experiments/catch/catch.py:67: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(deepmind)bsuite/bsuite/experiments/catch/catch.py:68: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(deepmind)bsuite/bsuite/experiments/catch/catch.py:69: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(deepmind)bsuite/bsuite/experiments/catch/catch.py:80: error: Unsupported operand types for + ("None" and "int")  [operator]
(deepmind)bsuite/bsuite/experiments/catch/catch.py:83: error: Unsupported operand types for + ("None" and "int")  [operator]
(deepmind)bsuite/bsuite/experiments/catch/catch.py:83: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(deepmind)bsuite/bsuite/baselines/utils/replay.py:48: error: Argument 1 to "zip" has incompatible type "Optional[Sequence[Any]]"; expected "Iterable[Any]"  [arg-type]
(deepmind)bsuite/bsuite/baselines/utils/replay.py:56: error: Item "None" of "Optional[Sequence[Any]]" has no attribute "__iter__" (not iterable)  [union-attr]
(deepmind)bsuite/bsuite/utils/plotting.py:109: error: Incompatible types in assignment (expression has type "Tuple[int, float]", variable has type "Tuple[int, int]")  [assignment]
(deepmind)bsuite/bsuite/utils/plotting.py:187: error: Unsupported left operand type for + ("Sequence[str]")  [operator]
(deepmind)bsuite/bsuite/utils/plotting.py:258: error: "_make_unique_group_col" does not return a value  [func-returns-value]
(deepmind)bsuite/bsuite/utils/gym_wrapper.py:52: error: Missing return statement  [return]
(deepmind)bsuite/bsuite/utils/gym_wrapper.py:63: error: "None" has no attribute "imshow"  [attr-defined]
(deepmind)bsuite/bsuite/utils/gym_wrapper.py:64: error: "None" has no attribute "isopen"  [attr-defined]
(deepmind)bsuite/bsuite/sweep.py:78: error: Incompatible return value type (got "Tuple[Any, ...]", expected "Tuple[str]")  [return-value]
(deepmind)bsuite/bsuite/logging/terminal_logging.py:55: error: Incompatible types in assignment (expression has type "str", variable has type "Mapping[str, Any]")  [assignment]
(deepmind)bsuite/bsuite/logging/terminal_logging.py:63: error: Incompatible types in string interpolation (expression has type "Real", placeholder has type "Union[int, float]")  [str-format]
(deepmind)bsuite/bsuite/bsuite.py:20: error: Module 'bsuite' has no attribute 'sweep'  [attr-defined]
(deepmind)bsuite/bsuite/tests/environments_test.py:23: error: Module 'bsuite' has no attribute 'bsuite'  [attr-defined]
(deepmind)bsuite/bsuite/logging/csv_logging.py:66: error: Need type annotation for '_data' (hint: "_data: List[<type>] = ...")  [var-annotated]
(deepmind)bsuite/bsuite/baselines/dqn_jax/run.py:23: error: Module 'bsuite' has no attribute 'bsuite'  [attr-defined]
(deepmind)bsuite/bsuite/logging/sqlite_logging.py:96: error: Incompatible types in assignment (expression has type "str", variable has type "None")  [assignment]
(deepmind)bsuite/bsuite/logging/sqlite_logging.py:101: error: Argument 1 to "execute" of "Connection" has incompatible type "None"; expected "str"  [arg-type]
(deepmind)bsuite/bsuite/logging/sqlite_logging.py:102: error: "None" has no attribute "__iter__" (not iterable)  [attr-defined]
(deepmind)bsuite/bsuite/logging/sqlite_logging.py:121: error: Incompatible types in assignment (expression has type "List[str]", variable has type "None")  [assignment]
Found 25 errors in 11 files (checked 80 source files)

[RRepo](Twinters007)robotpy-wpilib-utilities
(Twinters007)robotpy-wpilib-utilities/robotpy_ext/common_drivers/xl_max_sonar_ez.py:8: error: No parent module -- cannot perform relative import  [misc]
(Twinters007)robotpy-wpilib-utilities/robotpy_ext/common_drivers/xl_max_sonar_ez.py:9: error: No parent module -- cannot perform relative import  [misc]
Found 2 errors in 1 file (checked 44 source files)

[RRepo](kenkov)smt
Success: no issues found in 12 source files

[RRepo](PayloadSecurity)VxAPI
(PayloadSecurity)VxAPI/api/callers/api_caller.py:27: error: Need type annotation for 'data' (hint: "data: Dict[<type>, <type>] = ...")  [var-annotated]
(PayloadSecurity)VxAPI/api/callers/api_caller.py:28: error: Need type annotation for 'params' (hint: "params: Dict[<type>, <type>] = ...")  [var-annotated]
(PayloadSecurity)VxAPI/api/callers/api_caller.py:29: error: Need type annotation for 'files' (hint: "files: Dict[<type>, <type>] = ...")  [var-annotated]
(PayloadSecurity)VxAPI/api/callers/api_caller.py:40: error: Need type annotation for 'api_response_json' (hint: "api_response_json: Dict[<type>, <type>] = ...")  [var-annotated]
(PayloadSecurity)VxAPI/tests/base_test.py:65: error: Not all arguments converted during string formatting  [str-format]

[RRepo](StoDevX)cs251-toolkit
(StoDevX)cs251-toolkit/cs251tk/student/markdownify/process_file.py:33: error: Not all arguments converted during string formatting  [str-format]
(StoDevX)cs251-toolkit/cs251tk/student/markdownify/markdownify.py:7: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/formatters/base.py:25: error: Need type annotation for 'results'  [var-annotated]
(StoDevX)cs251-toolkit/cs251tk/webapp/web_cli.py:3: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/webapp/web_cli.py:4: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/webapp/web_cli.py:5: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/specs/load.py:8: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/toolkit/__main__.py:10: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/toolkit/__main__.py:11: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/toolkit/__main__.py:12: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/toolkit/__main__.py:19: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/toolkit/__main__.py:20: error: Relative import climbs too many namespaces  [misc]
Found 12 errors in 6 files (checked 62 source files)

[RRepo](jeffmahoney)crash-python
(jeffmahoney)crash-python/contrib/mods.py:27: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 74 source files)

[RRepo](tmerr)bank_wrangler
(tmerr)bank_wrangler/bank_wrangler/bank_wrangler.py:12: error: Module 'bank_wrangler' has no attribute 'aggregate'  [attr-defined]
(tmerr)bank_wrangler/bank_wrangler/bank_wrangler.py:12: error: Module 'bank_wrangler' has no attribute 'deduplicate'  [attr-defined]
(tmerr)bank_wrangler/bank_wrangler/bank_wrangler.py:12: error: Module 'bank_wrangler' has no attribute 'rules'  [attr-defined]
(tmerr)bank_wrangler/bank_wrangler/bank_wrangler.py:12: error: Module 'bank_wrangler' has no attribute 'report'  [attr-defined]
(tmerr)bank_wrangler/bank_wrangler/report/__init__.py:81: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[str], AnyStr]"  [arg-type]
(tmerr)bank_wrangler/bank_wrangler/report/__init__.py:82: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[str], AnyStr]"  [arg-type]
(tmerr)bank_wrangler/bank_wrangler/report/__init__.py:82: error: List item 0 has incompatible type "str"; expected "AnyStr"  [list-item]
(tmerr)bank_wrangler/bank_wrangler/rules.py:5: error: Module 'bank_wrangler' has no attribute 'tresult'  [attr-defined]
Found 8 errors in 3 files (checked 21 source files)

[RRepo](telminov)django-voximplant
(telminov)django-voximplant/voximplant/admin.py:3: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 11 source files)

[RRepo](X-DataInitiative)tick
(X-DataInitiative)tick/tick/hawkes/simulation/hawkes_kernels/hawkes_kernel_sum_exp.py:7: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 215 source files)

[RRepo](Microsoft)PTVS
(Microsoft)PTVS/Python/Tests/TestData/Copy of SteppingTest4.py:3: error: Missing parentheses in call to 'print'. Did you mean print(i)?  [syntax]
Found 1 error in 1 file (checked 544 source files)

[RRepo](mabuchilab)QNET
(mabuchilab)QNET/src/qnet/printing/_precedence.py:3: error: Need type annotation for '__all__' (hint: "__all__: List[<type>] = ...")  [var-annotated]
(mabuchilab)QNET/src/qnet/utils/permutations.py:1: error: Need type annotation for '__all__' (hint: "__all__: List[<type>] = ...")  [var-annotated]

[RRepo](NB0174)AbricotGame
(NB0174)AbricotGame/serveur/pathfinding.py:123: error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "int")  [assignment]
(NB0174)AbricotGame/serveur/pathfinding.py:205: error: Need type annotation for 'open_list' (hint: "open_list: List[<type>] = ...")  [var-annotated]
(NB0174)AbricotGame/serveur/pathfinding.py:207: error: Need type annotation for 'closed_list' (hint: "closed_list: Set[<type>] = ...")  [var-annotated]
(NB0174)AbricotGame/serveur/pathfinding.py:208: error: Need type annotation for 'all_cells' (hint: "all_cells: List[<type>] = ...")  [var-annotated]
(NB0174)AbricotGame/serveur/pathfinding.py:318: error: Incompatible return value type (got "Optional[Tuple[int, int]]", expected "Tuple[int, int]")  [return-value]
(NB0174)AbricotGame/serveur/commandes.py:7: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:7: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:7: error: Name 'List' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:7: note: Did you forget to import it from "typing"? (Suggestion: "from typing import List")
(NB0174)AbricotGame/serveur/commandes.py:13: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:15: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:17: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:19: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:22: error: Name 'MAPS' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:26: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:26: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:26: error: Name 'Tuple' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:26: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Tuple")
(NB0174)AbricotGame/serveur/commandes.py:28: error: Name 'Joueur' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:30: error: Name 'MAPS' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:38: error: Missing return statement  [return]
(NB0174)AbricotGame/serveur/commandes.py:38: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:38: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:43: error: Name 'MAPS' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:48: error: Incompatible types in assignment (expression has type "List[<nothing>]", variable has type "Dict[str, Any]")  [assignment]
(NB0174)AbricotGame/serveur/commandes.py:49: error: Name 'MAPS' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:50: error: "Dict[str, Any]" has no attribute "append"  [attr-defined]
(NB0174)AbricotGame/serveur/commandes.py:54: error: Name 'List' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:54: note: Did you forget to import it from "typing"? (Suggestion: "from typing import List")
(NB0174)AbricotGame/serveur/commandes.py:54: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:54: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:54: error: Name 'Tuple' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:54: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Tuple")
(NB0174)AbricotGame/serveur/commandes.py:66: error: Name 'MAPS' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:72: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:72: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:89: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:89: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:95: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:97: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:99: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:101: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:107: error: Name 'Tuple' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:107: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Tuple")
(NB0174)AbricotGame/serveur/commandes.py:107: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:107: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:112: error: Name 'SPELLS' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:112: error: "str" has no attribute "classe"  [attr-defined]
(NB0174)AbricotGame/serveur/commandes.py:113: error: "str" has no attribute "verif_conditions"  [attr-defined]
(NB0174)AbricotGame/serveur/commandes.py:114: error: "str" has no attribute "liste_case"  [attr-defined]
(NB0174)AbricotGame/serveur/commandes.py:115: error: "str" has no attribute "combat"  [attr-defined]
(NB0174)AbricotGame/serveur/commandes.py:117: error: "str" has no attribute "appliquer_effet"  [attr-defined]
(NB0174)AbricotGame/serveur/commandes.py:122: error: Name 'List' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:122: note: Did you forget to import it from "typing"? (Suggestion: "from typing import List")
(NB0174)AbricotGame/serveur/commandes.py:122: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:122: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/main.py:37: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/main.py:37: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/main.py:37: error: Name 'List' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/main.py:37: note: Did you forget to import it from "typing"? (Suggestion: "from typing import List")
(NB0174)AbricotGame/serveur/main.py:37: error: Name 'Tuple' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/main.py:37: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Tuple")
(NB0174)AbricotGame/serveur/main.py:50: error: Name 'MAPS' is not defined  [name-defined]
(NB0174)AbricotGame/launcher/client_part/updat.py:123: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
Found 47 errors in 4 files (checked 6 source files)

[RRepo](henridwyer)pyhomekit
(henridwyer)pyhomekit/pyhomekit/utils.py:9: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 4 source files)

[RRepo](turbinenreiter)micropython
(turbinenreiter)micropython/tests/micropython/viper_args.py:3: error: Name 'micropython' is not defined  [name-defined]
(turbinenreiter)micropython/tests/micropython/viper_args.py:8: error: Name 'micropython' is not defined  [name-defined]
(turbinenreiter)micropython/tests/micropython/viper_args.py:13: error: Name 'micropython' is not defined  [name-defined]
(turbinenreiter)micropython/tests/micropython/viper_args.py:18: error: Name 'micropython' is not defined  [name-defined]
(turbinenreiter)micropython/tests/micropython/viper_args.py:23: error: Name 'micropython' is not defined  [name-defined]
(turbinenreiter)micropython/tests/cmdline/cmd_showbc.py:121: error: Name 'f' already defined on line 4  [no-redef]
(turbinenreiter)micropython/tests/cmdline/cmd_showbc.py:128: error: Name 'f' already defined on line 4  [no-redef]
(turbinenreiter)micropython/tests/basics/fun_calldblstar3.py:16: error: Argument after ** must be a mapping, not "Mapping"  [misc]
(turbinenreiter)micropython/tests/basics/boundmeth1.py:19: error: Incompatible types in assignment (expression has type "Callable[[Any], Any]", variable has type "Callable[[], Any]")  [assignment]
(turbinenreiter)micropython/tests/basics/boundmeth1.py:20: error: Too many arguments  [call-arg]
(turbinenreiter)micropython/tests/basics/boundmeth1.py:23: error: Incompatible types in assignment (expression has type "Callable[[Any, Any, Any, Any, Any, Any], Any]", variable has type "Callable[[], Any]")  [assignment]
(turbinenreiter)micropython/tests/basics/boundmeth1.py:24: error: Too many arguments  [call-arg]
(turbinenreiter)micropython/tests/basics/builtin_reversed.py:32: error: No overload variant of "reversed" matches argument type "A"  [call-overload]
(turbinenreiter)micropython/tests/basics/builtin_reversed.py:32: note: Possible overload variants:
(turbinenreiter)micropython/tests/basics/builtin_reversed.py:32: note:     def [_T] reversed(Sequence[_T]) -> Iterator[_T]
(turbinenreiter)micropython/tests/basics/builtin_reversed.py:32: note:     def [_T] reversed(Reversible[_T]) -> Iterator[_T]
(turbinenreiter)micropython/tests/basics/iter1.py:7: error: "NotIterable" has no attribute "__iter__" (not iterable)  [attr-defined]
(turbinenreiter)micropython/tests/basics/int1.py:87: error: No overload variant of "int" matches argument type "List[<nothing>]"  [call-overload]
(turbinenreiter)micropython/tests/basics/int1.py:87: note: Possible overload variant:
(turbinenreiter)micropython/tests/basics/int1.py:87: note:     def int(self, x: Union[str, bytes, SupportsInt, _SupportsIndex] = ...) -> int
(turbinenreiter)micropython/tests/basics/int1.py:87: note:     <1 more non-matching overload not shown>
(turbinenreiter)micropython/tests/basics/try2.py:7: error: Name 'foo' is not defined  [name-defined]
(turbinenreiter)micropython/tests/basics/try2.py:10: error: Name 'bar' is not defined  [name-defined]
(turbinenreiter)micropython/tests/basics/try2.py:18: error: Name 'foo' is not defined  [name-defined]
(turbinenreiter)micropython/tests/basics/try2.py:21: error: Name 'bar' is not defined  [name-defined]
(turbinenreiter)micropython/tests/basics/class_store_class.py:8: error: Name 'namedtuple' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/basics/class_store_class.py:27: error: "Type[DefragResult]" has no attribute "_encoded_counterpart"  [attr-defined]
(turbinenreiter)micropython/tests/basics/class_store_class.py:28: error: "Type[DefragResultBytes]" has no attribute "_decoded_counterpart"  [attr-defined]
(turbinenreiter)micropython/tests/basics/del_global.py:25: error: Trying to read deleted variable 'a'  [misc]
(turbinenreiter)micropython/tests/basics/del_global.py:33: error: Trying to read deleted variable 'a'  [misc]
(turbinenreiter)micropython/tests/basics/del_global.py:37: error: Trying to read deleted variable 'b'  [misc]
(turbinenreiter)micropython/tests/basics/del_global.py:46: error: Trying to read deleted variable 'a'  [misc]
(turbinenreiter)micropython/tests/basics/del_global.py:50: error: Trying to read deleted variable 'b'  [misc]
(turbinenreiter)micropython/tests/basics/del_global.py:54: error: Trying to read deleted variable 'c'  [misc]
(turbinenreiter)micropython/tests/basics/class_super_object.py:15: error: Incompatible types in assignment (expression has type "Test2", variable has type "Test")  [assignment]
(turbinenreiter)micropython/tests/basics/builtin_property.py:5: error: Argument 1 to "property" has incompatible type "int"; expected "Optional[Callable[[Any], Any]]"  [arg-type]
(turbinenreiter)micropython/tests/basics/builtin_property.py:5: error: Argument 2 to "property" has incompatible type "int"; expected "Optional[Callable[[Any, Any], None]]"  [arg-type]
(turbinenreiter)micropython/tests/basics/builtin_property.py:5: error: Argument 3 to "property" has incompatible type "int"; expected "Optional[Callable[[Any], None]]"  [arg-type]
(turbinenreiter)micropython/tests/basics/builtin_property.py:9: error: Argument 1 to "getter" of "property" has incompatible type "int"; expected "Callable[[Any], Any]"  [arg-type]
(turbinenreiter)micropython/tests/basics/builtin_property.py:10: error: Argument 1 to "setter" of "property" has incompatible type "int"; expected "Callable[[Any, Any], None]"  [arg-type]
(turbinenreiter)micropython/tests/basics/builtin_property.py:11: error: Argument 1 to "deleter" of "property" has incompatible type "int"; expected "Callable[[Any], None]"  [arg-type]
(turbinenreiter)micropython/tests/basics/builtin_property.py:27: error: Property "x" defined in "A" is read-only  [misc]
(turbinenreiter)micropython/tests/basics/object_new.py:24: error: Argument 1 to "__new__" of "object" has incompatible type "int"; expected "Type[object]"  [arg-type]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:7: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:8: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:9: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:10: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:11: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:12: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:13: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:14: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:16: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:17: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:18: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:21: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:22: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:24: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:27: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:28: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:29: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:30: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:31: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:32: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:33: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:36: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:37: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:38: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:41: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:44: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:45: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:46: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:47: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:48: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:49: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/esp8266/modules/onewire.py:10: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/esp8266/modules/onewire.py:11: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/esp8266/modules/onewire.py:12: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/esp8266/modules/ds18x20.py:4: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/esp8266/modules/ds18x20.py:5: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/esp8266/modules/ds18x20.py:6: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:20: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:21: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:22: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:24: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:25: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:26: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:28: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:29: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:31: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:33: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:34: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:35: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:37: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:38: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/tests/misc/print_exception.py:4: error: Name 'io' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/misc/print_exception.py:7: error: Module has no attribute "print_exception"  [attr-defined]
(turbinenreiter)micropython/tests/micropython/viper_misc.py:12: error: Unsupported left operand type for + ("object")  [operator]
(turbinenreiter)micropython/tests/micropython/viper_misc.py:18: error: Incompatible return value type (got "None", expected "int")  [return-value]
(turbinenreiter)micropython/tests/micropython/viper_misc.py:55: error: Name 'uint' is not defined  [name-defined]
(turbinenreiter)micropython/tests/micropython/viper_misc.py:56: error: Name 'uint' is not defined  [name-defined]
(turbinenreiter)micropython/tests/micropython/viper_misc.py:75: error: Name 'gl' is not defined  [name-defined]
(turbinenreiter)micropython/tests/extmod/uheapq1.py:4: error: Name 'heapq' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/uheapq1.py:22: error: Need type annotation for 'h' (hint: "h: List[<type>] = ...")  [var-annotated]
(turbinenreiter)micropython/cc3200/tools/smoke.py:50: error: Argument 1 to "write" of "IO" has incompatible type "bytes"; expected "str"  [arg-type]
(turbinenreiter)micropython/cc3200/tools/smoke.py:54: error: "TextIO" has no attribute "readall"  [attr-defined]
(turbinenreiter)micropython/cc3200/tools/smoke.py:72: error: Module has no attribute "sleep_ms"; maybe "sleep"?  [attr-defined]
(turbinenreiter)micropython/drivers/sdcard/sdcard.py:27: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/sdcard/sdcard.py:29: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/sdcard/sdcard.py:31: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/sdcard/sdcard.py:36: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/sdcard/sdcard.py:37: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/sdcard/sdcard.py:38: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:8: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:9: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:10: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:11: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:12: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:13: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:14: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:16: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:17: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:18: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:19: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:20: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:21: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:22: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:24: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/tests/float/float2int.py:6: error: Name 'struct' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/float/float2int_doubleprec.py:6: error: Name 'struct' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/float/float2int_fp30.py:6: error: Name 'struct' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/thread/thread_start2.py:8: error: Name 'time' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/thread/thread_lock4.py:30: error: Need type annotation for 'output' (hint: "output: List[<type>] = ...")  [var-annotated]
(turbinenreiter)micropython/tests/thread/stress_aes.py:207: error: Name 'time' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ure_namedclass.py:6: error: Name 're' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ure_group.py:6: error: Name 're' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ujson_loads.py:4: error: Name 'json' already defined (by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ure_error.py:6: error: Name 're' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ujson_loads_float.py:4: error: Name 'json' already defined (by an import)  [no-redef]
(turbinenreiter)micropython/examples/network/http_client.py:4: error: Name 'socket' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/examples/network/http_server_simplistic.py:4: error: Name 'socket' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/py/makeqstrdefs.py:20: error: Incompatible types in assignment (expression has type "Type[bytes]", variable has type "Callable[[Any, Any], bytearray]")  [assignment]
(turbinenreiter)micropython/tools/pyboard.py:47: error: Incompatible types in assignment (expression has type "TextIO", variable has type "BinaryIO")  [assignment]
(turbinenreiter)micropython/docs/sphinx_selective_exclude/modindex_exclude.py:23: error: Need type annotation for 'EXCLUDES' (hint: "EXCLUDES: Dict[<type>, <type>] = ...")  [var-annotated]
Found 142 errors in 39 files (checked 95 source files)

[RRepo](bagage)cadastre-conflation
Success: no issues found in 8 source files

[RRepo](languitar)autosuspend
(languitar)autosuspend/src/autosuspend/checks/wakeup.py:6: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 12 source files)

[RRepo](a-slide)pycoQC
(a-slide)pycoQC/pycoQC/pycoQC_parse.py:58: error: Name 'get_logger' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:16: error: Module 'pycoQC' has no attribute '__version__'  [attr-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:90: error: Name 'get_logger' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:94: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:95: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:96: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:97: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:98: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:99: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:100: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:101: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:102: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:103: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:104: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:107: error: Name 'dict_to_str' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:109: error: Name 'dict_to_str' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/common.py:92: error: Invalid conversion specifier in format string: unexpected }  [str-format]
(a-slide)pycoQC/pycoQC/common.py:215: error: Invalid type comment or annotation  [valid-type]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:77: error: Invalid type comment or annotation  [valid-type]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:79: error: Invalid type comment or annotation  [valid-type]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:112: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:114: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:116: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:119: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:132: error: Need type annotation for 'in_q'  [var-annotated]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:133: error: Need type annotation for 'out_q'  [var-annotated]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:134: error: Need type annotation for 'error_q'  [var-annotated]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:135: error: Need type annotation for 'counter_q'  [var-annotated]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:151: error: Need type annotation for 'tb'  [var-annotated]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:152: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:158: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/__main__.py:21: error: Module 'pycoQC' has no attribute '__version__'  [attr-defined]
(a-slide)pycoQC/pycoQC/pycoQC_report.py:17: error: Module 'pycoQC' has no attribute '__version__'  [attr-defined]
(a-slide)pycoQC/pycoQC/pycoQC_report.py:52: error: Name 'get_logger' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC_report.py:57: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC_report.py:107: error: Name 'pycoQCError' is not defined  [name-defined]
Found 36 errors in 6 files (checked 6 source files)

[RRepo](consbio)seedsource
(consbio)seedsource/source/socket_logging/management/commands/run_logging_server.py:46: error: Incompatible types in assignment (expression has type "int", base class "BaseServer" defined the type as "bool")  [assignment]
Found 1 error in 1 file (checked 20 source files)

[RRepo](benchmeeting)booking
Success: no issues found in 3 source files

[RRepo](Nocturnal42)runmyrobot
(Nocturnal42)runmyrobot/hardware/pololu.py:5: error: unindent does not match any outer indentation level  [syntax]
Found 1 error in 1 file (checked 33 source files)

[RRepo](boriel)zxbasic
(boriel)zxbasic/arch/zx48k/translatorvisitor.py:17: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 116 source files)

[RRepo](sloria)aiohttp_utils
(sloria)aiohttp_utils/aiohttp_utils/runner.py:78: error: Item "None" of "Optional[Application]" has no attribute "debug"  [union-attr]
(sloria)aiohttp_utils/aiohttp_utils/negotiation.py:240: error: Function "builtins.callable" is not valid as a type  [valid-type]
(sloria)aiohttp_utils/aiohttp_utils/negotiation.py:240: note: Perhaps you need "Callable[...]" or a callback protocol?
(sloria)aiohttp_utils/aiohttp_utils/negotiation.py:241: error: Incompatible default for argument "renderers" (default has type "object", argument has type "OrderedDict[Any, Any]")  [assignment]
(sloria)aiohttp_utils/aiohttp_utils/negotiation.py:242: error: Incompatible default for argument "force_negotiation" (default has type "object", argument has type "bool")  [assignment]
(sloria)aiohttp_utils/aiohttp_utils/negotiation.py:243: error: Incompatible default for argument "force_rendering" (default has type "object", argument has type "bool")  [assignment]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:74: error: Incompatible types in assignment (expression has type "List[str]", variable has type "Tuple[Any, ...]")  [assignment]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:131: error: Argument 1 to "import_module" has incompatible type "Union[str, bytes]"; expected "str"  [arg-type]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:239: error: Argument 1 to "import_module" has incompatible type "Union[str, bytes]"; expected "str"  [arg-type]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:256: error: Argument 2 to "getattr" has incompatible type "Union[str, bytes]"; expected "str"  [arg-type]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:267: error: "UrlDispatcher" has no attribute "add_resource_object"; maybe "add_resource"?  [attr-defined]

[RRepo](tildetown)tilde-wiki
(tildetown)tilde-wiki/tildewiki/main.py:13: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 4 source files)

[RRepo](albertz)PyOverheadGame
(albertz)PyOverheadGame/game/app.py:4: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 2 source files)

[RRepo](OpenSourcePolicyCenter)webapp-public
(OpenSourcePolicyCenter)webapp-public/webapp/apps/taxbrain/behaviors.py:9: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 33 source files)

[RRepo](mikonapoli)grakn-python
(mikonapoli)grakn-python/features/steps/steps.py:9: error: Name 'use_step_matcher' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:12: error: Name 'given' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:17: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:17: error: Name 'given' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:22: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:22: error: Name 'given' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:27: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:27: error: Name 'given' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:32: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:32: error: Name 'given' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:37: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:37: error: Name 'when' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:42: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:42: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:48: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:48: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:53: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:53: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:61: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:61: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:67: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:67: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:72: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:72: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:77: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:77: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/tests/test_grakn.py:28: error: Incompatible types in assignment (expression has type "None", variable has type "Dict[Any, Any]")  [assignment]
(mikonapoli)grakn-python/tests/test_grakn.py:29: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(mikonapoli)grakn-python/tests/test_grakn.py:30: error: Incompatible types in assignment (expression has type "None", variable has type "Dict[Any, Any]")  [assignment]
(mikonapoli)grakn-python/tests/test_grakn.py:34: error: Incompatible types in assignment (expression has type "CaseInsensitiveDict[str]", variable has type "Dict[Any, Any]")  [assignment]
(mikonapoli)grakn-python/tests/test_grakn.py:35: error: Incompatible types in assignment (expression has type "Union[bytes, str, None]", variable has type "str")  [assignment]
Found 31 errors in 2 files (checked 4 source files)

[RRepo](gopythongo)aptly-api-client
Success: no issues found in 8 source files

[RRepo](marketcoin)marketcoin
(marketcoin)marketcoin/mockrpc.py:7: error: Need type annotation for 'balance'  [var-annotated]
(marketcoin)marketcoin/mockrpc.py:10: error: Need type annotation for 'transactions'  [var-annotated]
Found 2 errors in 1 file (checked 7 source files)

[RRepo](jsandovalc)poster
(jsandovalc)poster/poster/migrations/env.py:25: error: Module has no attribute "metadata"  [attr-defined]
(jsandovalc)poster/poster/app.py:26: error: The return type of an async generator function should be "AsyncGenerator" or one of its supertypes  [misc]
(jsandovalc)poster/poster/app.py:50: error: List item 0 has incompatible type "Callable[[Application], None]"; expected "Callable[[Application], AsyncIterator[None]]"  [list-item]

[RRepo](der-michik)c3bottles
(der-michik)c3bottles/c3bottles/model/user.py:16: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/user.py:24: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:25: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:27: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:28: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:29: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:30: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:31: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:32: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:33: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:137: error: Cannot determine type of 'lm'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:172: error: Cannot determine type of 'lm'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:186: error: Cannot determine type of 'app'  [has-type]
(der-michik)c3bottles/c3bottles/views/__init__.py:11: error: Cannot determine type of 'app'  [has-type]
(der-michik)c3bottles/c3bottles/views/__init__.py:58: error: Cannot determine type of 'app'  [has-type]
(der-michik)c3bottles/c3bottles/views/__init__.py:73: error: Cannot determine type of 'app'  [has-type]
(der-michik)c3bottles/c3bottles/views/__init__.py:82: error: Cannot determine type of 'app'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:9: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/location.py:29: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:31: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:32: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:33: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:37: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:39: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:40: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:41: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:42: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:43: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:9: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/visit.py:28: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:30: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:31: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:32: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:36: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:38: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:40: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:41: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:9: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/report.py:32: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:34: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:35: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:36: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:40: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:42: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:44: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:45: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:14: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/drop_point.py:31: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:32: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:33: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:34: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:35: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:36: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:37: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/translations/translate-js.py:6: error: Module has no attribute "sys"  [attr-defined]
(der-michik)c3bottles/c3bottles/model/user.py:16: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/user.py:24: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:25: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:27: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:28: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:29: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:30: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:31: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:32: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:33: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:137: error: Cannot determine type of 'lm'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:172: error: Cannot determine type of 'lm'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:186: error: Cannot determine type of 'app'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:9: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/visit.py:28: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:30: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:31: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:32: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:36: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:38: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:40: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:41: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:9: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/location.py:29: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:31: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:32: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:33: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:37: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:39: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:40: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:41: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:42: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:43: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:14: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/drop_point.py:31: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:32: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:33: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:34: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:35: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:36: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:37: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:9: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/report.py:32: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:34: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:35: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:36: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:40: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:42: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:44: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:45: error: Cannot determine type of 'db'  [has-type]
Found 105 errors in 7 files (checked 28 source files)

[RRepo](OpenSlides)OpenSlides
(OpenSlides)OpenSlides/openslides/users/apps.py:12: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 82 source files)

[RRepo](robotpy)pyfrc
(robotpy)pyfrc/lib/pyfrc/configloader.py:53: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 37 source files)

[RRepo](UTNkar)moore
(UTNkar)moore/src/involvement/forms/approval_form.py:17: error: Need type annotation for 'fields' (hint: "fields: List[<type>] = ...")  [var-annotated]
(UTNkar)moore/src/involvement/models/recruitment_page.py:85: error: Need type annotation for 'subpage_types' (hint: "subpage_types: List[<type>] = ...")  [var-annotated]
(UTNkar)moore/src/involvement/rules.py:7: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:12: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:18: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:23: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:29: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:34: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:39: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:44: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:49: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:55: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:60: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:67: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:73: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:73: error: Module has no attribute "always_allow"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:75: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:76: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:77: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:79: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:82: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:83: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:84: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:86: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:89: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:90: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:91: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:93: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:95: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:98: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:101: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:105: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:106: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:107: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:109: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:111: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:114: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:115: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:116: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:118: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:120: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/news/models.py:109: error: Need type annotation for 'subpage_types' (hint: "subpage_types: List[<type>] = ...")  [var-annotated]
(UTNkar)moore/src/involvement/rule_utils.py:4: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:11: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:17: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:23: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:29: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:35: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:41: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:47: error: Module has no attribute "predicate"  [attr-defined]
Found 50 errors in 5 files (checked 48 source files)

[RRepo](groutr)conda-tools
(groutr)conda-tools/src/conda_tools/cache/__init__.py:4: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 12 source files)

[RRepo](OParl)liboparl
Success: no issues found in 1 source file

[RRepo](fkie-cad)FACT_core
(fkie-cad)FACT_core/src/helperFunctions/database_structure.py:4: error: Need type annotation for 'LEAF_CONSTRAINT'  [var-annotated]
(fkie-cad)FACT_core/src/plugins/analysis/linter/test/test_lua_linter.py:3: error: Relative import climbs too many namespaces  [misc]
(fkie-cad)FACT_core/src/plugins/analysis/linter/test/test_js_linter.py:3: error: Relative import climbs too many namespaces  [misc]
(fkie-cad)FACT_core/src/plugins/analysis/linter/test/test_python_linter.py:3: error: Relative import climbs too many namespaces  [misc]
(fkie-cad)FACT_core/src/plugins/analysis/linter/test/test_shell_linter.py:3: error: Relative import climbs too many namespaces  [misc]
(fkie-cad)FACT_core/src/plugins/analysis/known_vulnerabilities/test/test_rulebook.py:3: error: Relative import climbs too many namespaces  [misc]

[RRepo](sorgloomer)websocket_terminal
Success: no issues found in 12 source files

[RRepo](jrabbit)pyborg-1up
(jrabbit)pyborg-1up/misc/pyborg-telnet.py:42: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 32 source files)

[RRepo](python-hyper)hyper-h2
(python-hyper)hyper-h2/test/test_utility_functions.py:19: error: Name 'xrange' is not defined  [name-defined]
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:41: error: Argument 1 of "connection_made" is incompatible with supertype "BaseProtocol"; supertype defines the argument type as "BaseTransport"  [override]
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:79: error: Incompatible types in assignment (expression has type "OrderedDict[str, str]", variable has type "List[Tuple[str, str]]")  [assignment]
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:80: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:80: note: Possible overload variants:
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:80: note:     def __getitem__(self, int) -> Tuple[str, str]
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:80: note:     def __getitem__(self, slice) -> List[Tuple[str, str]]
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:201: error: Value of type "Optional[List[socket]]" is not indexable  [index]
Found 5 errors in 2 files (checked 13 source files)

[RRepo](awslabs)sockeye
(awslabs)sockeye/sockeye/lexicon.py:26: error: No parent module -- cannot perform relative import  [misc]
(awslabs)sockeye/sockeye/lexicon.py:27: error: No parent module -- cannot perform relative import  [misc]
(awslabs)sockeye/sockeye/lexicon.py:28: error: No parent module -- cannot perform relative import  [misc]
Found 3 errors in 1 file (checked 52 source files)

[RRepo](TheAlgorithms)Python
(TheAlgorithms)Python/strings/levenshtein_distance.py:69: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/ciphers/atbash.py:2: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/ciphers/atbash.py:3: error: Cannot determine type of 'unichr'  [has-type]
(TheAlgorithms)Python/backtracking/all_subsequences.py:41: error: List item 0 has incompatible type "str"; expected "int"  [list-item]
(TheAlgorithms)Python/backtracking/all_subsequences.py:41: error: List item 1 has incompatible type "str"; expected "int"  [list-item]
(TheAlgorithms)Python/backtracking/all_subsequences.py:41: error: List item 2 has incompatible type "str"; expected "int"  [list-item]
(TheAlgorithms)Python/backtracking/sudoku.py:145: error: Argument 1 to "map" has incompatible type "Type[List[Any]]"; expected "Callable[[List[int]], List[_T]]"  [arg-type]
(TheAlgorithms)Python/backtracking/all_permutations.py:44: error: List item 0 has incompatible type "str"; expected "int"  [list-item]
(TheAlgorithms)Python/backtracking/all_permutations.py:44: error: List item 1 has incompatible type "str"; expected "int"  [list-item]
(TheAlgorithms)Python/backtracking/all_permutations.py:44: error: List item 2 has incompatible type "str"; expected "int"  [list-item]
(TheAlgorithms)Python/backtracking/all_combinations.py:10: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/backtracking/all_combinations.py:10: note: Did you mean "List[...]"?
(TheAlgorithms)Python/backtracking/all_combinations.py:16: error: Need type annotation for 'result' (hint: "result: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/dynamic_programming/rod_cutting.py:48: error: Incompatible return value type (got "float", expected "int")  [return-value]
(TheAlgorithms)Python/graphs/minimum_spanning_tree_prims.py:107: error: Need type annotation for 'adjlist'  [var-annotated]
(TheAlgorithms)Python/data_structures/trie/trie.py:15: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/data_structures/trie/trie.py:15: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:10: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:10: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:27: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:27: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:39: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:39: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:51: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:51: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:63: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:63: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:68: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:68: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:73: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:73: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:78: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:78: note: Did you mean "List[...]"?
(TheAlgorithms)Python/sorts/comb_sort.py:52: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/searches/sentinel_linear_search.py:49: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/other/anagrams.py:13: error: Need type annotation for 'word_bysig'  [var-annotated]
(TheAlgorithms)Python/dynamic_programming/integer_partition.py:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/dynamic_programming/edit_distance.py:86: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/hashes/enigma_machine.py:47: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")  [assignment]
(TheAlgorithms)Python/hashes/enigma_machine.py:56: error: Incompatible types in assignment (expression has type "str", variable has type "int")  [assignment]
(TheAlgorithms)Python/graphs/scc_kosaraju.py:37: error: Need type annotation for 'g'  [var-annotated]
(TheAlgorithms)Python/graphs/scc_kosaraju.py:38: error: Need type annotation for 'r'  [var-annotated]
(TheAlgorithms)Python/graphs/scc_kosaraju.py:45: error: Need type annotation for 'stack' (hint: "stack: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/graphs/scc_kosaraju.py:47: error: Need type annotation for 'scc' (hint: "scc: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/graphs/scc_kosaraju.py:48: error: Need type annotation for 'component' (hint: "component: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/graphs/even_tree.py:51: error: Need type annotation for 'tree'  [var-annotated]
(TheAlgorithms)Python/graphs/even_tree.py:52: error: Need type annotation for 'visited' (hint: "visited: Dict[<type>, <type>] = ...")  [var-annotated]
(TheAlgorithms)Python/graphs/even_tree.py:53: error: Need type annotation for 'cuts' (hint: "cuts: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/graphs/basic_graphs.py:4: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/graphs/basic_graphs.py:19: error: Need type annotation for 'g' (hint: "g: Dict[<type>, <type>] = ...")  [var-annotated]
(TheAlgorithms)Python/graphs/bellman_ford.py:41: error: Need type annotation for 'graph'  [var-annotated]
(TheAlgorithms)Python/graphs/multi_hueristic_astar.py:188: error: Need type annotation for 'blocks_no' (hint: "blocks_no: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/data_structures/heap/heap.py:6: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/project_euler/problem_01/sol6.py:10: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/project_euler/problem_01/sol5.py:10: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/project_euler/problem_02/sol3.py:15: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/gnome_sort.py:25: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/quick_sort.py:51: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/cocktail_shaker_sort.py:25: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/counting_sort.py:69: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/cycle_sort.py:49: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/pigeon_sort.py:42: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/insertion_sort.py:44: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/bubble_sort.py:37: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/shell_sort.py:48: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/merge_sort.py:50: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/quick_sort_3_partition.py:24: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/heap_sort.py:58: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/merge_sort_fastest.py:40: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/selection_sort.py:47: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/searches/ternary_search.py:14: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/searches/binary_search.py:16: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/searches/linear_search.py:15: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/searches/interpolation_search.py:7: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/neural_network/perceptron.py:122: error: Need type annotation for 'sample' (hint: "sample: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/hashes/chaos_machine.py:5: error: Name 'raw_input' is not defined  [name-defined]
(TheAlgorithms)Python/hashes/chaos_machine.py:13: error: Need type annotation for 'buffer_space' (hint: "buffer_space: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/hashes/chaos_machine.py:13: error: Need type annotation for 'params_space' (hint: "params_space: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:33: error: Incompatible types in assignment (expression has type "Node", variable has type "None")  [assignment]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:33: error: Argument 1 to "split" has incompatible type "None"; expected "Node"  [arg-type]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:39: error: Incompatible types in assignment (expression has type "Node", variable has type "None")  [assignment]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:39: error: Argument 1 to "split" has incompatible type "None"; expected "Node"  [arg-type]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:58: error: Incompatible types in assignment (expression has type "Node", variable has type "None")  [assignment]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:58: error: Argument 1 to "merge" has incompatible type "None"; expected "Node"  [arg-type]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:64: error: Incompatible types in assignment (expression has type "Node", variable has type "None")  [assignment]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:64: error: Argument 2 to "merge" has incompatible type "None"; expected "Node"  [arg-type]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:102: error: Argument 1 to "node_print" has incompatible type "None"; expected "Node"  [arg-type]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:104: error: Argument 1 to "node_print" has incompatible type "None"; expected "Node"  [arg-type]
(TheAlgorithms)Python/project_euler/problem_02/sol4.py:17: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/bogo_sort.py:43: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/maths/zellers_congruence.py:1: error: Module '__future__' has no attribute 'annotations'  [attr-defined]
Found 81 errors in 49 files (checked 263 source files)

[RRepo](trezor)micropython
(trezor)micropython/tests/micropython/viper_binop_divmod.py:3: error: Name 'micropython' is not defined  [name-defined]
(trezor)micropython/tests/micropython/viper_binop_divmod.py:7: error: Name 'micropython' is not defined  [name-defined]
(trezor)micropython/tests/micropython/heapalloc_traceback.py:33: error: Module has no attribute "print_exception"  [attr-defined]
(trezor)micropython/tests/basics/class_super.py:26: error: Name 'A' already defined on line 19  [no-redef]
(trezor)micropython/tests/basics/class_super.py:41: error: Invalid assignment target  [misc]
(trezor)micropython/tests/basics/class_super.py:45: error: Invalid delete target  [misc]
(trezor)micropython/tests/basics/class_super.py:45: error: "foo" undefined in superclass  [misc]
(trezor)micropython/tests/basics/fun_error.py:5: error: Unexpected keyword argument "x" for "append" of "list"  [call-arg]
(trezor)micropython/tests/basics/fun_error.py:11: error: All overload variants of "round" require at least one argument  [call-overload]
(trezor)micropython/tests/basics/fun_error.py:11: note: Possible overload variants:
(trezor)micropython/tests/basics/fun_error.py:11: note:     def round(number: float) -> int
(trezor)micropython/tests/basics/fun_error.py:11: note:     def round(number: float, ndigits: None) -> int
(trezor)micropython/tests/basics/fun_error.py:11: note:     <4 more similar overloads not shown, out of 6 total overloads>
(trezor)micropython/tests/basics/fun_error.py:17: error: No overload variant of "round" matches argument types "int", "int", "int"  [call-overload]
(trezor)micropython/tests/basics/fun_error.py:17: note: Possible overload variants:
(trezor)micropython/tests/basics/fun_error.py:17: note:     def round(number: float) -> int
(trezor)micropython/tests/basics/fun_error.py:17: note:     def round(number: float, ndigits: None) -> int
(trezor)micropython/tests/basics/fun_error.py:17: note:     <4 more similar overloads not shown, out of 6 total overloads>
(trezor)micropython/tests/basics/fun_error.py:23: error: Too many arguments for "append" of "list"  [call-arg]
(trezor)micropython/tests/basics/fun_error.py:23: error: Argument 1 to "append" of "list" has incompatible type "int"; expected <nothing>  [arg-type]
(trezor)micropython/tests/basics/fun_error.py:29: error: Too many positional arguments for "sort" of "list"  [misc]
(trezor)micropython/tests/basics/fun_error.py:29: error: Argument 1 to "sort" of "list" has incompatible type "int"; expected "Optional[Callable[[<nothing>], Any]]"  [arg-type]
(trezor)micropython/tests/basics/fun_error.py:35: error: Unexpected keyword argument "noexist" for "sort" of "list"  [call-arg]
(trezor)micropython/tests/basics/fun_error.py:42: error: Missing positional argument "y" in call to "f"  [call-arg]
(trezor)micropython/tests/basics/del_attr.py:2: error: Method must have at least one argument  [misc]
(trezor)micropython/tests/basics/del_attr.py:9: error: "Type[C]" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/basics/del_attr.py:21: error: "C" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/basics/del_attr.py:22: error: "C" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/basics/del_attr.py:24: error: "C" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/basics/del_attr.py:26: error: "C" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/basics/del_attr.py:30: error: "C" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/basics/builtin_setattr.py:16: error: Argument 2 to "setattr" has incompatible type "bytes"; expected "str"  [arg-type]
(trezor)micropython/tests/basics/fun_calldblstar2.py:16: error: Name 'foo' is not defined  [name-defined]
(trezor)micropython/tests/basics/fun_calldblstar2.py:19: error: Name 'foo' is not defined  [name-defined]
(trezor)micropython/tests/basics/iter1.py:7: error: "NotIterable" has no attribute "__iter__" (not iterable)  [attr-defined]
(trezor)micropython/tests/basics/iter1.py:13: error: Name 'NotIterable' already defined on line 4  [no-redef]
(trezor)micropython/tests/basics/iter1.py:17: error: Argument 1 to "all" has incompatible type "NotIterable"; expected "Iterable[object]"  [arg-type]
(trezor)micropython/tests/basics/builtin_dir.py:22: error: Method must have at least one argument  [misc]
(trezor)micropython/tests/basics/builtin_dir.py:25: error: Method must have at least one argument  [misc]
(trezor)micropython/tests/basics/builtin_dir.py:32: error: Method must have at least one argument  [misc]
(trezor)micropython/tests/basics/builtin_dir.py:35: error: Method must have at least one argument  [misc]
(trezor)micropython/tests/basics/fun_calldblstar.py:10: error: Keywords must be strings  [misc]
(trezor)micropython/tests/basics/op_error_intbig.py:14: error: Unsupported right operand type for in ("int")  [operator]
(trezor)micropython/tests/basics/subclass_native_init.py:34: error: Cannot access "__init__" directly  [misc]
(trezor)micropython/tests/basics/subclass_native_init.py:38: error: Name 'L' already defined on line 4  [no-redef]
(trezor)micropython/tests/basics/subclass_native_init.py:41: error: Too few arguments for "L"  [call-arg]
(trezor)micropython/tests/basics/subclass_native_init.py:41: error: Incompatible types in assignment (expression has type "L", variable has type "D")  [assignment]
(trezor)micropython/tests/basics/builtin_exec.py:10: error: "int" not callable  [operator]
(trezor)micropython/tests/basics/builtin_exec.py:12: error: Need type annotation for 'd' (hint: "d: Dict[<type>, <type>] = ...")  [var-annotated]
(trezor)micropython/tests/basics/builtin_exec.py:32: error: Argument 2 to "exec" has incompatible type "str"; expected "Optional[Dict[str, Any]]"  [arg-type]
(trezor)micropython/tests/basics/builtin_exec.py:38: error: Argument 3 to "exec" has incompatible type "int"; expected "Optional[Mapping[str, Any]]"  [arg-type]
(trezor)micropython/tests/basics/builtin_hasattr.py:39: error: Argument 2 to "hasattr" has incompatible type "bytes"; expected "str"  [arg-type]
(trezor)micropython/tests/basics/builtin_hasattr.py:44: error: Argument 2 to "hasattr" has incompatible type "int"; expected "str"  [arg-type]
(trezor)micropython/tests/basics/object_new.py:37: error: Argument 1 to "__new__" of "object" has incompatible type "int"; expected "Type[object]"  [arg-type]
(trezor)micropython/tests/pyb/can.py:72: error: Argument 1 to "len" has incompatible type "object"; expected "Sized"  [arg-type]
(trezor)micropython/tests/pyb/can.py:77: error: Argument 1 to "len" has incompatible type "object"; expected "Sized"  [arg-type]
(trezor)micropython/tests/pyb/can.py:82: error: Argument 1 to "len" has incompatible type "object"; expected "Sized"  [arg-type]
(trezor)micropython/tests/pyb/can.py:87: error: Argument 1 to "len" has incompatible type "object"; expected "Sized"  [arg-type]
(trezor)micropython/tests/pyb/can.py:93: error: Argument 1 to "memoryview" has incompatible type "array[int]"; expected "Union[bytes, bytearray, memoryview]"  [arg-type]
(trezor)micropython/tests/pyb/can.py:95: error: Argument 1 to "memoryview" has incompatible type "array[int]"; expected "Union[bytes, bytearray, memoryview]"  [arg-type]
(trezor)micropython/tests/pyb/can.py:128: error: Argument 1 to "memoryview" has incompatible type "array[int]"; expected "Union[bytes, bytearray, memoryview]"  [arg-type]
(trezor)micropython/tests/misc/non_compliant.py:18: error: "ValueError" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/misc/non_compliant.py:139: error: Cannot determine consistent method resolution order (MRO) for "B"  [misc]

[RRepo](littlezz)ESL-Model
(littlezz)ESL-Model/esl_model/datasets/data_set.py:91: error: Incompatible types in assignment (expression has type "List[str]", base class "BaseDataSet" defined the type as "str")  [assignment]
(littlezz)ESL-Model/esl_model/datasets/data_set.py:128: error: Incompatible types in assignment (expression has type "List[str]", base class "BaseDataSet" defined the type as "str")  [assignment]
(littlezz)ESL-Model/esl_model/base.py:29: error: Decorated property not supported  [misc]
(littlezz)ESL-Model/esl_model/base.py:38: error: Decorated property not supported  [misc]
(littlezz)ESL-Model/esl_model/ch4/models.py:2: error: Relative import climbs too many namespaces  [misc]
(littlezz)ESL-Model/esl_model/ch4/models.py:5: error: Relative import climbs too many namespaces  [misc]
(littlezz)ESL-Model/esl_model/ch4/models.py:6: error: Relative import climbs too many namespaces  [misc]
(littlezz)ESL-Model/esl_model/ch4/models.py:18: error: Decorated property not supported  [misc]
(littlezz)ESL-Model/esl_model/ch4/models.py:47: error: Decorated property not supported  [misc]
Found 9 errors in 3 files (checked 9 source files)

[RRepo](sussexstudent)falmer
(sussexstudent)falmer/falmer/auth/types.py:4: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 37 source files)

[RRepo](python)the-knights-who-say-ni
(python)the-knights-who-say-ni/ni/__main__.py:11: error: No parent module -- cannot perform relative import  [misc]
(python)the-knights-who-say-ni/ni/__main__.py:12: error: No parent module -- cannot perform relative import  [misc]
(python)the-knights-who-say-ni/ni/__main__.py:13: error: No parent module -- cannot perform relative import  [misc]
(python)the-knights-who-say-ni/ni/__main__.py:14: error: No parent module -- cannot perform relative import  [misc]
Found 4 errors in 1 file (checked 9 source files)

[RRepo](mitmproxy)mitmproxy
(mitmproxy)mitmproxy/pathod/test.py:4: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 352 source files)

[RRepo](sliceofcode)dogbot
(sliceofcode)dogbot/dog/core/bot.py:16: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 48 source files)

[RRepo](movidius)ncappzoo
(movidius)ncappzoo/apps/classifier_grid/canvas.py:105: error: Need type annotation for '_grid_image_list' (hint: "_grid_image_list: List[<type>] = ...")  [var-annotated]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:106: error: Need type annotation for '_large_image_list' (hint: "_large_image_list: List[<type>] = ...")  [var-annotated]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:114: error: No overload variant of "__setitem__" of "list" matches argument types "int", "int"  [call-overload]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:114: note: Possible overload variants:
(movidius)ncappzoo/apps/classifier_grid/canvas.py:114: note:     def __setitem__(self, int, None) -> None
(movidius)ncappzoo/apps/classifier_grid/canvas.py:114: note:     def __setitem__(self, slice, Iterable[None]) -> None
(movidius)ncappzoo/apps/classifier_grid/canvas.py:205: error: Argument 1 to "draw_inference_label" of "Canvas" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:304: error: Argument 3 to "_put_text_on_canvas" of "Canvas" has incompatible type "None"; expected "int"  [arg-type]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:311: error: Argument 3 to "_put_text_on_canvas" of "Canvas" has incompatible type "None"; expected "int"  [arg-type]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:323: error: Unsupported operand types for - ("None" and "int")  [operator]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:331: error: Unsupported operand types for - ("None" and "int")  [operator]
(movidius)ncappzoo/apps/mnist_calc/calcui.py:150: error: Read-only property cannot override read-write property  [misc]
(movidius)ncappzoo/apps/mnist_calc/calcui.py:156: error: Read-only property cannot override read-write property  [misc]
(movidius)ncappzoo/apps/classifier_gui/classifier_gui.py:19: error: Name 'Image' already defined (possibly by an import)  [no-redef]
Found 11 errors in 3 files (checked 16 source files)

[RRepo](portfoliome)foil
(portfoliome)foil/foil/counting.py:10: error: Need type annotation for 'counter'  [var-annotated]

[RRepo](coblo)pyiscclib
(coblo)pyiscclib/src/iscclib/data.py:83: error: Need type annotation for 'ids' (hint: "ids: Set[<type>] = ...")  [var-annotated]
(coblo)pyiscclib/src/iscclib/instance.py:111: error: Need type annotation for 'ids' (hint: "ids: Set[<type>] = ...")  [var-annotated]
(coblo)pyiscclib/ci/appveyor-bootstrap.py:17: error: Module 'urllib' has no attribute 'urlretrieve'  [attr-defined]
(coblo)pyiscclib/ci/appveyor-bootstrap.py:17: error: Name 'urlretrieve' already defined (possibly by an import)  [no-redef]
Found 4 errors in 3 files (checked 26 source files)

[RRepo](motion-planning)rrt-algorithms
Success: no issues found in 12 source files

[RRepo](Nexterot)labyrinth-project
Success: no issues found in 14 source files

[RRepo](c3cashdesk)postix
(c3cashdesk)postix/src/postix/core/models/base.py:183: error: No parent module -- cannot perform relative import  [misc]
(c3cashdesk)postix/src/postix/core/models/base.py:196: error: No parent module -- cannot perform relative import  [misc]
Found 2 errors in 1 file (checked 75 source files)

[RRepo](raster-foundry)raster-foundry
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_landsat_h.py:7: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_landsat_h.py:8: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_landsat_h.py:9: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/update_aoi_project.py:6: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/export.py:11: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/export.py:12: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/find_aoi_projects.py:8: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/find_aoi_projects.py:12: error: Item "None" of "Optional[str]" has no attribute "title"  [union-attr]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_geotiff_to_cog.py:4: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_geotiff_to_cog.py:5: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_geotiff_to_cog.py:7: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:7: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:8: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:9: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:10: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:11: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:12: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:13: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/ingest_scene.py:8: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/ingest_scene.py:9: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/ingest_scene.py:10: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_sentinel.py:8: error: Relative import climbs too many namespaces  [misc]
Found 22 errors in 8 files (checked 38 source files)

[RRepo](eliostvs)tomate-statusicon-plugin
Success: no issues found in 3 source files

[RRepo](rr-)szurubooru
(rr-)szurubooru/server/szurubooru/model/post.py:228: error: Name 'flags' already defined on line 224  [no-redef]
(rr-)szurubooru/server/szurubooru/migrations/versions/9ef1a1643c2a_update_user_table_for_hardened_passwords.py:23: error: Variable "9ef1a1643c2a_update_user_table_for_hardened_passwords.Base" is not valid as a type  [valid-type]
(rr-)szurubooru/server/szurubooru/migrations/versions/9ef1a1643c2a_update_user_table_for_hardened_passwords.py:23: error: Invalid base class "Base"  [misc]
(rr-)szurubooru/server/szurubooru/migrations/versions/9837fc981ec7_add_order_to_tag_names.py:22: error: Variable "9837fc981ec7_add_order_to_tag_names.Base" is not valid as a type  [valid-type]
(rr-)szurubooru/server/szurubooru/migrations/versions/9837fc981ec7_add_order_to_tag_names.py:22: error: Invalid base class "Base"  [misc]
(rr-)szurubooru/server/szurubooru/migrations/versions/5f00af3004a4_add_default_tag_category.py:23: error: Variable "5f00af3004a4_add_default_tag_category.Base" is not valid as a type  [valid-type]
(rr-)szurubooru/server/szurubooru/migrations/versions/5f00af3004a4_add_default_tag_category.py:23: error: Invalid base class "Base"  [misc]
(rr-)szurubooru/server/szurubooru/rest/app.py:48: error: "Iterable[str]" has no attribute "__next__"  [attr-defined]
(rr-)szurubooru/server/szurubooru/func/image_hash.py:157: error: Value of type "Union[Any, int]" is not indexable  [index]
(rr-)szurubooru/server/szurubooru/func/image_hash.py:159: error: Value of type "Union[Any, int]" is not indexable  [index]
(rr-)szurubooru/server/szurubooru/func/user_tokens.py:137: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")  [assignment]
Found 11 errors in 7 files (checked 137 source files)

[RRepo](Netflix-Skunkworks)iep-apps
Success: no issues found in 2 source files

[RRepo](Pitt-CSC)PittAPI
(Pitt-CSC)PittAPI/PittAPI/people.py:93: error: Incompatible return value type (got "List[Generator[Any, None, None]]", expected "List[Iterator[str]]")  [return-value]
(Pitt-CSC)PittAPI/PittAPI/people.py:93: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
(Pitt-CSC)PittAPI/PittAPI/people.py:93: note: Consider using "Sequence" instead, which is covariant
(Pitt-CSC)PittAPI/PittAPI/people.py:93: note: Perhaps you need a type annotation for "url_list"? Suggestion: "List[Iterator[str]]"
(Pitt-CSC)PittAPI/tests/people_test.py:24: error: Argument 1 to "skip" has incompatible type "Type[PeopleTest]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/tests/library_test.py:24: error: Argument 1 to "skip" has incompatible type "Type[LibraryTest]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/tests/news_test.py:24: error: Argument 1 to "skip" has incompatible type "Type[NewsTest]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/PittAPI/textbook.py:178: error: "str" has no attribute "json"  [attr-defined]
(Pitt-CSC)PittAPI/PittAPI/textbook.py:196: error: Argument 3 to "_extract_id" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/PittAPI/textbook.py:196: error: Argument 4 to "_extract_id" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:71: error: Dict entry 1 has incompatible type "str": "int"; expected "str": "str"  [dict-item]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:71: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:72: error: Dict entry 2 has incompatible type "str": "int"; expected "str": "str"  [dict-item]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:72: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:73: error: Dict entry 3 has incompatible type "str": "int"; expected "str": "str"  [dict-item]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:73: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:74: error: Dict entry 4 has incompatible type "str": "int"; expected "str": "str"  [dict-item]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:74: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
Found 15 errors in 6 files (checked 19 source files)

[RRepo](arthurmensch)modl
(arthurmensch)modl/modl/utils/tests/test_system.py:49: error: Name 'test_get_data_dir' already defined on line 22  [no-redef]
(arthurmensch)modl/modl/utils/randomkit/tests/test_random.py:7: error: Module 'modl.utils.randomkit' has no attribute 'RandomState'  [attr-defined]
(arthurmensch)modl/modl/decomposition/tests/test_fmri.py:8: error: Module 'modl.decomposition' has no attribute 'fMRIDictFact'  [attr-defined]
(arthurmensch)modl/modl/input_data/fmri/base.py:69: error: Name 'check_embedded_nifti_masker' already defined (possibly by an import)  [no-redef]
(arthurmensch)modl/examples/stability_selection.py:79: error: Need type annotation for 'dictionaries_' (hint: "dictionaries_: Dict[<type>, <type>] = ...")  [var-annotated]
(arthurmensch)modl/examples/stability_selection.py:80: error: Need type annotation for 'scores' (hint: "scores: Dict[<type>, <type>] = ...")  [var-annotated]
(arthurmensch)modl/exps/multi_decompose_fmri.py:34: error: Name 'config' already defined on line 27  [no-redef]
(arthurmensch)modl/exps/multi_decompose_images.py:34: error: Name 'config' already defined on line 27  [no-redef]
Found 8 errors in 7 files (checked 33 source files)

[RRepo](steinitzu)spotify-api
(steinitzu)spotify-api/spotify/client.py:5: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 4 source files)

[RRepo](globality-corp)microcosm-flask
(globality-corp)microcosm-flask/microcosm_flask/swagger/parameters/nested.py:21: error: "Field" has no attribute "schema"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/parameters/enum.py:41: error: "Field" has no attribute "by_value"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/parameters/timestamp.py:16: error: "Field" has no attribute "use_isoformat"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/parameters/timestamp.py:21: error: "Field" has no attribute "use_isoformat"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/parameters/list.py:21: error: "Field" has no attribute "container"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/schemas.py:36: error: Argument 1 has incompatible type "Field"; expected "Schema"  [arg-type]
(globality-corp)microcosm-flask/microcosm_flask/swagger/schemas.py:65: error: "Field" has no attribute "dump_to"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/schemas.py:84: error: "List" has no attribute "container"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/schemas.py:85: error: "List" has no attribute "container"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/schemas.py:86: error: "List" has no attribute "container"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/tests/test_audit.py:5: error: Module 'logging' has no attribute 'DEBUG'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/tests/test_audit.py:5: error: Module 'logging' has no attribute 'NOTSET'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/tests/test_audit.py:5: error: Module 'logging' has no attribute 'getLogger'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/conventions/logging_level.py:6: error: Module 'logging' has no attribute 'PlaceHolder'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/conventions/logging_level.py:6: error: Module 'logging' has no attribute 'root'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/parameters/default.py:2: error: Module 'logging' has no attribute 'Logger'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/definitions.py:19: error: Module 'logging' has no attribute 'getLogger'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/errors.py:5: error: Module 'logging' has no attribute 'getLogger'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/errors.py:28: error: Incompatible types in assignment (expression has type "Nested", base class "Schema" defined the type as "Dict[Any, Any]")  [assignment]
(globality-corp)microcosm-flask/microcosm_flask/audit.py:10: error: Module 'logging' has no attribute 'DEBUG'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/audit.py:10: error: Module 'logging' has no attribute 'getLogger'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/memory.py:2: error: Module 'logging' has no attribute 'Logger'  [attr-defined]
Found 22 errors in 12 files (checked 116 source files)

[RRepo](rokups)Urho3D
(rokups)Urho3D/script/AutoSwig/walkcpp/generator.py:82: error: Name 'Module' is not defined  [name-defined]
(rokups)Urho3D/script/AutoSwig/walkcpp/generator.py:93: error: Need type annotation for 'pass_factories' (hint: "pass_factories: List[<type>] = ...")  [var-annotated]
Found 2 errors in 1 file (checked 4 source files)

[RRepo](gilesknap)gphotos-sync
(gilesknap)gphotos-sync/gphotos/LocalFilesMedia.py:7: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 28 source files)

[RRepo](steven-zou)harbor
(steven-zou)harbor/contrib/registryapi/cli.py:35: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 54 source files)

[RRepo](horazont)aioxmpp
(horazont)aioxmpp/aioxmpp/mdr/service.py:26: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 85 source files)

[RRepo](zillow)aiographite
(zillow)aiographite/tests/test_graphite_send.py:5: error: Module 'asyncio' has no attribute 'test_utils'  [attr-defined]
Found 1 error in 1 file (checked 7 source files)

[RRepo](ChristophGaukel)ev3-python3
(ChristophGaukel)ev3-python3/ev3_sound.py:306: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(ChristophGaukel)ev3-python3/ev3_sound.py:313: error: Unsupported operand types for + ("None" and "int")  [operator]
(ChristophGaukel)ev3-python3/ev3_sound.py:313: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(ChristophGaukel)ev3-python3/ev3_sound.py:317: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(ChristophGaukel)ev3-python3/ev3_sound.py:319: error: Missing return statement  [return]
(ChristophGaukel)ev3-python3/ev3_sound.py:321: error: Unsupported operand types for + ("None" and "int")  [operator]
(ChristophGaukel)ev3-python3/ev3_sound.py:321: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(ChristophGaukel)ev3-python3/ev3_sound.py:322: error: Unsupported operand types for % ("None" and "int")  [operator]
(ChristophGaukel)ev3-python3/ev3_sound.py:322: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(ChristophGaukel)ev3-python3/ev3_file.py:91: error: Name 'SysCmdError' is not defined  [name-defined]
(ChristophGaukel)ev3-python3/ev3_file.py:170: error: Name 'SysCmdError' is not defined  [name-defined]
Found 11 errors in 2 files (checked 2 source files)

[RRepo](jaywink)federation
(jaywink)federation/federation/protocols/diaspora/signatures.py:5: error: Module 'Crypto.PublicKey.RSA' has no attribute 'RsaKey'  [attr-defined]
(jaywink)federation/federation/protocols/diaspora/encrypted.py:5: error: Module 'Crypto.Random' has no attribute 'get_random_bytes'  [attr-defined]
(jaywink)federation/federation/entities/mixins.py:12: error: Incompatible types in assignment (expression has type "None", variable has type "List[Any]")  [assignment]
(jaywink)federation/federation/entities/mixins.py:13: error: Incompatible types in assignment (expression has type "None", variable has type "Set[Any]")  [assignment]
(jaywink)federation/federation/entities/mixins.py:14: error: Incompatible types in assignment (expression has type "None", variable has type "List[Any]")  [assignment]
(jaywink)federation/federation/entities/mixins.py:17: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(jaywink)federation/federation/entities/mixins.py:20: error: Incompatible types in assignment (expression has type "None", variable has type "ActivityType")  [assignment]
(jaywink)federation/federation/tests/entities/activitypub/django/test_views.py:8: error: Module 'django.views' has no attribute 'View'  [attr-defined]

[RRepo](ScheduledOvers)quizwipe

[RRepo](jopohl)urh
(jopohl)urh/src/urh/ui/ui_send_recv_sniff_settings.py:211: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 293 source files)

[RRepo](ysavary)WindMobile2-Server
(ysavary)WindMobile2-Server/providers/yvbeach.py:7: error: Module 'commons' has no attribute 'user_agents'  [attr-defined]
(ysavary)WindMobile2-Server/providers/meteoswiss_web.py:5: error: Module 'commons' has no attribute 'user_agents'  [attr-defined]
(ysavary)WindMobile2-Server/providers/thunerwetter.py:8: error: Module 'commons' has no attribute 'user_agents'  [attr-defined]
(ysavary)WindMobile2-Server/providers/iweathar.py:8: error: Module 'commons' has no attribute 'user_agents'  [attr-defined]
Found 4 errors in 4 files (checked 24 source files)

[RRepo](flycheck)flycheck
(flycheck)flycheck/test/resources/language/python/invalid_type.py:2: error: Incompatible return value type (got "str", expected "int")  [return-value]
(flycheck)flycheck/test/resources/language/python/test.py:5: error: Module 'python' has no attribute 'antigravit'; maybe "antigravity"?  [attr-defined]
(flycheck)flycheck/test/resources/language/python/test.py:22: error: Name 'antigravity' is not defined  [name-defined]
Found 3 errors in 2 files (checked 6 source files)

[RRepo](timothycrosley)hug
(timothycrosley)hug/tests/module_fake_simple.py:8: error: Module has no attribute "get"  [attr-defined]
(timothycrosley)hug/tests/module_fake_simple.py:13: error: Module has no attribute "get"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:26: error: Module has no attribute "json"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:27: error: Module has no attribute "text"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:30: error: Module has no attribute "input_format"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:31: error: Module has no attribute "input_format"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:32: error: Module has no attribute "input_format"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:33: error: Module has no attribute "input_format"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:34: error: Module has no attribute "input_format"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:35: error: Module has no attribute "input_format"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:39: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:40: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:41: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:42: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:43: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:44: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:45: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:46: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/tests/test_interface.py:27: error: Module has no attribute "http"  [attr-defined]
(timothycrosley)hug/tests/module_fake_http_and_cli.py:4: error: Module has no attribute "get"  [attr-defined]
(timothycrosley)hug/tests/module_fake_http_and_cli.py:5: error: Module has no attribute "cli"  [attr-defined]
(timothycrosley)hug/tests/test_route.py:25: error: Module has no attribute "API"  [attr-defined]
(timothycrosley)hug/tests/module_fake_post.py:5: error: Module has no attribute "post"  [attr-defined]
(timothycrosley)hug/tests/test_directives.py:28: error: Module has no attribute "API"  [attr-defined]
(timothycrosley)hug/tests/test_directives.py:31: error: Name '__hug__' is not defined  [name-defined]
(timothycrosley)hug/tests/test_directives.py:151: error: Name 'hug.directives.Timer' is not defined  [name-defined]
(timothycrosley)hug/tests/test_directives.py:201: error: Name 'hug.directives.user' is not defined  [name-defined]
(timothycrosley)hug/tests/test_directives.py:207: error: Name 'hug.directives.user' is not defined  [name-defined]
(timothycrosley)hug/tests/test_directives.py:219: error: Name 'hug.directives.cors' is not defined  [name-defined]
(timothycrosley)hug/tests/test_api.py:26: error: Module has no attribute "API"  [attr-defined]

[RRepo](ColumbiaSC-Tech)botty_mcbotface
(ColumbiaSC-Tech)botty_mcbotface/test_botty/tests/test_plugins/test_help.py:3: error: Module 'test_botty.mocks' has no attribute 'MockMessage'  [attr-defined]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/botty/db/routines/routine_populate_db.py:3: error: Module 'botty_mcbotface.botty.db' has no attribute 'Channel'  [attr-defined]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/botty/db/routines/routine_populate_db.py:3: error: Module 'botty_mcbotface.botty.db' has no attribute 'User'  [attr-defined]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/plugins/flipper.py:12: error: Cannot infer type argument 2 of "defaultdict"  [misc]
(ColumbiaSC-Tech)botty_mcbotface/test_botty/tests/test_plugins/test_seen.py:5: error: Module 'test_botty.mocks' has no attribute 'MockMessage'  [attr-defined]
(ColumbiaSC-Tech)botty_mcbotface/test_botty/tests/test_plugins/test_seen.py:5: error: Module 'test_botty.mocks' has no attribute 'MockRequestGET'  [attr-defined]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/plugins/calendar.py:32: error: Need type annotation for '_CACHE' (hint: "_CACHE: Dict[<type>, <type>] = ...")  [var-annotated]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/plugins/calendar.py:66: error: "Type[datetime]" has no attribute "fromisoformat"  [attr-defined]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/plugins/calendar.py:102: error: Unexpected type declaration  [misc]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/plugins/calendar.py:120: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]

[RRepo](fametrano)BitcoinBlockchainTechnology
(fametrano)BitcoinBlockchainTechnology/btclib/dsa.py:190: error: "Sequence[Any]" has no attribute "append"  [attr-defined]
(fametrano)BitcoinBlockchainTechnology/btclib/dsa.py:194: error: "Sequence[Any]" has no attribute "append"  [attr-defined]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:26: error: Argument 1 to "int" has incompatible type "Union[str, int, bytes]"; expected "Union[str, bytes, bytearray]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:28: error: Unsupported right operand type for in ("Union[int, Tuple[Any, ...]]")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:28: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:29: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:31: error: Incompatible return value type (got "Union[str, int, bytes]", expected "str")  [return-value]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:33: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:35: error: Unsupported right operand type for in ("Union[int, Tuple[Any, ...]]")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:38: error: Argument 1 to "from_bytes" of "int" has incompatible type "Union[str, int, bytes]"; expected "Sequence[int]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:42: error: Unsupported operand types for < ("str" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:42: error: Unsupported operand types for < ("bytes" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:42: note: Left operand is of type "Union[str, int, bytes]"
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:43: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:44: error: Argument 1 to "bin" has incompatible type "Union[str, int, bytes]"; expected "Union[int, _SupportsIndex]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:46: error: Unsupported right operand type for in ("Union[int, Tuple[Any, ...]]")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:58: error: Argument 1 to "int" has incompatible type "Union[str, int, bytes]"; expected "Union[str, bytes, bytearray]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:60: error: Unsupported operand types for < ("str" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:60: error: Unsupported operand types for < ("bytes" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:60: note: Left operand is of type "Union[str, int, bytes]"
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:61: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:62: error: Incompatible return value type (got "Union[str, int, bytes]", expected "int")  [return-value]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:64: error: Argument 1 to "from_bytes" of "int" has incompatible type "Union[str, int, bytes]"; expected "Sequence[int]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:77: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:78: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:80: error: Incompatible return value type (got "Union[str, int, bytes]", expected "bytes")  [return-value]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:82: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:87: error: Argument 1 to "int" has incompatible type "Union[str, int, bytes]"; expected "Union[str, bytes, bytearray]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:90: error: Unsupported operand types for < ("str" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:90: error: Unsupported operand types for < ("bytes" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:90: note: Left operand is of type "Union[str, int, bytes]"
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:91: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:92: error: Item "str" of "Union[str, int, bytes]" has no attribute "bit_length"  [union-attr]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:92: error: Item "bytes" of "Union[str, int, bytes]" has no attribute "bit_length"  [union-attr]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:97: error: Item "str" of "Union[str, int, bytes]" has no attribute "to_bytes"  [union-attr]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:97: error: Item "bytes" of "Union[str, int, bytes]" has no attribute "to_bytes"  [union-attr]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:75: error: Incompatible types in assignment (expression has type "int", target has type "None")  [assignment]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:76: error: Incompatible types in assignment (expression has type "int", target has type "None")  [assignment]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:78: error: Incompatible types in assignment (expression has type "List[str]", target has type "None")  [assignment]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:82: error: Incompatible return value type (got "None", expected "int")  [return-value]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:86: error: Incompatible return value type (got "None", expected "List[str]")  [return-value]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:90: error: Incompatible return value type (got "None", expected "int")  [return-value]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:106: error: Unsupported operand types for divmod ("int" and "None")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:111: error: Unsupported operand types for / ("int" and "None")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:123: error: Value of type "None" is not indexable  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:132: error: "None" has no attribute "index"  [attr-defined]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:141: error: Unsupported operand types for * ("int" and "None")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:147: error: Unsupported operand types for * ("int" and "None")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/base58.py:127: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:49: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:70: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:74: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:75: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:76: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:77: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:82: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:87: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:88: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:62: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:134: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:152: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:154: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:191: error: Incompatible types in assignment (expression has type "Sequence[int]", variable has type "List[int]")  [assignment]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:249: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:78: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:79: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:87: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:91: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:94: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:96: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:127: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:134: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:30: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:32: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:42: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:99: error: Unsupported operand types for + ("None" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:99: note: Left operand is of type "Union[int, Any, None]"
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:247: error: Invalid type comment or annotation  [valid-type]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:247: note: Suggestion: use Sequence[...] instead of Sequence(...)
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:265: error: "Sequence[Any]" has no attribute "append"  [attr-defined]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:267: error: "Sequence[Any]" has no attribute "append"  [attr-defined]
Found 76 errors in 8 files (checked 31 source files)

[RRepo](carbonblack)cb-integration
(carbonblack)cb-integration/cbint/globals.py:25: error: Need type annotation for 'g_status' (hint: "g_status: Dict[<type>, <type>] = ...")  [var-annotated]
(carbonblack)cb-integration/cbint/binary_collector.py:6: error: Name 'datetime' already defined (by an import)  [no-redef]
Found 2 errors in 2 files (checked 11 source files)

[RRepo](Islandman93)reinforcepy
(Islandman93)reinforcepy/docs/conf.py:223: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
(Islandman93)reinforcepy/reinforcepy/networks/dqn/tflow/dqn_inits.py:2: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/environments/openaigym/gym_atari.py:2: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/environments/openaigym/gym_wrapper.py:1: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/learners/TableLookup/sarsatable.py:1: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/learners/TableLookup/sarsatable.py:3: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/learners/TableLookup/qtable.py:1: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/learners/TableLookup/qtable.py:2: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/networks/dqn/tflow/dqn_inits.py:2: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/learners/dqn/asynchronous/base_thread_learner.py:3: error: Module 'reinforcepy.handlers' has no attribute 'ActionHandler'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/learners/dqn/asynchronous/onestep_sarsa_thread_learner.py:2: error: Module 'reinforcepy.learners' has no attribute 'BaseSarsaLearner'  [attr-defined]
(Islandman93)reinforcepy/examples/SimpleQLearn/FrozenLakev0.py:1: error: Module 'reinforcepy.environments' has no attribute 'GymWrapper'  [attr-defined]
(Islandman93)reinforcepy/examples/SimpleQLearn/FrozenLakev0.py:2: error: Module 'reinforcepy.learners.TableLookup' has no attribute 'QTable'  [attr-defined]
(Islandman93)reinforcepy/examples/SimpleQLearn/FrozenLakev0.py:2: error: Module 'reinforcepy.learners.TableLookup' has no attribute 'SARSATable'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/test/test_actionhandler.py:2: error: Module 'reinforcepy.handlers' has no attribute 'ActionHandler'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/test/test_actionhandler.py:2: error: Module 'reinforcepy.handlers' has no attribute 'ActionPolicy'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/test/test_framebuffer.py:2: error: Module 'reinforcepy.handlers' has no attribute 'FrameBuffer'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/test/test_binarytree.py:3: error: Module 'reinforcepy.handlers.experience_replay.prioritized' has no attribute 'Node'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/test/test_binarytree.py:3: error: Module 'reinforcepy.handlers.experience_replay.prioritized' has no attribute 'BinaryTree'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/environments/ALE/ALE_environment.py:3: error: Module 'reinforcepy.environments' has no attribute 'BaseEnvironment'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/handlers/actionhandler.py:57: error: Unsupported left operand type for < ("Number")  [operator]
(Islandman93)reinforcepy/reinforcepy/learners/dqn/asynchronous/q_thread_learner.py:2: error: Module 'reinforcepy.learners' has no attribute 'BaseQLearner'  [attr-defined]

[RRepo](laramies)theHarvester
(laramies)theHarvester/tests/discovery/test_githubcode.py:33: error: Cannot assign to a method  [assignment]
(laramies)theHarvester/tests/discovery/test_githubcode.py:37: error: Cannot assign to a method  [assignment]
(laramies)theHarvester/tests/discovery/test_githubcode.py:42: error: Cannot assign to a method  [assignment]
(laramies)theHarvester/tests/discovery/test_githubcode.py:64: error: Cannot assign to a method  [assignment]
(laramies)theHarvester/theHarvester/discovery/githubcode.py:23: error: Function "builtins.any" is not valid as a type  [valid-type]
(laramies)theHarvester/theHarvester/discovery/githubcode.py:23: note: Perhaps you need "Callable[...]" or a callback protocol?
(laramies)theHarvester/theHarvester/discovery/githubcode.py:59: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")  [assignment]
(laramies)theHarvester/theHarvester/discovery/githubcode.py:59: error: List item 0 has incompatible type "None"; expected "str"  [list-item]
(laramies)theHarvester/theHarvester/discovery/githubcode.py:61: error: Incompatible return value type (got "Union[str, int]", expected "Optional[int]")  [return-value]
(laramies)theHarvester/theHarvester/discovery/githubcode.py:86: error: Name 'Core' is not defined  [name-defined]
Found 9 errors in 2 files (checked 46 source files)

[RRepo](playpauseandstop)rororo
(playpauseandstop)rororo/tests/test_settings.py:15: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 12 source files)

[RRepo](PhilipTrauner)cmus-osx
(PhilipTrauner)cmus-osx/cmus_osx/__init__.py:42: error: "__new__" must return a class instance (got "Optional[_CmusConfig]")  [misc]
Found 1 error in 1 file (checked 5 source files)

[RRepo](CoolProp)CoolProp
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:34: error: Name 'Python' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:42: error: Name 'Octave' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:44: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:52: error: Name 'Java' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:54: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:63: error: Name 'Csharp' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:65: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:74: error: Name 'R' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:76: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:34: error: Name 'Python' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:42: error: Name 'Octave' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:44: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:52: error: Name 'Java' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:54: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:63: error: Name 'Csharp' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:65: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:74: error: Name 'R' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:76: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/viscosity_builder.py:111: error: Name 'Model' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/viscosity_builder.py:112: error: Name 'Data' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/viscosity_builder.py:113: error: Name 'ODR' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:91: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:101: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:111: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:121: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:131: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:141: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:151: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:161: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/wrappers/Python/CoolProp/Plots/Tests.py:4: error: Module 'CoolProp.Plots' has no attribute 'PropertyPlot'  [attr-defined]
(CoolProp)CoolProp/wrappers/Python/CoolProp/Plots/PsychChart.py:185: error: Argument 1 to "write" of "IO" has incompatible type "bytes"; expected "str"  [arg-type]
(CoolProp)CoolProp/wrappers/Python/CoolProp/Plots/PsychChart.py:187: error: Name 'execfile' is not defined  [name-defined]
(CoolProp)CoolProp/Web/scripts/__init__.py:49: error: Incompatible types in assignment (expression has type "time", variable has type "datetime")  [assignment]
(CoolProp)CoolProp/Web/scripts/__init__.py:50: error: Incompatible types in assignment (expression has type "time", variable has type "datetime")  [assignment]
(CoolProp)CoolProp/Web/scripts/__init__.py:57: error: Unsupported operand types for <= ("datetime" and "time")  [operator]
(CoolProp)CoolProp/dev/Tickets/1443.py:245: error: Need type annotation for 'results' (hint: "results: Dict[<type>, <type>] = ...")  [var-annotated]
(CoolProp)CoolProp/dev/Tickets/351.py:2: error: Module 'CoolProp.Plots' has no attribute 'PropertyPlot'  [attr-defined]
(CoolProp)CoolProp/dev/Tickets/1118.py:78: error: Module 'CoolProp.Plots' has no attribute 'PropertyPlot'  [attr-defined]
(CoolProp)CoolProp/dev/scripts/fit_saturation_critical_splines.py:209: error: Need type annotation for 'e' (hint: "e: Dict[<type>, <type>] = ...")  [var-annotated]
(CoolProp)CoolProp/dev/scripts/fit_saturation_critical_splines.py:277: error: Incompatible types in assignment (expression has type "QuadraticFitter", variable has type "CubicFitter")  [assignment]
(CoolProp)CoolProp/dev/scripts/fit_saturation_critical_splines.py:297: error: Incompatible types in assignment (expression has type "QuadraticFitter", variable has type "CubicFitter")  [assignment]
(CoolProp)CoolProp/dev/scripts/fit_saturation_critical_splines.py:384: error: Trying to read deleted variable 'V'  [misc]
(CoolProp)CoolProp/dev/scripts/convert_FLD.py:130: error: Need type annotation for 'ALPHA0' (hint: "ALPHA0: List[<type>] = ...")  [var-annotated]
(CoolProp)CoolProp/dev/scripts/fit_avoid_ECS.py:84: error: Name 'Model' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/fit_avoid_ECS.py:85: error: Name 'Data' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/fit_avoid_ECS.py:87: error: Name 'ODR' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:219: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "bool"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:219: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Type[JSONEncoder]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:219: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Tuple[str, str]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:219: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Callable[[Any], Any]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:244: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "bool"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:244: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Type[JSONEncoder]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:244: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Tuple[str, str]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:244: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Callable[[Any], Any]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/ideal_curves.py:144: error: Module has no attribute "iT_triple"  [attr-defined]
(CoolProp)CoolProp/dev/scripts/ideal_curves.py:145: error: Module has no attribute "iT_critical"  [attr-defined]
(CoolProp)CoolProp/dev/TTSE/validate_TTSE.py:4: error: Module 'CoolProp.Plots' has no attribute 'Ph'  [attr-defined]
(CoolProp)CoolProp/dev/TTSE/check_TTSE_v5.py:159: error: Unsupported operand types for / ("List[float]" and "float")  [operator]
(CoolProp)CoolProp/dev/TTSE/check_TTSE_v5.py:169: error: Unsupported operand types for / ("List[float]" and "float")  [operator]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:1: error: Module 'CoolProp.Plots' has no attribute 'Ph'  [attr-defined]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:296: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:316: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:323: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:353: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:373: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:380: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/check_TTSE_v4.py:172: error: Unsupported operand types for / ("List[float]" and "float")  [operator]
(CoolProp)CoolProp/dev/TTSE/check_TTSE_v4.py:182: error: Unsupported operand types for / ("List[float]" and "float")  [operator]
(CoolProp)CoolProp/dev/incompressible_liquids/CPIncomp/__init__.py:10: error: Module 'CPIncomp' has no attribute 'MelinderFluids'; maybe "getMelinderFluids"?  [attr-defined]
(CoolProp)CoolProp/dev/incompressible_liquids/CPIncomp/__init__.py:10: error: Module 'CPIncomp' has no attribute 'SolutionFluids'; maybe "getSolutionFluids"?  [attr-defined]
(CoolProp)CoolProp/dev/incompressible_liquids/all_incompressibles.py:70: error: Need type annotation for 'doneObjs' (hint: "doneObjs: List[<type>] = ...")  [var-annotated]
(CoolProp)CoolProp/dev/incompressible_liquids/all_incompressibles.py:74: error: Need type annotation for 'solObjs' (hint: "solObjs: List[<type>] = ...")  [var-annotated]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:19: error: Name 'Python' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:22: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:25: error: Name 'Octave' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:29: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:32: error: Name 'Java' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:36: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:41: error: Name 'Csharp' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:8: error: Incompatible types in assignment (expression has type "bytes", variable has type "str")  [assignment]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:9: error: "str" has no attribute "decode"; maybe "encode"?  [attr-defined]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:20: error: Name 'oauth2_token' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:28: error: Name 'Request' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:31: error: Name 'oauth2_token' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:35: error: Name 'urlopen' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:87: error: Incompatible types in assignment (expression has type "object", variable has type "str")  [assignment]
(CoolProp)CoolProp/wrappers/Python/generate_meta_info.py:78: error: Incompatible types in assignment (expression has type "Template", variable has type "str")  [assignment]
(CoolProp)CoolProp/wrappers/Python/generate_meta_info.py:81: error: "str" has no attribute "render"  [attr-defined]
(CoolProp)CoolProp/wrappers/Python/generate_meta_info.py:148: error: Incompatible types in assignment (expression has type "Template", variable has type "str")  [assignment]
(CoolProp)CoolProp/wrappers/Python/generate_meta_info.py:151: error: "str" has no attribute "render"  [attr-defined]
Found 90 errors in 24 files (checked 59 source files)

[RRepo](alex-ta)Fontinator
(alex-ta)Fontinator/NeuralNet/Oli/libs/ProcessingPipeline.py:26: error: Syntax error in type annotation  [syntax]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ProcessingPipeline.py:26: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(alex-ta)Fontinator/NeuralNet/Oli/libs/ProcessingPipeline.py:44: error: Need type annotation for 'labels' (hint: "labels: List[<type>] = ...")  [var-annotated]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ImageLoader.py:10: error: Incompatible types in assignment (expression has type "None", variable has type "Path")  [assignment]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ImageLoader.py:11: error: Need type annotation for '_font_names' (hint: "_font_names: List[<type>] = ...")  [var-annotated]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ImageLoader.py:12: error: Need type annotation for '_img_count_per_font' (hint: "_img_count_per_font: List[<type>] = ...")  [var-annotated]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ImageLoader.py:40: error: Missing return statement  [return]
(alex-ta)Fontinator/DataGenerator/libs/WordDict.py:16: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:15: error: Incompatible types in assignment (expression has type "None", variable has type "Path")  [assignment]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:16: error: Incompatible types in assignment (expression has type "None", variable has type "Path")  [assignment]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:17: error: Incompatible types in assignment (expression has type "None", variable has type "Path")  [assignment]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:18: error: Incompatible types in assignment (expression has type "None", variable has type "Path")  [assignment]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:91: error: "List[Any]" has no attribute "tolist"  [attr-defined]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:93: error: "List[Any]" has no attribute "tolist"  [attr-defined]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:96: error: Argument 1 to "open" has incompatible type "Optional[Path]"; expected "Union[str, bytes, int, _PathLike[Any]]"  [arg-type]
Found 14 errors in 4 files (checked 15 source files)

[RRepo](c3nav)c3nav
(c3nav)c3nav/src/c3nav/api/__init__.py: error: Duplicate module named 'api' (also at '/home/bew/archive/typed_project/(c3nav)c3nav/src/c3nav/routing/api.py')  [misc]
Found 1 error in 1 file (checked 86 source files)

[RRepo](w1ll1am23)simplisafe-python
(w1ll1am23)simplisafe-python/tests/test_sensor.py:7: error: Module 'simplipy' has no attribute 'API'  [attr-defined]
(w1ll1am23)simplisafe-python/tests/test_api.py:11: error: Module 'simplipy' has no attribute 'API'  [attr-defined]
(w1ll1am23)simplisafe-python/tests/test_system.py:10: error: Module 'simplipy' has no attribute 'API'  [attr-defined]
(w1ll1am23)simplisafe-python/example.py:9: error: Module 'simplipy' has no attribute 'API'  [attr-defined]
Found 4 errors in 4 files (checked 11 source files)

[RRepo](gjbex)training-material
(gjbex)training-material/DataStorage/Hdf5/PythonSamples/compute_avg.py:10: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 260 source files)

[RRepo](numba)numba
(numba)numba/numba/typeconv/typeconv.py:6: error: No parent module -- cannot perform relative import  [misc]
(numba)numba/numba/typeconv/typeconv.py:18: error: No parent module -- cannot perform relative import  [misc]
(numba)numba/numba/typeconv/typeconv.py:19: error: No parent module -- cannot perform relative import  [misc]
Found 3 errors in 1 file (checked 445 source files)

[RRepo](project-everest)vale
(project-everest)vale/tools/scripts/collect-fstar-times.py:83: error: Missing parentheses in call to 'print'. Did you mean print("WARNING: Found existing pickled file %s.  No data written.  Consider moving or deleting it." % pickle_file)?  [syntax]
Found 1 error in 1 file (checked 2 source files)

[RRepo](yi-jiayu)bus-eta-bot
Success: no issues found in 2 source files

[RRepo](Tobotimus)Tobo-Cogs
(Tobotimus)Tobo-Cogs/register/register.py:47: error: Unsupported dynamic base class "getattr"  [misc]
(Tobotimus)Tobo-Cogs/filterhelp/formatter.py:58: error: Missing return statement  [return]
(Tobotimus)Tobo-Cogs/welcomecount/welcomecount.py:38: error: Unsupported dynamic base class "getattr"  [misc]
(Tobotimus)Tobo-Cogs/welcomecount/welcomecount.py:170: error: Name 'last_message' already defined on line 168  [no-redef]
(Tobotimus)Tobo-Cogs/welcomecount/welcomecount.py:177: error: "int" has no attribute "delete"  [attr-defined]
(Tobotimus)Tobo-Cogs/docref/types.py:184: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:191: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:192: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:193: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:196: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:197: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:198: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:199: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/reactkarma/reactkarma.py:38: error: Unsupported dynamic base class "getattr"  [misc]
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:53: error: Need type annotation for 'lines'  [var-annotated]
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:55: error: Need type annotation for 'new_lines'  [var-annotated]
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:55: error: Unsupported operand types for - ("None" and "int")  [operator]
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:55: note: Left operand is of type "Optional[int]"
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:62: error: Unsupported operand types for >= ("int" and "None")  [operator]
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:62: note: Right operand is of type "Optional[int]"
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:150: error: "None" has no attribute "delete"  [attr-defined]
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:154: error: "None" has no attribute "id"  [attr-defined]
(Tobotimus)Tobo-Cogs/updatered/updatered.py:40: error: Unsupported dynamic base class "getattr"  [misc]
(Tobotimus)Tobo-Cogs/errorlogs/errorlogs.py:123: error: Module has no attribute "create_task"  [attr-defined]
Found 22 errors in 8 files (checked 15 source files)

[RRepo](ranisalt)moita-ufsc-crawler
(ranisalt)moita-ufsc-crawler/moita/spiders/cagr.py:9: error: Relative import climbs too many namespaces  [misc]
(ranisalt)moita-ufsc-crawler/moita/spiders/cagr.py:24: error: Need type annotation for 'subject' (hint: "subject: Dict[<type>, <type>] = ...")  [var-annotated]
(ranisalt)moita-ufsc-crawler/moita/spiders/cagr.py:24: error: Need type annotation for 'campus'  [var-annotated]
(ranisalt)moita-ufsc-crawler/moita/spiders/cagr.py:25: error: Need type annotation for 'campi_names'  [var-annotated]
(ranisalt)moita-ufsc-crawler/moita/pipelines.py:25: error: Need type annotation for 'data'  [var-annotated]
Found 5 errors in 2 files (checked 2 source files)

[RRepo](HenriWahl)Nagstamon
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/protocol/structs.py:23: error: Module 'Xlib.protocol' has no attribute 'rq'  [attr-defined]
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/xobject/resource.py:19: error: Module 'Xlib.protocol' has no attribute 'request'  [attr-defined]
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/error.py:23: error: Module 'Xlib.protocol' has no attribute 'rq'  [attr-defined]
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/ext/composite.py:34: error: Module 'Xlib.protocol' has no attribute 'rq'  [attr-defined]
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/ext/composite.py:35: error: Module 'Xlib.xobject' has no attribute 'drawable'  [attr-defined]
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/ext/record.py:20: error: Module 'Xlib.protocol' has no attribute 'rq'  [attr-defined]
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/ext/xtest.py:20: error: Module 'Xlib.protocol' has no attribute 'rq'  [attr-defined]

[RRepo](seznam)fastrpc
(seznam)fastrpc/python/example/client_example2.py:13: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 15 source files)

[RRepo](lostatc)codot
(lostatc)codot/codot/commands/role.py:62: error: "None" has no attribute "dir_path"  [attr-defined]
(lostatc)codot/codot/commands/role.py:66: error: "None" has no attribute "get_configs"  [attr-defined]
(lostatc)codot/codot/commands/role.py:73: error: "None" has no attribute "selected"  [attr-defined]
(lostatc)codot/codot/commands/role.py:82: error: "None" has no attribute "get_config_by_name"  [attr-defined]
(lostatc)codot/codot/commands/rm_template.py:79: error: Need type annotation for 'template_identifiers' (hint: "template_identifiers: Set[<type>] = ...")  [var-annotated]
(lostatc)codot/codot/commands/list.py:90: error: List item 0 has incompatible type "Tuple[str]"; expected "Tuple[str, str]"  [list-item]
(lostatc)codot/codot/commands/list.py:92: error: Generator has incompatible item type "Tuple[str]"; expected "Tuple[str, str]"  [misc]
(lostatc)codot/codot/commandbase.py:69: error: Incompatible types in assignment (expression has type "socket", variable has type "None")  [assignment]
(lostatc)codot/codot/commandbase.py:71: error: "None" has no attribute "bind"  [attr-defined]
(lostatc)codot/codot/cli.py:165: error: Return type "None" of "error" incompatible with return type "NoReturn" in supertype "ArgumentParser"  [override]
(lostatc)codot/codot/container.py:59: error: Missing return statement  [return]
(lostatc)codot/codot/container.py:61: error: Value of type "Callable[..., Any]" is not indexable  [index]
(lostatc)codot/codot/container.py:70: error: Value of type "Callable[..., Any]" is not indexable  [index]
(lostatc)codot/codot/container.py:86: error: Name 'last_sync' already defined on line 72  [no-redef]
(lostatc)codot/codot/container.py:113: error: Need type annotation for 'raw_vals' (hint: "raw_vals: Dict[<type>, <type>] = ...")  [var-annotated]
(lostatc)codot/codot/container.py:120: error: Name 'vals' already defined on line 115  [no-redef]
(lostatc)codot/codot/container.py:126: error: Missing return statement  [return]
(lostatc)codot/codot/container.py:147: error: 'None' object is not iterable  [misc]
(lostatc)codot/codot/container.py:207: error: Need type annotation for '_req_keys' (hint: "_req_keys: List[<type>] = ...")  [var-annotated]
(lostatc)codot/codot/container.py:228: error: Name 'vals' already defined on line 220  [no-redef]
(lostatc)codot/codot/container.py:233: error: Missing return statement  [return]
(lostatc)codot/codot/container.py:293: error: Incompatible types in assignment (expression has type "Dict[<nothing>, <nothing>]", variable has type "None")  [assignment]
(lostatc)codot/codot/container.py:297: error: Unsupported target for indexed assignment  [index]
(lostatc)codot/codot/user_files.py:198: error: Need type annotation for 'config_values' (hint: "config_values: Dict[<type>, <type>] = ...")  [var-annotated]
(lostatc)codot/codot/user_files.py:226: error: Argument 1 to "isfile" has incompatible type "Optional[str]"; expected "Union[bytes, str, _PathLike[Any]]"  [arg-type]
(lostatc)codot/codot/utils.py:217: error: The return type of a generator function should be "Generator" or one of its supertypes  [misc]
(lostatc)codot/codot/utils.py:245: error: No overload variant of "next" matches argument type "str"  [call-overload]
(lostatc)codot/codot/utils.py:245: note: Possible overload variant:
(lostatc)codot/codot/utils.py:245: note:     def [_T] next(Iterator[_T]) -> _T
(lostatc)codot/codot/utils.py:245: note:     <1 more non-matching overload not shown>
Found 27 errors in 8 files (checked 12 source files)

[RRepo](pycrystem)pycrystem
(pycrystem)pycrystem/tests/test_signals/test_crystallographic_map.py:177: error: Name 'test_Crystallographic_Map_io' already defined on line 169  [no-redef]
(pycrystem)pycrystem/tests/test_physical/test_orientation_mapping_nonphys.py:41: error: Need type annotation for 'dp_sim_list' (hint: "dp_sim_list: List[<type>] = ...")  [var-annotated]
(pycrystem)pycrystem/tests/test_physical/test_orientation_mapping_nonphys.py:43: error: Need type annotation for 'library' (hint: "library: Dict[<type>, <type>] = ...")  [var-annotated]
(pycrystem)pycrystem/docs/source/conf.py:104: error: Need type annotation for 'exclude_patterns' (hint: "exclude_patterns: List[<type>] = ...")  [var-annotated]
(pycrystem)pycrystem/docs/source/conf.py:262: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
Found 5 errors in 3 files (checked 54 source files)

[RRepo](meng89)wpi
(meng89)wpi/wpi/__init__.py:5: error: Need type annotation for '_modules' (hint: "_modules: Dict[<type>, <type>] = ...")  [var-annotated]
(meng89)wpi/wpi/main.py:21: error: Argument 1 to "join" has incompatible type "Optional[str]"; expected "Union[str, _PathLike[str]]"  [arg-type]
(meng89)wpi/wpi/main.py:416: error: Not all arguments converted during string formatting  [str-format]
Found 3 errors in 2 files (checked 12 source files)

