[RRepo](argaen)aiocache
(argaen)aiocache/aiocache/serializers/serializers.py:10:5: error: Name 'json' already defined (by an import)  [no-redef]
(argaen)aiocache/aiocache/serializers/serializers.py:99:24: error: Incompatible types in assignment (expression has type "None", base class "BaseSerializer" defined the type as "str")  [assignment]
(argaen)aiocache/tests/acceptance/test_serializers.py:7:5: error: Name 'json' already defined (by an import)  [no-redef]
(argaen)aiocache/tests/acceptance/test_serializers.py:11:5: error: Name 'pickle' already defined (possibly by an import)  [no-redef]
(argaen)aiocache/aiocache/backends/redis.py:53:5: error: Need type annotation for 'pools' (hint: "pools: Dict[<type>, <type>] = ...")  [var-annotated]
(argaen)aiocache/aiocache/backends/memory.py:12:5: error: Need type annotation for '_cache' (hint: "_cache: Dict[<type>, <type>] = ...")  [var-annotated]
(argaen)aiocache/aiocache/backends/memory.py:13:5: error: Need type annotation for '_handlers' (hint: "_handlers: Dict[<type>, <type>] = ...")  [var-annotated]
(argaen)aiocache/aiocache/lock.py:64:5: error: Need type annotation for '_EVENTS' (hint: "_EVENTS: Dict[<type>, <type>] = ...")  [var-annotated]
Found 8 errors in 5 files (checked 36 source files)

[RRepo](thismachinechills)pyscreencapture
(thismachinechills)pyscreencapture/screenshot/get_window_id.py:26:31: error: Invalid index type "Iterable[str]" for "Dict[str, Any]"; expected type "str"  [index]
(thismachinechills)pyscreencapture/screenshot/get_window_id.py:43:9: error: Incompatible types in "yield" (actual type "Tuple[Union[Any, int], Union[Any, int], Union[Any, int]]", expected type "Tuple[int, str, str]")  [misc]
(thismachinechills)pyscreencapture/screenshot/get_window_id.py:53:15: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(thismachinechills)pyscreencapture/screenshot/get_window_id.py:54:31: error: Argument 1 to "get_window_info" has incompatible type "str"; expected "int"  [arg-type]
(thismachinechills)pyscreencapture/screenshot/screencapture.py:32:15: error: Incompatible types in assignment (expression has type "str", variable has type "Optional[List[str]]")  [assignment]
Found 5 errors in 2 files (checked 2 source files)

[RRepo](City-of-Helsinki)linkedevents
(City-of-Helsinki)linkedevents/events/tests/test_signals.py:5:1: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_auth.py:5:1: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_models.py:5:1: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/auth.py:42:18: error: Unsupported dynamic base class "get_user_model"  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_api.py:11:1: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_api.py:12:1: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_api.py:13:1: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_permissions.py:6:1: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_permissions.py:7:1: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/test_events_search.py:11:1: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/tests/conftest.py:28:1: error: Relative import climbs too many namespaces  [misc]
(City-of-Helsinki)linkedevents/events/renderers/docx.py:8:1: error: Module 'docx' has no attribute 'Document'  [attr-defined]
(City-of-Helsinki)linkedevents/linkedevents/settings.py:388:1: error: Need type annotation for 'AUTO_ENABLED_EXTENSIONS' (hint: "AUTO_ENABLED_EXTENSIONS: List[<type>] = ...")  [var-annotated]
Found 13 errors in 10 files (checked 62 source files)

[RRepo](trin5tensa)pigjar
(trin5tensa)pigjar/pigjar/payeesmenu.py:66:14: error: No overload variant of "fromkeys" of "dict" matches argument types "Tuple[str]", "str"  [call-overload]
(trin5tensa)pigjar/pigjar/payeesmenu.py:66:14: note: Possible overload variants:
(trin5tensa)pigjar/pigjar/payeesmenu.py:66:14: note:     def fromkeys() -> Dict[<nothing>, Any]
(trin5tensa)pigjar/pigjar/payeesmenu.py:66:14: note:     def [_S] fromkeys(value: _S) -> Dict[<nothing>, _S]
(trin5tensa)pigjar/pigjar/payeesmenu.py:77:13: error: Return value expected  [return-value]
(trin5tensa)pigjar/pigjar/payeesmenu.py:84:17: error: Return value expected  [return-value]
(trin5tensa)pigjar/pigjar/register.py:17:1: error: Module '__future__' has no attribute 'annotations'  [attr-defined]
(trin5tensa)pigjar/pigjar/observerpattern.py:94:5: error: Signature of "notify" incompatible with supertype "Observable"  [override]
(trin5tensa)pigjar/pigjar/pig.py:128:17: error: Incompatible types in assignment (expression has type "List[EventqItem]", target has type "Dict[Any, Any]")  [assignment]
(trin5tensa)pigjar/pigjar/pig.py:131:17: error: Incompatible types in assignment (expression has type "List[EventqItem]", target has type "Dict[Any, Any]")  [assignment]
(trin5tensa)pigjar/pigjar/pig.py:173:12: error: Name 'payee' is not defined  [name-defined]
(trin5tensa)pigjar/pigjar/pig.py:174:14: error: Name 'account' is not defined  [name-defined]
(trin5tensa)pigjar/pigjar/pig.py:248: error: The return type of a generator function should be "Generator" or one of its supertypes  [misc]
(trin5tensa)pigjar/pigjar/pig.py:269:17: error: Cannot infer type argument 1 of "heappush"  [misc]
(trin5tensa)pigjar/pigjar/cashflow.py:51:34: error: Incompatible types in assignment (expression has type "Tuple[None, None]", variable has type "Tuple[Decimal]")  [assignment]
(trin5tensa)pigjar/pigjar/cashflow.py:85:13: error: Unsupported target for indexed assignment  [index]
(trin5tensa)pigjar/pigjar/cashflow.py:86:39: error: Incompatible types in assignment (expression has type "Tuple[Any, Any]", variable has type "Tuple[Decimal]")  [assignment]
(trin5tensa)pigjar/pigjar/cashflow.py:110:42: error: No overload variant of "next" matches argument type "Tuple[Any, Decimal, Decimal]"  [call-overload]
(trin5tensa)pigjar/pigjar/cashflow.py:110:42: note: Possible overload variant:
(trin5tensa)pigjar/pigjar/cashflow.py:110:42: note:     def [_T] next(Iterator[_T]) -> _T
(trin5tensa)pigjar/pigjar/cashflow.py:110:42: note:     <1 more non-matching overload not shown>
(trin5tensa)pigjar/pigjar/cashflow.py:118:21: error: Unsupported target for indexed assignment  [index]
(trin5tensa)pigjar/pigjar/cashflow.py:119:21: error: Unsupported target for indexed assignment  [index]
(trin5tensa)pigjar/pigjar/cashflow.py:131:9: error: Need type annotation for 'spendq' (hint: "spendq: List[<type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/cashflow.py:132:9: error: Need type annotation for 'svgq' (hint: "svgq: List[<type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/impexp.py:95:5: error: Need type annotation for 'accounts_memo' (hint: "accounts_memo: Dict[<type>, <type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/impexp.py:96:5: error: Need type annotation for 'pigs_memo' (hint: "pigs_memo: Dict[<type>, <type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/impexp.py:97:5: error: Need type annotation for 'payees_memo' (hint: "payees_memo: Set[<type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/impexp.py:98:5: error: Need type annotation for 'assembler' (hint: "assembler: Dict[<type>, <type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/impexp.py:99:5: error: Need type annotation for 'clearances' (hint: "clearances: List[<type>] = ...")  [var-annotated]
(trin5tensa)pigjar/pigjar/impexp.py:229:20: error: Incompatible types in assignment (expression has type "Tuple[Any, Any, Any, Decimal]", variable has type "str")  [assignment]
(trin5tensa)pigjar/pigjar/impexp.py:266:12: error: Incompatible return value type (got "Tuple[Any, Optional[Any], Optional[Any]]", expected "Tuple[bool, bool, bool]")  [return-value]
(trin5tensa)pigjar/pigjar/impexp.py:305:12: error: Incompatible return value type (got "Tuple[Any, Optional[bool], Any]", expected "Tuple[bool, bool, Any]")  [return-value]
(trin5tensa)pigjar/pigjar/test/test_payeesmenu.py:42:23: error: No overload variant of "fromkeys" of "dict" matches argument types "Tuple[str]", "str"  [call-overload]
(trin5tensa)pigjar/pigjar/test/test_payeesmenu.py:42:23: note: Possible overload variants:
(trin5tensa)pigjar/pigjar/test/test_payeesmenu.py:42:23: note:     def fromkeys() -> Dict[<nothing>, Any]
(trin5tensa)pigjar/pigjar/test/test_payeesmenu.py:42:23: note:     def [_S] fromkeys(value: _S) -> Dict[<nothing>, _S]
(trin5tensa)pigjar/pigjar/userhandlers.py:16:1: error: Module '__future__' has no attribute 'annotations'  [attr-defined]
(trin5tensa)pigjar/pigjar/userhandlers.py:34: error: Name 'tk' is not defined  [name-defined]
(trin5tensa)pigjar/pigjar/userhandlers.py:230:28: error: Name 'guipanes' is not defined  [name-defined]
(trin5tensa)pigjar/pigjar/userhandlers.py:235:34: error: Name 'guipanes' is not defined  [name-defined]
(trin5tensa)pigjar/pigjar/guimainwindow.py:125:17: error: Incompatible types in assignment (expression has type "Pattern[str]", variable has type "str")  [assignment]
(trin5tensa)pigjar/pigjar/guimainwindow.py:128:13: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(trin5tensa)pigjar/pigjar/guimainwindow.py:131:13: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(trin5tensa)pigjar/pigjar/guimainwindow.py:151:18: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(trin5tensa)pigjar/pigjar/guimainwindow.py:152:18: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(trin5tensa)pigjar/pigjar/guimainwindow.py:153:35: error: Argument 1 to "abs" has incompatible type "str"; expected "SupportsAbs[<nothing>]"  [arg-type]
(trin5tensa)pigjar/pigjar/guimainwindow.py:154:21: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(trin5tensa)pigjar/pigjar/guimainwindow.py:159:22: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
(trin5tensa)pigjar/pigjar/guimainwindow.py:162:29: error: Numeric flags are only allowed for numeric types  [str-format]
(trin5tensa)pigjar/pigjar/guimainwindow.py:183:41: error: Argument 3 to "_place_menu_cascade" of "MainWindow" has incompatible type "Optional[Callable[..., Any]]"; expected "Callable[..., Any]"  [arg-type]
Found 42 errors in 9 files (checked 26 source files)

[RRepo](Berserker66)omnitool
(Berserker66)omnitool/omnitool/themes/Underworld/generate.py:85:44: error: Name 'SWSURFACE' is not defined  [name-defined]
(Berserker66)omnitool/omnitool/themes/Underworld/generate.py:85:56: error: Name 'SRCALPHA' is not defined  [name-defined]
(Berserker66)omnitool/omnitool/themes/Underworld/generate.py:92:22: error: "str" has no attribute "subsurface"  [attr-defined]
(Berserker66)omnitool/omnitool/themes/Underworld/generate.py:95:34: error: Unsupported left operand type for + ("None")  [operator]
(Berserker66)omnitool/omnitool/themes/Underworld/generate.py:95:41: note: Left operand is of type "Optional[str]"
(Berserker66)omnitool/omnitool/plugingui.py:88:5: error: Name 'run_rec' is not defined  [name-defined]
(Berserker66)omnitool/omnitool/relay.py:22:1: error: Module 'omnitool' has no attribute 'launch_plugin'  [attr-defined]
(Berserker66)omnitool/omnitool/relay.py:23:1: error: Module 'omnitool' has no attribute 'gen_slices'  [attr-defined]
(Berserker66)omnitool/omnitool/version.py:58:12: error: Unsupported operand types for < ("int" and "Version")  [operator]
(Berserker66)omnitool/omnitool/version.py:61:12: error: Unsupported operand types for < ("int" and "Version")  [operator]
(Berserker66)omnitool/omnitool/version.py:62:17: error: Unsupported operand types for < ("int" and "Version")  [operator]
(Berserker66)omnitool/omnitool/binarysplit.py:57:13: error: Name 'get_header' is not defined  [name-defined]
(Berserker66)omnitool/omnitool/binarysplit.py:59:9: error: Name 'set_header' is not defined  [name-defined]
(Berserker66)omnitool/plugins/tetris.py:10:9: error: Name 'K_LEFT' is not defined  [name-defined]
(Berserker66)omnitool/plugins/tetris.py:10:17: error: Name 'K_a' is not defined  [name-defined]
(Berserker66)omnitool/plugins/tetris.py:11:10: error: Name 'K_RIGHT' is not defined  [name-defined]
(Berserker66)omnitool/plugins/tetris.py:11:18: error: Name 'K_d' is not defined  [name-defined]
(Berserker66)omnitool/plugins/tetris.py:12:9: error: Name 'K_DOWN' is not defined  [name-defined]
(Berserker66)omnitool/plugins/tetris.py:12:17: error: Name 'K_d' is not defined  [name-defined]
(Berserker66)omnitool/plugins/tetris.py:13:13: error: Name 'K_SPACE' is not defined  [name-defined]
(Berserker66)omnitool/plugins/tetris.py:14:11: error: Name 'K_UP' is not defined  [name-defined]
(Berserker66)omnitool/plugins/tetris.py:14:17: error: Name 'K_w' is not defined  [name-defined]
(Berserker66)omnitool/plugins/tetris.py:21:5: error: Incompatible import of "TetrisConfig" (imported name has type "Type[tetris_lib.TetrisConfig]", local name has type "Type[plugins.tetris_lib.TetrisConfig]")  [misc]
(Berserker66)omnitool/plugins/tetris.py:277:17: error: Argument 1 to "run" has incompatible type "None"; expected "Program"  [arg-type]
(Berserker66)omnitool/worldview.py:7:1: error: Module 'tinterface' has no attribute 'get_header'  [attr-defined]
(Berserker66)omnitool/worldview.py:7:1: error: Module 'tinterface' has no attribute 'get_pointers'  [attr-defined]
(Berserker66)omnitool/worldview.py:164:19: error: Module has no attribute "windll"  [attr-defined]
(Berserker66)omnitool/worldview.py:186:13: error: Incompatible types in assignment (expression has type "Process", variable has type "str")  [assignment]
(Berserker66)omnitool/worldview.py:188:24: error: "str" has no attribute "is_alive"  [attr-defined]
(Berserker66)omnitool/worldview.py:190:17: error: Too few arguments for "join" of "str"  [call-arg]
(Berserker66)omnitool/worldview.py:191:34: error: Argument 1 to "remove" of "list" has incompatible type "str"; expected "Process"  [arg-type]
Found 30 errors in 7 files (checked 30 source files)

[RRepo](deepmind)bsuite
(deepmind)bsuite/bsuite/experiments/catch/catch.py:67:20: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(deepmind)bsuite/bsuite/experiments/catch/catch.py:68:22: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(deepmind)bsuite/bsuite/experiments/catch/catch.py:69:22: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(deepmind)bsuite/bsuite/experiments/catch/catch.py:80:30: error: Unsupported operand types for + ("None" and "int")  [operator]
(deepmind)bsuite/bsuite/experiments/catch/catch.py:83:5: error: Unsupported operand types for + ("None" and "int")  [operator]
(deepmind)bsuite/bsuite/experiments/catch/catch.py:83:5: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(deepmind)bsuite/bsuite/baselines/utils/replay.py:48:27: error: Argument 1 to "zip" has incompatible type "Optional[Sequence[Any]]"; expected "Iterable[Any]"  [arg-type]
(deepmind)bsuite/bsuite/baselines/utils/replay.py:56:39: error: Item "None" of "Optional[Sequence[Any]]" has no attribute "__iter__" (not iterable)  [union-attr]
(deepmind)bsuite/bsuite/utils/plotting.py:109:17: error: Incompatible types in assignment (expression has type "Tuple[int, float]", variable has type "Tuple[int, int]")  [assignment]
(deepmind)bsuite/bsuite/utils/plotting.py:187:16: error: Unsupported left operand type for + ("Sequence[str]")  [operator]
(deepmind)bsuite/bsuite/utils/plotting.py:258:24: error: "_make_unique_group_col" does not return a value  [func-returns-value]
(deepmind)bsuite/bsuite/utils/gym_wrapper.py:52:3: error: Missing return statement  [return]
(deepmind)bsuite/bsuite/utils/gym_wrapper.py:63:7: error: "None" has no attribute "imshow"  [attr-defined]
(deepmind)bsuite/bsuite/utils/gym_wrapper.py:64:14: error: "None" has no attribute "isopen"  [attr-defined]
(deepmind)bsuite/bsuite/sweep.py:78:10: error: Incompatible return value type (got "Tuple[Any, ...]", expected "Tuple[str]")  [return-value]
(deepmind)bsuite/bsuite/logging/terminal_logging.py:55:14: error: Incompatible types in assignment (expression has type "str", variable has type "Mapping[str, Any]")  [assignment]
(deepmind)bsuite/bsuite/logging/terminal_logging.py:63:12: error: Incompatible types in string interpolation (expression has type "Real", placeholder has type "Union[int, float]")  [str-format]
(deepmind)bsuite/bsuite/bsuite.py:20:1: error: Module 'bsuite' has no attribute 'sweep'  [attr-defined]
(deepmind)bsuite/bsuite/tests/environments_test.py:23:1: error: Module 'bsuite' has no attribute 'bsuite'  [attr-defined]
(deepmind)bsuite/bsuite/logging/csv_logging.py:66:5: error: Need type annotation for '_data' (hint: "_data: List[<type>] = ...")  [var-annotated]
(deepmind)bsuite/bsuite/baselines/dqn_jax/run.py:23:1: error: Module 'bsuite' has no attribute 'bsuite'  [attr-defined]
(deepmind)bsuite/bsuite/logging/sqlite_logging.py:96:32: error: Incompatible types in assignment (expression has type "str", variable has type "None")  [assignment]
(deepmind)bsuite/bsuite/logging/sqlite_logging.py:101:34: error: Argument 1 to "execute" of "Connection" has incompatible type "None"; expected "str"  [arg-type]
(deepmind)bsuite/bsuite/logging/sqlite_logging.py:102:56: error: "None" has no attribute "__iter__" (not iterable)  [attr-defined]
(deepmind)bsuite/bsuite/logging/sqlite_logging.py:121:18: error: Incompatible types in assignment (expression has type "List[str]", variable has type "None")  [assignment]
Found 25 errors in 11 files (checked 80 source files)

[RRepo](Twinters007)robotpy-wpilib-utilities
(Twinters007)robotpy-wpilib-utilities/tests/magicbot_annotation_tester.py:113:26: error: Incompatible types in assignment (expression has type "None", variable has type "float")  [assignment]
(Twinters007)robotpy-wpilib-utilities/robotpy_ext/autonomous/selector.py:10:1: error: Relative import climbs too many namespaces  [misc]
(Twinters007)robotpy-wpilib-utilities/robotpy_ext/misc/asyncio_policy.py:10:26: error: Variable "asyncio.SelectorEventLoop" is not valid as a type  [valid-type]
(Twinters007)robotpy-wpilib-utilities/robotpy_ext/misc/asyncio_policy.py:10:26: error: Invalid base class "SelectorEventLoop"  [misc]
Found 4 errors in 3 files (checked 42 source files)

[RRepo](kenkov)smt
Success: no issues found in 12 source files

[RRepo](PayloadSecurity)VxAPI
(PayloadSecurity)VxAPI/api/callers/api_caller.py:27:5: error: Need type annotation for 'data' (hint: "data: Dict[<type>, <type>] = ...")  [var-annotated]
(PayloadSecurity)VxAPI/api/callers/api_caller.py:28:5: error: Need type annotation for 'params' (hint: "params: Dict[<type>, <type>] = ...")  [var-annotated]
(PayloadSecurity)VxAPI/api/callers/api_caller.py:29:5: error: Need type annotation for 'files' (hint: "files: Dict[<type>, <type>] = ...")  [var-annotated]
(PayloadSecurity)VxAPI/api/callers/api_caller.py:40:5: error: Need type annotation for 'api_response_json' (hint: "api_response_json: Dict[<type>, <type>] = ...")  [var-annotated]
(PayloadSecurity)VxAPI/tests/base_test.py:65:16: error: Not all arguments converted during string formatting  [str-format]

/
h
o
m
e
/
b
e
w
/
a
r
c
h
i
v
e
/
t
y
p
e
d
_
p
r
o
j
e
c
t
/
(
P
a
y
l
o
a
d
S
e
c
u
r
i
t
y
)
V
x
A
P
I
/
a
p
i
/
c
a
l
l
e
r
s
/
a
p
i
_
c
a
l
l
e
r
.
p
y
:
9
:
 
e
r
r
o
r
:
 
I
N
T
E
R
N
A
L
 
E
R
R
O
R
 
-
-
 
P
l
e
a
s
e
 
t
r
y
 
u
s
i
n
g
 
m
y
p
y
 
m
a
s
t
e
r
 
o
n
 
G
i
t
h
u
b
:


h
t
t
p
s
:
/
/
m
y
p
y
.
r
t
f
d
.
i
o
/
e
n
/
l
a
t
e
s
t
/
c
o
m
m
o
n
_
i
s
s
u
e
s
.
h
t
m
l
#
u
s
i
n
g
-
a
-
d
e
v
e
l
o
p
m
e
n
t
-
m
y
p
y
-
b
u
i
l
d


I
f
 
t
h
i
s
 
i
s
s
u
e
 
c
o
n
t
i
n
u
e
s
 
w
i
t
h
 
m
y
p
y
 
m
a
s
t
e
r
,
 
p
l
e
a
s
e
 
r
e
p
o
r
t
 
a
 
b
u
g
 
a
t
 
h
t
t
p
s
:
/
/
g
i
t
h
u
b
.
c
o
m
/
p
y
t
h
o
n
/
m
y
p
y
/
i
s
s
u
e
s


v
e
r
s
i
o
n
:
 
0
.
7
6
1


/
h
o
m
e
/
b
e
w
/
a
r
c
h
i
v
e
/
t
y
p
e
d
_
p
r
o
j
e
c
t
/
(
P
a
y
l
o
a
d
S
e
c
u
r
i
t
y
)
V
x
A
P
I
/
a
p
i
/
c
a
l
l
e
r
s
/
a
p
i
_
c
a
l
l
e
r
.
p
y
:
9
:
 
:
 
n
o
t
e
:
 
p
l
e
a
s
e
 
u
s
e
 
-
-
s
h
o
w
-
t
r
a
c
e
b
a
c
k
 
t
o
 
p
r
i
n
t
 
a
 
t
r
a
c
e
b
a
c
k
 
w
h
e
n
 
r
e
p
o
r
t
i
n
g
 
a
 
b
u
g


[RRepo](StoDevX)cs251-toolkit
(StoDevX)cs251-toolkit/cs251tk/student/markdownify/process_file.py:33:9: error: Not all arguments converted during string formatting  [str-format]
(StoDevX)cs251-toolkit/cs251tk/student/markdownify/markdownify.py:7:1: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/formatters/base.py:25:15: error: Need type annotation for 'results'  [var-annotated]
(StoDevX)cs251-toolkit/cs251tk/webapp/web_cli.py:3:1: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/webapp/web_cli.py:4:1: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/webapp/web_cli.py:5:1: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/specs/load.py:8:1: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/toolkit/__main__.py:10:1: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/toolkit/__main__.py:11:1: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/toolkit/__main__.py:12:1: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/toolkit/__main__.py:19:1: error: Relative import climbs too many namespaces  [misc]
(StoDevX)cs251-toolkit/cs251tk/toolkit/__main__.py:20:1: error: Relative import climbs too many namespaces  [misc]
Found 12 errors in 6 files (checked 62 source files)

[RRepo](jeffmahoney)crash-python
(jeffmahoney)crash-python/contrib/mods.py:27:43: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 83 source files)

[RRepo](tmerr)bank_wrangler
(tmerr)bank_wrangler/bank_wrangler/bank_wrangler.py:12:1: error: Module 'bank_wrangler' has no attribute 'aggregate'  [attr-defined]
(tmerr)bank_wrangler/bank_wrangler/bank_wrangler.py:12:1: error: Module 'bank_wrangler' has no attribute 'deduplicate'  [attr-defined]
(tmerr)bank_wrangler/bank_wrangler/bank_wrangler.py:12:1: error: Module 'bank_wrangler' has no attribute 'rules'  [attr-defined]
(tmerr)bank_wrangler/bank_wrangler/bank_wrangler.py:12:1: error: Module 'bank_wrangler' has no attribute 'report'  [attr-defined]
(tmerr)bank_wrangler/bank_wrangler/rules.py:5:1: error: Module 'bank_wrangler' has no attribute 'tresult'  [attr-defined]
(tmerr)bank_wrangler/bank_wrangler/report/__init__.py:81:26: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[str], AnyStr]"  [arg-type]
(tmerr)bank_wrangler/bank_wrangler/report/__init__.py:82:25: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[str], AnyStr]"  [arg-type]
(tmerr)bank_wrangler/bank_wrangler/report/__init__.py:82:57: error: List item 0 has incompatible type "str"; expected "AnyStr"  [list-item]
Found 8 errors in 3 files (checked 21 source files)

[RRepo](telminov)django-voximplant
Success: no issues found in 1 source file

[RRepo](X-DataInitiative)tick
(X-DataInitiative)tick/tick/survival/build/__init__.py: error: Duplicate module named 'build' (also at '/home/bew/archive/typed_project/(X-DataInitiative)tick/tick/hawkes/model/build/__init__.py')  [misc]
(X-DataInitiative)tick/tick/survival/build/__init__.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 207 source files)

[RRepo](Microsoft)PTVS
(Microsoft)PTVS/Python/Tests/TestData/Copy of SteppingTest4.py:3:10: error: Missing parentheses in call to 'print'. Did you mean print(i)?  [syntax]
Found 1 error in 1 file (checked 519 source files)

[RRepo](mabuchilab)QNET
(mabuchilab)QNET/src/qnet/printing/_precedence.py:3:1: error: Need type annotation for '__all__' (hint: "__all__: List[<type>] = ...")  [var-annotated]
(mabuchilab)QNET/src/qnet/utils/permutations.py:1:1: error: Need type annotation for '__all__' (hint: "__all__: List[<type>] = ...")  [var-annotated]

/
h
o
m
e
/
b
e
w
/
a
r
c
h
i
v
e
/
t
y
p
e
d
_
p
r
o
j
e
c
t
/
(
m
a
b
u
c
h
i
l
a
b
)
Q
N
E
T
/
s
r
c
/
q
n
e
t
/
p
r
i
n
t
i
n
g
/
_
p
r
e
c
e
d
e
n
c
e
.
p
y
:
 
e
r
r
o
r
:
 
I
N
T
E
R
N
A
L
 
E
R
R
O
R
 
-
-
 
P
l
e
a
s
e
 
t
r
y
 
u
s
i
n
g
 
m
y
p
y
 
m
a
s
t
e
r
 
o
n
 
G
i
t
h
u
b
:


h
t
t
p
s
:
/
/
m
y
p
y
.
r
t
f
d
.
i
o
/
e
n
/
l
a
t
e
s
t
/
c
o
m
m
o
n
_
i
s
s
u
e
s
.
h
t
m
l
#
u
s
i
n
g
-
a
-
d
e
v
e
l
o
p
m
e
n
t
-
m
y
p
y
-
b
u
i
l
d


I
f
 
t
h
i
s
 
i
s
s
u
e
 
c
o
n
t
i
n
u
e
s
 
w
i
t
h
 
m
y
p
y
 
m
a
s
t
e
r
,
 
p
l
e
a
s
e
 
r
e
p
o
r
t
 
a
 
b
u
g
 
a
t
 
h
t
t
p
s
:
/
/
g
i
t
h
u
b
.
c
o
m
/
p
y
t
h
o
n
/
m
y
p
y
/
i
s
s
u
e
s


v
e
r
s
i
o
n
:
 
0
.
7
6
1


/
h
o
m
e
/
b
e
w
/
a
r
c
h
i
v
e
/
t
y
p
e
d
_
p
r
o
j
e
c
t
/
(
m
a
b
u
c
h
i
l
a
b
)
Q
N
E
T
/
s
r
c
/
q
n
e
t
/
p
r
i
n
t
i
n
g
/
_
p
r
e
c
e
d
e
n
c
e
.
p
y
:
 
:
 
n
o
t
e
:
 
p
l
e
a
s
e
 
u
s
e
 
-
-
s
h
o
w
-
t
r
a
c
e
b
a
c
k
 
t
o
 
p
r
i
n
t
 
a
 
t
r
a
c
e
b
a
c
k
 
w
h
e
n
 
r
e
p
o
r
t
i
n
g
 
a
 
b
u
g


[RRepo](NB0174)AbricotGame
(NB0174)AbricotGame/serveur/pathfinding.py:123:9: error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "int")  [assignment]
(NB0174)AbricotGame/serveur/pathfinding.py:205:9: error: Need type annotation for 'open_list' (hint: "open_list: List[<type>] = ...")  [var-annotated]
(NB0174)AbricotGame/serveur/pathfinding.py:207:9: error: Need type annotation for 'closed_list' (hint: "closed_list: Set[<type>] = ...")  [var-annotated]
(NB0174)AbricotGame/serveur/pathfinding.py:208:9: error: Need type annotation for 'all_cells' (hint: "all_cells: List[<type>] = ...")  [var-annotated]
(NB0174)AbricotGame/serveur/pathfinding.py:318:12: error: Incompatible return value type (got "Optional[Tuple[int, int]]", expected "Tuple[int, int]")  [return-value]
(NB0174)AbricotGame/serveur/commandes.py:7:55: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:7:55: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:7:69: error: Name 'List' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:7:69: note: Did you forget to import it from "typing"? (Suggestion: "from typing import List")
(NB0174)AbricotGame/serveur/commandes.py:13:33: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:15:33: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:17:33: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:19:33: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:22:20: error: Name 'MAPS' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:26:42: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:26:42: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:26:51: error: Name 'Tuple' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:26:51: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Tuple")
(NB0174)AbricotGame/serveur/commandes.py:28:14: error: Name 'Joueur' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:30:11: error: Name 'MAPS' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:38:1: error: Missing return statement  [return]
(NB0174)AbricotGame/serveur/commandes.py:38:36: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:38:36: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:43:27: error: Name 'MAPS' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:48:16: error: Incompatible types in assignment (expression has type "List[<nothing>]", variable has type "Dict[str, Any]")  [assignment]
(NB0174)AbricotGame/serveur/commandes.py:49:24: error: Name 'MAPS' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:50:13: error: "Dict[str, Any]" has no attribute "append"  [attr-defined]
(NB0174)AbricotGame/serveur/commandes.py:54:28: error: Name 'List' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:54:28: note: Did you forget to import it from "typing"? (Suggestion: "from typing import List")
(NB0174)AbricotGame/serveur/commandes.py:54:61: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:54:61: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:54:85: error: Name 'Tuple' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:54:85: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Tuple")
(NB0174)AbricotGame/serveur/commandes.py:66:21: error: Name 'MAPS' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:72:38: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:72:38: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:89:62: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:89:62: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:95:33: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:97:33: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:99:33: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:101:33: error: Name 'Mouvements' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:107:48: error: Name 'Tuple' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:107:48: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Tuple")
(NB0174)AbricotGame/serveur/commandes.py:107:74: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:107:74: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/commandes.py:112:16: error: Name 'SPELLS' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:112:27: error: "str" has no attribute "classe"  [attr-defined]
(NB0174)AbricotGame/serveur/commandes.py:113:12: error: "str" has no attribute "verif_conditions"  [attr-defined]
(NB0174)AbricotGame/serveur/commandes.py:114:22: error: "str" has no attribute "liste_case"  [attr-defined]
(NB0174)AbricotGame/serveur/commandes.py:115:22: error: "str" has no attribute "combat"  [attr-defined]
(NB0174)AbricotGame/serveur/commandes.py:117:48: error: "str" has no attribute "appliquer_effet"  [attr-defined]
(NB0174)AbricotGame/serveur/commandes.py:122:29: error: Name 'List' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:122:29: note: Did you forget to import it from "typing"? (Suggestion: "from typing import List")
(NB0174)AbricotGame/serveur/commandes.py:122:52: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/commandes.py:122:52: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/main.py:37:10: error: Name 'Dict' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/main.py:37:10: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
(NB0174)AbricotGame/serveur/main.py:37:16: error: Name 'List' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/main.py:37:16: note: Did you forget to import it from "typing"? (Suggestion: "from typing import List")
(NB0174)AbricotGame/serveur/main.py:37:93: error: Name 'Tuple' is not defined  [name-defined]
(NB0174)AbricotGame/serveur/main.py:37:93: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Tuple")
(NB0174)AbricotGame/serveur/main.py:50:14: error: Name 'MAPS' is not defined  [name-defined]
(NB0174)AbricotGame/launcher/client_part/updat.py:123:15: error: Incompatible types in assignment (expression has type "int", variable has type "str")  [assignment]
Found 47 errors in 4 files (checked 6 source files)

[RRepo](henridwyer)pyhomekit
(henridwyer)pyhomekit/pyhomekit/constants.py:69:26: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
Found 1 error in 1 file (checked 3 source files)

[RRepo](turbinenreiter)micropython
(turbinenreiter)micropython/tests/micropython/viper_args.py:3:2: error: Name 'micropython' is not defined  [name-defined]
(turbinenreiter)micropython/tests/micropython/viper_args.py:8:2: error: Name 'micropython' is not defined  [name-defined]
(turbinenreiter)micropython/tests/micropython/viper_args.py:13:2: error: Name 'micropython' is not defined  [name-defined]
(turbinenreiter)micropython/tests/micropython/viper_args.py:18:2: error: Name 'micropython' is not defined  [name-defined]
(turbinenreiter)micropython/tests/micropython/viper_args.py:23:2: error: Name 'micropython' is not defined  [name-defined]
(turbinenreiter)micropython/tests/cmdline/cmd_showbc.py:121:1: error: Name 'f' already defined on line 4  [no-redef]
(turbinenreiter)micropython/tests/cmdline/cmd_showbc.py:128:1: error: Name 'f' already defined on line 4  [no-redef]
(turbinenreiter)micropython/tests/basics/fun_calldblstar3.py:16:1: error: Argument after ** must be a mapping, not "Mapping"  [misc]
(turbinenreiter)micropython/tests/basics/boundmeth1.py:19:5: error: Incompatible types in assignment (expression has type "Callable[[Any], Any]", variable has type "Callable[[], Any]")  [assignment]
(turbinenreiter)micropython/tests/basics/boundmeth1.py:20:7: error: Too many arguments  [call-arg]
(turbinenreiter)micropython/tests/basics/boundmeth1.py:23:5: error: Incompatible types in assignment (expression has type "Callable[[Any, Any, Any, Any, Any, Any], Any]", variable has type "Callable[[], Any]")  [assignment]
(turbinenreiter)micropython/tests/basics/boundmeth1.py:24:7: error: Too many arguments  [call-arg]
(turbinenreiter)micropython/tests/basics/builtin_reversed.py:32:10: error: No overload variant of "reversed" matches argument type "A"  [call-overload]
(turbinenreiter)micropython/tests/basics/builtin_reversed.py:32:10: note: Possible overload variants:
(turbinenreiter)micropython/tests/basics/builtin_reversed.py:32:10: note:     def [_T] reversed(Sequence[_T]) -> Iterator[_T]
(turbinenreiter)micropython/tests/basics/builtin_reversed.py:32:10: note:     def [_T] reversed(Reversible[_T]) -> Iterator[_T]
(turbinenreiter)micropython/tests/basics/iter1.py:7:14: error: "NotIterable" has no attribute "__iter__" (not iterable)  [attr-defined]
(turbinenreiter)micropython/tests/basics/int1.py:87:5: error: No overload variant of "int" matches argument type "List[<nothing>]"  [call-overload]
(turbinenreiter)micropython/tests/basics/int1.py:87:5: note: Possible overload variant:
(turbinenreiter)micropython/tests/basics/int1.py:87:5: note:     def int(self, x: Union[str, bytes, SupportsInt, _SupportsIndex] = ...) -> int
(turbinenreiter)micropython/tests/basics/int1.py:87:5: note:     <1 more non-matching overload not shown>
(turbinenreiter)micropython/tests/basics/try2.py:7:9: error: Name 'foo' is not defined  [name-defined]
(turbinenreiter)micropython/tests/basics/try2.py:10:5: error: Name 'bar' is not defined  [name-defined]
(turbinenreiter)micropython/tests/basics/try2.py:18:9: error: Name 'foo' is not defined  [name-defined]
(turbinenreiter)micropython/tests/basics/try2.py:21:5: error: Name 'bar' is not defined  [name-defined]
(turbinenreiter)micropython/tests/basics/class_store_class.py:8:5: error: Name 'namedtuple' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/basics/class_store_class.py:27:1: error: "Type[DefragResult]" has no attribute "_encoded_counterpart"  [attr-defined]
(turbinenreiter)micropython/tests/basics/class_store_class.py:28:1: error: "Type[DefragResultBytes]" has no attribute "_decoded_counterpart"  [attr-defined]
(turbinenreiter)micropython/tests/basics/del_global.py:25:11: error: Trying to read deleted variable 'a'  [misc]
(turbinenreiter)micropython/tests/basics/del_global.py:33:11: error: Trying to read deleted variable 'a'  [misc]
(turbinenreiter)micropython/tests/basics/del_global.py:37:11: error: Trying to read deleted variable 'b'  [misc]
(turbinenreiter)micropython/tests/basics/del_global.py:46:11: error: Trying to read deleted variable 'a'  [misc]
(turbinenreiter)micropython/tests/basics/del_global.py:50:11: error: Trying to read deleted variable 'b'  [misc]
(turbinenreiter)micropython/tests/basics/del_global.py:54:11: error: Trying to read deleted variable 'c'  [misc]
(turbinenreiter)micropython/tests/basics/class_super_object.py:15:5: error: Incompatible types in assignment (expression has type "Test2", variable has type "Test")  [assignment]
(turbinenreiter)micropython/tests/basics/builtin_property.py:5:10: error: Argument 1 to "property" has incompatible type "int"; expected "Optional[Callable[[Any], Any]]"  [arg-type]
(turbinenreiter)micropython/tests/basics/builtin_property.py:5:13: error: Argument 2 to "property" has incompatible type "int"; expected "Optional[Callable[[Any, Any], None]]"  [arg-type]
(turbinenreiter)micropython/tests/basics/builtin_property.py:5:16: error: Argument 3 to "property" has incompatible type "int"; expected "Optional[Callable[[Any], None]]"  [arg-type]
(turbinenreiter)micropython/tests/basics/builtin_property.py:9:10: error: Argument 1 to "getter" of "property" has incompatible type "int"; expected "Callable[[Any], Any]"  [arg-type]
(turbinenreiter)micropython/tests/basics/builtin_property.py:10:10: error: Argument 1 to "setter" of "property" has incompatible type "int"; expected "Callable[[Any, Any], None]"  [arg-type]
(turbinenreiter)micropython/tests/basics/builtin_property.py:11:11: error: Argument 1 to "deleter" of "property" has incompatible type "int"; expected "Callable[[Any], None]"  [arg-type]
(turbinenreiter)micropython/tests/basics/builtin_property.py:27:5: error: Property "x" defined in "A" is read-only  [misc]
(turbinenreiter)micropython/tests/basics/object_new.py:24:20: error: Argument 1 to "__new__" of "object" has incompatible type "int"; expected "Type[object]"  [arg-type]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:7:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:8:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:9:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:10:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:11:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:12:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:13:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:14:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:15:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:16:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:17:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:18:13: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:21:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:22:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:23:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:24:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:27:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:28:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:29:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:30:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:31:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:32:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:33:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:36:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:37:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:38:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:41:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:44:16: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:45:16: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:46:16: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:47:16: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:48:16: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/nrf24l01/nrf24l01.py:49:16: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/esp8266/modules/onewire.py:10:18: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/esp8266/modules/onewire.py:11:17: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/esp8266/modules/onewire.py:12:16: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/esp8266/modules/ds18x20.py:4:12: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/esp8266/modules/ds18x20.py:5:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/esp8266/modules/ds18x20.py:6:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:20:17: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:21:20: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:22:17: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:23:14: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:24:14: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:25:14: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:26:14: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:28:25: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:29:27: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:31:17: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:33:24: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:34:26: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:35:26: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:37:26: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/stmhal/boards/STM32F4DISC/staccel.py:38:26: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/tests/misc/print_exception.py:4:5: error: Name 'io' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/misc/print_exception.py:7:23: error: Module has no attribute "print_exception"  [attr-defined]
(turbinenreiter)micropython/tests/micropython/viper_misc.py:12:12: error: Unsupported left operand type for + ("object")  [operator]
(turbinenreiter)micropython/tests/micropython/viper_misc.py:18:12: error: Incompatible return value type (got "None", expected "int")  [return-value]
(turbinenreiter)micropython/tests/micropython/viper_misc.py:55:21: error: Name 'uint' is not defined  [name-defined]
(turbinenreiter)micropython/tests/micropython/viper_misc.py:56:12: error: Name 'uint' is not defined  [name-defined]
(turbinenreiter)micropython/tests/micropython/viper_misc.py:75:30: error: Name 'gl' is not defined  [name-defined]
(turbinenreiter)micropython/tests/extmod/uheapq1.py:4:5: error: Name 'heapq' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/uheapq1.py:22:1: error: Need type annotation for 'h' (hint: "h: List[<type>] = ...")  [var-annotated]
(turbinenreiter)micropython/cc3200/tools/smoke.py:50:15: error: Argument 1 to "write" of "IO" has incompatible type "bytes"; expected "str"  [arg-type]
(turbinenreiter)micropython/cc3200/tools/smoke.py:54:11: error: "TextIO" has no attribute "readall"  [attr-defined]
(turbinenreiter)micropython/cc3200/tools/smoke.py:72:1: error: Module has no attribute "sleep_ms"; maybe "sleep"?  [attr-defined]
(turbinenreiter)micropython/drivers/sdcard/sdcard.py:27:16: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/sdcard/sdcard.py:29:18: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/sdcard/sdcard.py:31:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/sdcard/sdcard.py:36:16: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/sdcard/sdcard.py:37:20: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/sdcard/sdcard.py:38:15: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:8:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:9:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:10:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:11:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:12:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:13:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:14:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:15:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:16:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:17:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:18:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:19:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:20:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:21:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:22:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:23:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/drivers/display/ssd1306.py:24:23: error: Name 'const' is not defined  [name-defined]
(turbinenreiter)micropython/tests/float/float2int.py:6:5: error: Name 'struct' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/float/float2int_doubleprec.py:6:5: error: Name 'struct' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/float/float2int_fp30.py:6:5: error: Name 'struct' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/thread/thread_start2.py:8:5: error: Name 'time' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/thread/thread_lock4.py:30:1: error: Need type annotation for 'output' (hint: "output: List[<type>] = ...")  [var-annotated]
(turbinenreiter)micropython/tests/thread/stress_aes.py:207:5: error: Name 'time' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ure_namedclass.py:6:5: error: Name 're' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ure_group.py:6:5: error: Name 're' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ujson_loads.py:4:5: error: Name 'json' already defined (by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ure_error.py:6:5: error: Name 're' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ujson_loads_float.py:4:5: error: Name 'json' already defined (by an import)  [no-redef]
(turbinenreiter)micropython/examples/network/http_client.py:4:5: error: Name 'socket' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/examples/network/http_server_simplistic.py:4:5: error: Name 'socket' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/py/makeqstrdefs.py:20:18: error: Incompatible types in assignment (expression has type "Type[bytes]", variable has type "Callable[[Any, Any], bytearray]")  [assignment]
(turbinenreiter)micropython/tools/pyboard.py:47:14: error: Incompatible types in assignment (expression has type "TextIO", variable has type "BinaryIO")  [assignment]
(turbinenreiter)micropython/docs/sphinx_selective_exclude/modindex_exclude.py:23:1: error: Need type annotation for 'EXCLUDES' (hint: "EXCLUDES: Dict[<type>, <type>] = ...")  [var-annotated]
Found 142 errors in 39 files (checked 95 source files)

[RRepo](bagage)cadastre-conflation
Success: no issues found in 8 source files

[RRepo](languitar)autosuspend
Success: no issues found in 11 source files

[RRepo](a-slide)pycoQC
(a-slide)pycoQC/pycoQC/pycoQC_parse.py:58:23: error: Name 'get_logger' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:16:1: error: Module 'pycoQC' has no attribute '__version__'  [attr-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:90:14: error: Name 'get_logger' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:94:18: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:95:26: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:96:27: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:97:21: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:98:14: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:99:20: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:100:20: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:101:20: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:102:19: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:103:21: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:104:20: error: Name 'check_arg' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:107:18: error: Name 'dict_to_str' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC.py:109:18: error: Name 'dict_to_str' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/common.py:92:18: error: Invalid conversion specifier in format string: unexpected }  [str-format]
(a-slide)pycoQC/pycoQC/common.py:215:14: error: Invalid type comment or annotation  [valid-type]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:77:23: error: Invalid type comment or annotation  [valid-type]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:79:16: error: Invalid type comment or annotation  [valid-type]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:112:19: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:114:19: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:116:19: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:119:23: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:132:16: error: Need type annotation for 'in_q'  [var-annotated]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:133:17: error: Need type annotation for 'out_q'  [var-annotated]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:134:19: error: Need type annotation for 'error_q'  [var-annotated]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:135:21: error: Need type annotation for 'counter_q'  [var-annotated]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:151:13: error: Need type annotation for 'tb'  [var-annotated]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:152:23: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/Fast5_to_seq_summary.py:158:53: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/__main__.py:21:1: error: Module 'pycoQC' has no attribute '__version__'  [attr-defined]
(a-slide)pycoQC/pycoQC/pycoQC_report.py:17:1: error: Module 'pycoQC' has no attribute '__version__'  [attr-defined]
(a-slide)pycoQC/pycoQC/pycoQC_report.py:52:23: error: Name 'get_logger' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC_report.py:57:19: error: Name 'pycoQCError' is not defined  [name-defined]
(a-slide)pycoQC/pycoQC/pycoQC_report.py:107:20: error: Name 'pycoQCError' is not defined  [name-defined]
Found 36 errors in 6 files (checked 6 source files)

[RRepo](consbio)seedsource
(consbio)seedsource/source/socket_logging/management/commands/run_logging_server.py:46:27: error: Incompatible types in assignment (expression has type "int", base class "BaseServer" defined the type as "bool")  [assignment]
Found 1 error in 1 file (checked 20 source files)

[RRepo](benchmeeting)booking
Success: no issues found in 3 source files

[RRepo](Nocturnal42)runmyrobot
(Nocturnal42)runmyrobot/hardware/pololu.py:5:90: error: unindent does not match any outer indentation level  [syntax]
Found 1 error in 1 file (checked 33 source files)

[RRepo](boriel)zxbasic
(boriel)zxbasic/api/opcodestemps.py:18:1: error: "__Singleton" has no attribute "table"  [attr-defined]
(boriel)zxbasic/api/opcodestemps.py:19:1: error: "__Singleton" has no attribute "count"  [attr-defined]
(boriel)zxbasic/arch/zx48k/backend/__common.py:8:1: error: Need type annotation for 'MEMORY' (hint: "MEMORY: List[<type>] = ...")  [var-annotated]
(boriel)zxbasic/arch/zx48k/backend/__common.py:15:1: error: Need type annotation for 'TMP_STORAGES' (hint: "TMP_STORAGES: List[<type>] = ...")  [var-annotated]
(boriel)zxbasic/arch/zx48k/backend/__common.py:18:1: error: Need type annotation for 'REQUIRES' (hint: "REQUIRES: Set[<type>] = ...")  [var-annotated]
(boriel)zxbasic/arch/zx48k/backend/__common.py:21:1: error: Need type annotation for 'INITS' (hint: "INITS: Set[<type>] = ...")  [var-annotated]
(boriel)zxbasic/arch/zx48k/backend/__common.py:27:1: error: Need type annotation for 'TMP_LABELS' (hint: "TMP_LABELS: Set[<type>] = ...")  [var-annotated]
(boriel)zxbasic/symbols/symbol_.py:13:1: error: Module 'ast_' has no attribute 'Ast'  [attr-defined]

/
h
o
m
e
/
b
e
w
/
a
r
c
h
i
v
e
/
t
y
p
e
d
_
p
r
o
j
e
c
t
/
(
b
o
r
i
e
l
)
z
x
b
a
s
i
c
/
s
y
m
b
o
l
s
/
s
y
m
b
o
l
_
.
p
y
:
1
3
:
 
e
r
r
o
r
:
 
I
N
T
E
R
N
A
L
 
E
R
R
O
R
 
-
-
 
P
l
e
a
s
e
 
t
r
y
 
u
s
i
n
g
 
m
y
p
y
 
m
a
s
t
e
r
 
o
n
 
G
i
t
h
u
b
:


h
t
t
p
s
:
/
/
m
y
p
y
.
r
t
f
d
.
i
o
/
e
n
/
l
a
t
e
s
t
/
c
o
m
m
o
n
_
i
s
s
u
e
s
.
h
t
m
l
#
u
s
i
n
g
-
a
-
d
e
v
e
l
o
p
m
e
n
t
-
m
y
p
y
-
b
u
i
l
d


I
f
 
t
h
i
s
 
i
s
s
u
e
 
c
o
n
t
i
n
u
e
s
 
w
i
t
h
 
m
y
p
y
 
m
a
s
t
e
r
,
 
p
l
e
a
s
e
 
r
e
p
o
r
t
 
a
 
b
u
g
 
a
t
 
h
t
t
p
s
:
/
/
g
i
t
h
u
b
.
c
o
m
/
p
y
t
h
o
n
/
m
y
p
y
/
i
s
s
u
e
s


v
e
r
s
i
o
n
:
 
0
.
7
6
1


/
h
o
m
e
/
b
e
w
/
a
r
c
h
i
v
e
/
t
y
p
e
d
_
p
r
o
j
e
c
t
/
(
b
o
r
i
e
l
)
z
x
b
a
s
i
c
/
s
y
m
b
o
l
s
/
s
y
m
b
o
l
_
.
p
y
:
1
3
:
 
:
 
n
o
t
e
:
 
p
l
e
a
s
e
 
u
s
e
 
-
-
s
h
o
w
-
t
r
a
c
e
b
a
c
k
 
t
o
 
p
r
i
n
t
 
a
 
t
r
a
c
e
b
a
c
k
 
w
h
e
n
 
r
e
p
o
r
t
i
n
g
 
a
 
b
u
g


[RRepo](sloria)aiohttp_utils
(sloria)aiohttp_utils/aiohttp_utils/runner.py:78:57: error: Item "None" of "Optional[Application]" has no attribute "debug"  [union-attr]
(sloria)aiohttp_utils/aiohttp_utils/negotiation.py:240:46: error: Function "builtins.callable" is not valid as a type  [valid-type]
(sloria)aiohttp_utils/aiohttp_utils/negotiation.py:240:46: note: Perhaps you need "Callable[...]" or a callback protocol?
(sloria)aiohttp_utils/aiohttp_utils/negotiation.py:241:34: error: Incompatible default for argument "renderers" (default has type "object", argument has type "OrderedDict[Any, Any]")  [assignment]
(sloria)aiohttp_utils/aiohttp_utils/negotiation.py:242:35: error: Incompatible default for argument "force_negotiation" (default has type "object", argument has type "bool")  [assignment]
(sloria)aiohttp_utils/aiohttp_utils/negotiation.py:243:33: error: Incompatible default for argument "force_rendering" (default has type "object", argument has type "bool")  [assignment]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:74:28: error: Incompatible types in assignment (expression has type "List[str]", variable has type "Tuple[Any, ...]")  [assignment]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:131:42: error: Argument 1 to "import_module" has incompatible type "Union[str, bytes]"; expected "str"  [arg-type]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:239:42: error: Argument 1 to "import_module" has incompatible type "Union[str, bytes]"; expected "str"  [arg-type]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:256:44: error: Argument 2 to "getattr" has incompatible type "Union[str, bytes]"; expected "str"  [arg-type]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:267:16: error: "UrlDispatcher" has no attribute "add_resource_object"; maybe "add_resource"?  [attr-defined]

/
h
o
m
e
/
b
e
w
/
a
r
c
h
i
v
e
/
t
y
p
e
d
_
p
r
o
j
e
c
t
/
(
s
l
o
r
i
a
)
a
i
o
h
t
t
p
_
u
t
i
l
s
/
a
i
o
h
t
t
p
_
u
t
i
l
s
/
n
e
g
o
t
i
a
t
i
o
n
.
p
y
:
2
3
9
:
 
e
r
r
o
r
:
 
I
N
T
E
R
N
A
L
 
E
R
R
O
R
 
-
-
 
P
l
e
a
s
e
 
t
r
y
 
u
s
i
n
g
 
m
y
p
y
 
m
a
s
t
e
r
 
o
n
 
G
i
t
h
u
b
:


h
t
t
p
s
:
/
/
m
y
p
y
.
r
t
f
d
.
i
o
/
e
n
/
l
a
t
e
s
t
/
c
o
m
m
o
n
_
i
s
s
u
e
s
.
h
t
m
l
#
u
s
i
n
g
-
a
-
d
e
v
e
l
o
p
m
e
n
t
-
m
y
p
y
-
b
u
i
l
d


I
f
 
t
h
i
s
 
i
s
s
u
e
 
c
o
n
t
i
n
u
e
s
 
w
i
t
h
 
m
y
p
y
 
m
a
s
t
e
r
,
 
p
l
e
a
s
e
 
r
e
p
o
r
t
 
a
 
b
u
g
 
a
t
 
h
t
t
p
s
:
/
/
g
i
t
h
u
b
.
c
o
m
/
p
y
t
h
o
n
/
m
y
p
y
/
i
s
s
u
e
s


v
e
r
s
i
o
n
:
 
0
.
7
6
1


/
h
o
m
e
/
b
e
w
/
a
r
c
h
i
v
e
/
t
y
p
e
d
_
p
r
o
j
e
c
t
/
(
s
l
o
r
i
a
)
a
i
o
h
t
t
p
_
u
t
i
l
s
/
a
i
o
h
t
t
p
_
u
t
i
l
s
/
n
e
g
o
t
i
a
t
i
o
n
.
p
y
:
2
3
9
:
 
:
 
n
o
t
e
:
 
p
l
e
a
s
e
 
u
s
e
 
-
-
s
h
o
w
-
t
r
a
c
e
b
a
c
k
 
t
o
 
p
r
i
n
t
 
a
 
t
r
a
c
e
b
a
c
k
 
w
h
e
n
 
r
e
p
o
r
t
i
n
g
 
a
 
b
u
g


[RRepo](tildetown)tilde-wiki
Success: no issues found in 3 source files

[RRepo](albertz)PyOverheadGame

u
s
a
g
e
:
 
m
y
p
y
 
[
-
h
]
 
[
-
v
]
 
[
-
V
]
 
[
m
o
r
e
 
o
p
t
i
o
n
s
;
 
s
e
e
 
b
e
l
o
w
]


 
 
 
 
 
 
 
 
 
 
 
 
[
-
m
 
M
O
D
U
L
E
]
 
[
-
p
 
P
A
C
K
A
G
E
]
 
[
-
c
 
P
R
O
G
R
A
M
_
T
E
X
T
]
 
[
f
i
l
e
s
 
.
.
.
]


m
y
p
y
:
 
e
r
r
o
r
:
 
M
i
s
s
i
n
g
 
t
a
r
g
e
t
 
m
o
d
u
l
e
,
 
p
a
c
k
a
g
e
,
 
f
i
l
e
s
,
 
o
r
 
c
o
m
m
a
n
d
.


[RRepo](OpenSourcePolicyCenter)webapp-public

T
r
a
c
e
b
a
c
k
 
(
m
o
s
t
 
r
e
c
e
n
t
 
c
a
l
l
 
l
a
s
t
)
:


 
 
F
i
l
e
 
"
/
u
s
r
/
l
o
c
a
l
/
b
i
n
/
m
y
p
y
"
,
 
l
i
n
e
 
8
,
 
i
n
 
<
m
o
d
u
l
e
>


 
 
 
 
s
y
s
.
e
x
i
t
(
c
o
n
s
o
l
e
_
e
n
t
r
y
(
)
)


 
 
F
i
l
e
 
"
/
u
s
r
/
l
o
c
a
l
/
l
i
b
/
p
y
t
h
o
n
3
.
6
/
d
i
s
t
-
p
a
c
k
a
g
e
s
/
m
y
p
y
/
_
_
m
a
i
n
_
_
.
p
y
"
,
 
l
i
n
e
 
8
,
 
i
n
 
c
o
n
s
o
l
e
_
e
n
t
r
y


 
 
 
 
m
a
i
n
(
N
o
n
e
,
 
s
y
s
.
s
t
d
o
u
t
,
 
s
y
s
.
s
t
d
e
r
r
)


 
 
F
i
l
e
 
"
m
y
p
y
/
m
a
i
n
.
p
y
"
,
 
l
i
n
e
 
8
9
,
 
i
n
 
m
a
i
n


 
 
F
i
l
e
 
"
m
y
p
y
/
b
u
i
l
d
.
p
y
"
,
 
l
i
n
e
 
1
6
6
,
 
i
n
 
b
u
i
l
d


 
 
F
i
l
e
 
"
m
y
p
y
/
b
u
i
l
d
.
p
y
"
,
 
l
i
n
e
 
2
3
5
,
 
i
n
 
_
b
u
i
l
d


 
 
F
i
l
e
 
"
m
y
p
y
/
b
u
i
l
d
.
p
y
"
,
 
l
i
n
e
 
2
6
1
1
,
 
i
n
 
d
i
s
p
a
t
c
h


 
 
F
i
l
e
 
"
m
y
p
y
/
b
u
i
l
d
.
p
y
"
,
 
l
i
n
e
 
2
9
1
1
,
 
i
n
 
p
r
o
c
e
s
s
_
g
r
a
p
h


 
 
F
i
l
e
 
"
m
y
p
y
/
b
u
i
l
d
.
p
y
"
,
 
l
i
n
e
 
2
9
8
9
,
 
i
n
 
p
r
o
c
e
s
s
_
f
r
e
s
h
_
m
o
d
u
l
e
s


 
 
F
i
l
e
 
"
m
y
p
y
/
b
u
i
l
d
.
p
y
"
,
 
l
i
n
e
 
1
9
1
9
,
 
i
n
 
f
i
x
_
c
r
o
s
s
_
r
e
f
s


 
 
F
i
l
e
 
"
m
y
p
y
/
f
i
x
u
p
.
p
y
"
,
 
l
i
n
e
 
2
5
,
 
i
n
 
f
i
x
u
p
_
m
o
d
u
l
e


 
 
F
i
l
e
 
"
m
y
p
y
/
f
i
x
u
p
.
p
y
"
,
 
l
i
n
e
 
7
6
,
 
i
n
 
v
i
s
i
t
_
s
y
m
b
o
l
_
t
a
b
l
e


 
 
F
i
l
e
 
"
m
y
p
y
/
f
i
x
u
p
.
p
y
"
,
 
l
i
n
e
 
2
9
9
,
 
i
n
 
l
o
o
k
u
p
_
q
u
a
l
i
f
i
e
d
_
s
t
n
o
d
e


 
 
F
i
l
e
 
"
m
y
p
y
/
l
o
o
k
u
p
.
p
y
"
,
 
l
i
n
e
 
4
7
,
 
i
n
 
l
o
o
k
u
p
_
f
u
l
l
y
_
q
u
a
l
i
f
i
e
d


A
s
s
e
r
t
i
o
n
E
r
r
o
r
:
 
C
a
n
n
o
t
 
f
i
n
d
 
c
o
m
p
o
n
e
n
t
 
'
A
S
T
'
 
f
o
r
 
'
b
u
i
l
t
i
n
s
.
A
S
T
'


[RRepo](mikonapoli)grakn-python
(mikonapoli)grakn-python/features/steps/steps.py:9:1: error: Name 'use_step_matcher' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:12:2: error: Name 'given' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:17:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:17:2: error: Name 'given' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:22:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:22:2: error: Name 'given' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:27:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:27:2: error: Name 'given' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:32:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:32:2: error: Name 'given' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:37:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:37:2: error: Name 'when' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:42:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:42:2: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:48:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:48:2: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:53:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:53:2: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:61:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:61:2: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:67:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:67:2: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:72:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:72:2: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/features/steps/steps.py:77:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:77:2: error: Name 'then' is not defined  [name-defined]
(mikonapoli)grakn-python/tests/test_grakn.py:28:30: error: Incompatible types in assignment (expression has type "None", variable has type "Dict[Any, Any]")  [assignment]
(mikonapoli)grakn-python/tests/test_grakn.py:29:26: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(mikonapoli)grakn-python/tests/test_grakn.py:30:29: error: Incompatible types in assignment (expression has type "None", variable has type "Dict[Any, Any]")  [assignment]
(mikonapoli)grakn-python/tests/test_grakn.py:34:28: error: Incompatible types in assignment (expression has type "CaseInsensitiveDict[str]", variable has type "Dict[Any, Any]")  [assignment]
(mikonapoli)grakn-python/tests/test_grakn.py:35:25: error: Incompatible types in assignment (expression has type "Union[bytes, str, None]", variable has type "str")  [assignment]
Found 31 errors in 2 files (checked 4 source files)

[RRepo](gopythongo)aptly-api-client
Success: no issues found in 8 source files

[RRepo](marketcoin)marketcoin
(marketcoin)marketcoin/mockrpc.py:7:11: error: Need type annotation for 'balance'  [var-annotated]
(marketcoin)marketcoin/mockrpc.py:10:16: error: Need type annotation for 'transactions'  [var-annotated]
Found 2 errors in 1 file (checked 7 source files)

[RRepo](jsandovalc)poster
(jsandovalc)poster/poster/migrations/env.py:25:19: error: Module has no attribute "metadata"  [attr-defined]
(jsandovalc)poster/poster/app.py:26: error: The return type of an async generator function should be "AsyncGenerator" or one of its supertypes  [misc]
(jsandovalc)poster/poster/app.py:50:9: error: List item 0 has incompatible type "Callable[[Application], None]"; expected "Callable[[Application], AsyncIterator[None]]"  [list-item]

/
h
o
m
e
/
b
e
w
/
a
r
c
h
i
v
e
/
t
y
p
e
d
_
p
r
o
j
e
c
t
/
(
j
s
a
n
d
o
v
a
l
c
)
p
o
s
t
e
r
/
p
o
s
t
e
r
/
a
p
p
.
p
y
:
2
6
:
 
e
r
r
o
r
:
 
I
N
T
E
R
N
A
L
 
E
R
R
O
R
 
-
-
 
P
l
e
a
s
e
 
t
r
y
 
u
s
i
n
g
 
m
y
p
y
 
m
a
s
t
e
r
 
o
n
 
G
i
t
h
u
b
:


h
t
t
p
s
:
/
/
m
y
p
y
.
r
t
f
d
.
i
o
/
e
n
/
l
a
t
e
s
t
/
c
o
m
m
o
n
_
i
s
s
u
e
s
.
h
t
m
l
#
u
s
i
n
g
-
a
-
d
e
v
e
l
o
p
m
e
n
t
-
m
y
p
y
-
b
u
i
l
d


I
f
 
t
h
i
s
 
i
s
s
u
e
 
c
o
n
t
i
n
u
e
s
 
w
i
t
h
 
m
y
p
y
 
m
a
s
t
e
r
,
 
p
l
e
a
s
e
 
r
e
p
o
r
t
 
a
 
b
u
g
 
a
t
 
h
t
t
p
s
:
/
/
g
i
t
h
u
b
.
c
o
m
/
p
y
t
h
o
n
/
m
y
p
y
/
i
s
s
u
e
s


v
e
r
s
i
o
n
:
 
0
.
7
6
1


/
h
o
m
e
/
b
e
w
/
a
r
c
h
i
v
e
/
t
y
p
e
d
_
p
r
o
j
e
c
t
/
(
j
s
a
n
d
o
v
a
l
c
)
p
o
s
t
e
r
/
p
o
s
t
e
r
/
a
p
p
.
p
y
:
2
6
:
 
:
 
n
o
t
e
:
 
p
l
e
a
s
e
 
u
s
e
 
-
-
s
h
o
w
-
t
r
a
c
e
b
a
c
k
 
t
o
 
p
r
i
n
t
 
a
 
t
r
a
c
e
b
a
c
k
 
w
h
e
n
 
r
e
p
o
r
t
i
n
g
 
a
 
b
u
g


[RRepo](der-michik)c3bottles
(der-michik)c3bottles/c3bottles/model/user.py:16:12: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/user.py:24:11: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:25:12: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:27:16: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:28:13: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:29:17: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:30:16: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:31:16: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:32:17: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:33:21: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:137:2: error: Cannot determine type of 'lm'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:172:1: error: Cannot determine type of 'lm'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:186:2: error: Cannot determine type of 'app'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:9:16: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/location.py:29:14: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:31:13: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:32:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:33:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:37:10: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:39:12: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:40:19: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:41:11: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:42:11: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:43:13: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:9:13: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/visit.py:28:14: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:30:13: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:31:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:32:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:36:10: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:38:12: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:40:14: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:41:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:9:14: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/report.py:32:14: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:34:13: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:35:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:36:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:40:10: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:42:12: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:44:13: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:45:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:14:17: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/drop_point.py:31:14: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:32:19: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:33:12: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:34:15: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:35:17: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:36:15: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:37:14: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/views/__init__.py:11:2: error: Cannot determine type of 'app'  [has-type]
(der-michik)c3bottles/c3bottles/views/__init__.py:58:2: error: Cannot determine type of 'app'  [has-type]
(der-michik)c3bottles/c3bottles/views/__init__.py:73:2: error: Cannot determine type of 'app'  [has-type]
(der-michik)c3bottles/c3bottles/views/__init__.py:82:2: error: Cannot determine type of 'app'  [has-type]
(der-michik)c3bottles/translations/translate-js.py:6:1: error: Module has no attribute "sys"  [attr-defined]
(der-michik)c3bottles/c3bottles/model/user.py:16:12: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/user.py:24:11: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:25:12: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:27:16: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:28:13: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:29:17: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:30:16: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:31:16: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:32:17: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:33:21: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:137:2: error: Cannot determine type of 'lm'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:172:1: error: Cannot determine type of 'lm'  [has-type]
(der-michik)c3bottles/c3bottles/model/user.py:186:2: error: Cannot determine type of 'app'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:9:13: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/visit.py:28:14: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:30:13: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:31:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:32:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:36:10: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:38:12: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:40:14: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/visit.py:41:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:9:16: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/location.py:29:14: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:31:13: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:32:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:33:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:37:10: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:39:12: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:40:19: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:41:11: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:42:11: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/location.py:43:13: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:14:17: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/drop_point.py:31:14: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:32:19: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:33:12: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:34:15: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:35:17: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:36:15: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/drop_point.py:37:14: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:9:14: error: Name 'db.Model' is not defined  [name-defined]
(der-michik)c3bottles/c3bottles/model/report.py:32:14: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:34:13: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:35:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:36:9: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:40:10: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:42:12: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:44:13: error: Cannot determine type of 'db'  [has-type]
(der-michik)c3bottles/c3bottles/model/report.py:45:9: error: Cannot determine type of 'db'  [has-type]
Found 105 errors in 7 files (checked 24 source files)

[RRepo](OpenSlides)OpenSlides
(OpenSlides)OpenSlides/tests/unit/motions/test_projector.py:7:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/tests/integration/mediafiles/test_viewset.py:10:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/core/management/commands/migrate.py:5:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/motions/numbering.py:8:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/motions/numbering.py:9:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/utils/auth.py:159:5: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/utils/auth.py:168:5: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/users/management/commands/createsuperuser.py:3:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/users/management/commands/createopenslidesuser.py:3:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/users/projector.py:3:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/users/signals.py:5:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/users/serializers.py:4:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/users/serializers.py:5:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/users/access_permissions.py:3:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/users/access_permissions.py:4:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/users/access_permissions.py:5:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/mediafiles/config.py:3:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/utils/autoupdate.py:249:5: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/utils/consumers.py:7:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/utils/consumers.py:57:46: error: Invalid index type "bytes" for "Dict[str, List[str]]"; expected type "str"  [index]
(OpenSlides)OpenSlides/openslides/utils/consumers.py:64:59: error: Invalid index type "bytes" for "Dict[str, List[str]]"; expected type "str"  [index]
(OpenSlides)OpenSlides/openslides/users/models.py:20:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/users/models.py:21:1: error: Relative import climbs too many namespaces  [misc]
(OpenSlides)OpenSlides/openslides/users/models.py:22:1: error: Relative import climbs too many namespaces  [misc]
Found 24 errors in 15 files (checked 81 source files)

[RRepo](robotpy)pyfrc
(robotpy)pyfrc/lib/pyfrc/sim/robot_controller.py:9:1: error: Relative import climbs too many namespaces  [misc]
(robotpy)pyfrc/docs/conf.py:103:1: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
Found 2 errors in 2 files (checked 28 source files)

[RRepo](UTNkar)moore
(UTNkar)moore/src/involvement/forms/approval_form.py:17:9: error: Need type annotation for 'fields' (hint: "fields: List[<type>] = ...")  [var-annotated]
(UTNkar)moore/src/involvement/models/recruitment_page.py:85:5: error: Need type annotation for 'subpage_types' (hint: "subpage_types: List[<type>] = ...")  [var-annotated]
(UTNkar)moore/src/involvement/rules.py:7:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:12:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:18:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:23:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:29:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:34:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:39:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:44:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:49:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:55:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:60:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:67:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:73:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:73:31: error: Module has no attribute "always_allow"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:75:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:76:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:77:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:79:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:82:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:83:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:84:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:86:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:89:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:90:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:91:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:93:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:95:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:98:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:101:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:105:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:106:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:107:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:109:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:111:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:114:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:115:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:116:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:118:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/involvement/rules.py:120:1: error: Module has no attribute "add_perm"  [attr-defined]
(UTNkar)moore/src/news/models.py:109:5: error: Need type annotation for 'subpage_types' (hint: "subpage_types: List[<type>] = ...")  [var-annotated]
(UTNkar)moore/src/involvement/rule_utils.py:4:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:11:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:17:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:23:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:29:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:35:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:41:2: error: Module has no attribute "predicate"  [attr-defined]
(UTNkar)moore/src/involvement/rule_utils.py:47:2: error: Module has no attribute "predicate"  [attr-defined]
Found 50 errors in 5 files (checked 48 source files)

[RRepo](groutr)conda-tools
(groutr)conda-tools/src/conda_tools/common.py:6:9: error: Need type annotation for '__slots__' (hint: "__slots__: List[<type>] = ...")  [var-annotated]
(groutr)conda-tools/src/conda_tools/environment/environment.py:11:1: error: Relative import climbs too many namespaces  [misc]
(groutr)conda-tools/src/conda_tools/environment/environment.py:12:1: error: Relative import climbs too many namespaces  [misc]
(groutr)conda-tools/src/conda_tools/environment/environment.py:14:1: error: Relative import climbs too many namespaces  [misc]
(groutr)conda-tools/src/conda_tools/environment/environment.py:15:1: error: Relative import climbs too many namespaces  [misc]
(groutr)conda-tools/src/conda_tools/environment/history.py:14:1: error: Relative import climbs too many namespaces  [misc]
Found 6 errors in 3 files (checked 8 source files)

[RRepo](OParl)liboparl
Success: no issues found in 1 source file

[RRepo](fkie-cad)FACT_core
(fkie-cad)FACT_core/src/helperFunctions/database_structure.py:4:20: error: Need type annotation for 'LEAF_CONSTRAINT'  [var-annotated]
(fkie-cad)FACT_core/src/plugins/analysis/linter/test/test_lua_linter.py:3:1: error: Relative import climbs too many namespaces  [misc]
(fkie-cad)FACT_core/src/plugins/analysis/linter/test/test_js_linter.py:3:1: error: Relative import climbs too many namespaces  [misc]
(fkie-cad)FACT_core/src/plugins/analysis/linter/test/test_python_linter.py:3:1: error: Relative import climbs too many namespaces  [misc]
(fkie-cad)FACT_core/src/plugins/analysis/linter/test/test_shell_linter.py:3:1: error: Relative import climbs too many namespaces  [misc]
(fkie-cad)FACT_core/src/plugins/analysis/known_vulnerabilities/test/test_rulebook.py:3:1: error: Relative import climbs too many namespaces  [misc]

/
h
o
m
e
/
b
e
w
/
a
r
c
h
i
v
e
/
t
y
p
e
d
_
p
r
o
j
e
c
t
/
(
f
k
i
e
-
c
a
d
)
F
A
C
T
_
c
o
r
e
/
s
r
c
/
h
e
l
p
e
r
F
u
n
c
t
i
o
n
s
/
d
a
t
a
b
a
s
e
_
s
t
r
u
c
t
u
r
e
.
p
y
:
4
:
 
e
r
r
o
r
:
 
I
N
T
E
R
N
A
L
 
E
R
R
O
R
 
-
-
 
P
l
e
a
s
e
 
t
r
y
 
u
s
i
n
g
 
m
y
p
y
 
m
a
s
t
e
r
 
o
n
 
G
i
t
h
u
b
:


h
t
t
p
s
:
/
/
m
y
p
y
.
r
t
f
d
.
i
o
/
e
n
/
l
a
t
e
s
t
/
c
o
m
m
o
n
_
i
s
s
u
e
s
.
h
t
m
l
#
u
s
i
n
g
-
a
-
d
e
v
e
l
o
p
m
e
n
t
-
m
y
p
y
-
b
u
i
l
d


I
f
 
t
h
i
s
 
i
s
s
u
e
 
c
o
n
t
i
n
u
e
s
 
w
i
t
h
 
m
y
p
y
 
m
a
s
t
e
r
,
 
p
l
e
a
s
e
 
r
e
p
o
r
t
 
a
 
b
u
g
 
a
t
 
h
t
t
p
s
:
/
/
g
i
t
h
u
b
.
c
o
m
/
p
y
t
h
o
n
/
m
y
p
y
/
i
s
s
u
e
s


v
e
r
s
i
o
n
:
 
0
.
7
6
1


/
h
o
m
e
/
b
e
w
/
a
r
c
h
i
v
e
/
t
y
p
e
d
_
p
r
o
j
e
c
t
/
(
f
k
i
e
-
c
a
d
)
F
A
C
T
_
c
o
r
e
/
s
r
c
/
h
e
l
p
e
r
F
u
n
c
t
i
o
n
s
/
d
a
t
a
b
a
s
e
_
s
t
r
u
c
t
u
r
e
.
p
y
:
4
:
 
:
 
n
o
t
e
:
 
p
l
e
a
s
e
 
u
s
e
 
-
-
s
h
o
w
-
t
r
a
c
e
b
a
c
k
 
t
o
 
p
r
i
n
t
 
a
 
t
r
a
c
e
b
a
c
k
 
w
h
e
n
 
r
e
p
o
r
t
i
n
g
 
a
 
b
u
g


[RRepo](sorgloomer)websocket_terminal
Success: no issues found in 12 source files

[RRepo](jrabbit)pyborg-1up
(jrabbit)pyborg-1up/misc/pyborg-telnet.py:42:33: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 32 source files)

[RRepo](python-hyper)hyper-h2
(python-hyper)hyper-h2/test/test_utility_functions.py:19:13: error: Name 'xrange' is not defined  [name-defined]
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:41:5: error: Argument 1 of "connection_made" is incompatible with supertype "BaseProtocol"; supertype defines the argument type as "BaseTransport"  [override]
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:79:19: error: Incompatible types in assignment (expression has type "OrderedDict[str, str]", variable has type "List[Tuple[str, str]]")  [assignment]
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:80:18: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:80:18: note: Possible overload variants:
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:80:18: note:     def __getitem__(self, int) -> Tuple[str, str]
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:80:18: note:     def __getitem__(self, slice) -> List[Tuple[str, str]]
(python-hyper)hyper-h2/examples/asyncio/asyncio-server.py:201:30: error: Value of type "Optional[List[socket]]" is not indexable  [index]
Found 5 errors in 2 files (checked 13 source files)

[RRepo](awslabs)sockeye
(awslabs)sockeye/sockeye/image_captioning/utils.py:24:1: error: Relative import climbs too many namespaces  [misc]
(awslabs)sockeye/sockeye/lr_scheduler.py:153:18: error: Unsupported operand types for / ("None" and "float")  [operator]
(awslabs)sockeye/sockeye/lr_scheduler.py:184:18: error: Unsupported operand types for / ("None" and "float")  [operator]
(awslabs)sockeye/sockeye/lr_scheduler.py:209:19: error: Incompatible types in assignment (expression has type "None", variable has type "float")  [assignment]
(awslabs)sockeye/sockeye/lr_scheduler.py:280:95: error: Argument 3 to "LearningRateSchedulerInvSqrtT" has incompatible type "Optional[int]"; expected "int"  [arg-type]
(awslabs)sockeye/sockeye/lr_scheduler.py:282:91: error: Argument 3 to "LearningRateSchedulerInvT" has incompatible type "Optional[int]"; expected "int"  [arg-type]
(awslabs)sockeye/sockeye/lr_scheduler.py:286:47: error: Argument 1 to "LearningRateSchedulerFixedStep" has incompatible type "Optional[List[Tuple[float, int]]]"; expected "List[Tuple[float, int]]"  [arg-type]
(awslabs)sockeye/sockeye/lr_scheduler.py:297:51: error: Argument 3 to "LearningRateSchedulerPlateauReduce" has incompatible type "Optional[int]"; expected "int"  [arg-type]
(awslabs)sockeye/sockeye/lexicon.py:26:1: error: Module 'sockeye' has no attribute 'arguments'  [attr-defined]
(awslabs)sockeye/sockeye/evaluate.py:28:1: error: Module 'sockeye' has no attribute 'arguments'  [attr-defined]
(awslabs)sockeye/sockeye/rerank.py:26:1: error: Module 'sockeye' has no attribute 'arguments'  [attr-defined]
(awslabs)sockeye/sockeye/translate.py:28:1: error: Module 'sockeye' has no attribute 'arguments'  [attr-defined]
(awslabs)sockeye/sockeye/loss.py:91:12: error: Incompatible return value type (got "None", expected "Loss")  [return-value]
(awslabs)sockeye/test/integration/test_constraints_int.py:127:43: error: Incompatible types in assignment (expression has type "List[str]", target has type "str")  [assignment]
(awslabs)sockeye/sockeye/model.py:21:1: error: Module 'sockeye' has no attribute '__version__'  [attr-defined]
(awslabs)sockeye/sockeye/model.py:122:13: error: Attribute 'embedding_source' already defined on line 120  [no-redef]
(awslabs)sockeye/sockeye/model.py:180:31: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "copy"  [union-attr]
(awslabs)sockeye/sockeye/model.py:182:31: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "copy"  [union-attr]
(awslabs)sockeye/sockeye/model.py:195:76: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "keys"  [union-attr]
(awslabs)sockeye/sockeye/model.py:197:76: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "keys"  [union-attr]
(awslabs)sockeye/sockeye/model.py:232:16: error: Unsupported right operand type for in ("Optional[str]")  [operator]
(awslabs)sockeye/sockeye/model.py:233:25: error: Unsupported right operand type for in ("Optional[str]")  [operator]
(awslabs)sockeye/sockeye/model.py:239:16: error: Unsupported right operand type for in ("Optional[str]")  [operator]
(awslabs)sockeye/setup.py:93:8: error: Incompatible types in assignment (expression has type "Dict[str, Any]", variable has type "Namespace")  [assignment]
Found 24 errors in 10 files (checked 29 source files)

[RRepo](TheAlgorithms)Python
(TheAlgorithms)Python/strings/levenshtein_distance.py:69:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/ciphers/atbash.py:2:5: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/ciphers/atbash.py:3:5: error: Cannot determine type of 'unichr'  [has-type]
(TheAlgorithms)Python/backtracking/all_subsequences.py:41:13: error: List item 0 has incompatible type "str"; expected "int"  [list-item]
(TheAlgorithms)Python/backtracking/all_subsequences.py:41:18: error: List item 1 has incompatible type "str"; expected "int"  [list-item]
(TheAlgorithms)Python/backtracking/all_subsequences.py:41:23: error: List item 2 has incompatible type "str"; expected "int"  [list-item]
(TheAlgorithms)Python/backtracking/sudoku.py:145:25: error: Argument 1 to "map" has incompatible type "Type[List[Any]]"; expected "Callable[[List[int]], List[_T]]"  [arg-type]
(TheAlgorithms)Python/backtracking/all_permutations.py:44:13: error: List item 0 has incompatible type "str"; expected "int"  [list-item]
(TheAlgorithms)Python/backtracking/all_permutations.py:44:18: error: List item 1 has incompatible type "str"; expected "int"  [list-item]
(TheAlgorithms)Python/backtracking/all_permutations.py:44:23: error: List item 2 has incompatible type "str"; expected "int"  [list-item]
(TheAlgorithms)Python/backtracking/all_combinations.py:10: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/backtracking/all_combinations.py:10: note: Did you mean "List[...]"?
(TheAlgorithms)Python/backtracking/all_combinations.py:16:5: error: Need type annotation for 'result' (hint: "result: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/dynamic_programming/rod_cutting.py:48:9: error: Incompatible return value type (got "float", expected "int")  [return-value]
(TheAlgorithms)Python/graphs/minimum_spanning_tree_prims.py:107:15: error: Need type annotation for 'adjlist'  [var-annotated]
(TheAlgorithms)Python/data_structures/trie/trie.py:15: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/data_structures/trie/trie.py:15: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:10: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:10: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:27: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:27: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:39: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:39: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:51: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:51: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:63: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:63: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:68: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:68: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:73: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:73: note: Did you mean "List[...]"?
(TheAlgorithms)Python/matrix/rotate_matrix.py:78: error: Bracketed expression "[...]" is not valid as a type  [misc]
(TheAlgorithms)Python/matrix/rotate_matrix.py:78: note: Did you mean "List[...]"?
(TheAlgorithms)Python/sorts/comb_sort.py:52:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/searches/sentinel_linear_search.py:49:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/other/anagrams.py:13:14: error: Need type annotation for 'word_bysig'  [var-annotated]
(TheAlgorithms)Python/dynamic_programming/integer_partition.py:9:2: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/dynamic_programming/edit_distance.py:86:13: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/hashes/enigma_machine.py:47:14: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")  [assignment]
(TheAlgorithms)Python/hashes/enigma_machine.py:56:5: error: Incompatible types in assignment (expression has type "str", variable has type "int")  [assignment]
(TheAlgorithms)Python/graphs/scc_kosaraju.py:37:10: error: Need type annotation for 'g'  [var-annotated]
(TheAlgorithms)Python/graphs/scc_kosaraju.py:38:10: error: Need type annotation for 'r'  [var-annotated]
(TheAlgorithms)Python/graphs/scc_kosaraju.py:45:5: error: Need type annotation for 'stack' (hint: "stack: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/graphs/scc_kosaraju.py:47:5: error: Need type annotation for 'scc' (hint: "scc: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/graphs/scc_kosaraju.py:48:5: error: Need type annotation for 'component' (hint: "component: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/graphs/even_tree.py:51:12: error: Need type annotation for 'tree'  [var-annotated]
(TheAlgorithms)Python/graphs/even_tree.py:52:5: error: Need type annotation for 'visited' (hint: "visited: Dict[<type>, <type>] = ...")  [var-annotated]
(TheAlgorithms)Python/graphs/even_tree.py:53:5: error: Need type annotation for 'cuts' (hint: "cuts: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/graphs/basic_graphs.py:4:5: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/graphs/basic_graphs.py:19:5: error: Need type annotation for 'g' (hint: "g: Dict[<type>, <type>] = ...")  [var-annotated]
(TheAlgorithms)Python/graphs/bellman_ford.py:41:14: error: Need type annotation for 'graph'  [var-annotated]
(TheAlgorithms)Python/graphs/multi_hueristic_astar.py:188:1: error: Need type annotation for 'blocks_no' (hint: "blocks_no: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/data_structures/heap/heap.py:6:5: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/project_euler/problem_01/sol6.py:10:5: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/project_euler/problem_01/sol5.py:10:5: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/project_euler/problem_02/sol3.py:15:5: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/gnome_sort.py:25:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/quick_sort.py:51:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/cocktail_shaker_sort.py:25:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/counting_sort.py:69:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/cycle_sort.py:49:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/pigeon_sort.py:42:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/insertion_sort.py:44:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/bubble_sort.py:37:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/shell_sort.py:48:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/merge_sort.py:50:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/quick_sort_3_partition.py:24:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/heap_sort.py:58:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/merge_sort_fastest.py:40:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/selection_sort.py:47:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/searches/ternary_search.py:14:5: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/searches/binary_search.py:16:5: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/searches/linear_search.py:15:5: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/searches/interpolation_search.py:7:5: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/neural_network/perceptron.py:122:9: error: Need type annotation for 'sample' (hint: "sample: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/hashes/chaos_machine.py:5:11: error: Name 'raw_input' is not defined  [name-defined]
(TheAlgorithms)Python/hashes/chaos_machine.py:13:1: error: Need type annotation for 'buffer_space' (hint: "buffer_space: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/hashes/chaos_machine.py:13:15: error: Need type annotation for 'params_space' (hint: "params_space: List[<type>] = ...")  [var-annotated]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:33:21: error: Incompatible types in assignment (expression has type "Node", variable has type "None")  [assignment]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:33:27: error: Argument 1 to "split" has incompatible type "None"; expected "Node"  [arg-type]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:39:21: error: Incompatible types in assignment (expression has type "Node", variable has type "None")  [assignment]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:39:27: error: Argument 1 to "split" has incompatible type "None"; expected "Node"  [arg-type]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:58:18: error: Incompatible types in assignment (expression has type "Node", variable has type "None")  [assignment]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:58:24: error: Argument 1 to "merge" has incompatible type "None"; expected "Node"  [arg-type]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:64:19: error: Incompatible types in assignment (expression has type "Node", variable has type "None")  [assignment]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:64:31: error: Argument 2 to "merge" has incompatible type "None"; expected "Node"  [arg-type]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:102:16: error: Argument 1 to "node_print" has incompatible type "None"; expected "Node"  [arg-type]
(TheAlgorithms)Python/data_structures/binary_tree/treap.py:104:16: error: Argument 1 to "node_print" has incompatible type "None"; expected "Node"  [arg-type]
(TheAlgorithms)Python/project_euler/problem_02/sol4.py:17:5: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/sorts/bogo_sort.py:43:9: error: Cannot determine type of 'raw_input'  [has-type]
(TheAlgorithms)Python/maths/zellers_congruence.py:1:1: error: Module '__future__' has no attribute 'annotations'  [attr-defined]
Found 81 errors in 49 files (checked 264 source files)

[RRepo](trezor)micropython
(trezor)micropython/tests/micropython/viper_binop_divmod.py:3:2: error: Name 'micropython' is not defined  [name-defined]
(trezor)micropython/tests/micropython/viper_binop_divmod.py:7:2: error: Name 'micropython' is not defined  [name-defined]
(trezor)micropython/tests/micropython/heapalloc_traceback.py:33:1: error: Module has no attribute "print_exception"  [attr-defined]
(trezor)micropython/tests/basics/class_super.py:26:1: error: Name 'A' already defined on line 19  [no-redef]
(trezor)micropython/tests/basics/class_super.py:41:5: error: Invalid assignment target  [misc]
(trezor)micropython/tests/basics/class_super.py:45:5: error: Invalid delete target  [misc]
(trezor)micropython/tests/basics/class_super.py:45:9: error: "foo" undefined in superclass  [misc]
(trezor)micropython/tests/basics/fun_error.py:5:5: error: Unexpected keyword argument "x" for "append" of "list"  [call-arg]
(trezor)micropython/tests/basics/fun_error.py:11:5: error: All overload variants of "round" require at least one argument  [call-overload]
(trezor)micropython/tests/basics/fun_error.py:11:5: note: Possible overload variants:
(trezor)micropython/tests/basics/fun_error.py:11:5: note:     def round(number: float) -> int
(trezor)micropython/tests/basics/fun_error.py:11:5: note:     def round(number: float, ndigits: None) -> int
(trezor)micropython/tests/basics/fun_error.py:11:5: note:     <4 more similar overloads not shown, out of 6 total overloads>
(trezor)micropython/tests/basics/fun_error.py:17:5: error: No overload variant of "round" matches argument types "int", "int", "int"  [call-overload]
(trezor)micropython/tests/basics/fun_error.py:17:5: note: Possible overload variants:
(trezor)micropython/tests/basics/fun_error.py:17:5: note:     def round(number: float) -> int
(trezor)micropython/tests/basics/fun_error.py:17:5: note:     def round(number: float, ndigits: None) -> int
(trezor)micropython/tests/basics/fun_error.py:17:5: note:     <4 more similar overloads not shown, out of 6 total overloads>
(trezor)micropython/tests/basics/fun_error.py:23:5: error: Too many arguments for "append" of "list"  [call-arg]
(trezor)micropython/tests/basics/fun_error.py:23:15: error: Argument 1 to "append" of "list" has incompatible type "int"; expected <nothing>  [arg-type]
(trezor)micropython/tests/basics/fun_error.py:29:5: error: Too many positional arguments for "sort" of "list"  [misc]
(trezor)micropython/tests/basics/fun_error.py:29:13: error: Argument 1 to "sort" of "list" has incompatible type "int"; expected "Optional[Callable[[<nothing>], Any]]"  [arg-type]
(trezor)micropython/tests/basics/fun_error.py:35:5: error: Unexpected keyword argument "noexist" for "sort" of "list"  [call-arg]
(trezor)micropython/tests/basics/fun_error.py:42:5: error: Missing positional argument "y" in call to "f"  [call-arg]
(trezor)micropython/tests/basics/del_attr.py:2:5: error: Method must have at least one argument  [misc]
(trezor)micropython/tests/basics/del_attr.py:9:11: error: "Type[C]" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/basics/del_attr.py:21:1: error: "C" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/basics/del_attr.py:22:7: error: "C" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/basics/del_attr.py:24:5: error: "C" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/basics/del_attr.py:26:11: error: "C" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/basics/del_attr.py:30:9: error: "C" has no attribute "x"  [attr-defined]
(trezor)micropython/tests/basics/builtin_setattr.py:16:16: error: Argument 2 to "setattr" has incompatible type "bytes"; expected "str"  [arg-type]
(trezor)micropython/tests/basics/fun_calldblstar2.py:16:1: error: Name 'foo' is not defined  [name-defined]
(trezor)micropython/tests/basics/fun_calldblstar2.py:19:1: error: Name 'foo' is not defined  [name-defined]
(trezor)micropython/tests/basics/iter1.py:7:14: error: "NotIterable" has no attribute "__iter__" (not iterable)  [attr-defined]
(trezor)micropython/tests/basics/iter1.py:13:1: error: Name 'NotIterable' already defined on line 4  [no-redef]
(trezor)micropython/tests/basics/iter1.py:17:15: error: Argument 1 to "all" has incompatible type "NotIterable"; expected "Iterable[object]"  [arg-type]
(trezor)micropython/tests/basics/builtin_dir.py:22:5: error: Method must have at least one argument  [misc]
(trezor)micropython/tests/basics/builtin_dir.py:25:5: error: Method must have at least one argument  [misc]
(trezor)micropython/tests/basics/builtin_dir.py:32:5: error: Method must have at least one argument  [misc]
(trezor)micropython/tests/basics/builtin_dir.py:35:5: error: Method must have at least one argument  [misc]
(trezor)micropython/tests/basics/fun_calldblstar.py:10:5: error: Keywords must be strings  [misc]
(trezor)micropython/tests/basics/op_error_intbig.py:14:5: error: Unsupported right operand type for in ("int")  [operator]
(trezor)micropython/tests/basics/subclass_native_init.py:34:1: error: Cannot access "__init__" directly  [misc]
(trezor)micropython/tests/basics/subclass_native_init.py:38:1: error: Name 'L' already defined on line 4  [no-redef]
(trezor)micropython/tests/basics/subclass_native_init.py:41:5: error: Too few arguments for "L"  [call-arg]
(trezor)micropython/tests/basics/subclass_native_init.py:41:5: error: Incompatible types in assignment (expression has type "L", variable has type "D")  [assignment]
(trezor)micropython/tests/basics/builtin_exec.py:10:7: error: "int" not callable  [operator]
(trezor)micropython/tests/basics/builtin_exec.py:12:1: error: Need type annotation for 'd' (hint: "d: Dict[<type>, <type>] = ...")  [var-annotated]
(trezor)micropython/tests/basics/builtin_exec.py:32:22: error: Argument 2 to "exec" has incompatible type "str"; expected "Optional[Dict[str, Any]]"  [arg-type]
(trezor)micropython/tests/basics/builtin_exec.py:38:28: error: Argument 3 to "exec" has incompatible type "int"; expected "Optional[Mapping[str, Any]]"  [arg-type]
(trezor)micropython/tests/basics/builtin_hasattr.py:39:16: error: Argument 2 to "hasattr" has incompatible type "bytes"; expected "str"  [arg-type]
(trezor)micropython/tests/basics/builtin_hasattr.py:44:16: error: Argument 2 to "hasattr" has incompatible type "int"; expected "str"  [arg-type]
(trezor)micropython/tests/basics/object_new.py:37:20: error: Argument 1 to "__new__" of "object" has incompatible type "int"; expected "Type[object]"  [arg-type]
(trezor)micropython/tests/pyb/can.py:72:14: error: Argument 1 to "len" has incompatible type "object"; expected "Sized"  [arg-type]
(trezor)micropython/tests/pyb/can.py:77:14: error: Argument 1 to "len" has incompatible type "object"; expected "Sized"  [arg-type]
(trezor)micropython/tests/pyb/can.py:82:14: error: Argument 1 to "len" has incompatible type "object"; expected "Sized"  [arg-type]
(trezor)micropython/tests/pyb/can.py:87:14: error: Argument 1 to "len" has incompatible type "object"; expected "Sized"  [arg-type]
