[RRepo](DiNitride)GAFBot
(DiNitride)GAFBot/modules/spotify.py:9: error: Module 'utils' has no attribute 'net'  [attr-defined]
(DiNitride)GAFBot/modules/gaf.py:5: error: Module 'utils' has no attribute 'checks'  [attr-defined]
(DiNitride)GAFBot/modules/admin.py:8: error: Module 'utils' has no attribute 'reaction_menu'  [attr-defined]
(DiNitride)GAFBot/modules/admin.py:11: error: Need type annotation for 'CONFIG'  [var-annotated]
Found 4 errors in 3 files (checked 15 source files)

[RRepo](jaantoots)bridgeview
(jaantoots)bridgeview/render/labels.py:5: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 7 source files)

[RRepo](CivicTechTO)ttc_subway_times
Success: no issues found in 7 source files

[RRepo](pytest-dev)pluggy
(pytest-dev)pluggy/src/pluggy/manager.py:2: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 20 source files)

[RRepo](romanpitak)torrentfile
Success: no issues found in 2 source files

[RRepo](BlackHC)mdp
(BlackHC)mdp/blackhc/mdp/dsl/ast.py:65: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(BlackHC)mdp/blackhc/mdp/dsl/ast.py:70: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(BlackHC)mdp/blackhc/mdp/__init__.py:60: error: Need type annotation for 'deduped_outcomes'  [var-annotated]
(BlackHC)mdp/blackhc/mdp/__init__.py:77: error: Argument 1 of "get_choices" is incompatible with supertype "Outcome"; supertype defines the argument type as "Iterable[Outcome]"  [override]
(BlackHC)mdp/blackhc/mdp/__init__.py:89: error: Argument 1 of "get_choices" is incompatible with supertype "Outcome"; supertype defines the argument type as "Iterable[Outcome]"  [override]
Found 5 errors in 2 files (checked 9 source files)

[RRepo](siddhantgoel)tornado-sqlalchemy
(siddhantgoel)tornado-sqlalchemy/tests/_common.py:17: error: Variable "_common.Base" is not valid as a type  [valid-type]
(siddhantgoel)tornado-sqlalchemy/tests/_common.py:17: error: Invalid base class "Base"  [misc]
(siddhantgoel)tornado-sqlalchemy/examples/tornado_web.py:17: error: Variable "tornado_web.DeclarativeBase" is not valid as a type  [valid-type]
(siddhantgoel)tornado-sqlalchemy/examples/tornado_web.py:17: error: Invalid base class "DeclarativeBase"  [misc]
Found 4 errors in 2 files (checked 7 source files)

[RRepo](paulhoule)gastrodon
(paulhoule)gastrodon/gastrodon/domain/__init__.py:75: error: Need type annotation for 'initial_data'  [var-annotated]
Found 1 error in 1 file (checked 1 source file)

[RRepo](kovidgoyal)kitty
(kovidgoyal)kitty/kittens/choose/main.py:11: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 64 source files)

[RRepo](mbourqui)django-celery-growthmonitor
(mbourqui)django-celery-growthmonitor/celery_growthmonitor/models/job.py:18: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 11 source files)

[RRepo](legoktm)toolforge
(legoktm)toolforge/tests/main_test.py:27: error: Cannot infer type of lambda  [misc]
Found 1 error in 1 file (checked 2 source files)

[RRepo](dpausp)arguments

[RRepo](clarkgrubb)data-tools
Success: no issues found in 16 source files

[RRepo](liweitianux)atoolbox
(liweitianux)atoolbox/cli/dict.py:89: error: Missing parentheses in call to 'print'. Did you mean print(RED+BOLD+word+DEFAULT)?  [syntax]
Found 1 error in 1 file (checked 56 source files)

[RRepo](just806me)voiceru_bot
(just806me)voiceru_bot/extentions.py:56: error: "Enum" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
Found 1 error in 1 file (checked 3 source files)

[RRepo](ICTU)quality-time
(ICTU)quality-time/components/server/src/utilities/functions.py: error: Duplicate module named 'functions' (also at '/home/bew/archive/typed_project/(ICTU)quality-time/components/collector/src/utilities/functions.py')  [misc]
Found 1 error in 1 file (checked 92 source files)

[RRepo](Karaage-Cluster)karaage
(Karaage-Cluster)karaage/karaage/templatetags/machines.py: error: Duplicate module named 'machines' (also at '/home/bew/archive/typed_project/(Karaage-Cluster)karaage/karaage/machines/views/machines.py')  [misc]
(Karaage-Cluster)karaage/karaage/templatetags/machines.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 129 source files)

[RRepo](mokemokechicken)keras_npi
(mokemokechicken)keras_npi/src/npi/add/lib.py:125: error: Need type annotation for 'step_queue_stack' (hint: "step_queue_stack: List[<type>] = ...")  [var-annotated]
(mokemokechicken)keras_npi/src/npi/add/lib.py:126: error: Need type annotation for 'sub_program' (hint: "sub_program: Dict[<type>, <type>] = ...")  [var-annotated]
(mokemokechicken)keras_npi/src/npi/add/lib.py:192: error: Incompatible types in assignment (expression has type "Tuple[Any, WriteProgram, Tuple[int, Any]]", target has type "Tuple[WriteProgram, Tuple[int, Any]]")  [assignment]
(mokemokechicken)keras_npi/src/npi/add/lib.py:208: error: Argument 1 to "append" of "list" has incompatible type "Tuple[Any, MovePtrProgram, Tuple[int, int]]"; expected "Tuple[MovePtrProgram, Tuple[int, int]]"  [arg-type]
(mokemokechicken)keras_npi/src/npi/add/lib.py:217: error: Argument 1 to "append" of "list" has incompatible type "Tuple[Any, MovePtrProgram, Tuple[int, int]]"; expected "Tuple[MovePtrProgram, Tuple[int, int]]"  [arg-type]
(mokemokechicken)keras_npi/src/npi/add/lib.py:226: error: Argument 1 to "append" of "list" has incompatible type "Tuple[Any, MovePtrProgram, Tuple[int, int]]"; expected "Tuple[MovePtrProgram, Tuple[int, int]]"  [arg-type]
(mokemokechicken)keras_npi/src/npi/terminal_core.py:119: error: Need type annotation for 'step_list' (hint: "step_list: List[<type>] = ...")  [var-annotated]
Found 7 errors in 2 files (checked 6 source files)

[RRepo](Codepoints)unidump
Success: no issues found in 4 source files

[RRepo](EpicEricEE)ShopChest
Success: no issues found in 1 source file

[RRepo](hsoft)dupeguru
(hsoft)dupeguru/qt/directories_dialog.py:21: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 69 source files)

[RRepo](larbibaraka)Bitly_clone
(larbibaraka)Bitly_clone/bitly_clone/bitly__clone_app/models.py:43: error: syntax error in type comment  [syntax]
Found 1 error in 1 file (checked 2 source files)

[RRepo](haifengat)hf_at_py
(haifengat)hf_at_py/hfpy/strategy.py:271: error: Bracketed expression "[...]" is not valid as a type  [misc]
(haifengat)hf_at_py/hfpy/strategy.py:271: note: Did you mean "List[...]"?
(haifengat)hf_at_py/hfpy/strategy.py:275: error: Bracketed expression "[...]" is not valid as a type  [misc]
(haifengat)hf_at_py/hfpy/strategy.py:275: note: Did you mean "List[...]"?
(haifengat)hf_at_py/hfpy/strategy.py:287: error: Bracketed expression "[...]" is not valid as a type  [misc]
(haifengat)hf_at_py/hfpy/strategy.py:287: note: Did you mean "List[...]"?
(haifengat)hf_at_py/hfpy/strategy.py:291: error: Bracketed expression "[...]" is not valid as a type  [misc]
(haifengat)hf_at_py/hfpy/strategy.py:291: note: Did you mean "List[...]"?
(haifengat)hf_at_py/hfpy/strategy.py:329: error: Invalid type comment or annotation  [valid-type]
(haifengat)hf_at_py/hfpy/strategy.py:329: note: Suggestion: use OrderField[...] instead of OrderField(...)
(haifengat)hf_at_py/hfpy/strategy.py:333: error: Invalid type comment or annotation  [valid-type]
(haifengat)hf_at_py/hfpy/strategy.py:333: note: Suggestion: use TradeField[...] instead of TradeField(...)

[RRepo](kubeflow)examples
(kubeflow)examples/mnist/web-ui/mnist_client.py: error: Duplicate module named 'mnist_client' (also at '/home/bew/archive/typed_project/(kubeflow)examples/pytorch_mnist/web-ui/mnist_client.py')  [misc]
Found 1 error in 1 file (checked 88 source files)

[RRepo](codeforboston)cornerwise
(codeforboston)cornerwise/server/task/views.py: error: Duplicate module named 'views' (also at '/home/bew/archive/typed_project/(codeforboston)cornerwise/server/cornerwise/views.py')  [misc]
Found 1 error in 1 file (checked 84 source files)

[RRepo](aamalev)aiohttp_apiset
(aamalev)aiohttp_apiset/aiohttp_apiset/views.py:6: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 25 source files)

[RRepo](GOVCERT-LU)eml_parser
Success: no issues found in 6 source files

[RRepo](telegram-bots)telegram-channels-feed
(telegram-bots)telegram-channels-feed/bot/src/handler/commands/list.py:7: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 24 source files)

[RRepo](raphaelm)python-fints
(raphaelm)python-fints/fints/fields.py:186: error: Incompatible types in assignment (expression has type "Type[bool]", base class "TextField" defined the type as "Type[str]")  [assignment]
(raphaelm)python-fints/fints/fields.py:262: error: Incompatible types in assignment (expression has type "Type[date]", base class "NumericField" defined the type as "Type[int]")  [assignment]
(raphaelm)python-fints/fints/fields.py:280: error: Incompatible types in assignment (expression has type "Type[time]", base class "DigitsField" defined the type as "Type[str]")  [assignment]
(raphaelm)python-fints/fints/connection.py:33: error: Name 'FinTSConnectionError' is not defined  [name-defined]
Found 4 errors in 2 files (checked 13 source files)

[RRepo](hrsetyono)theme_pacific
(hrsetyono)theme_pacific/sample/python.py:29: error: Missing parentheses in call to 'print'. Did you mean print(queens)?  [syntax]
Found 1 error in 1 file (checked 2 source files)

[RRepo](pfalcon)micropython
(pfalcon)micropython/tests/micropython/viper_args.py:43: error: named arguments must follow bare *  [syntax]
Found 1 error in 1 file (checked 109 source files)

[RRepo](tfeldmann)organize
(tfeldmann)organize/organize/cli.py:34: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 46 source files)

[RRepo](ziirish)burp-ui
(ziirish)burp-ui/pkgs/burp-ui-agent/burpui_agent-decoy/__main__.py: error: Duplicate module named '__main__' (also at '/home/bew/archive/typed_project/(ziirish)burp-ui/pkgs/burp-ui-monitor/burpui_monitor-decoy/__main__.py')  [misc]
Found 1 error in 1 file (checked 57 source files)

[RRepo](klieret)anki-template-tester
(klieret)anki-template-tester/previewtemplate.py:115: error: Syntax error in type annotation  [syntax]
(klieret)anki-template-tester/previewtemplate.py:115: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(klieret)anki-template-tester/previewtemplate.py:134: error: Argument 1 to "groups" of "Match" has incompatible type "int"; expected "str"  [arg-type]
(klieret)anki-template-tester/previewtemplate.py:165: error: Incompatible return value type (got "Union[str, bool]", expected "bool")  [return-value]
Found 3 errors in 1 file (checked 2 source files)

[RRepo](vladcalin)gemstone
(vladcalin)gemstone/gemstone/discovery/base.py: error: Duplicate module named 'base' (also at '/home/bew/archive/typed_project/(vladcalin)gemstone/gemstone/event/transport/base.py')  [misc]
(vladcalin)gemstone/gemstone/discovery/base.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 51 source files)

[RRepo](apirobot)shmitter
(apirobot)shmitter/backend/shmitter/tweets/models.py: error: Duplicate module named 'models' (also at '/home/bew/archive/typed_project/(apirobot)shmitter/backend/shmitter/users/models.py')  [misc]
Found 1 error in 1 file (checked 30 source files)

[RRepo](labsquare)CuteVariant
(labsquare)CuteVariant/cutevariant/core/query.py:2: error: No parent module -- cannot perform relative import  [misc]
(labsquare)CuteVariant/cutevariant/core/query.py:3: error: No parent module -- cannot perform relative import  [misc]
Found 2 errors in 1 file (checked 31 source files)

[RRepo](jreese)tasky
(jreese)tasky/tests/stats.py: error: Duplicate module named 'stats' (also at '/home/bew/archive/typed_project/(jreese)tasky/tasky/stats.py')  [misc]
Found 1 error in 1 file (checked 8 source files)

[RRepo](eliasdorneles)drawingapp-voc
(eliasdorneles)drawingapp-voc/drawingapp/app.py:8: error: Unexpected keyword argument "implements" for "__init_subclass__" of "object"  [call-arg]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:8: error: Name 'OnClickListener' is not defined  [name-defined]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:14: error: Name 'void' is not defined  [name-defined]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:17: error: Unexpected keyword argument "extends" for "__init_subclass__" of "object"  [call-arg]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:18: error: "super" not callable  [operator]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:18: error: Name 'context' is not defined  [name-defined]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:41: error: Name 'void' is not defined  [name-defined]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:47: error: Name 'void' is not defined  [name-defined]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:64: error: "DrawingView" has no attribute "invalidate"  [attr-defined]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:67: error: Name 'void' is not defined  [name-defined]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:72: error: Name 'void' is not defined  [name-defined]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:76: error: Name 'void' is not defined  [name-defined]
(eliasdorneles)drawingapp-voc/drawingapp/app.py:79: error: "DrawingView" has no attribute "invalidate"  [attr-defined]
Found 13 errors in 1 file (checked 1 source file)

[RRepo](taige)PyTools
(taige)PyTools/tsproxy/https_listener.py:4: error: Name 'HttpListener' is not defined  [name-defined]
(taige)PyTools/simcity/shop.py:5: error: Name 'Factories' is not defined  [name-defined]
(taige)PyTools/simcity/shop.py:28: error: Name 'Schedule' is not defined  [name-defined]
(taige)PyTools/simcity/shop.py:35: error: Name 'Product' is not defined  [name-defined]
(taige)PyTools/simcity/shop.py:37: error: Need type annotation for '_consumed' (hint: "_consumed: List[<type>] = ...")  [var-annotated]
(taige)PyTools/simcity/shop.py:45: error: Name 'Product' is not defined  [name-defined]
(taige)PyTools/simcity/shop.py:73: error: Name 'Product' is not defined  [name-defined]
(taige)PyTools/simcity/shop.py:130: error: Name 'FactorySchedule' is not defined  [name-defined]
(taige)PyTools/simcity/shop.py:138: error: Name 'time' is not defined  [name-defined]
(taige)PyTools/simcity/shop.py:138: error: Name 'zero_timing' is not defined  [name-defined]
(taige)PyTools/simcity/warehouse.py:5: error: Name 'MaterialList' is not defined  [name-defined]
(taige)PyTools/simcity/warehouse.py:42: error: Name 'Product' is not defined  [name-defined]
(taige)PyTools/tsproxy/shell.py:18: error: Module 'tsproxy' has no attribute 'topendns'  [attr-defined]
(taige)PyTools/tsproxy/streams.py:7: error: Module 'tsproxy' has no attribute 'topendns'  [attr-defined]
(taige)PyTools/tsproxy/streams.py:318: error: The return type of a generator function should be "Generator" or one of its supertypes  [misc]
(taige)PyTools/tsproxy/streams.py:321: error: "StreamReader" has no attribute "_limit"  [attr-defined]
(taige)PyTools/tsproxy/streams.py:325: error: "StreamReader" has no attribute "_loop"  [attr-defined]
(taige)PyTools/tsproxy/streams.py:327: error: "yield from" can't be applied to "Coroutine[Any, Any, bytes]"  [misc]
(taige)PyTools/tsproxy/streams.py:329: error: "yield from" can't be applied to "Coroutine[Any, Any, bytes]"  [misc]
(taige)PyTools/tsproxy/streams.py:340: error: The return type of a generator function should be "Generator" or one of its supertypes  [misc]
(taige)PyTools/tsproxy/streams.py:340: error: Signature of "read" incompatible with supertype "StreamReader"  [override]
(taige)PyTools/tsproxy/streams.py:344: error: Function does not return a value  [func-returns-value]
Found 22 errors in 5 files (checked 7 source files)

[RRepo](rtfd)readthedocs.org
(rtfd)readthedocs.org/readthedocs/gold/forms.py: error: Duplicate module named 'forms' (also at '/home/bew/archive/typed_project/(rtfd)readthedocs.org/readthedocs/builds/forms.py')  [misc]
Found 1 error in 1 file (checked 217 source files)

[RRepo](xgouchet)AutoMergeTool
(xgouchet)AutoMergeTool/automergetool/amt_launcher.py:22: error: misplaced type annotation  [syntax]
Found 1 error in 1 file (checked 29 source files)

[RRepo](NEU-Partner)NEU_Scripts
(NEU-Partner)NEU_Scripts/ipgw_login_python3/main.py:47: error: Incompatible return value type (got "bytes", expected "str")  [return-value]
Found 1 error in 1 file (checked 1 source file)

[RRepo](s-leger)archipack
(s-leger)archipack/pygeos/index_chain.py:100: error: "MonotoneChain" has no attribute "computeSelect"; maybe "_computeSelect"?  [attr-defined]
(s-leger)archipack/pygeos/index_chain.py:174: error: Need type annotation for 'startIndex' (hint: "startIndex: List[<type>] = ...")  [var-annotated]
(s-leger)archipack/pygeos/index_chain.py:284: error: "MonotoneChainOverlapAction" has no attribute "_overlapSeg1"; maybe "overlapSeg1", "overlapSeg2", or "_overlap"?  [attr-defined]
(s-leger)archipack/pygeos/index_chain.py:285: error: "MonotoneChainOverlapAction" has no attribute "_overlapSeg2"; maybe "overlapSeg2", "overlapSeg1", or "_overlap"?  [attr-defined]
(s-leger)archipack/pygeos/index_chain.py:286: error: "MonotoneChainOverlapAction" has no attribute "_overlapSeg1"; maybe "overlapSeg1", "overlapSeg2", or "_overlap"?  [attr-defined]
(s-leger)archipack/pygeos/index_chain.py:286: error: "MonotoneChainOverlapAction" has no attribute "_overlapSeg2"; maybe "overlapSeg2", "overlapSeg1", or "_overlap"?  [attr-defined]
(s-leger)archipack/pygeos/op_simple.py:46: error: "EndpointInfo" has no attribute "dregree"; maybe "degree"?  [attr-defined]
(s-leger)archipack/archipack_2d_layout.py:92: error: Value of type "object" is not indexable  [index]
(s-leger)archipack/archipack_2d_layout.py:93: error: Value of type "object" is not indexable  [index]
Found 9 errors in 3 files (checked 27 source files)

[RRepo](ZeoAlliance)aiomongo
(ZeoAlliance)aiomongo/tests/conftest.py: error: Duplicate module named 'conftest' (also at '/home/bew/archive/typed_project/(ZeoAlliance)aiomongo/benchmark/conftest.py')  [misc]
Found 1 error in 1 file (checked 16 source files)

[RRepo](Otetz)modulbank
Success: no issues found in 4 source files

[RRepo](the-it)WS_THEbotIT
(the-it)WS_THEbotIT/scripts/service/ws_re/register/base.py: error: Duplicate module named 'base' (also at '/home/bew/archive/typed_project/(the-it)WS_THEbotIT/scripts/service/ws_re/download/base.py')  [misc]
Found 1 error in 1 file (checked 100 source files)

[RRepo](PythonJS)PythonJS
(PythonJS)PythonJS/regtests/webclgl/gpu_sibling_class.py:16: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 126 source files)

[RRepo](Reaktoro)Reaktoro
(Reaktoro)Reaktoro/tests/conftest.py: error: Duplicate module named 'conftest' (also at '/home/bew/archive/typed_project/(Reaktoro)Reaktoro/Reaktoro/conftest.py')  [misc]
Found 1 error in 1 file (checked 20 source files)

[RRepo](DerAtrox)backup-rotation.py
(DerAtrox)backup-rotation.py/backup-rotation.py:211: error: Incompatible types in assignment (expression has type "List[Dict[str, object]]", target has type "Dict[str, object]")  [assignment]
Found 1 error in 1 file (checked 1 source file)

[RRepo](fnl)medic
(fnl)medic/src/medic/crud.py:30: error: Function "builtins.iter" is not valid as a type  [valid-type]
(fnl)medic/src/medic/crud.py:30: note: Perhaps you need "Callable[...]" or a callback protocol?
(fnl)medic/src/medic/crud.py:35: error: Function "builtins.iter" is not valid as a type  [valid-type]
(fnl)medic/src/medic/crud.py:35: note: Perhaps you need "Callable[...]" or a callback protocol?
(fnl)medic/src/medic/crud.py:40: error: Invalid type comment or annotation  [valid-type]
(fnl)medic/src/medic/crud.py:40: note: Suggestion: use list[...] instead of list(...)
(fnl)medic/src/medic/crud.py:40: note: Suggestion: use iter[...] instead of iter(...)
(fnl)medic/src/medic/crud.py:66: error: Invalid type comment or annotation  [valid-type]
(fnl)medic/src/medic/crud.py:66: note: Suggestion: use list[...] instead of list(...)
(fnl)medic/src/medic/crud.py:83: error: Function "builtins.iter" is not valid as a type  [valid-type]
(fnl)medic/src/medic/crud.py:83: note: Perhaps you need "Callable[...]" or a callback protocol?
(fnl)medic/src/medic/crud.py:124: error: iter? has no attribute "__iter__" (not iterable)  [attr-defined]
(fnl)medic/src/medic/crud.py:162: error: Function "builtins.iter" is not valid as a type  [valid-type]
(fnl)medic/src/medic/crud.py:162: note: Perhaps you need "Callable[...]" or a callback protocol?
(fnl)medic/src/medic/crud.py:169: error: iter? has no attribute "__iter__" (not iterable)  [attr-defined]
(fnl)medic/src/medic/crud.py:198: error: Function "builtins.iter" is not valid as a type  [valid-type]
(fnl)medic/src/medic/crud.py:198: note: Perhaps you need "Callable[...]" or a callback protocol?
(fnl)medic/src/medic/crud.py:211: error: iter? has no attribute "__iter__" (not iterable)  [attr-defined]
(fnl)medic/src/medic/crud.py:224: error: Function "builtins.iter" is not valid as a type  [valid-type]
(fnl)medic/src/medic/crud.py:224: note: Perhaps you need "Callable[...]" or a callback protocol?
(fnl)medic/src/medic/crud.py:226: error: Need type annotation for 'pub_types' (hint: "pub_types: List[<type>] = ...")  [var-annotated]
(fnl)medic/src/medic/crud.py:227: error: Need type annotation for 'citation' (hint: "citation: List[<type>] = ...")  [var-annotated]
(fnl)medic/src/medic/crud.py:230: error: iter? has no attribute "__iter__" (not iterable)  [attr-defined]
(fnl)medic/src/medic/crud.py:292: error: Function "builtins.iter" is not valid as a type  [valid-type]
(fnl)medic/src/medic/crud.py:292: note: Perhaps you need "Callable[...]" or a callback protocol?
(fnl)medic/src/medic/test/crud_test.py:65: error: Not all arguments converted during string formatting  [str-format]
(fnl)medic/src/medic/web.py:19: error: Name 'HTTPResponse' already defined (possibly by an import)  [no-redef]
(fnl)medic/src/medic/web.py:21: error: Name 'build_opener' already defined (possibly by an import)  [no-redef]
Found 18 errors in 3 files (checked 4 source files)

[RRepo](KmolYuan)Pyslvs-PyQt5
(KmolYuan)Pyslvs-PyQt5/core/synthesis/dimensional_synthesis/dialogs/chart.py: error: Duplicate module named 'chart' (also at '/home/bew/archive/typed_project/(KmolYuan)Pyslvs-PyQt5/core/graphics/chart.py')  [misc]
(KmolYuan)Pyslvs-PyQt5/core/synthesis/dimensional_synthesis/dialogs/chart.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 55 source files)

[RRepo](Zo0x)hedhes
(Zo0x)hedhes/app/views.py:4: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 8 source files)

[RRepo](MTgeophysics)mtpy
(MTgeophysics)mtpy/mtpy/contrib/netcdf/winglink_to_netCDF.py:18: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 192 source files)

[RRepo](winpython)winpython_afterdoc
(winpython)winpython_afterdoc/docs/WASM_almar_klein_demo/play_python.py:8: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 6 source files)

[RRepo](IgniparousTempest)py-minutiae-viewer
Success: no issues found in 9 source files

[RRepo](denisenkom)pytds
(denisenkom)pytds/src/pytds/tls.py:10: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 15 source files)

[RRepo](mdevaev)emonoda
(mdevaev)emonoda/emonoda/fmt.py:28: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 47 source files)

[RRepo](rokups)paste2box
(rokups)paste2box/gui/gui.py:27: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 22 source files)

[RRepo](ralph-group)pymeasure
(ralph-group)pymeasure/pymeasure/instruments/lakeshore/adapters.py: error: Duplicate module named 'adapters' (also at '/home/bew/archive/typed_project/(ralph-group)pymeasure/pymeasure/instruments/danfysik/adapters.py')  [misc]
Found 1 error in 1 file (checked 86 source files)

[RRepo](kensk8er)langdist
(kensk8er)langdist/langdist/transliterator.py:104: error: "MappingView" has no attribute "__iter__" (not iterable)  [attr-defined]

[RRepo](zhuoju36)StructEngPy
(zhuoju36)StructEngPy/fe_solver/dynamic.py:15: error: Module 'fe_model' has no attribute 'Model'  [attr-defined]
(zhuoju36)StructEngPy/fe_solver/dynamic.py:85: error: Name 'eigen_mode' is not defined  [name-defined]
(zhuoju36)StructEngPy/fe_solver/dynamic.py:121: error: Need type annotation for 'R' (hint: "R: List[<type>] = ...")  [var-annotated]
(zhuoju36)StructEngPy/fe_solver/dynamic.py:141: error: Name 'R_' is not defined  [name-defined]
(zhuoju36)StructEngPy/fe_solver/dynamic.py:152: error: Name 'eigen_mode' is not defined  [name-defined]
(zhuoju36)StructEngPy/fe_solver/dynamic.py:167: error: Name 'm' is not defined  [name-defined]
(zhuoju36)StructEngPy/fe_solver/dynamic.py:212: error: Name 'self' is not defined  [name-defined]
(zhuoju36)StructEngPy/fe_solver/dynamic.py:218: error: Name 'self' is not defined  [name-defined]
(zhuoju36)StructEngPy/fe_solver/dynamic.py:226: error: Name 'pd' is not defined  [name-defined]
(zhuoju36)StructEngPy/fe_solver/dynamic.py:244: error: Name 'self' is not defined  [name-defined]
(zhuoju36)StructEngPy/fe_solver/dynamic.py:255: error: Name 'self' is not defined  [name-defined]
(zhuoju36)StructEngPy/fe_solver/dynamic.py:268: error: Name 'pd' is not defined  [name-defined]
(zhuoju36)StructEngPy/fe_solver/static.py:12: error: Module 'fe_model' has no attribute 'Model'  [attr-defined]
(zhuoju36)StructEngPy/object_model/__init__.py:9: error: Module 'fe_model' has no attribute 'Model'  [attr-defined]

[RRepo](sourcegraph)python-langserver
(sourcegraph)python-langserver/langserver/fs.py:26: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(sourcegraph)python-langserver/langserver/fs.py:30: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(sourcegraph)python-langserver/langserver/fs.py:38: error: Invalid self argument "FileSystem" to attribute function "listdir" with type "Callable[[str, Any], List[str]]"  [misc]
(sourcegraph)python-langserver/langserver/fs.py:149: error: Signature of "open" incompatible with supertype "FileSystem"  [override]
(sourcegraph)python-langserver/langserver/fs.py:154: error: Signature of "listdir" incompatible with supertype "FileSystem"  [override]
(sourcegraph)python-langserver/langserver/fs.py:158: error: Need type annotation for 'entries' (hint: "entries: Dict[<type>, <type>] = ...")  [var-annotated]
(sourcegraph)python-langserver/langserver/fs.py:173: error: Incompatible return value type (got "ValuesView[Entry]", expected "List[Entry]")  [return-value]
(sourcegraph)python-langserver/langserver/fs.py:183: error: Signature of "open" incompatible with supertype "FileSystem"  [override]
(sourcegraph)python-langserver/langserver/fs.py:195: error: Signature of "listdir" incompatible with supertype "FileSystem"  [override]
(sourcegraph)python-langserver/test/repos/fizzbuzz_service/fizzbuzz_service/checkers/fizzbuzz/fizzbuzz_checker.py:1: error: Relative import climbs too many namespaces  [misc]
(sourcegraph)python-langserver/test/repos/fizzbuzz_service/fizzbuzz_service/checkers/fizzbuzz/fizzbuzz_checker.py:2: error: Relative import climbs too many namespaces  [misc]
(sourcegraph)python-langserver/test/repos/fizzbuzz_service/fizzbuzz_service/string_deciders/number_decision.py:2: error: Relative import climbs too many namespaces  [misc]
(sourcegraph)python-langserver/test/repos/fizzbuzz_service/fizzbuzz_service/string_deciders/number_decision.py:3: error: Relative import climbs too many namespaces  [misc]
(sourcegraph)python-langserver/test/repos/fizzbuzz_service/fizzbuzz_service/string_deciders/number_decision.py:4: error: Relative import climbs too many namespaces  [misc]

[RRepo](mosen)commandment
(mosen)commandment/commandment/dep/app.py: error: Duplicate module named 'app' (also at '/home/bew/archive/typed_project/(mosen)commandment/commandment/apns/app.py')  [misc]
Found 1 error in 1 file (checked 105 source files)

[RRepo](josuemontano)API-platform
(josuemontano)API-platform/tests/fixtures.py:3: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 21 source files)

[RRepo](halcy)MastodonToTwitter
Success: no issues found in 5 source files

[RRepo](evernym)sovrin-client-rust
(evernym)sovrin-client-rust/wrappers/python/sovrin/ledger.py:2: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 7 source files)

[RRepo](socialwifi)jsonapi-requests
Success: no issues found in 13 source files

[RRepo](jkbrzt)cointrol
(jkbrzt)cointrol/cointrol/trader/workers.py:20: error: No parent module -- cannot perform relative import  [misc]
(jkbrzt)cointrol/cointrol/trader/workers.py:21: error: No parent module -- cannot perform relative import  [misc]
Found 2 errors in 1 file (checked 17 source files)

[RRepo](chfoo)tellnext
Success: no issues found in 8 source files

[RRepo](Frizz925)gbf-autopilot
(Frizz925)gbf-autopilot/test/controller/window_test.py:4: error: Module 'controller.window' has no attribute 'DummyWindow'  [attr-defined]
(Frizz925)gbf-autopilot/test/controller/window_test.py:5: error: Module 'controller' has no attribute 'InputController'  [attr-defined]
(Frizz925)gbf-autopilot/server.py:13: error: Module 'controller.window' has no attribute 'Window'  [attr-defined]
(Frizz925)gbf-autopilot/server.py:14: error: Module 'controller' has no attribute 'JsonRpcMethods'  [attr-defined]
(Frizz925)gbf-autopilot/server.py:14: error: Module 'controller' has no attribute 'JsonRpcClient'  [attr-defined]
(Frizz925)gbf-autopilot/server.py:14: error: Module 'controller' has no attribute 'InputController'  [attr-defined]
Found 6 errors in 2 files (checked 10 source files)

[RRepo](blackmatrix7)apizen
(blackmatrix7)apizen/app/apizen/schema.py:142: error: 'bool' is not a valid base class  [misc]
Found 1 error in 1 file (checked 22 source files)

[RRepo](rtfd)sphinx-autoapi
(rtfd)sphinx-autoapi/autoapi/documenters.py:11: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 31 source files)

[RRepo](timabbott)zulip
(timabbott)zulip/corporate/views.py: error: Duplicate module named 'views' (also at '/home/bew/archive/typed_project/(timabbott)zulip/zilencer/views.py')  [misc]
Found 1 error in 1 file (checked 236 source files)

[RRepo](meyt)sqlalchemy-dict
(meyt)sqlalchemy-dict/sqlalchemy_dict/field.py:63: error: Incompatible types in assignment (expression has type "bool", target has type "str")  [assignment]
(meyt)sqlalchemy-dict/sqlalchemy_dict/field.py:88: error: Incompatible types in assignment (expression has type "bool", target has type "str")  [assignment]
(meyt)sqlalchemy-dict/sqlalchemy_dict/field.py:91: error: Incompatible types in assignment (expression has type "bool", target has type "str")  [assignment]
(meyt)sqlalchemy-dict/sqlalchemy_dict/field.py:118: error: Incompatible types in assignment (expression has type "bool", target has type "str")  [assignment]
(meyt)sqlalchemy-dict/sqlalchemy_dict/field.py:121: error: Incompatible types in assignment (expression has type "bool", target has type "str")  [assignment]
(meyt)sqlalchemy-dict/sqlalchemy_dict/formatter.py:51: error: Bracketed expression "[...]" is not valid as a type  [misc]
(meyt)sqlalchemy-dict/sqlalchemy_dict/formatter.py:51: note: Did you mean "List[...]"?
(meyt)sqlalchemy-dict/sqlalchemy_dict/formatter.py:61: error: Bracketed expression "[...]" is not valid as a type  [misc]
(meyt)sqlalchemy-dict/sqlalchemy_dict/formatter.py:61: note: Did you mean "List[...]"?
(meyt)sqlalchemy-dict/sqlalchemy_dict/formatter.py:71: error: Bracketed expression "[...]" is not valid as a type  [misc]
(meyt)sqlalchemy-dict/sqlalchemy_dict/formatter.py:71: note: Did you mean "List[...]"?
(meyt)sqlalchemy-dict/sqlalchemy_dict/base_model.py:133: error: Incompatible types in assignment (expression has type "str", variable has type "List[Any]")  [assignment]
(meyt)sqlalchemy-dict/sqlalchemy_dict/base_model.py:186: error: "Type[BaseModel]" has no attribute "__table__"  [attr-defined]
(meyt)sqlalchemy-dict/sqlalchemy_dict/base_model.py:248: error: Need type annotation for 'result' (hint: "result: Dict[<type>, <type>] = ...")  [var-annotated]
(meyt)sqlalchemy-dict/sqlalchemy_dict/tests/test_base_model.py:70: error: Variable "test_base_model.DeclarativeBase" is not valid as a type  [valid-type]
(meyt)sqlalchemy-dict/sqlalchemy_dict/tests/test_base_model.py:70: error: Invalid base class "DeclarativeBase"  [misc]
(meyt)sqlalchemy-dict/sqlalchemy_dict/tests/test_base_model.py:76: error: Variable "test_base_model.DeclarativeBase" is not valid as a type  [valid-type]
(meyt)sqlalchemy-dict/sqlalchemy_dict/tests/test_base_model.py:76: error: Invalid base class "DeclarativeBase"  [misc]
(meyt)sqlalchemy-dict/sqlalchemy_dict/tests/test_base_model.py:82: error: Variable "test_base_model.DeclarativeBase" is not valid as a type  [valid-type]
(meyt)sqlalchemy-dict/sqlalchemy_dict/tests/test_base_model.py:82: error: Invalid base class "DeclarativeBase"  [misc]
(meyt)sqlalchemy-dict/sqlalchemy_dict/tests/test_base_model.py:152: error: Name 'is_visible' already defined on line 148  [no-redef]
(meyt)sqlalchemy-dict/sqlalchemy_dict/tests/test_base_model.py:157: error: Name 'is_visible' already defined on line 148  [no-redef]
Found 19 errors in 4 files (checked 6 source files)

[RRepo](Morwenn)cpp-sort
(Morwenn)cpp-sort/test_package/conanfile.py: error: Duplicate module named 'conanfile' (also at '/home/bew/archive/typed_project/(Morwenn)cpp-sort/conanfile.py')  [misc]
(Morwenn)cpp-sort/test_package/conanfile.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 5 source files)

[RRepo](IlyaGusev)rnnmorph
(IlyaGusev)rnnmorph/rnnmorph/data_preparation/word_form.py:28: error: Need type annotation for 'possible_forms' (hint: "possible_forms: List[<type>] = ...")  [var-annotated]
(IlyaGusev)rnnmorph/rnnmorph/data_preparation/grammeme_vectorizer.py:128: error: Need type annotation for 'vector' (hint: "vector: List[<type>] = ...")  [var-annotated]
(IlyaGusev)rnnmorph/rnnmorph/data_preparation/loader.py:26: error: Need type annotation for 'char_set' (hint: "char_set: Set[<type>] = ...")  [var-annotated]
(IlyaGusev)rnnmorph/rnnmorph/data_preparation/loader.py:46: error: Incompatible types in assignment (expression has type "str", variable has type "Set[Any]")  [assignment]
(IlyaGusev)rnnmorph/rnnmorph/batch_generator.py:42: error: Need type annotation for 'buckets'  [var-annotated]
(IlyaGusev)rnnmorph/rnnmorph/predictor.py:185: error: "str" has no attribute "normal_form"  [attr-defined]
(IlyaGusev)rnnmorph/rnnmorph/predictor.py:189: error: Need type annotation for 'pos_map'  [var-annotated]
Found 7 errors in 5 files (checked 17 source files)

[RRepo](MaT1g3R)YasenBaka
(MaT1g3R)YasenBaka/bot/anime_searcher.py:13: error: Need type annotation for 'names' (hint: "names: List[<type>] = ...")  [var-annotated]
(MaT1g3R)YasenBaka/music/abstract_source.py:7: error: Function "builtins.callable" is not valid as a type  [valid-type]
(MaT1g3R)YasenBaka/music/abstract_source.py:7: note: Perhaps you need "Callable[...]" or a callback protocol?

[RRepo](calebj)Red-DiscordBot
(calebj)Red-DiscordBot/redbot/cogs/alias/__init__.py: error: Duplicate module named 'alias' (also at '/home/bew/archive/typed_project/(calebj)Red-DiscordBot/redbot/pytest/alias.py')  [misc]
(calebj)Red-DiscordBot/redbot/cogs/alias/__init__.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 102 source files)

[RRepo](fedora-infra)bodhi
(fedora-infra)bodhi/bodhi/messages/utils.py: error: Duplicate module named 'utils' (also at '/home/bew/archive/typed_project/(fedora-infra)bodhi/devel/ci/integration/tests/utils.py')  [misc]
(fedora-infra)bodhi/bodhi/messages/utils.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 116 source files)

[RRepo](ingokegel)intellij-community
(ingokegel)intellij-community/python/testData/editing/firstParamSimple.after.py:2: error: unexpected EOF while parsing  [syntax]
Found 1 error in 1 file (checked 3954 source files)

[RRepo](CompLab-StonyBrook)mgproc

[RRepo](googleapis)google-cloud-java
(googleapis)google-cloud-java/google-cloud-clients/google-cloud-firestore/synth.py: error: Duplicate module named 'synth' (also at '/home/bew/archive/typed_project/(googleapis)google-cloud-java/google-cloud-clients/google-cloud-bigtable/synth.py')  [misc]
Found 1 error in 1 file (checked 4 source files)

[RRepo](mgerst)pyquiz
(mgerst)pyquiz/jeopardy/controllers/utils.py:4: error: Relative import climbs too many namespaces  [misc]
(mgerst)pyquiz/jeopardy/controllers/utils.py:4: error: Relative import climbs too many namespaces  [misc]
Found 2 errors in 1 file (checked 9 source files)

[RRepo](JuezUN)INGInious
(JuezUN)INGInious/inginious/frontend/pages/course_admin/utils.py: error: Duplicate module named 'utils' (also at '/home/bew/archive/typed_project/(JuezUN)INGInious/inginious/frontend/pages/utils.py')  [misc]
(JuezUN)INGInious/inginious/frontend/pages/course_admin/utils.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 89 source files)

[RRepo](soxofaan)dahuffman
Success: no issues found in 8 source files

[RRepo](darkfeline)mir.dlsite
(darkfeline)mir.dlsite/mir/dlsite/workinfo.py:44: error: Name 'Optional' is not defined  [name-defined]
(darkfeline)mir.dlsite/mir/dlsite/workinfo.py:44: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Optional")
(darkfeline)mir.dlsite/mir/dlsite/workinfo.py:45: error: Name 'Optional' is not defined  [name-defined]
(darkfeline)mir.dlsite/mir/dlsite/workinfo.py:45: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Optional")
(darkfeline)mir.dlsite/mir/dlsite/workinfo.py:46: error: Name 'Optional' is not defined  [name-defined]
(darkfeline)mir.dlsite/mir/dlsite/workinfo.py:46: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Optional")

[RRepo](KeepSafe)aiohttp
(KeepSafe)aiohttp/aiohttp/web_routedef.py:19: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 42 source files)

[RRepo](mapsme)omim
(mapsme)omim/tools/download_statistics/aggregator.py:14: error: inconsistent use of tabs and spaces in indentation  [syntax]
Found 1 error in 1 file (checked 82 source files)

[RRepo](openatx)facebook-wda
Success: no issues found in 6 source files

[RRepo](olivierkes)manuskript
(olivierkes)manuskript/manuskript/ui/exporters/exporter.py: error: Duplicate module named 'exporter' (also at '/home/bew/archive/typed_project/(olivierkes)manuskript/manuskript/exporter/__init__.py')  [misc]
(olivierkes)manuskript/manuskript/ui/exporters/exporter.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 113 source files)

[RRepo](google)python-spanner-orm
(google)python-spanner-orm/spanner_orm/admin/metadata.py: error: Duplicate module named 'metadata' (also at '/home/bew/archive/typed_project/(google)python-spanner-orm/spanner_orm/metadata.py')  [misc]
(google)python-spanner-orm/spanner_orm/admin/metadata.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 30 source files)

[RRepo](TingPing)transmission-remote-gnome
(TingPing)transmission-remote-gnome/trg/torrent_file.py:18: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 17 source files)

[RRepo](bogdanvuk)sydpy
(bogdanvuk)sydpy/tests/test_sata.py:18: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 70 source files)

[RRepo](pydata)xarray
(pydata)xarray/xarray/backends/cfgrib_.py:3: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 75 source files)

[RRepo](ze-phyr-us)pearhash
Success: no issues found in 2 source files

[RRepo](pektin)jam
(pektin)jam/compiler/errors.py:124: error: No parent module -- cannot perform relative import  [misc]
Found 1 error in 1 file (checked 47 source files)

[RRepo](piontec)docker-enforcer
(piontec)docker-enforcer/dockerenforcer/config.py:22: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")  [assignment]
(piontec)docker-enforcer/dockerenforcer/config.py:23: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")  [assignment]

[RRepo](illagrenan)django-brotli
(illagrenan)django-brotli/tests/test_middleware.py:47: error: Unsupported target for indexed assignment  [index]
Found 1 error in 1 file (checked 3 source files)

[RRepo](massmutual)py4jdbc
(massmutual)py4jdbc/py4jdbc/exceptions/dbapi2.py: error: Duplicate module named 'dbapi2' (also at '/home/bew/archive/typed_project/(massmutual)py4jdbc/py4jdbc/dbapi2.py')  [misc]
(massmutual)py4jdbc/py4jdbc/exceptions/dbapi2.py: error: Are you missing an __init__.py?  [misc]
Found 2 errors in 1 file (checked 14 source files)

