(thorgate)tg-utils/tg_utils/admin.py:14:5: error: Name 'ReadOnlyAddAdminMixin' already defined on line 9  [no-redef]
(zutn)ACME/acme/exit_after.py:17:5: error: Name 'thread' already defined (possibly by an import)  [no-redef]
(carpyncho)feets/ez_setup.py:26:5: error: Name 'urlopen' already defined (possibly by an import)  [no-redef]
(ahawker)scratchdir/tests.py:16:5: error: Name 'pathlib' already defined (by an import)  [no-redef]
(biolink)ontobio/ontobio/io/gaference.py:151:17: error: Name 'extension_unit' already defined on line 144  [no-redef]
(nitely)regexy/regexy/compile/nfa.py:173:5: error: Name 'nodes' already defined on line 152  [no-redef]
(ZingBallyhoo)OverwatchDataManager/pyow/lib/withhacks/frameutils.py:14:5: error: Name 'threading' already defined (by an import)  [no-redef]
(FrederichRiver)neutrino/applications/form.py:22:1: error: Name 'formStock' already defined on line 8  [no-redef]
(FrederichRiver)neutrino/applications/finance/event_stock.py:13:1: error: Name 'time' already defined (possibly by an import)  [no-redef]
(csxeba)brainforge/layers/fancy.py:81:9: error: Attribute 'mask' already defined on line 71  [no-redef]
(HurricaneLabs)machinae/src/machinae/sites/base.py:20:5: error: Name 'exceptions' already defined (by an import)  [no-redef]
(cgre-aachen)gempy/gempy/utils/extract_geomodeller_data.py:11:5: error: Name 'ET' already defined (by an import)  [no-redef]
(vert-x3)vertx-web/vertx-web/src/test/sockjs-protocol/unittest2/compatibility.py:91:5: error: Name 'catch_warnings' already defined (possibly by an import)  [no-redef]
(vert-x3)vertx-web/vertx-web/src/test/sockjs-protocol/unittest2/test/test_break.py:294:1: error: Name 'TestBreakDefaultIntHandler' already defined on line 272  [no-redef]
(vert-x3)vertx-web/vertx-web/src/test/sockjs-protocol/unittest2/test/test_break.py:301:1: error: Name 'TestBreakSignalIgnored' already defined on line 279  [no-redef]
(vert-x3)vertx-web/vertx-web/src/test/sockjs-protocol/unittest2/test/test_break.py:308:1: error: Name 'TestBreakSignalDefault' already defined on line 286  [no-redef]
(pythonfoo)pythonfooLite/Level_08/generatoren.py:35:2: error: Name 'f' already defined on line 18  [no-redef]
(pythonfoo)pythonfooLite/Level_05/funktionen.py:11:1: error: Name 'funktion' already defined on line 5  [no-redef]
(pythonfoo)pythonfooLite/Level_05/funktionen.py:17:1: error: Name 'funktion' already defined on line 5  [no-redef]
(pythonfoo)pythonfooLite/Level_05/funktionen.py:28:1: error: Name 'funktion' already defined on line 5  [no-redef]
(pythonfoo)pythonfooLite/Level_05/funktionen.py:82:1: error: Name 'fun' already defined on line 69  [no-redef]
(SunDwarf)asyncqlio/asyncqlio/orm/schema/column.py:137:13: error: Attribute 'type' already defined on line 134  [no-redef]
(drssoccer55)RLBot/src/main/python/rlbot/utils/public_utils.py:10:5: error: Name 'httplib' already defined (possibly by an import)  [no-redef]
(futuresimple)triggear/app/clients/github_client.py:17:13: error: Attribute '__async_github' already defined on line 13  [no-redef]
(IDSIA)sacred/tests/test_observers/test_queue_mongo_observer.py:13:1: error: Name 'pymongo' already defined on line 10  [no-redef]
(akashin)HSE_AI_Labs/Lab_5/Content/Scripts/play.py:10:5: error: Name 'pickle' already defined (possibly by an import)  [no-redef]
(balabit)typesafety/features/steps/steps.py:36:2: error: Name 'write_file' already defined on line 31  [no-redef]
(python-cmd2)cmd2/tests/test_argparse.py:22:9: error: Name 'readline' already defined (possibly by an import)  [no-redef]
(python-cmd2)cmd2/tests/conftest.py:24:9: error: Name 'readline' already defined (possibly by an import)  [no-redef]
(python-cmd2)cmd2/tests/test_run_pyscript.py:16:5: error: Name 'mock' already defined (by an import)  [no-redef]
(python-cmd2)cmd2/cmd2/rl_utils.py:17:9: error: Name 'readline' already defined (possibly by an import)  [no-redef]
(freeipa)freeipa-pr-ci/ansible/callback_plugins/human_log.py:27:5: error: Name 'json' already defined (by an import)  [no-redef]
(kiwicom)iwant-bot/tests/unit/test_storage.py:87:2: error: Name 'test_postgres_storage_removes' already defined on line 71  [no-redef]
(mathLab)RBniCS/rbnics/utils/test/diff.py:66:2: error: Name '_diff_content' already defined on line 46  [no-redef]
(mathLab)RBniCS/rbnics/utils/test/diff.py:92:2: error: Name '_diff_content' already defined on line 46  [no-redef]
(mathLab)RBniCS/rbnics/utils/test/diff.py:112:2: error: Name '_diff_content' already defined on line 46  [no-redef]
(mathLab)RBniCS/rbnics/utils/io/folders.py:31:10: error: Name '__init__' already defined on line 27  [no-redef]
(mathLab)RBniCS/rbnics/backends/dolfin/wrapping/to_petsc4py.py:27:2: error: Name 'to_petsc4py' already defined on line 23  [no-redef]
(mathLab)RBniCS/rbnics/backends/dolfin/wrapping/to_petsc4py.py:31:2: error: Name 'to_petsc4py' already defined on line 23  [no-redef]
(mathLab)RBniCS/rbnics/backends/dolfin/wrapping/is_problem_solution_type.py:34:2: error: Name 'is_problem_solution_type' already defined on line 30  [no-redef]
(mathLab)RBniCS/rbnics/backends/dolfin/wrapping/is_problem_solution_type.py:38:2: error: Name 'is_problem_solution_type' already defined on line 30  [no-redef]
(mathLab)RBniCS/rbnics/backends/dolfin/wrapping/is_problem_solution_type.py:44:2: error: Name 'is_problem_solution_type' already defined on line 30  [no-redef]
(mathLab)RBniCS/rbnics/backends/dolfin/wrapping/get_function_subspace.py:26:2: error: Name 'get_function_subspace' already defined on line 22  [no-redef]
(mathLab)RBniCS/rbnics/backends/dolfin/wrapping/get_function_subspace.py:30:2: error: Name 'get_function_subspace' already defined on line 22  [no-redef]
(mathLab)RBniCS/rbnics/backends/dolfin/wrapping/get_function_subspace.py:41:2: error: Name 'get_function_subspace' already defined on line 22  [no-redef]
(mathLab)RBniCS/rbnics/shape_parametrization/utils/symbolic/python_string_to_sympy.py:37:2: error: Name 'python_string_to_sympy' already defined on line 28  [no-redef]
(mathLab)RBniCS/rbnics/shape_parametrization/utils/symbolic/python_string_to_sympy.py:41:2: error: Name 'python_string_to_sympy' already defined on line 28  [no-redef]
(mathLab)RBniCS/rbnics/shape_parametrization/utils/symbolic/python_string_to_sympy.py:50:2: error: Name 'python_string_to_sympy' already defined on line 28  [no-redef]
(mathLab)RBniCS/rbnics/shape_parametrization/utils/symbolic/python_string_to_sympy.py:57:2: error: Name 'python_string_to_sympy' already defined on line 28  [no-redef]
(mathLab)RBniCS/rbnics/shape_parametrization/utils/symbolic/python_string_to_sympy.py:66:2: error: Name 'python_string_to_sympy' already defined on line 28  [no-redef]
(mathLab)RBniCS/rbnics/backends/dolfin/wrapping/get_mpi_comm.py:27:2: error: Name 'get_mpi_comm' already defined on line 23  [no-redef]
(mathLab)RBniCS/rbnics/backends/dolfin/wrapping/get_mpi_comm.py:32:2: error: Name 'get_mpi_comm' already defined on line 23  [no-redef]
(mathLab)RBniCS/rbnics/backends/dolfin/wrapping/get_mpi_comm.py:37:2: error: Name 'get_mpi_comm' already defined on line 23  [no-redef]
(mathLab)RBniCS/rbnics/utils/config/config.py:118:6: error: Name '_value_to_parser' already defined on line 113  [no-redef]
(mathLab)RBniCS/rbnics/utils/config/config.py:123:6: error: Name '_value_to_parser' already defined on line 113  [no-redef]
(5agado)data-science-learning/ds_utils/image_processing.py:149:1: error: Name 'crop' already defined on line 130  [no-redef]
(5agado)data-science-learning/graphics/agents/flock_blender.py:21:1: error: Name 'Flock' already defined (by an import)  [no-redef]
(5agado)data-science-learning/graphics/agents/flock_blender.py:22:1: error: Name 'Spirograph' already defined (by an import)  [no-redef]
(5agado)data-science-learning/graphics/morphogenesis/morphogenesis_blender.py:17:1: error: Name 'Morphogenesis' already defined (by an import)  [no-redef]
(5agado)data-science-learning/graphics/spirograph/spirograph_blender.py:20:1: error: Name 'Spirograph' already defined (by an import)  [no-redef]
(5agado)data-science-learning/graphics/l_systems/l_system_blender.py:13:1: error: Name 'LSystem' already defined (by an import)  [no-redef]
(imayhaveborkedit)discord.py/discord/__init__.py:64:5: error: Name 'NullHandler' already defined (possibly by an import)  [no-redef]
(ktok07b6)polyphony/tests/error/redefined_name01.py:9:1: error: Name 'func0' already defined on line 5  [no-redef]
(ktok07b6)polyphony/tests/error/redefined_name02.py:9:1: error: Name 'C' already defined on line 5  [no-redef]
(adbpy)wire-protocol/tests/conftest.py:189:2: error: Name 'random_signature' already defined on line 181  [no-redef]
(feluxe)very_hungry_pi/vhpi/constants.py:30:9: error: Name 'version' already defined on line 26  [no-redef]
(feluxe)very_hungry_pi/vhpi/api/logging.py:95:9: error: Name 'output' already defined on line 91  [no-redef]
(feluxe)very_hungry_pi/vhpi/api/logging.py:103:13: error: Name 'output' already defined on line 91  [no-redef]
(feluxe)very_hungry_pi/vhpi/api/logging.py:106:13: error: Name 'output' already defined on line 91  [no-redef]
(feluxe)very_hungry_pi/vhpi/api/logging.py:109:13: error: Name 'output' already defined on line 91  [no-redef]
(feluxe)very_hungry_pi/vhpi/api/logging.py:112:9: error: Name 'output' already defined on line 91  [no-redef]
(feluxe)very_hungry_pi/vhpi/api/logging.py:128:5: error: Name 'due_jobs' already defined on line 117  [no-redef]
(PyCQA)astroid/astroid/_ast.py:9:5: error: Name '_ast_py3' already defined on line 7  [no-redef]
(PyCQA)astroid/astroid/_ast.py:10:5: error: Name '_ast_py2' already defined on line 7  [no-redef]
(PyCQA)astroid/astroid/interpreter/_import/spec.py:28:5: error: Name 'lru_cache' already defined (possibly by an import)  [no-redef]
(Jigsaw-Code)net-analysis/netanalysis/dns/data/serialization.py:32:2: error: Name '_' already defined on line 28  [no-redef]
(Jigsaw-Code)net-analysis/netanalysis/dns/data/serialization.py:37:2: error: Name '_' already defined on line 28  [no-redef]
(Jigsaw-Code)net-analysis/netanalysis/dns/data/serialization.py:42:2: error: Name '_' already defined on line 28  [no-redef]
(Jigsaw-Code)net-analysis/netanalysis/dns/data/serialization.py:55:2: error: Name '_' already defined on line 28  [no-redef]
(Jigsaw-Code)net-analysis/netanalysis/ooni/ooni_client.py:97:2: error: Name '_' already defined on line 84  [no-redef]
(netsec-ethz)scion/python/external/expiring_dict.py:28:5: error: Name 'OrderedDict' already defined (possibly by an import)  [no-redef]
(bosondata)badwolf/badwolf/utils.py:8:5: error: Name 're' already defined (possibly by an import)  [no-redef]
(bosondata)badwolf/badwolf/tasks.py:9:5: error: Name 're' already defined (possibly by an import)  [no-redef]
(mushorg)conpot/conpot/tests/test_ipmi_server.py:22:1: error: Name 'subprocess' already defined (by an import)  [no-redef]
(kitelightning)UnrealEnginePython/tests/test_randomstream.py:31:5: error: Name 'test_get_fraction' already defined on line 24  [no-redef]
(allenai)allennlp/allennlp/state_machines/states/checklist_statelet.py:50:13: error: Attribute 'terminal_indices_dict' already defined on line 48  [no-redef]
(libnano)libnano/libnano/fileio/naformat.py:22:5: error: Name 'NEWLINE_STR' already defined on line 19  [no-redef]
(libnano)libnano/libnano/fileio/naformat.py:137:9: error: Name 'lim_hi' already defined on line 135  [no-redef]
(libnano)libnano/libnano/fileio/naformat.py:174:9: error: Name 'out_rev' already defined on line 167  [no-redef]
(silver-castle)mach9/tests/test_config.py:25:1: error: Name 'test_auto_load_env' already defined on line 19  [no-redef]
(jamesliu)mxnet/tests/python/unittest/common.py:235:5: error: Name 'TemporaryDirectory' already defined (possibly by an import)  [no-redef]
(jamesliu)mxnet/tests/python/unittest/test_gluon_trainer.py:161:1: error: Name 'test_trainer_save_load' already defined on line 99  [no-redef]
(e-gun)HipparchiaServer/server/hipparchiaobjects/connectionobject.py:352:3: error: Name 'ConnectionObject' already defined on line 349  [no-redef]
(e-gun)HipparchiaServer/server/hipparchiaobjects/connectionobject.py:357:3: error: Name 'ConnectionObject' already defined on line 349  [no-redef]
(e-gun)HipparchiaServer/server/hipparchiaobjects/connectionobject.py:361:3: error: Name 'ConnectionObject' already defined on line 349  [no-redef]
(e-gun)HipparchiaServer/server/hipparchiaobjects/progresspoll.py:332:2: error: Name 'ProgressPoll' already defined on line 329  [no-redef]
(tr8dr).Net-Bridge/src/Python/pyDotNet/src/pydotnet/clr/CLRTypeFactory.py:84:6: error: Name 'createByValue' already defined on line 75  [no-redef]
(myint)language-check/download_lt.py:23:5: error: Name 'urlopen' already defined (possibly by an import)  [no-redef]
(myint)language-check/download_lt.py:24:5: error: Name 'urljoin' already defined (possibly by an import)  [no-redef]
(damorim)compilers-cin/ap3/antlr4-python3-runtime-4.7.2/src/antlr4/atn/SemanticContext.py:155:1: error: Name 'AND' already defined on line 64  [no-redef]
(damorim)compilers-cin/ap3/antlr4-python3-runtime-4.7.2/src/antlr4/atn/SemanticContext.py:240:1: error: Name 'OR' already defined on line 78  [no-redef]
(mpi-sws-rse)thingflow-python/examples/esp8266/lux_sensor_demo.py:10:1: error: Name 'Output' already defined (possibly by an import)  [no-redef]
(lobnek)pyutil/test/test_portfolio/test_portfolio.py:216:5: error: Name 'test_state' already defined on line 136  [no-redef]
(lobnek)pyutil/test/test_performance/test_summary.py:122:5: error: Name 'test_adjust' already defined on line 31  [no-redef]
(lobnek)pyutil/pyutil/sql/interfaces/risk/owner.py:31:6: error: Name 'currency' already defined on line 27  [no-redef]
(lobnek)pyutil/pyutil/message.py:116:6: error: Name 'text' already defined on line 99  [no-redef]
(lobnek)pyutil/pyutil/message.py:120:6: error: Name 'subject' already defined on line 112  [no-redef]
(lobnek)pyutil/pyutil/message.py:124:6: error: Name 'fromAdr' already defined on line 108  [no-redef]
(lobnek)pyutil/pyutil/message.py:128:6: error: Name 'toAdr' already defined on line 104  [no-redef]
(danionescu0)robot-camera-platform/navigation/ObjectDetector.py:21:6: error: Name 'detected' already defined on line 13  [no-redef]
(danionescu0)robot-camera-platform/navigation/ObjectDetector.py:25:6: error: Name 'circle_coordonates' already defined on line 17  [no-redef]
(makerdao)keeper/tests/test_proxy.py:98:9: error: Name 'past_build' already defined on line 87  [no-redef]
(red8012)portkey/portkey/selector.py:11:5: error: Name 'html_tag' already defined (possibly by an import)  [no-redef]
(kobinpy)kobin/example/helloworld/hello.py:12:2: error: Name 'hello' already defined on line 6  [no-redef]
(kosior)taktyk/tests/test_save.py:48:6: error: Name 'test_get_gfycat_url_when_gfycat_exist' already defined on line 42  [no-redef]
(kosior)taktyk/tests/test_strategies.py:20:6: error: Name 'test_get_content_by_ids_when_scrape_true' already defined on line 13  [no-redef]
(kosior)taktyk/tests/test_render.py:33:6: error: Name 'test_create_file_name_strftime_called' already defined on line 28  [no-redef]
(N-BodyPhysicsSimulator)Main/nbp/bodies/body_state.py:8:1: error: Name 'BodyState' already defined on line 4  [no-redef]
(N-BodyPhysicsSimulator)Main/nbp/bodies/body.py:10:1: error: Name 'Body' already defined on line 6  [no-redef]
(Technikradio)C3FOCSite/c3shop/frontpage/management/export/export_invoice.py:114:9: error: Name 'r' already defined on line 95  [no-redef]
(Technikradio)C3FOCSite/c3shop/frontpage/management/articletools/article_select.py:77:13: error: Name 's' already defined on line 64  [no-redef]
(ECP-CANDLE)Benchmarks/Pilot2/P2B1/p2b1_AE_models.py:13:5: error: Name 'configparser' already defined (by an import)  [no-redef]
(ECP-CANDLE)Benchmarks/Pilot2/P2B1/p2b1.py:208:1: error: Name 'get_activations' already defined on line 105  [no-redef]
(ECP-CANDLE)Benchmarks/Pilot1/Uno/uno.py:10:5: error: Name 'configparser' already defined (by an import)  [no-redef]
(ECP-CANDLE)Benchmarks/Pilot1/P1B2/p1b2.py:15:5: error: Name 'configparser' already defined (by an import)  [no-redef]
(BernardFW)bernard/src/bernard/layers/stack.py:73:9: error: Attribute '_layers' already defined on line 42  [no-redef]
(BernardFW)bernard/src/bernard/i18n/loaders.py:298:13: error: Name 'neg' already defined on line 287  [no-redef]
(intel-ctrlsys)actsys/actsys/control/job_launch/tests/test_mock_job_launch.py:74:5: error: Name 'test_check_job_no_job_id_no_state' already defined on line 58  [no-redef]
(intel-ctrlsys)actsys/actsys/control/job_launch/tests/test_mock_job_launch.py:79:5: error: Name 'test_check_job_no_job_id_invalid_state' already defined on line 63  [no-redef]
(intel-ctrlsys)actsys/actsys/control/job_launch/tests/test_mock_job_launch.py:84:5: error: Name 'test_check_job_no_job_id_valid_state' already defined on line 68  [no-redef]
(alphagov)digitalmarketplace-api/tests/test_generate_model_schemas.py:5:5: error: Name 'builtins' already defined (possibly by an import)  [no-redef]
(scipy)scipy/benchmarks/benchmarks/sparse.py:12:5: error: Name 'pickle' already defined (possibly by an import)  [no-redef]
(bintoro)overloading.py/tests/_test_classmethods.py:12:6: error: Name 'f' already defined on line 7  [no-redef]
(bintoro)overloading.py/tests/_test_classmethods.py:16:6: error: Name 'f' already defined on line 7  [no-redef]
(bintoro)overloading.py/tests/_test_classmethods.py:33:6: error: Name 'f' already defined on line 28  [no-redef]
(bintoro)overloading.py/tests/_test_classmethods.py:38:6: error: Name 'f' already defined on line 28  [no-redef]
(bintoro)overloading.py/tests/_test_classmethods.py:56:6: error: Name 'f' already defined on line 51  [no-redef]
(bintoro)overloading.py/tests/_test_classmethods.py:61:6: error: Name 'f' already defined on line 51  [no-redef]
(bintoro)overloading.py/tests/_test_classes.py:11:6: error: Name 'f' already defined on line 7  [no-redef]
(bintoro)overloading.py/tests/_test_classes.py:15:6: error: Name 'f' already defined on line 7  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:10:2: error: Name 'f' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:14:2: error: Name 'f' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:18:2: error: Name 'f' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:22:2: error: Name 'f' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:26:2: error: Name 'f' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:30:2: error: Name 'f' already defined on line 6  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:53:2: error: Name 'g' already defined on line 49  [no-redef]
(bintoro)overloading.py/tests/_test_basics.py:57:2: error: Name 'g' already defined on line 49  [no-redef]
(bintoro)overloading.py/tests/_test_decorated.py:16:2: error: Name 'f' already defined on line 10  [no-redef]
(bintoro)overloading.py/tests/_test_decorated.py:22:2: error: Name 'f' already defined on line 10  [no-redef]
(bintoro)overloading.py/tests/_test_decorated.py:37:2: error: Name 'g' already defined on line 32  [no-redef]
(bintoro)overloading.py/tests/_test_decorated.py:42:2: error: Name 'g' already defined on line 32  [no-redef]
(mara)mara-db/mara_db/sqlalchemy_engine.py:32:2: error: Name '__' already defined on line 27  [no-redef]
(mara)mara-db/mara_db/sqlalchemy_engine.py:37:2: error: Name '__' already defined on line 27  [no-redef]
(mara)mara-db/mara_db/sqlalchemy_engine.py:44:2: error: Name '__' already defined on line 27  [no-redef]
(mara)mara-db/mara_db/auto_migration.py:160:9: error: Name 'MyTable' already defined on line 139  [no-redef]
(marrow)WebCore/example/future/methods.py:19:6: error: Name 'login' already defined on line 15  [no-redef]
(marrow)WebCore/example/future/multihead.py:25:6: error: Name 'foo' already defined on line 21  [no-redef]
(marrow)WebCore/example/future/multihead.py:29:6: error: Name 'foo' already defined on line 21  [no-redef]
(marrow)WebCore/example/future/monster.py:98:6: error: Name 'login' already defined on line 94  [no-redef]
(marrow)WebCore/example/future/monster.py:112:6: error: Name 'foo' already defined on line 69  [no-redef]
(marrow)WebCore/example/future/monster.py:116:6: error: Name 'foo' already defined on line 112  [no-redef]
(marrow)WebCore/example/future/monster.py:120:6: error: Name 'foo' already defined on line 112  [no-redef]
(marrow)WebCore/web/ext/serialize.py:19:2: error: Name 'json' already defined (possibly by an import)  [no-redef]
(zydiig)Container/namespace.py:27:1: error: Name 'require_root' already defined (possibly by an import)  [no-redef]
(zydiig)Container/contain.py:11:2: error: Name 'mount' already defined (possibly by an import)  [no-redef]
(zydiig)Container/contain.py:17:1: error: Name 'try_unmount_all' already defined (possibly by an import)  [no-redef]
(cybertec-postgresql)pgwatch2/webpy/datadb.py:20:1: error: Name 'setConnectionString' already defined on line 10  [no-redef]
(aio-libs)aiohttp/tests/test_web_log.py:170:5: error: Name 'Logger' already defined on line 160  [no-redef]
(tornadoweb)tornado/demos/file_upload/file_uploader.py:22:5: error: Name 'quote' already defined (possibly by an import)  [no-redef]
(tornadoweb)tornado/demos/file_upload/file_receiver.py:17:5: error: Name 'unquote' already defined (possibly by an import)  [no-redef]
(semanticbits)survey_stats/src/survey_stats/api.py:117:2: error: Name 'fetch_questions' already defined on line 107  [no-redef]
(kenkov)seq2seq/relu_rnn.py:141:1: error: Name 'Classifier' already defined on line 15  [no-redef]
(MarcoBuster)OrarioTreniBot/src/viaggiatreno/viaggiatreno.py:33:5: error: Name 'urlopen' already defined (possibly by an import)  [no-redef]
(zhangxin20121923)QuanSim/baseClass/Bit.py:39:2: error: Name '__add__' already defined on line 36  [no-redef]
(zhangxin20121923)QuanSim/baseClass/Qubit.py:14:1: error: Name 'get_curl_info' already defined (possibly by an import)  [no-redef]
(christabor)MoAL/MOAL/systems_engineering/architecture/restful/restful_eve.py:16:1: error: Name 'sys' already defined (possibly by an import)  [no-redef]
(christabor)MoAL/MOAL/software_engineering/problem_solving/design_patterns/unix/transparency.py:17:1: error: Name 'sys' already defined (possibly by an import)  [no-redef]
(autokey)autokey/lib/autokey/qtui/dialogs/hotkeysettings.py:130:13: error: Name 'modifiers' already defined on line 127  [no-redef]
(KawashiroNitori)Anubis/anubis/model/user.py:158:2: error: Name 'set_mail' already defined on line 140  [no-redef]
(KawashiroNitori)Anubis/anubis/model/user.py:164:2: error: Name 'change_password' already defined on line 146  [no-redef]
(KawashiroNitori)Anubis/anubis/handler/home.py:117:1: error: Name 'HomeAccountHandler' already defined on line 102  [no-redef]
(dmwyatt)disney.api/helpers.py:24:2: error: Name 'target_dt' already defined on line 22  [no-redef]
(pybel)pybel/tests/test_manager/test_connection.py:15:5: error: Name 'mock' already defined (by an import)  [no-redef]
(argaen)aiocache/aiocache/serializers/serializers.py:10:5: error: Name 'json' already defined (by an import)  [no-redef]
(argaen)aiocache/tests/acceptance/test_serializers.py:7:5: error: Name 'json' already defined (by an import)  [no-redef]
(argaen)aiocache/tests/acceptance/test_serializers.py:11:5: error: Name 'pickle' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/cmdline/cmd_showbc.py:121:1: error: Name 'f' already defined on line 4  [no-redef]
(turbinenreiter)micropython/tests/cmdline/cmd_showbc.py:128:1: error: Name 'f' already defined on line 4  [no-redef]
(turbinenreiter)micropython/tests/basics/class_store_class.py:8:5: error: Name 'namedtuple' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/misc/print_exception.py:4:5: error: Name 'io' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/uheapq1.py:4:5: error: Name 'heapq' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/float/float2int.py:6:5: error: Name 'struct' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/float/float2int_doubleprec.py:6:5: error: Name 'struct' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/float/float2int_fp30.py:6:5: error: Name 'struct' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/thread/thread_start2.py:8:5: error: Name 'time' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/thread/stress_aes.py:207:5: error: Name 'time' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ure_namedclass.py:6:5: error: Name 're' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ure_group.py:6:5: error: Name 're' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ujson_loads.py:4:5: error: Name 'json' already defined (by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ure_error.py:6:5: error: Name 're' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/tests/extmod/ujson_loads_float.py:4:5: error: Name 'json' already defined (by an import)  [no-redef]
(turbinenreiter)micropython/examples/network/http_client.py:4:5: error: Name 'socket' already defined (possibly by an import)  [no-redef]
(turbinenreiter)micropython/examples/network/http_server_simplistic.py:4:5: error: Name 'socket' already defined (possibly by an import)  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:17:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:22:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:27:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:32:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:37:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:42:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:48:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:53:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:61:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:67:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:72:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(mikonapoli)grakn-python/features/steps/steps.py:77:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(awslabs)sockeye/sockeye/model.py:122:13: error: Attribute 'embedding_source' already defined on line 120  [no-redef]
(trezor)micropython/tests/basics/class_super.py:26:1: error: Name 'A' already defined on line 19  [no-redef]
(trezor)micropython/tests/basics/iter1.py:13:1: error: Name 'NotIterable' already defined on line 4  [no-redef]
(trezor)micropython/tests/basics/subclass_native_init.py:38:1: error: Name 'L' already defined on line 4  [no-redef]
(sussexstudent)falmer/falmer/events/admin.py:16:1: error: Name 'VenueModelAdmin' already defined on line 11  [no-redef]
(movidius)ncappzoo/apps/classifier_gui/classifier_gui.py:19:1: error: Name 'Image' already defined (possibly by an import)  [no-redef]
(coblo)pyiscclib/ci/appveyor-bootstrap.py:17:5: error: Name 'urlretrieve' already defined (possibly by an import)  [no-redef]
(rr-)szurubooru/server/szurubooru/model/post.py:228:6: error: Name 'flags' already defined on line 224  [no-redef]
(arthurmensch)modl/modl/utils/tests/test_system.py:49:1: error: Name 'test_get_data_dir' already defined on line 22  [no-redef]
(arthurmensch)modl/modl/input_data/fmri/base.py:69:1: error: Name 'check_embedded_nifti_masker' already defined (possibly by an import)  [no-redef]
(arthurmensch)modl/exps/multi_decompose_fmri.py:34:2: error: Name 'config' already defined on line 27  [no-redef]
(arthurmensch)modl/exps/multi_decompose_images.py:34:2: error: Name 'config' already defined on line 27  [no-redef]
(carbonblack)cb-integration/cbint/binary_collector.py:6:1: error: Name 'datetime' already defined (by an import)  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:91:1: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:101:1: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:111:1: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:121:1: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:131:1: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:141:1: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:151:1: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:161:1: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:296:1: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:316:1: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:323:1: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:353:1: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:373:1: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:380:1: error: Name 'get_Z' already defined on line 26  [no-redef]
(Tobotimus)Tobo-Cogs/welcomecount/welcomecount.py:170:21: error: Name 'last_message' already defined on line 168  [no-redef]
(lostatc)codot/codot/container.py:86:6: error: Name 'last_sync' already defined on line 72  [no-redef]
(lostatc)codot/codot/container.py:120:6: error: Name 'vals' already defined on line 115  [no-redef]
(lostatc)codot/codot/container.py:228:6: error: Name 'vals' already defined on line 220  [no-redef]
(pycrystem)pycrystem/tests/test_signals/test_crystallographic_map.py:177:5: error: Name 'test_Crystallographic_Map_io' already defined on line 169  [no-redef]
(peterhinch)micropython-tft-gui/asyn.py:12:5: error: Name 'asyncio' already defined (possibly by an import)  [no-redef]
(niwinz)cobrascript/samples/sample1.py:9:1: error: Name 'foo' already defined on line 5  [no-redef]
(Kilerd)nougat/tests/test_signal.py:60:10: error: Name 'test' already defined on line 56  [no-redef]
(Kilerd)nougat/tests/test_signal.py:77:10: error: Name 'test' already defined on line 73  [no-redef]
(Kilerd)nougat/tests/test_signal.py:94:10: error: Name 'test' already defined on line 90  [no-redef]
(TeamHG-Memex)scrapy-cdr/scrapy_cdr/v2_to_v3.py:6:5: error: Name 'json' already defined (by an import)  [no-redef]
(getpelican)pelican-plugins/share_post/share_post.py:16:5: error: Name 'quote' already defined (possibly by an import)  [no-redef]
(diyclassics)cltk/cltk/tests/test_nlp/test_orthophonology.py:274:2: error: Name 'test_add_rule' already defined on line 270  [no-redef]
(diyclassics)cltk/cltk/tests/test_nlp/test_tag.py:137:5: error: Name 'test_check_latest_latin' already defined on line 131  [no-redef]
(diyclassics)cltk/cltk/tests/test_languages/test_middle_high_german.py:85:5: error: Name 'test_middle_high_german_normalizer' already defined on line 67  [no-redef]
(secrary)SSMA/ext/validate_email.py:38:5: error: Name 'ServerError' already defined on line 33  [no-redef]
(baffelli)pyperator/pyperator/components.py:354:2: error: Name 'Repeat' already defined on line 239  [no-redef]
(Kane610)axis/tests/test_event_stream.py:161:1: error: Name 'test_manage_event_port_any_init' already defined on line 117  [no-redef]
(twitter)pants/src/python/pants/base/file_system_project_tree.py:20:3: error: Name 'scandir' already defined (possibly by an import)  [no-redef]
(twitter)pants/src/python/pants/util/process_handler.py:25:3: error: Name 'subprocess3' already defined (possibly by an import)  [no-redef]
(Clinical-Genomics)scout/scout/adapter/client.py:17:5: error: Name 'quote_plus' already defined (possibly by an import)  [no-redef]
(Clinical-Genomics)scout/scout/adapter/utils.py:8:5: error: Name 'quote_plus' already defined (possibly by an import)  [no-redef]
(Clinical-Genomics)scout/tests/adapter/mongo/test_hpo_handler.py:203:1: error: Name 'test_add_disease_term' already defined on line 183  [no-redef]
(EeOneDown)spbu4u/tg_bot/handlers/start.py:160:2: error: Name 'exit_handler' already defined on line 102  [no-redef]
(AstroTech)workshop-python/functions/solution/kwargs_numeric.py:8:1: error: Name 'is_numeric' already defined on line 1  [no-redef]
(AstroTech)workshop-python/functions/solution/functions_aviation_numbers.py:26:1: error: Name 'aviation_numbers' already defined on line 17  [no-redef]
(AstroTech)workshop-python/object-oriented-programming/src/oop-tell-dont-ask.py:14:1: error: Name 'Rocket' already defined on line 2  [no-redef]
(AstroTech)workshop-python/design-patterns/src/decorators-usage.py:7:1: error: Name 'double' already defined on line 1  [no-redef]
(AstroTech)workshop-python/design-patterns/src/decorators-usage.py:13:2: error: Name 'double' already defined on line 1  [no-redef]
(AstroTech)workshop-python/design-patterns/src/decorators-usage.py:19:1: error: Name 'double' already defined on line 13  [no-redef]
(AstroTech)workshop-python/design-patterns/src/decorators-case-study-django.py:16:2: error: Name 'edit_profile' already defined on line 5  [no-redef]
(AstroTech)workshop-python/object-oriented-programming/solution/oop_dragon_2.py:5:1: error: Name 'Status' already defined (possibly by an import)  [no-redef]
(AstroTech)workshop-python/performance/solution/performance_memoize.py:27:1: error: Name 'factorial_cache' already defined on line 13  [no-redef]
(AstroTech)workshop-python/serialization/solution/json_deserialize_classes.py:46:1: error: Name 'User' already defined on line 32  [no-redef]
(4dsolutions)Python5/circle2.py:44:6: error: Name 'area' already defined on line 28  [no-redef]
(4dsolutions)Python5/circle2.py:50:6: error: Name 'radius' already defined on line 32  [no-redef]
(python-bonobo)bonobo/bonobo/config/configurables.py:76:5: error: Name 'PartiallyConfigured' already defined on line 73  [no-redef]
(openatx)uiautomator2/uiautomator2/messagebox.py:9:5: error: Name 'tk' already defined (possibly by an import)  [no-redef]
(Diapolo10)RPGenie/src/classes.py:275:13: error: Attribute 'inventory' already defined on line 273  [no-redef]
(Aearsis)economy-game/data/blackmarket_offers.py:8:1: error: Name 'random' already defined (by an import)  [no-redef]
(sassoftware)saspy/saspy/tests/test_io.py:65:5: error: Name 'test_sasio_mexist_submit' already defined on line 59  [no-redef]
(fumitoh)modelx/doc/source/samples/sample_inheritance.py:55:2: error: Name 'benefits' already defined on line 27  [no-redef]
(fumitoh)modelx/modelx/tests/core/cells/test_cells_repr.py:48:2: error: Name 'test_fullname' already defined on line 29  [no-redef]
(ozmartian)vidcutter/vidcutter/videostyle.py:36:5: error: Name 'QProxyStyle' already defined (possibly by an import)  [no-redef]
(ozmartian)vidcutter/vidcutter/libs/munch.py:324:9: error: Name 'json' already defined (by an import)  [no-redef]
(crashtua)hvapi/hvapi/clr/powershell.py:8:1: error: Name 'PSObject' already defined (possibly by an import)  [no-redef]
(crashtua)hvapi/hvapi/clr/base.py:63:1: error: Name 'ManagementScope' already defined (possibly by an import)  [no-redef]
(crashtua)hvapi/hvapi/clr/base.py:127:1: error: Name 'ManagementObject' already defined (possibly by an import)  [no-redef]
(BitLooter)htmlark/htmlark.py:23:5: error: Name 'RequestException' already defined (possibly by an import)  [no-redef]
(ros2)launch/launch/launch/substitutions/launch_configuration.py:63:13: error: Attribute '__default' already defined on line 48  [no-redef]
(memento7)KINCluster/tests/test_cluster.py:20:1: error: Name 'Pipeline' already defined (possibly by an import)  [no-redef]
(memento7)KINCluster/tests/test_pipeline.py:14:1: error: Name 'Pipeline' already defined (possibly by an import)  [no-redef]
(memento7)KINCluster/tests/test_extractor.py:22:1: error: Name 'Pipeline' already defined (possibly by an import)  [no-redef]
(memento7)KINCluster/test_app/item.py:3:1: error: Name 'Item' already defined (possibly by an import)  [no-redef]
(jfde)augentbot/scripts/pymarkovchain_dynamic/MarkovChain.py:6:5: error: Name 'pickle' already defined (possibly by an import)  [no-redef]
(ResolveWang)WeiboSpider/tests/test_utils.py:7:5: error: Name 'mock' already defined (by an import)  [no-redef]
(corpnewt)CorpBot.py/Cogs/Mute.py:71:5: error: Name 'onjoin' already defined on line 24  [no-redef]
(alexarnautu)deenux/src/deenuxapi/deezer/DeezerProvider.py:43:6: error: Name 'token' already defined on line 31  [no-redef]
(tomerfiliba)plumbum/plumbum/fs/atomic.py:17:9: error: Name 'thread' already defined (possibly by an import)  [no-redef]
(cbg-ethz)rnaiutilities/tests/test_query_query.py:163:5: error: Name 'test_compose_creates_unit_variance_columns' already defined on line 157  [no-redef]
(cbg-ethz)rnaiutilities/tests/test_query_insert.py:97:5: error: Name 'test_number_of_sirna_elements' already defined on line 92  [no-redef]
(cbg-ethz)rnaiutilities/tests/test_parse.py:173:5: error: Name 'test_perinuclei_data_file_values' already defined on line 158  [no-redef]
(samuelcolvin)aiohttp-devtools/aiohttp_devtools/start/template/app/views.py:60:1: error: Name 'index' already defined on line 29  [no-redef]
(scottwernervt)cloudstorage/src/cloudstorage/exceptions.py:7:5: error: Name 'HTTPStatus' already defined (possibly by an import)  [no-redef]
(scottwernervt)cloudstorage/tests/test_drivers_google.py:8:5: error: Name 'HTTPStatus' already defined (possibly by an import)  [no-redef]
(scottwernervt)cloudstorage/tests/test_drivers_amazon.py:5:5: error: Name 'HTTPStatus' already defined (possibly by an import)  [no-redef]
(scottwernervt)cloudstorage/tests/test_drivers_rackspace.py:5:5: error: Name 'HTTPStatus' already defined (possibly by an import)  [no-redef]
(scottwernervt)cloudstorage/tests/test_drivers_minio.py:5:5: error: Name 'HTTPStatus' already defined (possibly by an import)  [no-redef]
(scottwernervt)cloudstorage/tests/test_drivers_microsoft.py:5:5: error: Name 'HTTPStatus' already defined (possibly by an import)  [no-redef]
(PetterKraabol)Twitch-Chat-Downloader/tcd/arguments.py:73:13: error: Attribute 'formats' already defined on line 63  [no-redef]
(PetterKraabol)Twitch-Chat-Downloader/tcd/__init__.py:11:1: error: Name '__name__' already defined (possibly by an import)  [no-redef]
(makerdao)maker.py/tests/test_proxy.py:98:9: error: Name 'past_build' already defined on line 87  [no-redef]
(pybel)pybel-tools/src/pybel_tools/analysis/concordance.py:253:5: error: Name 'graph' already defined on line 224  [no-redef]
(pypa)warehouse/warehouse/accounts/models.py:109:6: error: Name 'email' already defined on line 104  [no-redef]
(d10genes)pollen/util/junk.py:53:1: error: Name 'get_batch' already defined on line 36  [no-redef]
(HumanCompatibleAI)imitation/src/imitation/util/util.py:132:3: error: Name 'layer' already defined on line 126  [no-redef]
(borevitzlab)spc-eyepi/ansible/plugins/callback_plugins/human_log.py:27:5: error: Name 'json' already defined (by an import)  [no-redef]
(agdsn)pycroft/pycroft/model/task.py:50:6: error: Name 'parameters' already defined on line 44  [no-redef]
(caterinaurban)Lyra/src/lyra/abstract_domains/assumption/alphabet_domain.py:73:9: error: Name 'variables' already defined on line 69  [no-redef]
(caterinaurban)Lyra/src/lyra/abstract_domains/assumption/quantity_domain.py:83:9: error: Name 'variables' already defined on line 79  [no-redef]
(caterinaurban)Lyra/src/lyra/abstract_domains/assumption/wordset_domain.py:71:9: error: Name 'variables' already defined on line 67  [no-redef]
(caterinaurban)Lyra/src/lyra/abstract_domains/assumption/range_domain.py:87:9: error: Name 'variables' already defined on line 83  [no-redef]
(caterinaurban)Lyra/src/lyra/abstract_domains/state.py:276:13: error: Name 'arguments' already defined on line 273  [no-redef]
(jesopo)bitbot/modules/channel_op.py:133:6: error: Name 'op' already defined on line 121  [no-redef]
(Solcast)howto-pandas/tests/test_howto.py:5:1: error: Name 'datetime' already defined (by an import)  [no-redef]
(PUTvision)decision_tree/decision_trees/datasets/emg_raw.py:60:13: error: Name 'file' already defined on line 59  [no-redef]
(PaulSonOfLars)tgbot/tg_bot/modules/global_bans.py:232:13: error: Name 'user' already defined on line 219  [no-redef]
(mdovgialo)steam-vr-wheel/steam_vr_wheel/pyvjoy/_wrapper.py:98:1: error: Name 'SetBtn' already defined on line 68  [no-redef]
(mdovgialo)steam-vr-wheel/steam_vr_wheel/pyvjoy/_sdk.py:117:1: error: Name 'SetBtn' already defined on line 70  [no-redef]
(5j9)num2fawords/num2fawords/__init__.py:174:2: error: Name '_' already defined on line 128  [no-redef]
(5j9)num2fawords/num2fawords/__init__.py:207:2: error: Name '_' already defined on line 128  [no-redef]
(5j9)num2fawords/num2fawords/__init__.py:226:2: error: Name '_' already defined on line 128  [no-redef]
(dmerejkowsky)twittback/twittback/server.py:33:6: error: Name 'repository' already defined on line 21  [no-redef]
(dougli1sqrd)yamldown/tests/test_yamldown.py:76:5: error: Name 'test_yaml_not_started' already defined on line 60  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:8:5: error: Name 'mock' already defined (by an import)  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:54:1: error: Name 'I1' already defined on line 15  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:61:1: error: Name 'I2' already defined on line 22  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:68:1: error: Name 'Thing1' already defined on line 29  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:76:1: error: Name 'Thing2' already defined on line 37  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:84:2: error: Name 'some_func' already defined on line 45  [no-redef]
(tim-mitchell)pure_interface/tests/test_py3/test_adapt_args3.py:89:2: error: Name 'other_func' already defined on line 49  [no-redef]
(tim-mitchell)pure_interface/tests/test_weakref.py:28:2: error: Name 'foo' already defined on line 23  [no-redef]
(tim-mitchell)pure_interface/tests/test_isinstance.py:11:5: error: Name 'mock' already defined (by an import)  [no-redef]
(tim-mitchell)pure_interface/tests/test_adapt_args2.py:8:5: error: Name 'mock' already defined (by an import)  [no-redef]
(tim-mitchell)pure_interface/tests/test_adaption.py:10:5: error: Name 'mock' already defined (by an import)  [no-redef]
(tim-mitchell)pure_interface/tests/test_implementation_checks.py:12:5: error: Name 'mock' already defined (by an import)  [no-redef]
(appu1232)Selfbot-for-Discord/cogs/mod.py:168:6: error: Name 'channel' already defined on line 122  [no-redef]
(stuxcrystal)yuuno/yuuno_ipython/ipython/feature.py:22:1: error: Name 'Any' already defined (possibly by an import)  [no-redef]
(Drakulix)knex/backend/__init__.py:127:2: error: Name 'init_global_mongoclient' already defined on line 93  [no-redef]
(Drakulix)knex/backend/__init__.py:294:2: error: Name 'index' already defined on line 285  [no-redef]
(lukas)ml-class/examples/lstm/imdb-classifier/imdb-attention.py:12:1: error: Name 'imdb' already defined (possibly by an import)  [no-redef]
(timofurrer)pyobservable/tests/test_property.py:16:6: error: Name 'prop' already defined on line 12  [no-redef]
(timofurrer)pyobservable/tests/test_property.py:20:6: error: Name 'prop' already defined on line 12  [no-redef]
(thought-machine)please/tools/please_pex/pex_test.py:17:6: error: Name 'testSkipped' already defined on line 12  [no-redef]
(thought-machine)please/test/python_rules/behave/features/steps/behave_test_steps.py:9:2: error: Name 'step_impl' already defined on line 4  [no-redef]
(thought-machine)please/test/python_rules/behave/features/steps/behave_test_steps.py:14:2: error: Name 'step_impl' already defined on line 4  [no-redef]
(thought-machine)please/test/python_rules/behave/features/steps/behave_test_steps.py:20:2: error: Name 'step_impl' already defined on line 4  [no-redef]
(thought-machine)please/test/python_rules/behave/features/steps/behave_test_steps.py:26:2: error: Name 'step_impl' already defined on line 4  [no-redef]
(mdutkin)m2core/m2core/utils/json_helper.py:8:5: error: Name 'json' already defined (by an import)  [no-redef]
(thomaxxl)safrs/examples/v1_examples/expose_existing/sakila.py:33:1: error: Name 'SMALLINT' already defined (possibly by an import)  [no-redef]
(thomaxxl)safrs/examples/v1_examples/expose_existing/sakila.py:37:1: error: Name 'INTEGER' already defined (possibly by an import)  [no-redef]
(thomaxxl)safrs/examples/v1_examples/expose_existing/employees.py:8:1: error: Name 'INTEGER' already defined (possibly by an import)  [no-redef]
(achimnol)aiotools/src/aiotools/context.py:34:5: error: Name 'AbstractAsyncContextManager' already defined on line 27  [no-redef]
(achimnol)aiotools/src/aiotools/context.py:71:5: error: Name 'AsyncContextManager' already defined on line 28  [no-redef]
(skytoup)AppServer/app/blueprints/exception.py:42:2: error: Name 'request_timeout' already defined on line 27  [no-redef]
(skytoup)AppServer/app/blueprints/exception.py:47:2: error: Name 'request_timeout' already defined on line 42  [no-redef]
(AVSystem)Anjay/doc/sphinx/extensions/builders/dummy.py:24:5: error: Name 'DummyBuilder' already defined (possibly by an import)  [no-redef]
(nyxxxie)spade/tests/typesystem/test_char.py:46:1: error: Name 'test_convert_letter_string_lower' already defined on line 39  [no-redef]
(nyxxxie)spade/tests/typesystem/test_char.py:82:1: error: Name 'test_convert_number_string' already defined on line 64  [no-redef]
(nyxxxie)spade/tests/typesystem/test_char.py:89:1: error: Name 'test_convert_number_chars' already defined on line 71  [no-redef]
(marcosfede)algorithms/backtrack/palindrome_partitioning.py:28:1: error: Name 'palindromic_substrings' already defined on line 7  [no-redef]
(marcosfede)algorithms/maths/next_perfect_square.py:17:1: error: Name 'find_next_square' already defined on line 8  [no-redef]
(marcosfede)algorithms/matrix/sparse_mul.py:47:1: error: Name 'multiply' already defined on line 27  [no-redef]
(marcosfede)algorithms/matrix/sparse_mul.py:72:1: error: Name 'multiply' already defined on line 27  [no-redef]
(marcosfede)algorithms/tree/binary_search_tree/kth_smallest/kth_smallest.py:6:1: error: Name 'Node' already defined on line 1  [no-redef]
(marcosfede)algorithms/tree/binary_search_tree/kth_smallest/kth_smallest.py:11:1: error: Name 'Node' already defined on line 1  [no-redef]
(marcosfede)algorithms/bit/count_ones.py:25:1: error: Name 'count_ones' already defined on line 19  [no-redef]
(marcosfede)algorithms/backtrack/anagram/anagram.py:7:1: error: Name 'perm' already defined on line 2  [no-redef]
(marcosfede)algorithms/backtrack/anagram/anagram.py:17:1: error: Name 'perm' already defined on line 2  [no-redef]
(palmtree5)palmtree5-cogs/hpapi/helpers.py:4:1: error: Name 'datetime' already defined (possibly by an import)  [no-redef]
(allianceauth)allianceauth/allianceauth/eveonline/tests/test_managers.py:193:6: error: Name 'test_create_corporation' already defined on line 170  [no-redef]
(mackeyja92)django-asyncio-redis/django_asyncio_redis/serializers/pickle.py:6:5: error: Name 'pickle' already defined (possibly by an import)  [no-redef]
(gavinfish)leetcode-share/python/010 Regular Expression Matching.py:56:1: error: Name 'Solution' already defined on line 22  [no-redef]
(KDE)labplot/admin/run-clang-tidy.py:58:5: error: Name 'queue' already defined (possibly by an import)  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:47:2: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:55:2: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:65:2: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:73:2: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:81:2: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:93:2: error: Name 'step_impl' already defined on line 17  [no-redef]
(geneontology)go-site/tests/behave/steps/basic.py:106:2: error: Name 'step_impl' already defined on line 17  [no-redef]
(ThaWeatherman)trackopy/trackopy/__init__.py:15:5: error: Name 'NullHandler' already defined (possibly by an import)  [no-redef]
(portfoliome)pgawedge/pgawedge/triggers.py:53:2: error: Name 'compile' already defined on line 38  [no-redef]
(managedbyq)mbq.metrics/tests/contrib/django/middleware/compat.py:9:5: error: Name 'mock' already defined (by an import)  [no-redef]
(KevinFasusi)supplychainpy/tests/features/steps/analyse_data_from_datafram.py:22:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(KevinFasusi)supplychainpy/tests/features/steps/analyse_data_from_datafram.py:44:2: error: Name 'step_impl' already defined on line 12  [no-redef]
(KevinFasusi)supplychainpy/tests/features/steps/chat.py:16:2: error: Name 'step_impl' already defined on line 6  [no-redef]
(KevinFasusi)supplychainpy/tests/features/steps/chat.py:29:2: error: Name 'step_impl' already defined on line 6  [no-redef]
(pyecore)pyecore/tests/test_basics.py:56:1: error: Name 'test_eenum_simple_instance_with_defaultvalue' already defined on line 50  [no-redef]
(pyecore)pyecore/tests/test_basics.py:61:1: error: Name 'test_eenum_simple_instance' already defined on line 44  [no-redef]
(pyecore)pyecore/pyecore/commands.py:308:6: error: Name 'top' already defined on line 300  [no-redef]
(pyecore)pyecore/pyecore/commands.py:314:6: error: Name 'top' already defined on line 308  [no-redef]
(healerkx)PySQLKits/deprecated/mysqlbinlog/field_descriptor.py:80:1: error: Name 'long_descriptor' already defined on line 69  [no-redef]
(healerkx)PySQLKits/deprecated/mysqlbinlog/mysqlbinlog.py:338:5: error: Name 'bytes_2_leuint' already defined on line 210  [no-redef]
(healerkx)PySQLKits/deprecated/mysqlbinlog/mysqlbinlog.py:349:5: error: Name 'read_field_length' already defined on line 221  [no-redef]
(bitmovin)bitmovin-python/bitmovin/resources/models/encodings/conditions/abstract_conjunction.py:16:6: error: Name 'conditions' already defined on line 7  [no-redef]
(bitmovin)bitmovin-python/bitmovin/resources/models/encodings/encoding.py:69:6: error: Name 'encoderVersion' already defined on line 44  [no-redef]
(bitmovin)bitmovin-python/bitmovin/resources/models/encodings/stream.py:108:6: error: Name 'conditions' already defined on line 79  [no-redef]
(bitmovin)bitmovin-python/bitmovin/resources/models/encodings/stream.py:120:6: error: Name 'outputs' already defined on line 104  [no-redef]
(bitmovin)bitmovin-python/tests/bitmovin/services/inputs/https_input_service_tests.py:35:5: error: Name 'test_create_https_input' already defined on line 27  [no-redef]
(acrisci)playerctl/test/mpris.py:108:6: error: Name 'LoopStatus' already defined on line 104  [no-redef]
(acrisci)playerctl/test/mpris.py:116:6: error: Name 'Rate' already defined on line 112  [no-redef]
(acrisci)playerctl/test/mpris.py:124:6: error: Name 'Shuffle' already defined on line 120  [no-redef]
(acrisci)playerctl/test/mpris.py:136:6: error: Name 'Volume' already defined on line 132  [no-redef]
(rgeorgi)intent/intent/utils/token.py:37:6: error: Name 'parent' already defined on line 30  [no-redef]
(rgeorgi)intent/intent/igt/metadata.py:201:1: error: Name 'set_meta_text' already defined on line 74  [no-redef]
(hydroffice)hyo_soundspeed/hyo2/soundspeed/listener/seacat/seacat_emulator.py:13:5: error: Name 'UTF8Serial' already defined (possibly by an import)  [no-redef]
(mosquito)aio-pika/aio_pika/connection.py:118:9: error: Attribute 'connection' already defined on line 54  [no-redef]
(valerius21)ERMA17/ERMA17_alpha.py:19:1: error: Name 'dispatcher' already defined (possibly by an import)  [no-redef]
(jiadaizhao)LeetCode/0801-0900/0832-Flipping an Image/0832-Flipping an Image.py:7:1: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/1001-1100/1048-Longest String Chain/1048-Longest String Chain.py:24:1: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/0201-0300/0268-Missing Number/0268-Missing Number.py:8:1: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/0901-1000/0962-Maximum Width Ramp/0962-Maximum Width Ramp.py:18:1: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/0701-0800/0756-Pyramid Transition Matrix/0756-Pyramid Transition Matrix.py:29:1: error: Name 'Solution' already defined on line 2  [no-redef]
(jiadaizhao)LeetCode/0701-0800/0712-Minimum ASCII Delete Sum for Two Strings/0712-Minimum ASCII Delete Sum for Two Strings.py:20:1: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/0301-0400/0395-Longest Substring with At Least K Repeating Characters/0395-Longest Substring with At Least K Repeating Characters.py:9:1: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/0301-0400/0367-Valid Perfect Square/0367-Valid Perfect Square.py:15:1: error: Name 'Solution' already defined on line 1  [no-redef]
(jiadaizhao)LeetCode/0301-0400/0341-Flatten Nested List Iterator/0341-Flatten Nested List Iterator.py:65:1: error: Name 'NestedIterator' already defined on line 26  [no-redef]
(jiadaizhao)LeetCode/0801-0900/0820-Short Encoding of Words/0820-Short Encoding of Words.py:13:1: error: Name 'Solution' already defined on line 4  [no-redef]
(korsimoro)indy-sdk/wrappers/python/tests/signus/test_replace_keys.py:36:2: error: Name 'test_replace_keys_works' already defined on line 8  [no-redef]
(Dentosal)python-sc2/sc2/game_info.py:213:21: error: Name 'point' already defined on line 191  [no-redef]
(kissf-lu)jupyter_app/ipython/py36_simpy_sim/effective_python/code/class_property.py:39:6: error: Name 'ohms' already defined on line 31  [no-redef]
(kissf-lu)jupyter_app/ipython/py36_simpy_sim/effective_python/code/class_property.py:48:6: error: Name 'voltage' already defined on line 35  [no-redef]
(saurabh1e)open-pos-api/src/orders/models.py:61:6: error: Name 'items_count' already defined on line 57  [no-redef]
(saurabh1e)open-pos-api/src/orders/models.py:122:6: error: Name 'retail_shop_id' already defined on line 118  [no-redef]
(saurabh1e)open-pos-api/src/user/models.py:155:6: error: Name 'retail_shop_ids' already defined on line 151  [no-redef]
(Vogtinator)micropython/tests/misc/features.py:100:2: error: Name 'A' already defined on line 36  [no-redef]
(Vogtinator)micropython/tests/misc/features.py:135:1: error: Name 'f' already defined on line 89  [no-redef]
(Vogtinator)micropython/tests/extmod/ujson_loads.py:4:5: error: Name 'json' already defined (by an import)  [no-redef]
(asphalt-framework)asphalt-web/asphalt/web/rpc/jsonrpc.py:80:13: error: Attribute 'serializer' already defined on line 55  [no-redef]
(kolypto)py-mongosql/mongosql/util/selectinquery.py:164:2: error: Name 'selectinquery' already defined on line 137  [no-redef]
(kolypto)py-mongosql/mongosql/util/raiseload_col.py:21:2: error: Name 'raiseload_col' already defined on line 6  [no-redef]
(metacontainer)metac/py/metac/unix_http.py:13:5: error: Name 'httplib' already defined (by an import)  [no-redef]
(metacontainer)metac/py/metac/unix_http.py:18:5: error: Name 'urllib3' already defined (by an import)  [no-redef]
(laanwj)bitcoin/contrib/linearize/linearize-hashes.py:14:5: error: Name 'httplib' already defined (by an import)  [no-redef]
(laanwj)bitcoin/contrib/devtools/github-merge.py:29:5: error: Name 'Request' already defined (possibly by an import)  [no-redef]
(laanwj)bitcoin/contrib/devtools/github-merge.py:29:5: error: Name 'urlopen' already defined (possibly by an import)  [no-redef]
(un-def)polypie/tests/samples/specialattrs.py:20:5: error: Name 'check_special_attrs' already defined on line 9  [no-redef]
(Mondanzo)vlt-Music/log.py:15:6: error: Name 'get_time' already defined on line 7  [no-redef]
(fnl)medic/src/medic/web.py:19:5: error: Name 'HTTPResponse' already defined (possibly by an import)  [no-redef]
(fnl)medic/src/medic/web.py:21:5: error: Name 'build_opener' already defined (possibly by an import)  [no-redef]
(denisenkom)pytds/tests/sspi_test.py:4:5: error: Name 'unittest' already defined (possibly by an import)  [no-redef]
(mosen)commandment/commandment/mutablelist.py:14:5: error: Name 'MutableList' already defined (possibly by an import)  [no-redef]
(meyt)sqlalchemy-dict/sqlalchemy_dict/tests/test_base_model.py:152:6: error: Name 'is_visible' already defined on line 148  [no-redef]
(meyt)sqlalchemy-dict/sqlalchemy_dict/tests/test_base_model.py:157:6: error: Name 'is_visible' already defined on line 148  [no-redef]
(KeepSafe)aiohttp/tests/test_web_log.py:147:5: error: Name 'Logger' already defined on line 137  [no-redef]
(KeepSafe)aiohttp/tests/test_web_app.py:100:5: error: Name 'Logger' already defined on line 92  [no-redef]
(TheReverend403)ricedb/plugins/userdb.py:4:5: error: Name 'json' already defined (by an import)  [no-redef]
(SunDwarf)Jokusoramame/jokusoramame/plugins/roles/rolestate.py:123:13: error: Name 'sess' already defined on line 108  [no-redef]
(SunDwarf)Jokusoramame/jokusoramame/plugins/roles/rolestate.py:125:17: error: Name 'setting' already defined on line 110  [no-redef]
(mjirik)io3d/tests/datasets_test.py:37:5: error: Name 'test_download_package_dry_run' already defined on line 32  [no-redef]
(RudolfCardinal)crate/crate_anon/common/extendedconfigparser.py:354:13: error: Name 'env' already defined on line 352  [no-redef]
(Michael-F-Bryan)auto-changelog/tests/test_presenter.py:58:1: error: Name 'test_markdown_presenter_changelog_with_features' already defined on line 38  [no-redef]
(firebase)firebase-android-sdk/ci/fireci/fireci/stats.py:139:2: error: Name 'measure' already defined (possibly by an import)  [no-redef]
(BigBrotherTrade)trader/test/test_api.py:25:5: error: Name 'json' already defined (by an import)  [no-redef]
(SUSE)DeepSea/tests/unit/_modules/test_cephdisks.py:65:6: error: Name 'test_find_root_disk_vnme' already defined on line 56  [no-redef]
(SUSE)DeepSea/tests/unit/runners/test_disk_led.py:101:5: error: Name 'test_process_invalid_arg_1' already defined on line 97  [no-redef]
(SUSE)DeepSea/srv/modules/runners/openstack.py:16:5: error: Name 'configparser' already defined (by an import)  [no-redef]
(HackBinghamton)club/demo/regex/demo.py:115:1: error: Name 'example_7' already defined on line 87  [no-redef]
(HackBinghamton)club/demo/regex/demo.py:125:1: error: Name 'example_7' already defined on line 87  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/outbound_dao.py:4:1: error: Name 'Outbound' already defined (possibly by an import)  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/outbound_dao.py:35:5: error: Name '_from' already defined on line 5  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/outbound_dao.py:38:5: error: Name 'subject' already defined on line 6  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/outbound_dao.py:41:5: error: Name 'story' already defined on line 7  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/inbound_dao.py:38:5: error: Name '_from' already defined on line 5  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/inbound_dao.py:41:5: error: Name 'to' already defined on line 6  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/inbound_dao.py:44:5: error: Name 'subject' already defined on line 7  [no-redef]
(gengstrand)clojure-news-feed/server/feed5/swagger_server/daos/inbound_dao.py:47:5: error: Name 'story' already defined on line 8  [no-redef]
(HugoSoaresFontes)robotic-arm-control-lynxmotion/interface.py:33:1: error: Name 'QSlider' already defined (possibly by an import)  [no-redef]
(HugoSoaresFontes)robotic-arm-control-lynxmotion/interface.py:48:1: error: Name 'QDial' already defined (possibly by an import)  [no-redef]
(esPass)pretix-espass/pretix_espass/signals.py:17:2: error: Name 'register_global_settings' already defined (possibly by an import)  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:37:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:42:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:47:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:52:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:60:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:66:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:71:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:76:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:82:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:89:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:97:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:107:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:115:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:125:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:133:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:141:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:150:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:159:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:169:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:177:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:183:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:192:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:200:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/learning_unit_read.py:212:2: error: Name 'step_impl' already defined on line 32  [no-redef]
(uclouvain)osis/features/steps/5_offer_delete.py:60:2: error: Name 'step_impl' already defined on line 37  [no-redef]
(uclouvain)osis/features/steps/5_offer_delete.py:68:2: error: Name 'step_impl' already defined on line 37  [no-redef]
(uclouvain)osis/features/steps/5_offer_delete.py:76:2: error: Name 'step_impl' already defined on line 37  [no-redef]
(uclouvain)osis/features/steps/student_search.py:44:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/student_search.py:50:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/student_search.py:61:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/student_search.py:72:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:43:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:48:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:57:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:66:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:71:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:76:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:81:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:86:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:91:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:96:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:106:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:118:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:125:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:131:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:136:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/6_offer_update.py:142:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/learning_unit_search.py:41:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/learning_unit_search.py:46:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/learning_unit_search.py:51:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/learning_unit_search.py:57:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/learning_unit_search.py:62:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/learning_unit_search.py:69:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/learning_unit_search.py:74:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/learning_unit_search.py:82:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/learning_unit_search.py:91:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/learning_unit_search.py:99:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/4_offer_create.py:43:2: error: Name 'step_impl' already defined on line 33  [no-redef]
(uclouvain)osis/features/steps/4_offer_create.py:48:2: error: Name 'step_impl' already defined on line 33  [no-redef]
(uclouvain)osis/features/steps/4_offer_create.py:56:2: error: Name 'step_impl' already defined on line 33  [no-redef]
(uclouvain)osis/features/steps/4_offer_create.py:64:2: error: Name 'step_impl' already defined on line 33  [no-redef]
(uclouvain)osis/features/steps/4_offer_create.py:77:2: error: Name 'step_impl' already defined on line 33  [no-redef]
(uclouvain)osis/features/steps/4_offer_create.py:87:2: error: Name 'step_impl' already defined on line 33  [no-redef]
(uclouvain)osis/features/steps/4_offer_create.py:95:2: error: Name 'step_impl' already defined on line 33  [no-redef]
(uclouvain)osis/features/steps/4_offer_create.py:103:2: error: Name 'step_impl' already defined on line 33  [no-redef]
(uclouvain)osis/features/steps/organization_search.py:44:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/organization_search.py:50:2: error: Name 'step_impl' already defined on line 34  [no-redef]
(uclouvain)osis/features/steps/entity_search.py:43:2: error: Name 'step_impl' already defined on line 33  [no-redef]
(uclouvain)osis/features/steps/entity_search.py:49:2: error: Name 'step_impl' already defined on line 33  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:48:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:53:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:62:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:67:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:72:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:80:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:89:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:96:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:104:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:109:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:114:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:119:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:127:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:135:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:143:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:151:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:160:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:168:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:174:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:179:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:188:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:196:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:205:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:213:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:223:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:228:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:238:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:246:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:256:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:265:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:273:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:283:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:291:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:299:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:311:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:319:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:327:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:335:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/learning_unit_edit.py:344:2: error: Name 'step_impl' already defined on line 43  [no-redef]
(uclouvain)osis/features/steps/generic.py:58:2: error: Name 'step_impl' already defined on line 52  [no-redef]
(uclouvain)osis/features/steps/generic.py:72:2: error: Name 'step_impl' already defined on line 52  [no-redef]
(uclouvain)osis/features/steps/generic.py:99:2: error: Name 'step_impl' already defined on line 52  [no-redef]
(uclouvain)osis/features/steps/generic.py:109:2: error: Name 'step_impl' already defined on line 52  [no-redef]
(uclouvain)osis/features/steps/generic.py:116:2: error: Name 'step_impl' already defined on line 52  [no-redef]
(uclouvain)osis/features/steps/generic.py:142:2: error: Name 'step_impl' already defined on line 52  [no-redef]
(uclouvain)osis/features/steps/generic.py:148:2: error: Name 'step_impl' already defined on line 52  [no-redef]
(uclouvain)osis/features/steps/generic.py:155:2: error: Name 'step_impl' already defined on line 52  [no-redef]
(uclouvain)osis/features/steps/generic.py:177:2: error: Name 'step_impl' already defined on line 52  [no-redef]
(uclouvain)osis/features/steps/generic.py:191:2: error: Name 'step_impl' already defined on line 52  [no-redef]
(uclouvain)osis/features/steps/generic.py:205:2: error: Name 'step_impl' already defined on line 52  [no-redef]
(uclouvain)osis/features/steps/generic.py:210:2: error: Name 'step_impl' already defined on line 52  [no-redef]
(pythondigest)pythondigest/digest/management/commands/__init__.py:15:5: error: Name 'urlopen' already defined (possibly by an import)  [no-redef]
(outlierbio)ob-pipelines/ob_pipelines/entities/experiment.py:27:6: error: Name 'name' already defined on line 19  [no-redef]
(outlierbio)ob-pipelines/ob_pipelines/entities/task.py:66:6: error: Name 'name' already defined on line 42  [no-redef]
(outlierbio)ob-pipelines/ob_pipelines/entities/task.py:70:6: error: Name 'status' already defined on line 58  [no-redef]
(outlierbio)ob-pipelines/ob_pipelines/entities/task.py:76:6: error: Name 'started_at' already defined on line 50  [no-redef]
(outlierbio)ob-pipelines/ob_pipelines/entities/task.py:80:6: error: Name 'completed_at' already defined on line 54  [no-redef]
(outlierbio)ob-pipelines/ob_pipelines/entities/task.py:84:6: error: Name 'exception' already defined on line 62  [no-redef]
(dpshelio)sunpy/sunpy/database/attrs.py:160:2: error: Name '_create' already defined on line 151  [no-redef]
(dpshelio)sunpy/sunpy/database/attrs.py:166:2: error: Name '_create' already defined on line 151  [no-redef]
(dpshelio)sunpy/sunpy/database/attrs.py:230:2: error: Name '_convert' already defined on line 225  [no-redef]
(dpshelio)sunpy/sunpy/database/attrs.py:235:2: error: Name '_convert' already defined on line 225  [no-redef]
(dpshelio)sunpy/sunpy/database/attrs.py:240:2: error: Name '_convert' already defined on line 225  [no-redef]
(dpshelio)sunpy/sunpy/database/attrs.py:246:2: error: Name '_convert' already defined on line 225  [no-redef]
(dpshelio)sunpy/sunpy/database/attrs.py:252:2: error: Name '_convert' already defined on line 225  [no-redef]
(dpshelio)sunpy/sunpy/database/attrs.py:257:2: error: Name '_convert' already defined on line 225  [no-redef]
(dpshelio)sunpy/sunpy/database/attrs.py:262:2: error: Name '_convert' already defined on line 225  [no-redef]
(dpshelio)sunpy/tools/hektemplate.py:219:2: error: Name '_a' already defined on line 197  [no-redef]
(dpshelio)sunpy/tools/hektemplate.py:226:2: error: Name '_a' already defined on line 219  [no-redef]
(dpshelio)sunpy/tools/hektemplate.py:236:2: error: Name '_a' already defined on line 219  [no-redef]
(dpshelio)sunpy/tools/hektemplate.py:244:2: error: Name '_a' already defined on line 219  [no-redef]
(dpshelio)sunpy/tools/hektemplate.py:257:2: error: Name '_a' already defined on line 219  [no-redef]
(dpshelio)sunpy/tools/hektemplate.py:263:2: error: Name '_c' already defined on line 211  [no-redef]
(dpshelio)sunpy/sunpy/map/map_factory.py:44:5: error: Name 'DatabaseEntry' already defined (possibly by an import)  [no-redef]
(srusskih)SublimeJEDI/dependencies/jedi/debug.py:50:5: error: Name 'Fore' already defined (possibly by an import)  [no-redef]
(tuanavu)python-cookbook-3rd/src/8/implementing_a_data_model_or_type_system/example_clsdec.py:130:5: error: Name 'Stock' already defined on line 115  [no-redef]
(tuanavu)python-cookbook-3rd/src/8/implementing_a_data_model_or_type_system/example_clsdec.py:142:5: error: Name 'Stock' already defined on line 115  [no-redef]
(ctxis)cvsslib/cvsslib/base_enum.py:7:5: error: Name 'lru_cache' already defined (possibly by an import)  [no-redef]
(ctxis)cvsslib/cvsslib/utils.py:8:5: error: Name 'lru_cache' already defined (possibly by an import)  [no-redef]
(ctxis)cvsslib/tests/test_vector.py:42:2: error: Name 'test_v3_vector_files_random2' already defined on line 35  [no-redef]
(MegaShow)college-programming/Homework/Principles of Artificial Neural Networks/Week 8 Object Detection/utils1.py:32:1: error: Name 'train' already defined (possibly by an import)  [no-redef]
(MegaShow)college-programming/Homework/Principles of Artificial Neural Networks/Week 8 Object Detection/utils1.py:92:1: error: Name 'validate' already defined (possibly by an import)  [no-redef]
(vijos)vj4/vj4/handler/home.py:155:1: error: Name 'HomeAccountHandler' already defined on line 127  [no-redef]
(vijos)vj4/vj4/job/num.py:16:2: error: Name 'discussion' already defined (possibly by an import)  [no-redef]
(Ghadjeres)DeepBach/musescore_flask_server.py:241:1: error: Name 'get_fermatas_tensor' already defined on line 133  [no-redef]
(BigEgg)LeetCode/Python/LeetCode.Test/_001_050/Test_003_LongestSubstringWithoutRepeatingCharacters.py:19:5: error: Name 'test_lengthOfLongestSubstring' already defined on line 10  [no-redef]
(BigEgg)LeetCode/Python/LeetCode.Test/_001_050/Test_002_AddTwoNumbers.py:100:5: error: Name 'test_addTwoNumbers_l1Long_withZero' already defined on line 70  [no-redef]
(BigEgg)LeetCode/Python/LeetCode.Test/_001_050/Test_002_AddTwoNumbers.py:110:5: error: Name 'test_addTwoNumbers_l1None' already defined on line 80  [no-redef]
(Pink-Silver)PyDoom/pydoom.py:34:5: error: Name 'GITVERSION' already defined on line 32  [no-redef]
(HPAC)matchpy/matchpy/expressions/functions.py:165:2: error: Name '_' already defined on line 151  [no-redef]
(shafferm)SCNIC/SCNIC/between_correls.py:23:1: error: Name 'spearmanr' already defined (possibly by an import)  [no-redef]
(shafferm)SCNIC/SCNIC/correlation_analysis.py:26:1: error: Name 'spearmanr' already defined (possibly by an import)  [no-redef]
(rmorshea)spectate/tests/test_core.py:20:5: error: Name 'signature' already defined (possibly by an import)  [no-redef]
(Wintellect)WintellectWebinars/2019-06-06-ten-tips-python-web-devs-kennedy/code/top_10_web_explore/ex07_viewmodels/pypi_vm/viewmodels/packages/package_details_viewmodel.py:17:13: error: Attribute 'latest_release' already defined on line 14  [no-redef]
(datmellow)League.py/league/__init__.py:41:5: error: Name 'NullHandler' already defined (possibly by an import)  [no-redef]
(smlbiobot)SML-Cogs/reactionpoll/reactionpoll.py:104:6: error: Name 'reactionpoll_add' already defined on line 76  [no-redef]
(superdesk)Live-Blog/documentor/libraries/Sphinx-1.1.3-py3.2/sphinx/locale/__init__.py:77:5: error: Name '__str__' already defined on line 74  [no-redef]
(jcchoiling)learningPython/s13/Day11/practice/s21.py:54:1: error: Name 'put' already defined on line 12  [no-redef]
(JustArchi)program-y/src/test/aiml_tests/condition_tests/test_condition_aiml.py:79:5: error: Name 'test_condition_type3_variant1_default' already defined on line 74  [no-redef]
(JustArchi)program-y/src/test/aiml_tests/get_tests/test_get_aiml.py:46:5: error: Name 'test_name_get_with_topic' already defined on line 41  [no-redef]
(StructuralNeurobiologyLab)SyConn/syconn/extraction/block_processing.py:12:5: error: Name 'pkl' already defined (possibly by an import)  [no-redef]
(StructuralNeurobiologyLab)SyConn/syconn/proc/depr_realignment_trafo.py:10:5: error: Name 'pkl' already defined (possibly by an import)  [no-redef]
(StructuralNeurobiologyLab)SyConn/syconn/proc/depr_checking.py:10:5: error: Name 'pkl' already defined (possibly by an import)  [no-redef]
(StructuralNeurobiologyLab)SyConn/syconn/cnn/miga.py:12:5: error: Name 'pkl' already defined (possibly by an import)  [no-redef]
(SWE574-Nerds)friendly-eureka/backend/eureka/api/dto/LoginForm.py:10:5: error: Name '__init__' already defined on line 5  [no-redef]
(SWE574-Nerds)friendly-eureka/backend/eureka/api/dto/RegisterForm.py:14:5: error: Name '__init__' already defined on line 9  [no-redef]
(michaeljoseph)changes/changes/models/repository.py:189:6: error: Name 'description' already defined on line 183  [no-redef]
(michaeljoseph)changes/changes/models/repository.py:193:6: error: Name 'author' already defined on line 184  [no-redef]
(juancarlospaco)anglerfish/examples/basic.py:159:2: error: Name 'process_job' already defined on line 140  [no-redef]
(usc-isi-i2)etk/etk/segment.py:110:9: error: Name 'storage_provenance_record' already defined on line 85  [no-redef]
(timercrack)pydatacoll/pydatacoll/plugins/formula_calc.py:26:5: error: Name 'json' already defined (by an import)  [no-redef]
(timercrack)pydatacoll/pydatacoll/plugins/db_save.py:23:5: error: Name 'json' already defined (by an import)  [no-redef]
(all3fox)algos-py/test/test_graph/test_graph.py:162:5: error: Name 'test_has_cycle_3' already defined on line 156  [no-redef]
(all3fox)algos-py/test/test_sset/test_sset.py:395:2: error: Name 'test_remove_5' already defined on line 379  [no-redef]
(all3fox)algos-py/test/test_gcf.py:26:1: error: Name 'test_00' already defined on line 7  [no-redef]
(all3fox)algos-py/test/test_gcf.py:29:1: error: Name 'test_10' already defined on line 10  [no-redef]
(all3fox)algos-py/test/test_gcf.py:32:1: error: Name 'test_01' already defined on line 13  [no-redef]
(purduesigbots)pros-cli/pros/common/ui/interactive/components/container.py:7:1: error: Name 'Container' already defined (possibly by an import)  [no-redef]
(purduesigbots)pros-cli/pros/serial/ports/serial_share_bridge.py:94:13: error: Attribute 'dying' already defined on line 41  [no-redef]
(purduesigbots)pros-cli/pros/cli/conductor_utils.py:93:9: error: Name 'matching_files' already defined on line 75  [no-redef]
(purduesigbots)pros-cli/pros/cli/conductor_utils.py:99:5: error: Name 'matching_system_files' already defined on line 96  [no-redef]
(purduesigbots)pros-cli/pros/conductor/conductor.py:76:9: error: Name 'template' already defined on line 64  [no-redef]
(NicolasLM)spinach/spinach/contrib/datadog.py:20:9: error: Name 'tracer' already defined on line 6  [no-redef]
(ak110)pytoolkit/pytoolkit/__init__.py:29:9: error: Name 'keras' already defined on line 26  [no-redef]
(vatlab)SOS/test/test_docker_actions.py:22:5: error: Name '_thread' already defined (by an import)  [no-redef]
(TuSimple)mxnet/tests/python/unittest/test_gluon_data.py:108:1: error: Name 'Dataset' already defined (possibly by an import)  [no-redef]
(NLeSC)noodles/examples/class-decorator.py:36:6: error: Name 'attr' already defined on line 29  [no-redef]
(NLeSC)noodles/noodles/serial/registry.py:11:5: error: Name 'json' already defined (by an import)  [no-redef]
(NLeSC)noodles/noodles/prov/sqlite.py:41:5: error: Name 'json' already defined (by an import)  [no-redef]
(NLeSC)noodles/noodles/prov/key.py:6:5: error: Name 'json' already defined (by an import)  [no-redef]
(johnbywater)eventsourcing/eventsourcing/tests/core_tests/test_persistence_policy.py:13:5: error: Name 'mock' already defined (by an import)  [no-redef]
(DesertBot)DesertBot/desertbot/modules/commands/LogSearch.py:15:5: error: Name 're2' already defined (possibly by an import)  [no-redef]
(DesertBot)DesertBot/desertbot/modules/commands/Sed.py:15:5: error: Name 're2' already defined (possibly by an import)  [no-redef]
(DesertBot)DesertBot/desertbot/modules/commands/Tell.py:17:5: error: Name 're2' already defined (possibly by an import)  [no-redef]
(pypa)virtualenv/tests/conftest.py:16:5: error: Name 'Path' already defined (possibly by an import)  [no-redef]
(pypa)virtualenv/tests/test_from_source.py:13:5: error: Name 'Path' already defined (possibly by an import)  [no-redef]
(pracedru)PracedruDesign/Data/Vertex.py:73:3: error: Name 'x' already defined on line 61  [no-redef]
(pracedru)PracedruDesign/Data/Vertex.py:77:3: error: Name 'y' already defined on line 65  [no-redef]
(pracedru)PracedruDesign/Data/Vertex.py:81:3: error: Name 'z' already defined on line 69  [no-redef]
(pracedru)PracedruDesign/Data/Point3d.py:169:3: error: Name 'x' already defined on line 157  [no-redef]
(pracedru)PracedruDesign/Data/Point3d.py:173:3: error: Name 'y' already defined on line 161  [no-redef]
(pracedru)PracedruDesign/Data/Point3d.py:177:3: error: Name 'z' already defined on line 165  [no-redef]
(AlexandreDecan)sismic/sismic/bdd/wrappers.py:38:6: error: Name '_' already defined on line 34  [no-redef]
(keon)algorithms/algorithms/matrix/sparse_mul.py:47:1: error: Name 'multiply' already defined on line 27  [no-redef]
(keon)algorithms/algorithms/matrix/sparse_mul.py:71:1: error: Name 'multiply' already defined on line 27  [no-redef]
(PyconUK)ConferenceScheduler/tests/lp_problem/test_constraints.py:167:1: error: Name 'test_constraints' already defined on line 160  [no-redef]
(ozmartian)tvlinker/tvlinker/threads.py:26:5: error: Name 'json' already defined (by an import)  [no-redef]
(M1ND-B3ND3R)BoopSuite/boop/__main__.py:16:2: error: Name 'pkt' already defined on line 11  [no-redef]
(ajinabraham)Mobile-Security-Framework-MobSF/scripts/start_avd.py:199:5: error: Name 'Qcow2' already defined (possibly by an import)  [no-redef]
(ajinabraham)Mobile-Security-Framework-MobSF/install/windows/setup.py:14:5: error: Name 'urlrequest' already defined (by an import)  [no-redef]
(choderalab)openmmtools/devtools/scripts/create_conda_env.py:15:9: error: Name 'yaml' already defined (by an import)  [no-redef]
(NephyProject)PyChroner/pychroner/thread/wrapper.py:36:9: error: Name 'args' already defined on line 31  [no-redef]
(lbryio)lbrycrd/contrib/linearize/linearize-hashes.py:14:5: error: Name 'httplib' already defined (by an import)  [no-redef]
(ulikoehler)UliEngineering/tests/Electronics/TestVoltageDivider.py:43:5: error: Name 'test_feedback_voltage' already defined on line 38  [no-redef]
(ulikoehler)UliEngineering/tests/Math/TestGeometry.py:45:6: error: Name 'test_polygon_area_rectangle' already defined on line 37  [no-redef]
(ulikoehler)UliEngineering/tests/Utils/TestNumPy.py:67:5: error: Name 'test_ngrams2' already defined on line 54  [no-redef]
(ulikoehler)UliEngineering/tests/Utils/TestNumPy.py:102:5: error: Name 'test_timedelta64_resolution' already defined on line 91  [no-redef]
(ulikoehler)UliEngineering/tests/TestEngineerIO.py:165:5: error: Name 'test_exp_suffix_map' already defined on line 153  [no-redef]
(ulikoehler)UliEngineering/tests/TestEngineerIO.py:190:6: error: Name 'test_normalize_numeric_invalid' already defined on line 56  [no-redef]
(ulikoehler)UliEngineering/tests/SignalProcessing/TestWindow.py:23:5: error: Name 'testWindowFunctor' already defined on line 12  [no-redef]
(Debith)py3traits/tests/unittest_typeconverted.py:72:5: error: Name 'test_handles_properly_tuple_arguments_with_type' already defined on line 65  [no-redef]
(Debith)py3traits/tests/unittest_inspector.py:96:6: error: Name 'test_isclass_checks_identifies_types_properly' already defined on line 92  [no-redef]
(Debith)py3traits/tests/unittest_typesafe.py:71:5: error: Name 'test_handles_properly_tuple_arguments_with_type' already defined on line 64  [no-redef]
(Debith)py3traits/tests/unittest_traits.py:26:5: error: Name 'test_does_not_need_preprosessing_for_multiple_trait_functions' already defined on line 22  [no-redef]
(dmlc)mxnet/tests/python/unittest/test_gluon_data.py:150:1: error: Name 'Dataset' already defined (possibly by an import)  [no-redef]
(wright-group)WrightTools/tests/data/from_PyCMDS.py:137:1: error: Name 'test_two_centers' already defined on line 124  [no-redef]
(facebook)fbthrift/thrift/lib/py/server/test/handler.py:9:5: error: Name 'asyncio' already defined (by an import)  [no-redef]
(facebook)fbthrift/thrift/compiler/test/fixtures/basic-annotations/gen-py/module/MyServicePrioChild.py:32:5: error: Name 'fastproto' already defined on line 29  [no-redef]
(facebook)fbthrift/thrift/compiler/test/fixtures/namespace/gen-py/my/namespacing/test/module/TestService.py:27:5: error: Name 'fastproto' already defined on line 24  [no-redef]
(facebook)fbthrift/thrift/compiler/test/fixtures/includes/gen-py/includes/ttypes.py:28:5: error: Name 'fastproto' already defined on line 25  [no-redef]
(FrancescoCeruti)linux-show-player/lisp/ui/styles/styles.py:30:5: error: Name 'scandir' already defined (possibly by an import)  [no-redef]
(welbornprod)colr/colr/colr_docopt.py:134:1: error: Name 'docopt' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 12/1c.py:7:1: error: Name 'f' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 12/1ab.py:6:1: error: Name 'f' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 11/1a.py:9:1: error: Name 'f' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 11/1a.py:13:1: error: Name 'g' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 10/simpson_err.py:8:1: error: Name 'f' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 10/romberg_err.py:8:1: error: Name 'f' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 10/trapezoidal_err.py:8:1: error: Name 'f' already defined (possibly by an import)  [no-redef]
(Jokiva)Computational-Physics/lecture 10/Problem 2.py:7:1: error: Name 'f' already defined (possibly by an import)  [no-redef]
(nismod)smif/src/smif/data_layer/results.py:26:13: error: Attribute '_store' already defined on line 24  [no-redef]
(nismod)smif/docs/conf.py:182:5: error: Name 'version' already defined on line 123  [no-redef]
(MobSF)Mobile-Security-Framework-MobSF/install/windows/setup.py:21:5: error: Name 'urlrequest' already defined (by an import)  [no-redef]
(plugaai)aioinflux/aioinflux/serialization/dataframe.py:21:5: error: Name 'df' already defined on line 18  [no-redef]
(plugaai)aioinflux/aioinflux/serialization/dataframe.py:54:9: error: Name 'series' already defined on line 48  [no-redef]
(ariebovenberg)snug/tests/test_clients.py:12:5: error: Name 'urllib' already defined (by an import)  [no-redef]
(ariebovenberg)snug/tests/test_query.py:13:5: error: Name 'urllib' already defined (by an import)  [no-redef]
(parrt)AniML/testing/testone.py:8:1: error: Name 'viz_iris' already defined (possibly by an import)  [no-redef]
(parrt)AniML/testing/testone.py:40:1: error: Name 'viz_boston' already defined (possibly by an import)  [no-redef]
(parrt)AniML/testing/testone.py:59:1: error: Name 'viz_knowledge' already defined (possibly by an import)  [no-redef]
(parrt)AniML/testing/testone.py:79:1: error: Name 'viz_diabetes' already defined (possibly by an import)  [no-redef]
(parrt)AniML/testing/testone.py:113:1: error: Name 'viz_digits' already defined (possibly by an import)  [no-redef]
(SunDwarf)OWAPI/owapi/app.py:138:2: error: Name 'root' already defined on line 31  [no-redef]
(chovanecm)sacredboard/sacredboard/tests/business/test_runfacade.py:28:2: error: Name 'test_removing_a_run' already defined on line 22  [no-redef]
(codesardine)Jade-Application-Kit/JAK/IPC.py:6:5: error: Name 'JavaScript' already defined (possibly by an import)  [no-redef]
(codesardine)Jade-Application-Kit/JAK/WebEngine.py:61:13: error: Name 'JCancelConfirmDialog' already defined (possibly by an import)  [no-redef]
(codesardine)Jade-Application-Kit/JAK/WebEngine.py:89:17: error: Name '_Communication' already defined (possibly by an import)  [no-redef]
(codesardine)Jade-Application-Kit/JAK/WebEngine.py:315:13: error: Name 'InfoDialog' already defined (possibly by an import)  [no-redef]
(wegamekinglc)alpha-mind/alphamind/model/composer.py:247:5: error: Name 'DataMeta' already defined on line 41  [no-redef]
(socialwifi)dila/tests/test_application.py:103:2: error: Name 'test_get_resources' already defined on line 71  [no-redef]
(socialwifi)dila/tests/test_application.py:222:2: error: Name 'test_get_translated_string' already defined on line 126  [no-redef]
(RasaHQ)rasa_core/rasa/core/policies/keras_policy.py:21:5: error: Name 'pickle' already defined (possibly by an import)  [no-redef]
(artificilabs)trelliolibs/trelliolibs/utils/helpers.py:11:5: error: Name 'json' already defined (by an import)  [no-redef]
(artificilabs)trelliolibs/trelliolibs/contrib/rbac/middlewares.py:6:5: error: Name 'json' already defined (by an import)  [no-redef]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/distribute/cluster_resolver/gce_cluster_resolver.py:173:4: error: Name 'task_type' already defined on line 165  [no-redef]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/distribute/cluster_resolver/gce_cluster_resolver.py:179:4: error: Name 'task_index' already defined on line 169  [no-redef]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/distribute/cluster_resolver/tfconfig_cluster_resolver.py:90:4: error: Name 'task_type' already defined on line 74  [no-redef]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/distribute/cluster_resolver/tfconfig_cluster_resolver.py:94:4: error: Name 'task_index' already defined on line 82  [no-redef]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/keras/engine/training_dataset_test.py:35:1: error: Name 'logging' already defined (by an import)  [no-redef]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/platform/googletest.py:94:1: error: Name 'main' already defined (possibly by an import)  [no-redef]
(kubeflow)kfserving/vendor/github.com/tensorflow/tensorflow/tensorflow/python/util/tf_inspect.py:34:17: error: Name 'FullArgSpec' already defined on line 32  [no-redef]
(mikeckennedy)write-pythonic-code-demos/code/ch_05_functions/_05_variable_length_arguments.py:12:1: error: Name 'biggest' already defined on line 1  [no-redef]
(mikeckennedy)write-pythonic-code-demos/code/ch_05_functions/_03_no_overloading.py:6:5: error: Name 'simple' already defined on line 3  [no-redef]
(samuelcolvin)arq/tests/test_jobs.py:39:5: error: Name 'worker' already defined on line 32  [no-redef]
(samuelcolvin)arq/tests/test_main.py:23:5: error: Name 'worker' already defined on line 18  [no-redef]
(samuelcolvin)arq/tests/test_main.py:51:5: error: Name 'worker' already defined on line 46  [no-redef]
(samuelcolvin)arq/tests/test_main.py:110:5: error: Name 'worker' already defined on line 93  [no-redef]
(getnikola)nikola/nikola/image_processing.py:41:5: error: Name 'Image' already defined on line 39  [no-redef]
(prkumar)uplink/uplink/utils.py:64:5: error: Name '_urlparse' already defined (by an import)  [no-redef]
(Ajapaik)ajapaik-web/ajapaik/ajapaik_face_recognition/management/commands/run_face_encoding_on_unencoded_rectangles.py:4:1: error: Name 'pickle' already defined (possibly by an import)  [no-redef]
(BookOwl)nustack/nustack/stdlib/Seq.py:26:2: error: Name 'first' already defined on line 17  [no-redef]
(BookOwl)nustack/nustack/stdlib/String.py:55:2: error: Name 'to_bytes' already defined on line 49  [no-redef]
(BookOwl)nustack/nustack/stdlib/Math.py:76:2: error: Name 'cos' already defined on line 64  [no-redef]
(BookOwl)nustack/nustack/stdlib/Math.py:82:2: error: Name 'cos' already defined on line 76  [no-redef]
(BookOwl)nustack/nustack/stdlib/Math.py:88:2: error: Name 'sin' already defined on line 70  [no-redef]
(BookOwl)nustack/nustack/stdlib/Math.py:94:2: error: Name 'cos' already defined on line 64  [no-redef]
(BookOwl)nustack/nustack/stdlib/Requests.py:31:2: error: Name 'get' already defined on line 24  [no-redef]
(BookOwl)nustack/nustack/stdlib/Requests.py:38:2: error: Name 'get' already defined on line 24  [no-redef]
(BookOwl)nustack/nustack/stdlib/Requests.py:45:2: error: Name 'get' already defined on line 24  [no-redef]
(BookOwl)nustack/nustack/stdlib/Requests.py:52:2: error: Name 'get' already defined on line 24  [no-redef]
(BookOwl)nustack/nustack/stdlib/Requests.py:59:2: error: Name 'get' already defined on line 24  [no-redef]
(BookOwl)nustack/nustack/stdlib/Requests.py:68:2: error: Name 'get' already defined on line 24  [no-redef]
(biosustain)venom/venom/protocol/__init__.py:17:5: error: Name 'json' already defined (by an import)  [no-redef]
(coldfix)pystif/pystif/core/geom.py:143:5: error: Name 'search_ensure_vertex' already defined on line 99  [no-redef]
(coldfix)pystif/test/test_it.py:31:5: error: Name 'test_elemental_inequalities_2' already defined on line 23  [no-redef]
(pyGrowler)Growler/growler/http/responder.py:274:6: error: Name 'headers' already defined on line 45  [no-redef]
(pyGrowler)Growler/tests/test_middleware_chain.py:111:1: error: Name 'test_chain_calls_iterate_subchain' already defined on line 98  [no-redef]
(pyGrowler)Growler/tests/middleware/test_renderer.py:59:1: error: Name 'test_string_renderer_fixture' already defined on line 54  [no-redef]
(pyGrowler)Growler/tests/test_http_responder.py:49:2: error: Name 'responder' already defined (possibly by an import)  [no-redef]
(googleapis)sample-tester/tests/convention/tag_test.py:73:3: error: Name 'test_invocation_with_placeholder' already defined on line 58  [no-redef]
(Parsl)parsl/parsl/executors/serialize/codeutil.py:21:5: error: Name 'copyreg' already defined (by an import)  [no-redef]
(dylanbstorey)angreal/tests/unit/integrations/test_git.py:21:5: error: Name 'test_git_1' already defined on line 11  [no-redef]
(rachekalmir)pyJolt/pyjolt/transforms/shiftr.py:156:9: error: Name 'spec' already defined on line 143  [no-redef]
(rachekalmir)pyJolt/pyjolt/transforms/shiftr.py:156:15: error: Name 'data' already defined on line 143  [no-redef]
(alexbielen)chainsmoke/chainsmoke/decide.py:39:1: error: Name 'Decision' already defined on line 28  [no-redef]
(alexbielen)chainsmoke/chainsmoke/decide.py:76:1: error: Name 'Action' already defined on line 32  [no-redef]
(morganbengtsson)microreader/favicon.py:8:5: error: Name 'Request' already defined (possibly by an import)  [no-redef]
(morganbengtsson)microreader/favicon.py:8:5: error: Name 'urlopen' already defined (possibly by an import)  [no-redef]
(morganbengtsson)microreader/favicon.py:9:5: error: Name 'urlretrieve' already defined (possibly by an import)  [no-redef]
(morganbengtsson)microreader/microreader.py:7:5: error: Name 'urlunsplit' already defined (possibly by an import)  [no-redef]
(morganbengtsson)microreader/microreader.py:8:5: error: Name 'urlencode' already defined (possibly by an import)  [no-redef]
(morganbengtsson)microreader/microreader.py:53:1: error: Name 'favicon' already defined (by an import)  [no-redef]
(morganbengtsson)microreader/microreader.py:255:2: error: Name 'update_channels' already defined on line 243  [no-redef]
(Nic30)hwtLib/docs/_ext/aafig.py:28:5: error: Name 'sha' already defined (possibly by an import)  [no-redef]
(viraja1)grammar-check/grammar_check/backports/subprocess.py:22:5: error: Name 'CalledProcessError' already defined (possibly by an import)  [no-redef]
(viraja1)grammar-check/download_lt.py:22:5: error: Name 'urlopen' already defined (possibly by an import)  [no-redef]
(viraja1)grammar-check/download_lt.py:23:5: error: Name 'urljoin' already defined (possibly by an import)  [no-redef]
