[RRepo](sliceofcode)dogbot
(sliceofcode)dogbot/dog/core/utils/enum.py:1: error: Module 'enum' has no attribute 'Enum'  [attr-defined]
(sliceofcode)dogbot/dog/core/utils/enum.py:13: error: Name 'DogbotContext' is not defined  [name-defined]
(sliceofcode)dogbot/dog/core/context.py:173: error: Module has no attribute "format_list"  [attr-defined]

[RRepo](movidius)ncappzoo
(movidius)ncappzoo/apps/classifier_grid/canvas.py:105: error: Need type annotation for '_grid_image_list' (hint: "_grid_image_list: List[<type>] = ...")  [var-annotated]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:106: error: Need type annotation for '_large_image_list' (hint: "_large_image_list: List[<type>] = ...")  [var-annotated]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:114: error: No overload variant of "__setitem__" of "list" matches argument types "int", "int"  [call-overload]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:114: note: Possible overload variants:
(movidius)ncappzoo/apps/classifier_grid/canvas.py:114: note:     def __setitem__(self, int, None) -> None
(movidius)ncappzoo/apps/classifier_grid/canvas.py:114: note:     def __setitem__(self, slice, Iterable[None]) -> None
(movidius)ncappzoo/apps/classifier_grid/canvas.py:205: error: Argument 1 to "draw_inference_label" of "Canvas" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:304: error: Argument 3 to "_put_text_on_canvas" of "Canvas" has incompatible type "None"; expected "int"  [arg-type]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:311: error: Argument 3 to "_put_text_on_canvas" of "Canvas" has incompatible type "None"; expected "int"  [arg-type]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:323: error: Unsupported operand types for - ("None" and "int")  [operator]
(movidius)ncappzoo/apps/classifier_grid/canvas.py:331: error: Unsupported operand types for - ("None" and "int")  [operator]
(movidius)ncappzoo/apps/mnist_calc/calcui.py:150: error: Read-only property cannot override read-write property  [misc]
(movidius)ncappzoo/apps/mnist_calc/calcui.py:156: error: Read-only property cannot override read-write property  [misc]
(movidius)ncappzoo/apps/classifier_gui/classifier_gui.py:19: error: Name 'Image' already defined (possibly by an import)  [no-redef]
Found 11 errors in 3 files (checked 16 source files)

[RRepo](portfoliome)foil
(portfoliome)foil/foil/counting.py:10: error: Need type annotation for 'counter'  [var-annotated]

[RRepo](coblo)pyiscclib
(coblo)pyiscclib/src/iscclib/data.py:83: error: Need type annotation for 'ids' (hint: "ids: Set[<type>] = ...")  [var-annotated]
(coblo)pyiscclib/src/iscclib/instance.py:111: error: Need type annotation for 'ids' (hint: "ids: Set[<type>] = ...")  [var-annotated]
(coblo)pyiscclib/ci/appveyor-bootstrap.py:17: error: Module 'urllib' has no attribute 'urlretrieve'  [attr-defined]
(coblo)pyiscclib/ci/appveyor-bootstrap.py:17: error: Name 'urlretrieve' already defined (possibly by an import)  [no-redef]
Found 4 errors in 3 files (checked 26 source files)

[RRepo](motion-planning)rrt-algorithms
Success: no issues found in 12 source files

[RRepo](Nexterot)labyrinth-project
Success: no issues found in 14 source files

[RRepo](c3cashdesk)postix
(c3cashdesk)postix/src/tests/core/utils/test_iputils.py:6: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/backoffice/test_backoffice_views_auth.py:3: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/backoffice/test_access.py:6: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/backoffice/test_views_supply.py:5: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/backoffice/test_checks.py:6: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/backoffice/test_views_user_management.py:4: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/backoffice/test_views_records.py:5: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/backoffice/test_backoffice_views_session.py:5: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/troubleshooter/test_troubleshooter_access.py:7: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/troubleshooter/test_troubleshooter_views_information.py:3: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/troubleshooter/test_troubleshooter_views_transactions.py:3: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/troubleshooter/test_troubleshooter_views_preorder.py:5: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/troubleshooter/test_troubleshooter_views_auth.py:3: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/troubleshooter/test_troubleshooter_views_ping.py:5: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/troubleshooter/test_invoicing.py:5: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/desk/test_views.py:3: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/backoffice/views/user_management.py:10: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/backoffice/views/user_management.py:11: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/troubleshooter/views/desk.py:6: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/troubleshooter/views/main.py:7: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/troubleshooter/views/preorders.py:8: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/troubleshooter/views/preorders.py:9: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/troubleshooter/views/constraints.py:9: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/troubleshooter/views/transactions.py:12: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/troubleshooter/views/transactions.py:15: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/troubleshooter/views/transactions.py:16: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/troubleshooter/context.py:4: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/desk/views.py:13: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/desk/views.py:14: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/troubleshooter/test_troubleshooter_views_constraints.py:5: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'Asset'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'Cashdesk'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'CashdeskSession'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'EventSettings'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'Item'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'ItemMovement'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'ListConstraint'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'ListConstraintEntry'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'ListConstraintProduct'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'Preorder'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'PreorderPosition'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'Product'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'ProductItem'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'Quota'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'TimeConstraint'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'Transaction'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'TransactionPosition'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'User'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'WarningConstraint'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:7: error: Module 'core.models' has no attribute 'WarningConstraintProduct'  [attr-defined]
(c3cashdesk)postix/src/postix/core/admin.py:18: error: Need type annotation for 'exclude' (hint: "exclude: List[<type>] = ...")  [var-annotated]
(c3cashdesk)postix/src/postix/core/admin.py:74: error: Need type annotation for 'filter_horizontal' (hint: "filter_horizontal: List[<type>] = ...")  [var-annotated]
(c3cashdesk)postix/src/tests/core/models/test_base.py:7: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/backoffice/test_wizard.py:10: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/api/test_viewsets.py:5: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/api/test_actions.py:5: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/api/test_auth.py:6: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/api/test_sale.py:8: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/api/test_preorder_redeem.py:8: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/tests/troubleshooter/test_troubleshooter_views_desk.py:7: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/core/utils/flow.py:7: error: Module 'core.models' has no attribute 'CashdeskSession'  [attr-defined]
(c3cashdesk)postix/src/postix/core/utils/flow.py:7: error: Module 'core.models' has no attribute 'ListConstraintEntry'  [attr-defined]
(c3cashdesk)postix/src/postix/core/utils/flow.py:7: error: Module 'core.models' has no attribute 'ListConstraintProduct'  [attr-defined]
(c3cashdesk)postix/src/postix/core/utils/flow.py:7: error: Module 'core.models' has no attribute 'PreorderPosition'  [attr-defined]
(c3cashdesk)postix/src/postix/core/utils/flow.py:7: error: Module 'core.models' has no attribute 'Product'  [attr-defined]
(c3cashdesk)postix/src/postix/core/utils/flow.py:7: error: Module 'core.models' has no attribute 'Transaction'  [attr-defined]
(c3cashdesk)postix/src/postix/core/utils/flow.py:7: error: Module 'core.models' has no attribute 'TransactionPosition'  [attr-defined]
(c3cashdesk)postix/src/postix/core/utils/flow.py:7: error: Module 'core.models' has no attribute 'TransactionPositionItem'  [attr-defined]
(c3cashdesk)postix/src/postix/core/utils/flow.py:7: error: Module 'core.models' has no attribute 'User'  [attr-defined]
(c3cashdesk)postix/src/postix/core/models/cashdesk.py:13: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/core/models/cashdesk.py:14: error: Relative import climbs too many namespaces  [misc]
(c3cashdesk)postix/src/postix/core/models/cashdesk.py:205: error: Need type annotation for 'transaction_dict'  [var-annotated]
(c3cashdesk)postix/src/postix/core/models/cashdesk.py:206: error: Need type annotation for 'movement_dict'  [var-annotated]
(c3cashdesk)postix/src/postix/core/models/cashdesk.py:207: error: Need type annotation for 'post_movement_dict'  [var-annotated]
(c3cashdesk)postix/src/postix/core/models/cashdesk.py:279: error: Incompatible return value type (got "Union[Any, int]", expected "Decimal")  [return-value]
Found 75 errors in 36 files (checked 73 source files)

[RRepo](raster-foundry)raster-foundry
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_landsat_h.py:7: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_landsat_h.py:8: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_landsat_h.py:9: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/update_aoi_project.py:6: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/export.py:11: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/export.py:12: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/find_aoi_projects.py:8: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/find_aoi_projects.py:12: error: Item "None" of "Optional[str]" has no attribute "title"  [union-attr]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_geotiff_to_cog.py:4: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_geotiff_to_cog.py:5: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_geotiff_to_cog.py:7: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:7: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:8: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:9: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:10: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:11: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:12: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/process_upload.py:13: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/ingest_scene.py:8: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/ingest_scene.py:9: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/ingest_scene.py:10: error: Relative import climbs too many namespaces  [misc]
(raster-foundry)raster-foundry/app-tasks/rf/src/rf/commands/reprocess_sentinel.py:8: error: Relative import climbs too many namespaces  [misc]
Found 22 errors in 8 files (checked 38 source files)

[RRepo](eliostvs)tomate-statusicon-plugin
Success: no issues found in 3 source files

[RRepo](rr-)szurubooru
(rr-)szurubooru/server/szurubooru/model/post.py:228: error: Name 'flags' already defined on line 224  [no-redef]
(rr-)szurubooru/server/szurubooru/migrations/versions/9ef1a1643c2a_update_user_table_for_hardened_passwords.py:23: error: Variable "9ef1a1643c2a_update_user_table_for_hardened_passwords.Base" is not valid as a type  [valid-type]
(rr-)szurubooru/server/szurubooru/migrations/versions/9ef1a1643c2a_update_user_table_for_hardened_passwords.py:23: error: Invalid base class "Base"  [misc]
(rr-)szurubooru/server/szurubooru/migrations/versions/9837fc981ec7_add_order_to_tag_names.py:22: error: Variable "9837fc981ec7_add_order_to_tag_names.Base" is not valid as a type  [valid-type]
(rr-)szurubooru/server/szurubooru/migrations/versions/9837fc981ec7_add_order_to_tag_names.py:22: error: Invalid base class "Base"  [misc]
(rr-)szurubooru/server/szurubooru/migrations/versions/5f00af3004a4_add_default_tag_category.py:23: error: Variable "5f00af3004a4_add_default_tag_category.Base" is not valid as a type  [valid-type]
(rr-)szurubooru/server/szurubooru/migrations/versions/5f00af3004a4_add_default_tag_category.py:23: error: Invalid base class "Base"  [misc]
(rr-)szurubooru/server/szurubooru/rest/app.py:48: error: "Iterable[str]" has no attribute "__next__"  [attr-defined]
(rr-)szurubooru/server/szurubooru/func/image_hash.py:157: error: Value of type "Union[Any, int]" is not indexable  [index]
(rr-)szurubooru/server/szurubooru/func/image_hash.py:159: error: Value of type "Union[Any, int]" is not indexable  [index]
(rr-)szurubooru/server/szurubooru/func/user_tokens.py:137: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")  [assignment]
Found 11 errors in 7 files (checked 137 source files)

[RRepo](Netflix-Skunkworks)iep-apps
Success: no issues found in 2 source files

[RRepo](Pitt-CSC)PittAPI
(Pitt-CSC)PittAPI/PittAPI/people.py:93: error: Incompatible return value type (got "List[Generator[Any, None, None]]", expected "List[Iterator[str]]")  [return-value]
(Pitt-CSC)PittAPI/PittAPI/people.py:93: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
(Pitt-CSC)PittAPI/PittAPI/people.py:93: note: Consider using "Sequence" instead, which is covariant
(Pitt-CSC)PittAPI/PittAPI/people.py:93: note: Perhaps you need a type annotation for "url_list"? Suggestion: "List[Iterator[str]]"
(Pitt-CSC)PittAPI/tests/people_test.py:24: error: Argument 1 to "skip" has incompatible type "Type[PeopleTest]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/tests/library_test.py:24: error: Argument 1 to "skip" has incompatible type "Type[LibraryTest]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/tests/news_test.py:24: error: Argument 1 to "skip" has incompatible type "Type[NewsTest]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/PittAPI/textbook.py:178: error: "str" has no attribute "json"  [attr-defined]
(Pitt-CSC)PittAPI/PittAPI/textbook.py:196: error: Argument 3 to "_extract_id" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/PittAPI/textbook.py:196: error: Argument 4 to "_extract_id" has incompatible type "Optional[str]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:71: error: Dict entry 1 has incompatible type "str": "int"; expected "str": "str"  [dict-item]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:71: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:72: error: Dict entry 2 has incompatible type "str": "int"; expected "str": "str"  [dict-item]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:72: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:73: error: Dict entry 3 has incompatible type "str": "int"; expected "str": "str"  [dict-item]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:73: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:74: error: Dict entry 4 has incompatible type "str": "int"; expected "str": "str"  [dict-item]
(Pitt-CSC)PittAPI/PittAPI/laundry.py:74: error: Item "None" of "Optional[Match[str]]" has no attribute "group"  [union-attr]
Found 15 errors in 6 files (checked 19 source files)

[RRepo](arthurmensch)modl
(arthurmensch)modl/modl/utils/tests/test_system.py:49: error: Name 'test_get_data_dir' already defined on line 22  [no-redef]
(arthurmensch)modl/modl/utils/randomkit/tests/test_random.py:7: error: Module 'modl.utils.randomkit' has no attribute 'RandomState'  [attr-defined]
(arthurmensch)modl/modl/decomposition/tests/test_fmri.py:8: error: Module 'modl.decomposition' has no attribute 'fMRIDictFact'  [attr-defined]
(arthurmensch)modl/modl/input_data/fmri/base.py:69: error: Name 'check_embedded_nifti_masker' already defined (possibly by an import)  [no-redef]
(arthurmensch)modl/examples/stability_selection.py:79: error: Need type annotation for 'dictionaries_' (hint: "dictionaries_: Dict[<type>, <type>] = ...")  [var-annotated]
(arthurmensch)modl/examples/stability_selection.py:80: error: Need type annotation for 'scores' (hint: "scores: Dict[<type>, <type>] = ...")  [var-annotated]
(arthurmensch)modl/exps/multi_decompose_fmri.py:34: error: Name 'config' already defined on line 27  [no-redef]
(arthurmensch)modl/exps/multi_decompose_images.py:34: error: Name 'config' already defined on line 27  [no-redef]
Found 8 errors in 7 files (checked 33 source files)

[RRepo](steinitzu)spotify-api
(steinitzu)spotify-api/spotify/client.py:19: error: Incompatible types in assignment (expression has type "Api", variable has type Module)  [assignment]
(steinitzu)spotify-api/spotify/client.py:20: error: Module has no attribute "request"  [attr-defined]
Found 2 errors in 1 file (checked 3 source files)

[RRepo](globality-corp)microcosm-flask
(globality-corp)microcosm-flask/microcosm_flask/swagger/parameters/nested.py:21: error: "Field" has no attribute "schema"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/parameters/enum.py:41: error: "Field" has no attribute "by_value"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/parameters/timestamp.py:16: error: "Field" has no attribute "use_isoformat"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/parameters/timestamp.py:21: error: "Field" has no attribute "use_isoformat"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/parameters/list.py:21: error: "Field" has no attribute "container"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/schemas.py:36: error: Argument 1 has incompatible type "Field"; expected "Schema"  [arg-type]
(globality-corp)microcosm-flask/microcosm_flask/swagger/schemas.py:65: error: "Field" has no attribute "dump_to"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/schemas.py:84: error: "List" has no attribute "container"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/schemas.py:85: error: "List" has no attribute "container"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/schemas.py:86: error: "List" has no attribute "container"  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/tests/test_audit.py:5: error: Module 'logging' has no attribute 'DEBUG'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/tests/test_audit.py:5: error: Module 'logging' has no attribute 'NOTSET'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/tests/test_audit.py:5: error: Module 'logging' has no attribute 'getLogger'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/conventions/logging_level.py:6: error: Module 'logging' has no attribute 'PlaceHolder'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/conventions/logging_level.py:6: error: Module 'logging' has no attribute 'root'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/parameters/default.py:2: error: Module 'logging' has no attribute 'Logger'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/swagger/definitions.py:19: error: Module 'logging' has no attribute 'getLogger'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/errors.py:5: error: Module 'logging' has no attribute 'getLogger'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/errors.py:28: error: Incompatible types in assignment (expression has type "Nested", base class "Schema" defined the type as "Dict[Any, Any]")  [assignment]
(globality-corp)microcosm-flask/microcosm_flask/audit.py:10: error: Module 'logging' has no attribute 'DEBUG'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/audit.py:10: error: Module 'logging' has no attribute 'getLogger'  [attr-defined]
(globality-corp)microcosm-flask/microcosm_flask/memory.py:2: error: Module 'logging' has no attribute 'Logger'  [attr-defined]
Found 22 errors in 12 files (checked 116 source files)

[RRepo](rokups)Urho3D
(rokups)Urho3D/script/AutoSwig/walkcpp/generator.py:82: error: Name 'Module' is not defined  [name-defined]
(rokups)Urho3D/script/AutoSwig/walkcpp/generator.py:93: error: Need type annotation for 'pass_factories' (hint: "pass_factories: List[<type>] = ...")  [var-annotated]
Found 2 errors in 1 file (checked 4 source files)

[RRepo](gilesknap)gphotos-sync
(gilesknap)gphotos-sync/gphotos/GooglePhotosIndex.py:38: error: Incompatible types in assignment (expression has type "None", variable has type "datetime")  [assignment]
(gilesknap)gphotos-sync/gphotos/GooglePhotosIndex.py:39: error: Incompatible types in assignment (expression has type "None", variable has type "datetime")  [assignment]
(gilesknap)gphotos-sync/gphotos/GooglePhotosIndex.py:139: error: Incompatible types in assignment (expression has type "None", variable has type "datetime")  [assignment]
(gilesknap)gphotos-sync/gphotos/Utils.py:57: error: Variable "Utils.PatType" is not valid as a type  [valid-type]
(gilesknap)gphotos-sync/gphotos/Utils.py:60: error: PatType? has no attribute "match"  [attr-defined]
(gilesknap)gphotos-sync/gphotos/Utils.py:64: error: Incompatible return value type (got "Optional[datetime]", expected "datetime")  [return-value]
(gilesknap)gphotos-sync/gphotos/Utils.py:78: error: Incompatible return value type (got "Optional[datetime]", expected "datetime")  [return-value]
(gilesknap)gphotos-sync/gphotos/LocationUpdate.py:21: error: Incompatible types in assignment (expression has type "None", variable has type "datetime")  [assignment]
(gilesknap)gphotos-sync/gphotos/LocationUpdate.py:22: error: Incompatible types in assignment (expression has type "None", variable has type "datetime")  [assignment]
(gilesknap)gphotos-sync/gphotos/LocationExtract.py:24: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(gilesknap)gphotos-sync/gphotos/LocationExtract.py:25: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(gilesknap)gphotos-sync/gphotos/LocationExtract.py:84: error: Item "None" of "Optional[Any]" has no attribute "find_element_by_xpath"  [union-attr]
(gilesknap)gphotos-sync/gphotos/LocationExtract.py:85: error: Item "None" of "Optional[Any]" has no attribute "find_elements_by_xpath"  [union-attr]
(gilesknap)gphotos-sync/gphotos/LocationExtract.py:88: error: Item "None" of "Optional[Any]" has no attribute "find_element_by_xpath"  [union-attr]
(gilesknap)gphotos-sync/gphotos/LocationExtract.py:92: error: Item "None" of "Optional[Any]" has no attribute "find_elements_by_xpath"  [union-attr]
(gilesknap)gphotos-sync/gphotos/Main.py:321: error: Argument 1 to "parse_args" of "ArgumentParser" has incompatible type "Optional[Dict[Any, Any]]"; expected "Optional[Sequence[str]]"  [arg-type]
(gilesknap)gphotos-sync/gphotos/LocalFilesRow.py:15: error: Name 'GooglePhotosRow' is not defined  [name-defined]
(gilesknap)gphotos-sync/gphotos/GooglePhotosDownload.py:53: error: Incompatible types in assignment (expression has type "None", variable has type "datetime")  [assignment]
(gilesknap)gphotos-sync/gphotos/GooglePhotosDownload.py:54: error: Incompatible types in assignment (expression has type "None", variable has type "datetime")  [assignment]
(gilesknap)gphotos-sync/gphotos/GooglePhotosDownload.py:62: error: Need type annotation for 'pool_future_to_media' (hint: "pool_future_to_media: Dict[<type>, <type>] = ...")  [var-annotated]
(gilesknap)gphotos-sync/gphotos/GooglePhotosDownload.py:224: error: Incompatible types in assignment (expression has type "None", variable has type "IO[bytes]")  [assignment]
(gilesknap)gphotos-sync/gphotos/GooglePhotosDownload.py:249: error: Item "None" of "Optional[Any]" has no attribute "is_video"  [union-attr]
(gilesknap)gphotos-sync/gphotos/GooglePhotosDownload.py:255: error: Item "None" of "Optional[Any]" has no attribute "relative_path"  [union-attr]
(gilesknap)gphotos-sync/gphotos/GooglePhotosDownload.py:258: error: Item "None" of "Optional[Any]" has no attribute "relative_path"  [union-attr]
(gilesknap)gphotos-sync/gphotos/GooglePhotosDownload.py:258: error: Item "None" of "Optional[Any]" has no attribute "id"  [union-attr]
(gilesknap)gphotos-sync/gphotos/GooglePhotosDownload.py:259: error: Item "None" of "Optional[Any]" has no attribute "url"  [union-attr]
(gilesknap)gphotos-sync/gphotos/GooglePhotosDownload.py:263: error: Item "None" of "Optional[Any]" has no attribute "id"  [union-attr]
(gilesknap)gphotos-sync/gphotos/GooglePhotosDownload.py:266: error: Item "None" of "Optional[Any]" has no attribute "relative_path"  [union-attr]
(gilesknap)gphotos-sync/gphotos/restclient.py:58: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(gilesknap)gphotos-sync/gphotos/restclient.py:59: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(gilesknap)gphotos-sync/gphotos/restclient.py:65: error: "Method" has no attribute "parameters"  [attr-defined]
(gilesknap)gphotos-sync/gphotos/restclient.py:75: error: Argument 1 to "make_path" of "Method" has incompatible type "Dict[str, Dict[str, str]]"; expected "Dict[str, str]"  [arg-type]
(gilesknap)gphotos-sync/gphotos/restclient.py:84: error: Argument "params" to "request" of "Session" has incompatible type "Dict[str, Dict[str, str]]"; expected "Union[None, bytes, MutableMapping[str, str]]"  [arg-type]
Found 33 errors in 8 files (checked 24 source files)

[RRepo](steven-zou)harbor
(steven-zou)harbor/contrib/registryapi/cli.py:35: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 54 source files)

[RRepo](horazont)aioxmpp
(horazont)aioxmpp/tests/chatstates/test_utils.py:25: error: Module 'aioxmpp.chatstates' has no attribute 'ChatState'  [attr-defined]
(horazont)aioxmpp/tests/chatstates/test_utils.py:25: error: Module 'aioxmpp.chatstates' has no attribute 'ChatStateManager'  [attr-defined]
(horazont)aioxmpp/tests/chatstates/test_utils.py:25: error: Module 'aioxmpp.chatstates' has no attribute 'DoNotEmit'  [attr-defined]
(horazont)aioxmpp/tests/chatstates/test_utils.py:25: error: Module 'aioxmpp.chatstates' has no attribute 'AlwaysEmit'  [attr-defined]
(horazont)aioxmpp/tests/chatstates/test_utils.py:25: error: Module 'aioxmpp.chatstates' has no attribute 'DiscoverSupport'  [attr-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:31: error: Name 'aioxmpp.xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:59: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:61: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:63: error: Module has no attribute "Integer"  [attr-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:66: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:75: error: Name 'aioxmpp.xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:78: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:80: error: Module has no attribute "Text"  [attr-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:83: error: Name 'aioxmpp.xso.AbstractElementType' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:99: error: Name 'aioxmpp.xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:136: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:138: error: Module has no attribute "ChildValueMultiMap"  [attr-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:154: error: Name 'aioxmpp.xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:164: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:168: error: Name 'aioxmpp.xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:183: error: Module has no attribute "Child"  [attr-defined]
(horazont)aioxmpp/aioxmpp/httpupload/xso.py:185: error: Module has no attribute "Child"  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:123: error: Module 'aioxmpp.presence' has no attribute 'PresenceClient'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:123: error: Module 'aioxmpp.presence' has no attribute 'PresenceServer'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:124: error: Module 'aioxmpp.roster' has no attribute 'RosterClient'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:125: error: Module 'aioxmpp.disco' has no attribute 'DiscoServer'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:125: error: Module 'aioxmpp.disco' has no attribute 'DiscoClient'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:126: error: Module 'aioxmpp.entitycaps' has no attribute 'EntityCapsService'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:127: error: Module 'aioxmpp.muc' has no attribute 'MUCClient'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:129: error: Module 'aioxmpp.shim' has no attribute 'SHIMService'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:130: error: Module 'aioxmpp.adhoc' has no attribute 'AdHocClient'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:130: error: Module 'aioxmpp.adhoc' has no attribute 'AdHocServer'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:131: error: Module 'aioxmpp.avatar' has no attribute 'AvatarService'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:132: error: Module 'aioxmpp.blocking' has no attribute 'BlockingClient'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:133: error: Module 'aioxmpp.carbons' has no attribute 'CarbonsClient'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:134: error: Module 'aioxmpp.ping' has no attribute 'PingService'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:136: error: Module 'aioxmpp.bookmarks' has no attribute 'BookmarkClient'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:137: error: Module 'aioxmpp.version' has no attribute 'VersionServer'  [attr-defined]
(horazont)aioxmpp/aioxmpp/__init__.py:138: error: Module 'aioxmpp.mdr' has no attribute 'DeliveryReceiptsService'  [attr-defined]
(horazont)aioxmpp/aioxmpp/benchtest/__init__.py:311: error: Need type annotation for '_registry'  [var-annotated]
(horazont)aioxmpp/aioxmpp/network.py:347: error: Incompatible types in assignment (expression has type "Tuple[Any, Any, Tuple[bytes, Any]]", target has type "Tuple[Any, Any, Tuple[str, Any]]")  [assignment]
(horazont)aioxmpp/aioxmpp/im/dispatcher.py:73: error: Module has no attribute "dispatcher"  [attr-defined]
(horazont)aioxmpp/aioxmpp/im/dispatcher.py:75: error: Module has no attribute "CarbonsClient"  [attr-defined]
(horazont)aioxmpp/aioxmpp/carbons/xso.py:26: error: Module 'aioxmpp.misc' has no attribute 'Forwarded'  [attr-defined]
(horazont)aioxmpp/aioxmpp/carbons/xso.py:34: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/carbons/xso.py:39: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/carbons/xso.py:43: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/carbons/xso.py:44: error: Module has no attribute "Child"  [attr-defined]
(horazont)aioxmpp/aioxmpp/carbons/xso.py:104: error: Module has no attribute "Child"  [attr-defined]
(horazont)aioxmpp/aioxmpp/carbons/xso.py:105: error: Module has no attribute "Child"  [attr-defined]
(horazont)aioxmpp/aioxmpp/mdr/xso.py:30: error: Module has no attribute "ChildFlag"  [attr-defined]
(horazont)aioxmpp/aioxmpp/mdr/xso.py:35: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/mdr/xso.py:38: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/mdr/xso.py:47: error: Module has no attribute "Child"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:34: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:157: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:157: error: Module has no attribute "Bool"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:158: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:158: error: Module has no attribute "JID"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:159: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:159: error: Module has no attribute "String"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:161: error: Module has no attribute "ChildText"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:165: error: Module has no attribute "ChildText"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:206: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:206: error: Module has no attribute "String"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:208: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:208: error: Module has no attribute "String"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:226: error: Module has no attribute "Query"  [attr-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:227: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/bookmarks/xso.py:238: error: Module has no attribute "ChildList"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:32: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:62: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:63: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:64: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:65: error: Module has no attribute "LangAttr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:99: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:112: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:119: error: Name 'xso.AbstractElementType' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:131: error: Name 'xso.CapturingXSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:170: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:172: error: Module has no attribute "ChildList"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:174: error: Module has no attribute "ChildValueList"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:179: error: Module has no attribute "ChildList"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:234: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:254: error: Module has no attribute "UnknownChildPolicy"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:256: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:258: error: Module has no attribute "JID"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:262: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:267: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:280: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:299: error: Module has no attribute "Attr"  [attr-defined]
(horazont)aioxmpp/aioxmpp/disco/xso.py:301: error: Module has no attribute "ChildList"  [attr-defined]
(horazont)aioxmpp/aioxmpp/rfc6120.py:42: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/rfc6120.py:51: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/rfc6120.py:69: error: Module has no attribute "Child"  [attr-defined]
(horazont)aioxmpp/aioxmpp/rfc6120.py:72: error: Name 'xso.XSO' is not defined  [name-defined]
(horazont)aioxmpp/aioxmpp/rfc6120.py:90: error: Module has no attribute "ChildText"  [attr-defined]
(horazont)aioxmpp/aioxmpp/rfc6120.py:92: error: Module has no attribute "JID"  [attr-defined]
(horazont)aioxmpp/aioxmpp/rfc6120.py:95: error: Module has no attribute "ChildText"  [attr-defined]
(horazont)aioxmpp/tests/test_errors.py:108: error: Name 'test_gone_new_address' already defined on line 98  [no-redef]

[RRepo](zillow)aiographite
(zillow)aiographite/tests/test_graphite_send.py:5: error: Module 'asyncio' has no attribute 'test_utils'  [attr-defined]
Found 1 error in 1 file (checked 7 source files)

[RRepo](ChristophGaukel)ev3-python3
(ChristophGaukel)ev3-python3/ev3_sound.py:306: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(ChristophGaukel)ev3-python3/ev3_sound.py:313: error: Unsupported operand types for + ("None" and "int")  [operator]
(ChristophGaukel)ev3-python3/ev3_sound.py:313: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(ChristophGaukel)ev3-python3/ev3_sound.py:317: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(ChristophGaukel)ev3-python3/ev3_sound.py:319: error: Missing return statement  [return]
(ChristophGaukel)ev3-python3/ev3_sound.py:321: error: Unsupported operand types for + ("None" and "int")  [operator]
(ChristophGaukel)ev3-python3/ev3_sound.py:321: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(ChristophGaukel)ev3-python3/ev3_sound.py:322: error: Unsupported operand types for % ("None" and "int")  [operator]
(ChristophGaukel)ev3-python3/ev3_sound.py:322: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
(ChristophGaukel)ev3-python3/ev3_file.py:91: error: Name 'SysCmdError' is not defined  [name-defined]
(ChristophGaukel)ev3-python3/ev3_file.py:170: error: Name 'SysCmdError' is not defined  [name-defined]
Found 11 errors in 2 files (checked 2 source files)

[RRepo](jaywink)federation
(jaywink)federation/federation/protocols/diaspora/signatures.py:5: error: Module 'Crypto.PublicKey.RSA' has no attribute 'RsaKey'  [attr-defined]
(jaywink)federation/federation/protocols/diaspora/encrypted.py:5: error: Module 'Crypto.Random' has no attribute 'get_random_bytes'  [attr-defined]
(jaywink)federation/federation/entities/mixins.py:12: error: Incompatible types in assignment (expression has type "None", variable has type "List[Any]")  [assignment]
(jaywink)federation/federation/entities/mixins.py:13: error: Incompatible types in assignment (expression has type "None", variable has type "Set[Any]")  [assignment]
(jaywink)federation/federation/entities/mixins.py:14: error: Incompatible types in assignment (expression has type "None", variable has type "List[Any]")  [assignment]
(jaywink)federation/federation/entities/mixins.py:17: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
(jaywink)federation/federation/entities/mixins.py:20: error: Incompatible types in assignment (expression has type "None", variable has type "ActivityType")  [assignment]
(jaywink)federation/federation/tests/entities/activitypub/django/test_views.py:8: error: Module 'django.views' has no attribute 'View'  [attr-defined]

[RRepo](ScheduledOvers)quizwipe
(ScheduledOvers)quizwipe/backend/backend.py:5: error: Need type annotation for 'sessions' (hint: "sessions: Dict[<type>, <type>] = ...")  [var-annotated]
Found 1 error in 1 file (checked 1 source file)

[RRepo](jopohl)urh
(jopohl)urh/src/urh/plugins/ZeroHide/ZeroHideAction.py:53: error: Need type annotation for 'result' (hint: "result: List[<type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/plugins/ZeroHide/ZeroHidePlugin.py:3: error: Relative import climbs too many namespaces  [misc]
(jopohl)urh/src/urh/plugins/ZeroHide/ZeroHidePlugin.py:4: error: Relative import climbs too many namespaces  [misc]
(jopohl)urh/src/urh/plugins/MessageBreak/MessageBreakPlugin.py:5: error: Relative import climbs too many namespaces  [misc]
(jopohl)urh/src/urh/plugins/MessageBreak/MessageBreakPlugin.py:6: error: Relative import climbs too many namespaces  [misc]
(jopohl)urh/src/urh/awre/Histogram.py:81: error: Need type annotation for 'values'  [var-annotated]
(jopohl)urh/src/urh/controller/dialogs/ProjectDialog.py:32: error: Item "None" of "Optional[Any]" has no attribute "participants"  [union-attr]
(jopohl)urh/src/urh/controller/dialogs/ProjectDialog.py:34: error: Item "None" of "Optional[Any]" has no attribute "device_conf"  [union-attr]
(jopohl)urh/src/urh/controller/dialogs/ProjectDialog.py:35: error: Item "None" of "Optional[Any]" has no attribute "device_conf"  [union-attr]
(jopohl)urh/src/urh/controller/dialogs/ProjectDialog.py:36: error: Item "None" of "Optional[Any]" has no attribute "device_conf"  [union-attr]
(jopohl)urh/src/urh/controller/dialogs/ProjectDialog.py:37: error: Item "None" of "Optional[Any]" has no attribute "device_conf"  [union-attr]
(jopohl)urh/src/urh/controller/dialogs/ProjectDialog.py:38: error: Item "None" of "Optional[Any]" has no attribute "description"  [union-attr]
(jopohl)urh/src/urh/controller/dialogs/ProjectDialog.py:39: error: Item "None" of "Optional[Any]" has no attribute "project_path"  [union-attr]
(jopohl)urh/src/urh/controller/dialogs/ProjectDialog.py:40: error: Item "None" of "Optional[Any]" has no attribute "broadcast_address_hex"  [union-attr]
(jopohl)urh/src/urh/ui/views/ParticipantTableView.py:22: error: Syntax error in type annotation  [syntax]
(jopohl)urh/src/urh/ui/views/ParticipantTableView.py:22: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(jopohl)urh/src/urh/ui/views/ZoomAndDropableGraphicView.py:38: error: "int" has no attribute "child"  [attr-defined]
(jopohl)urh/src/urh/ui/painting/GridScene.py:106: error: Incompatible return value type (got "None", expected "float")  [return-value]
(jopohl)urh/src/urh/ui/painting/Selection.py:120: error: Incompatible types in assignment (expression has type "None", variable has type "int")  [assignment]
(jopohl)urh/src/urh/signalprocessing/ProtocolGroup.py:11: error: Need type annotation for '__items' (hint: "__items: List[<type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/models/MessageTypeTableModel.py:15: error: "list" is not subscriptable, use "typing.List" instead  [misc]
(jopohl)urh/src/urh/models/MessageTypeTableModel.py:17: error: Need type annotation for 'selected_message_type_indices' (hint: "selected_message_type_indices: Set[<type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/models/ProtocolTreeModel.py:101: error: Item "None" of "Optional[Any]" has no attribute "isValid"  [union-attr]
(jopohl)urh/src/urh/models/ProtocolTableModel.py:17: error: Name 'urh' is not defined  [name-defined]
(jopohl)urh/src/urh/models/ProtocolTableModel.py:23: error: Invalid type comment or annotation  [valid-type]
(jopohl)urh/src/urh/models/ProtocolTableModel.py:23: note: Suggestion: use defaultdict[...] instead of defaultdict(...)
(jopohl)urh/src/urh/simulator/Transcript.py:25: error: Need type annotation for 'result' (hint: "result: List[<type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/dev/native/ExtensionHelper.py:206: error: Value of type "object" is not indexable  [index]
(jopohl)urh/src/urh/dev/native/ExtensionHelper.py:241: error: Incompatible types in assignment (expression has type "None", variable has type "List[str]")  [assignment]
(jopohl)urh/tests/device/TestSoundCard.py:34: error: Name 'current_rx' is not defined  [name-defined]
(jopohl)urh/tests/device/TestSoundCard.py:35: error: Name 'current_rx' is not defined  [name-defined]
(jopohl)urh/tests/device/TestSoundCard.py:42: error: Name 'current_tx' is not defined  [name-defined]
(jopohl)urh/tests/device/TestSoundCard.py:43: error: Name 'current_tx' is not defined  [name-defined]
(jopohl)urh/src/urh/plugins/RfCat/RfCatPlugin.py:141: error: Cannot find replacement for positional format specifier 2  [str-format]
(jopohl)urh/src/urh/plugins/RfCat/RfCatPlugin.py:156: error: Missing return statement  [return]
(jopohl)urh/src/urh/plugins/MessageBreak/MessageBreakAction.py:38: error: Need type annotation for 'result' (hint: "result: List[<type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/awre/engines/LengthEngine.py:91: error: Need type annotation for 'scored_ranges' (hint: "scored_ranges: Dict[<type>, <type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/awre/engines/LengthEngine.py:128: error: Need type annotation for 'possible_window_lengths'  [var-annotated]
(jopohl)urh/src/urh/awre/engines/Engine.py:40: error: Need type annotation for 'result' (hint: "result: List[<type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/awre/engines/Engine.py:75: error: Need type annotation for 'result' (hint: "result: List[<type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/awre/Preprocessor.py:24: error: "list" is not subscriptable, use "typing.List" instead  [misc]
(jopohl)urh/src/urh/awre/Preprocessor.py:27: error: Syntax error in type annotation  [syntax]
(jopohl)urh/src/urh/awre/Preprocessor.py:27: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(jopohl)urh/src/urh/awre/Preprocessor.py:108: error: Need type annotation for 'result'  [var-annotated]
(jopohl)urh/src/urh/awre/Preprocessor.py:180: error: Need type annotation for 'result' (hint: "result: Dict[<type>, <type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/awre/Preprocessor.py:237: error: Need type annotation for 'sync_lengths'  [var-annotated]
(jopohl)urh/src/urh/awre/CommonRange.py:235: error: "list" is not subscriptable, use "typing.List" instead  [misc]
(jopohl)urh/src/urh/ui/views/EpicGraphicView.py:59: error: Need type annotation for 'colors' (hint: "colors: List[<type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/ui/views/EpicGraphicView.py:77: error: Argument 1 to "append" of "list" has incompatible type "Tuple[float, Any]"; expected "Tuple[int, Any]"  [arg-type]
(jopohl)urh/src/urh/ui/views/EpicGraphicView.py:98: error: Incompatible types in assignment (expression has type "Optional[List[Tuple[int, Any]]]", variable has type "List[Tuple[int, Any]]")  [assignment]
(jopohl)urh/src/urh/ui/views/EpicGraphicView.py:99: error: Incompatible types in assignment (expression has type "Optional[List[Any]]", variable has type "List[Any]")  [assignment]
(jopohl)urh/src/urh/ui/actions/InsertColumn.py:16: error: Need type annotation for 'saved_messages' (hint: "saved_messages: Dict[<type>, <type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/ui/actions/DeleteBitsAndPauses.py:13: error: "list" is not subscriptable, use "typing.List" instead  [misc]
(jopohl)urh/src/urh/ui/actions/DeleteBitsAndPauses.py:21: error: Need type annotation for 'saved_messages' (hint: "saved_messages: List[<type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/ui/actions/DeleteBitsAndPauses.py:22: error: Need type annotation for 'removed_message_indices' (hint: "removed_message_indices: List[<type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/ui/actions/EditSignalAction.py:183: error: Item "None" of "Optional[Any]" has no attribute "messages"  [union-attr]
(jopohl)urh/src/urh/ui/actions/Fuzz.py:17: error: Need type annotation for 'added_message_indices' (hint: "added_message_indices: List[<type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/signalprocessing/ProtocolAnalyzerContainer.py:69: error: Need type annotation for 'result' (hint: "result: List[<type>] = ...")  [var-annotated]
(jopohl)urh/src/urh/signalprocessing/ProtocolAnalyzerContainer.py:116: error: "list" is not subscriptable, use "typing.List" instead  [misc]

[RRepo](ysavary)WindMobile2-Server
(ysavary)WindMobile2-Server/providers/yvbeach.py:7: error: Module 'commons' has no attribute 'user_agents'  [attr-defined]
(ysavary)WindMobile2-Server/providers/meteoswiss_web.py:5: error: Module 'commons' has no attribute 'user_agents'  [attr-defined]
(ysavary)WindMobile2-Server/providers/thunerwetter.py:8: error: Module 'commons' has no attribute 'user_agents'  [attr-defined]
(ysavary)WindMobile2-Server/providers/iweathar.py:8: error: Module 'commons' has no attribute 'user_agents'  [attr-defined]
Found 4 errors in 4 files (checked 24 source files)

[RRepo](flycheck)flycheck
(flycheck)flycheck/test/resources/language/python/invalid_type.py:2: error: Incompatible return value type (got "str", expected "int")  [return-value]
Found 1 error in 1 file (checked 5 source files)

[RRepo](timothycrosley)hug
(timothycrosley)hug/tests/module_fake_simple.py:8: error: Module has no attribute "get"  [attr-defined]
(timothycrosley)hug/tests/module_fake_simple.py:13: error: Module has no attribute "get"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:26: error: Module has no attribute "json"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:27: error: Module has no attribute "text"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:30: error: Module has no attribute "input_format"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:31: error: Module has no attribute "input_format"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:32: error: Module has no attribute "input_format"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:33: error: Module has no attribute "input_format"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:34: error: Module has no attribute "input_format"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:35: error: Module has no attribute "input_format"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:39: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:40: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:41: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:42: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:43: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:44: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:45: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/hug/defaults.py:46: error: Module has no attribute "directives"  [attr-defined]
(timothycrosley)hug/tests/test_interface.py:27: error: Module has no attribute "http"  [attr-defined]
(timothycrosley)hug/tests/module_fake_http_and_cli.py:4: error: Module has no attribute "get"  [attr-defined]
(timothycrosley)hug/tests/module_fake_http_and_cli.py:5: error: Module has no attribute "cli"  [attr-defined]
(timothycrosley)hug/tests/test_route.py:25: error: Module has no attribute "API"  [attr-defined]
(timothycrosley)hug/tests/module_fake_post.py:5: error: Module has no attribute "post"  [attr-defined]
(timothycrosley)hug/tests/test_directives.py:28: error: Module has no attribute "API"  [attr-defined]
(timothycrosley)hug/tests/test_directives.py:31: error: Name '__hug__' is not defined  [name-defined]
(timothycrosley)hug/tests/test_directives.py:151: error: Name 'hug.directives.Timer' is not defined  [name-defined]
(timothycrosley)hug/tests/test_directives.py:201: error: Name 'hug.directives.user' is not defined  [name-defined]
(timothycrosley)hug/tests/test_directives.py:207: error: Name 'hug.directives.user' is not defined  [name-defined]
(timothycrosley)hug/tests/test_directives.py:219: error: Name 'hug.directives.cors' is not defined  [name-defined]
(timothycrosley)hug/tests/test_api.py:26: error: Module has no attribute "API"  [attr-defined]

[RRepo](ColumbiaSC-Tech)botty_mcbotface
(ColumbiaSC-Tech)botty_mcbotface/test_botty/tests/test_plugins/test_help.py:3: error: Module 'test_botty.mocks' has no attribute 'MockMessage'  [attr-defined]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/botty/db/routines/routine_populate_db.py:3: error: Module 'botty_mcbotface.botty.db' has no attribute 'Channel'  [attr-defined]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/botty/db/routines/routine_populate_db.py:3: error: Module 'botty_mcbotface.botty.db' has no attribute 'User'  [attr-defined]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/plugins/flipper.py:12: error: Cannot infer type argument 2 of "defaultdict"  [misc]
(ColumbiaSC-Tech)botty_mcbotface/test_botty/tests/test_plugins/test_seen.py:5: error: Module 'test_botty.mocks' has no attribute 'MockMessage'  [attr-defined]
(ColumbiaSC-Tech)botty_mcbotface/test_botty/tests/test_plugins/test_seen.py:5: error: Module 'test_botty.mocks' has no attribute 'MockRequestGET'  [attr-defined]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/plugins/calendar.py:32: error: Need type annotation for '_CACHE' (hint: "_CACHE: Dict[<type>, <type>] = ...")  [var-annotated]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/plugins/calendar.py:66: error: "Type[datetime]" has no attribute "fromisoformat"  [attr-defined]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/plugins/calendar.py:102: error: Unexpected type declaration  [misc]
(ColumbiaSC-Tech)botty_mcbotface/botty_mcbotface/plugins/calendar.py:120: error: Item "None" of "Optional[Any]" has no attribute "get"  [union-attr]

[RRepo](fametrano)BitcoinBlockchainTechnology
(fametrano)BitcoinBlockchainTechnology/btclib/dsa.py:190: error: "Sequence[Any]" has no attribute "append"  [attr-defined]
(fametrano)BitcoinBlockchainTechnology/btclib/dsa.py:194: error: "Sequence[Any]" has no attribute "append"  [attr-defined]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:26: error: Argument 1 to "int" has incompatible type "Union[str, int, bytes]"; expected "Union[str, bytes, bytearray]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:28: error: Unsupported right operand type for in ("Union[int, Tuple[Any, ...]]")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:28: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:29: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:31: error: Incompatible return value type (got "Union[str, int, bytes]", expected "str")  [return-value]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:33: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:35: error: Unsupported right operand type for in ("Union[int, Tuple[Any, ...]]")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:38: error: Argument 1 to "from_bytes" of "int" has incompatible type "Union[str, int, bytes]"; expected "Sequence[int]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:42: error: Unsupported operand types for < ("str" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:42: error: Unsupported operand types for < ("bytes" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:42: note: Left operand is of type "Union[str, int, bytes]"
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:43: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:44: error: Argument 1 to "bin" has incompatible type "Union[str, int, bytes]"; expected "Union[int, _SupportsIndex]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:46: error: Unsupported right operand type for in ("Union[int, Tuple[Any, ...]]")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:58: error: Argument 1 to "int" has incompatible type "Union[str, int, bytes]"; expected "Union[str, bytes, bytearray]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:60: error: Unsupported operand types for < ("str" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:60: error: Unsupported operand types for < ("bytes" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:60: note: Left operand is of type "Union[str, int, bytes]"
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:61: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:62: error: Incompatible return value type (got "Union[str, int, bytes]", expected "int")  [return-value]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:64: error: Argument 1 to "from_bytes" of "int" has incompatible type "Union[str, int, bytes]"; expected "Sequence[int]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:77: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:78: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:80: error: Incompatible return value type (got "Union[str, int, bytes]", expected "bytes")  [return-value]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:82: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:87: error: Argument 1 to "int" has incompatible type "Union[str, int, bytes]"; expected "Union[str, bytes, bytearray]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:90: error: Unsupported operand types for < ("str" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:90: error: Unsupported operand types for < ("bytes" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:90: note: Left operand is of type "Union[str, int, bytes]"
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:91: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:92: error: Item "str" of "Union[str, int, bytes]" has no attribute "bit_length"  [union-attr]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:92: error: Item "bytes" of "Union[str, int, bytes]" has no attribute "bit_length"  [union-attr]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:97: error: Item "str" of "Union[str, int, bytes]" has no attribute "to_bytes"  [union-attr]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:97: error: Item "bytes" of "Union[str, int, bytes]" has no attribute "to_bytes"  [union-attr]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:75: error: Incompatible types in assignment (expression has type "int", target has type "None")  [assignment]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:76: error: Incompatible types in assignment (expression has type "int", target has type "None")  [assignment]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:78: error: Incompatible types in assignment (expression has type "List[str]", target has type "None")  [assignment]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:82: error: Incompatible return value type (got "None", expected "int")  [return-value]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:86: error: Incompatible return value type (got "None", expected "List[str]")  [return-value]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:90: error: Incompatible return value type (got "None", expected "int")  [return-value]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:106: error: Unsupported operand types for divmod ("int" and "None")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:111: error: Unsupported operand types for / ("int" and "None")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:123: error: Value of type "None" is not indexable  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:132: error: "None" has no attribute "index"  [attr-defined]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:141: error: Unsupported operand types for * ("int" and "None")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/mnemonic.py:147: error: Unsupported operand types for * ("int" and "None")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/base58.py:127: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior  [str-bytes-safe]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:49: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:70: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:74: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:75: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:76: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:77: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:82: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:87: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:88: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:62: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:134: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:152: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:154: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:191: error: Incompatible types in assignment (expression has type "Sequence[int]", variable has type "List[int]")  [assignment]
(fametrano)BitcoinBlockchainTechnology/btclib/bip32.py:249: error: Too many arguments for "HMAC"  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:78: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:79: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:87: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:91: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:94: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:96: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:127: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/borromean.py:134: error: Unsupported target for indexed assignment  [index]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:30: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:32: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:42: error: Too few arguments  [call-arg]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:99: error: Unsupported operand types for + ("None" and "int")  [operator]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:99: note: Left operand is of type "Union[int, Any, None]"
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:247: error: Invalid type comment or annotation  [valid-type]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:247: note: Suggestion: use Sequence[...] instead of Sequence(...)
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:265: error: "Sequence[Any]" has no attribute "append"  [attr-defined]
(fametrano)BitcoinBlockchainTechnology/btclib/ssa.py:267: error: "Sequence[Any]" has no attribute "append"  [attr-defined]
Found 76 errors in 8 files (checked 31 source files)

[RRepo](carbonblack)cb-integration
(carbonblack)cb-integration/cbint/globals.py:25: error: Need type annotation for 'g_status' (hint: "g_status: Dict[<type>, <type>] = ...")  [var-annotated]
(carbonblack)cb-integration/cbint/binary_collector.py:6: error: Name 'datetime' already defined (by an import)  [no-redef]
Found 2 errors in 2 files (checked 11 source files)

[RRepo](Islandman93)reinforcepy
(Islandman93)reinforcepy/docs/conf.py:223: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
(Islandman93)reinforcepy/reinforcepy/networks/dqn/tflow/dqn_inits.py:2: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/environments/openaigym/gym_atari.py:2: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/environments/openaigym/gym_wrapper.py:1: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/learners/TableLookup/sarsatable.py:1: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/learners/TableLookup/sarsatable.py:3: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/learners/TableLookup/qtable.py:1: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/learners/TableLookup/qtable.py:2: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/networks/dqn/tflow/dqn_inits.py:2: error: Relative import climbs too many namespaces  [misc]
(Islandman93)reinforcepy/reinforcepy/learners/dqn/asynchronous/base_thread_learner.py:3: error: Module 'reinforcepy.handlers' has no attribute 'ActionHandler'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/learners/dqn/asynchronous/onestep_sarsa_thread_learner.py:2: error: Module 'reinforcepy.learners' has no attribute 'BaseSarsaLearner'  [attr-defined]
(Islandman93)reinforcepy/examples/SimpleQLearn/FrozenLakev0.py:1: error: Module 'reinforcepy.environments' has no attribute 'GymWrapper'  [attr-defined]
(Islandman93)reinforcepy/examples/SimpleQLearn/FrozenLakev0.py:2: error: Module 'reinforcepy.learners.TableLookup' has no attribute 'QTable'  [attr-defined]
(Islandman93)reinforcepy/examples/SimpleQLearn/FrozenLakev0.py:2: error: Module 'reinforcepy.learners.TableLookup' has no attribute 'SARSATable'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/test/test_actionhandler.py:2: error: Module 'reinforcepy.handlers' has no attribute 'ActionHandler'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/test/test_actionhandler.py:2: error: Module 'reinforcepy.handlers' has no attribute 'ActionPolicy'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/test/test_framebuffer.py:2: error: Module 'reinforcepy.handlers' has no attribute 'FrameBuffer'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/test/test_binarytree.py:3: error: Module 'reinforcepy.handlers.experience_replay.prioritized' has no attribute 'Node'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/test/test_binarytree.py:3: error: Module 'reinforcepy.handlers.experience_replay.prioritized' has no attribute 'BinaryTree'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/environments/ALE/ALE_environment.py:3: error: Module 'reinforcepy.environments' has no attribute 'BaseEnvironment'  [attr-defined]
(Islandman93)reinforcepy/reinforcepy/handlers/actionhandler.py:57: error: Unsupported left operand type for < ("Number")  [operator]
(Islandman93)reinforcepy/reinforcepy/learners/dqn/asynchronous/q_thread_learner.py:2: error: Module 'reinforcepy.learners' has no attribute 'BaseQLearner'  [attr-defined]

[RRepo](laramies)theHarvester
(laramies)theHarvester/tests/discovery/test_githubcode.py:33: error: Cannot assign to a method  [assignment]
(laramies)theHarvester/tests/discovery/test_githubcode.py:37: error: Cannot assign to a method  [assignment]
(laramies)theHarvester/tests/discovery/test_githubcode.py:42: error: Cannot assign to a method  [assignment]
(laramies)theHarvester/tests/discovery/test_githubcode.py:64: error: Cannot assign to a method  [assignment]
(laramies)theHarvester/theHarvester/discovery/githubcode.py:23: error: Function "builtins.any" is not valid as a type  [valid-type]
(laramies)theHarvester/theHarvester/discovery/githubcode.py:23: note: Perhaps you need "Callable[...]" or a callback protocol?
(laramies)theHarvester/theHarvester/discovery/githubcode.py:59: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")  [assignment]
(laramies)theHarvester/theHarvester/discovery/githubcode.py:59: error: List item 0 has incompatible type "None"; expected "str"  [list-item]
(laramies)theHarvester/theHarvester/discovery/githubcode.py:61: error: Incompatible return value type (got "Union[str, int]", expected "Optional[int]")  [return-value]
(laramies)theHarvester/theHarvester/discovery/githubcode.py:86: error: Name 'Core' is not defined  [name-defined]
Found 9 errors in 2 files (checked 46 source files)

[RRepo](playpauseandstop)rororo
Success: no issues found in 9 source files

[RRepo](PhilipTrauner)cmus-osx
(PhilipTrauner)cmus-osx/cmus_osx/__init__.py:42: error: "__new__" must return a class instance (got "Optional[_CmusConfig]")  [misc]
Found 1 error in 1 file (checked 5 source files)

[RRepo](CoolProp)CoolProp
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:34: error: Name 'Python' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:42: error: Name 'Octave' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:44: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:52: error: Name 'Java' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:54: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:63: error: Name 'Csharp' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:65: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:74: error: Name 'R' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/LinuxRun.py:76: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:34: error: Name 'Python' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:42: error: Name 'Octave' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:44: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:52: error: Name 'Java' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:54: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:63: error: Name 'Csharp' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:65: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:74: error: Name 'R' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/OSXRun.py:76: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/viscosity_builder.py:111: error: Name 'Model' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/viscosity_builder.py:112: error: Name 'Data' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/viscosity_builder.py:113: error: Name 'ODR' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:91: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:101: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:111: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:121: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:131: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:141: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:151: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/dev/scripts/derivative_tester.py:161: error: Name 'f' already defined on line 81  [no-redef]
(CoolProp)CoolProp/wrappers/Python/CoolProp/Plots/Tests.py:4: error: Module 'CoolProp.Plots' has no attribute 'PropertyPlot'  [attr-defined]
(CoolProp)CoolProp/wrappers/Python/CoolProp/Plots/PsychChart.py:185: error: Argument 1 to "write" of "IO" has incompatible type "bytes"; expected "str"  [arg-type]
(CoolProp)CoolProp/wrappers/Python/CoolProp/Plots/PsychChart.py:187: error: Name 'execfile' is not defined  [name-defined]
(CoolProp)CoolProp/Web/scripts/__init__.py:49: error: Incompatible types in assignment (expression has type "time", variable has type "datetime")  [assignment]
(CoolProp)CoolProp/Web/scripts/__init__.py:50: error: Incompatible types in assignment (expression has type "time", variable has type "datetime")  [assignment]
(CoolProp)CoolProp/Web/scripts/__init__.py:57: error: Unsupported operand types for <= ("datetime" and "time")  [operator]
(CoolProp)CoolProp/dev/Tickets/1443.py:245: error: Need type annotation for 'results' (hint: "results: Dict[<type>, <type>] = ...")  [var-annotated]
(CoolProp)CoolProp/dev/Tickets/351.py:2: error: Module 'CoolProp.Plots' has no attribute 'PropertyPlot'  [attr-defined]
(CoolProp)CoolProp/dev/Tickets/1118.py:78: error: Module 'CoolProp.Plots' has no attribute 'PropertyPlot'  [attr-defined]
(CoolProp)CoolProp/dev/scripts/fit_saturation_critical_splines.py:209: error: Need type annotation for 'e' (hint: "e: Dict[<type>, <type>] = ...")  [var-annotated]
(CoolProp)CoolProp/dev/scripts/fit_saturation_critical_splines.py:277: error: Incompatible types in assignment (expression has type "QuadraticFitter", variable has type "CubicFitter")  [assignment]
(CoolProp)CoolProp/dev/scripts/fit_saturation_critical_splines.py:297: error: Incompatible types in assignment (expression has type "QuadraticFitter", variable has type "CubicFitter")  [assignment]
(CoolProp)CoolProp/dev/scripts/fit_saturation_critical_splines.py:384: error: Trying to read deleted variable 'V'  [misc]
(CoolProp)CoolProp/dev/scripts/convert_FLD.py:130: error: Need type annotation for 'ALPHA0' (hint: "ALPHA0: List[<type>] = ...")  [var-annotated]
(CoolProp)CoolProp/dev/scripts/fit_avoid_ECS.py:84: error: Name 'Model' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/fit_avoid_ECS.py:85: error: Name 'Data' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/fit_avoid_ECS.py:87: error: Name 'ODR' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:219: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "bool"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:219: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Type[JSONEncoder]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:219: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Tuple[str, str]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:219: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Callable[[Any], Any]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:244: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "bool"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:244: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Type[JSONEncoder]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:244: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Tuple[str, str]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:244: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Callable[[Any], Any]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/ideal_curves.py:144: error: Module has no attribute "iT_triple"  [attr-defined]
(CoolProp)CoolProp/dev/scripts/ideal_curves.py:145: error: Module has no attribute "iT_critical"  [attr-defined]
(CoolProp)CoolProp/dev/TTSE/validate_TTSE.py:4: error: Module 'CoolProp.Plots' has no attribute 'Ph'  [attr-defined]
(CoolProp)CoolProp/dev/TTSE/check_TTSE_v5.py:159: error: Unsupported operand types for / ("List[float]" and "float")  [operator]
(CoolProp)CoolProp/dev/TTSE/check_TTSE_v5.py:169: error: Unsupported operand types for / ("List[float]" and "float")  [operator]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:1: error: Module 'CoolProp.Plots' has no attribute 'Ph'  [attr-defined]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:296: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:316: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:323: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:353: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:373: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/TTSE_ranges.py:380: error: Name 'get_Z' already defined on line 26  [no-redef]
(CoolProp)CoolProp/dev/TTSE/check_TTSE_v4.py:172: error: Unsupported operand types for / ("List[float]" and "float")  [operator]
(CoolProp)CoolProp/dev/TTSE/check_TTSE_v4.py:182: error: Unsupported operand types for / ("List[float]" and "float")  [operator]
(CoolProp)CoolProp/dev/incompressible_liquids/CPIncomp/__init__.py:10: error: Module 'CPIncomp' has no attribute 'MelinderFluids'; maybe "getMelinderFluids"?  [attr-defined]
(CoolProp)CoolProp/dev/incompressible_liquids/CPIncomp/__init__.py:10: error: Module 'CPIncomp' has no attribute 'SolutionFluids'; maybe "getSolutionFluids"?  [attr-defined]
(CoolProp)CoolProp/dev/incompressible_liquids/all_incompressibles.py:70: error: Need type annotation for 'doneObjs' (hint: "doneObjs: List[<type>] = ...")  [var-annotated]
(CoolProp)CoolProp/dev/incompressible_liquids/all_incompressibles.py:74: error: Need type annotation for 'solObjs' (hint: "solObjs: List[<type>] = ...")  [var-annotated]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:19: error: Name 'Python' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:22: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:25: error: Name 'Octave' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:29: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:32: error: Name 'Java' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:36: error: Name 'sys' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/examples/win64run.py:41: error: Name 'Csharp' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:8: error: Incompatible types in assignment (expression has type "bytes", variable has type "str")  [assignment]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:9: error: "str" has no attribute "decode"; maybe "encode"?  [attr-defined]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:20: error: Name 'oauth2_token' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:28: error: Name 'Request' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:31: error: Name 'oauth2_token' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:35: error: Name 'urlopen' is not defined  [name-defined]
(CoolProp)CoolProp/dev/scripts/milestone2rst.py:87: error: Incompatible types in assignment (expression has type "object", variable has type "str")  [assignment]
(CoolProp)CoolProp/wrappers/Python/generate_meta_info.py:78: error: Incompatible types in assignment (expression has type "Template", variable has type "str")  [assignment]
(CoolProp)CoolProp/wrappers/Python/generate_meta_info.py:81: error: "str" has no attribute "render"  [attr-defined]
(CoolProp)CoolProp/wrappers/Python/generate_meta_info.py:148: error: Incompatible types in assignment (expression has type "Template", variable has type "str")  [assignment]
(CoolProp)CoolProp/wrappers/Python/generate_meta_info.py:151: error: "str" has no attribute "render"  [attr-defined]
Found 90 errors in 24 files (checked 58 source files)

[RRepo](alex-ta)Fontinator
(alex-ta)Fontinator/NeuralNet/Oli/libs/ProcessingPipeline.py:26: error: Syntax error in type annotation  [syntax]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ProcessingPipeline.py:26: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
(alex-ta)Fontinator/NeuralNet/Oli/libs/ProcessingPipeline.py:44: error: Need type annotation for 'labels' (hint: "labels: List[<type>] = ...")  [var-annotated]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ImageLoader.py:10: error: Incompatible types in assignment (expression has type "None", variable has type "Path")  [assignment]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ImageLoader.py:11: error: Need type annotation for '_font_names' (hint: "_font_names: List[<type>] = ...")  [var-annotated]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ImageLoader.py:12: error: Need type annotation for '_img_count_per_font' (hint: "_img_count_per_font: List[<type>] = ...")  [var-annotated]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ImageLoader.py:40: error: Missing return statement  [return]
(alex-ta)Fontinator/DataGenerator/libs/WordDict.py:16: error: Self argument missing for a non-static method (or an invalid type for self)  [misc]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:15: error: Incompatible types in assignment (expression has type "None", variable has type "Path")  [assignment]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:16: error: Incompatible types in assignment (expression has type "None", variable has type "Path")  [assignment]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:17: error: Incompatible types in assignment (expression has type "None", variable has type "Path")  [assignment]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:18: error: Incompatible types in assignment (expression has type "None", variable has type "Path")  [assignment]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:91: error: "List[Any]" has no attribute "tolist"  [attr-defined]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:93: error: "List[Any]" has no attribute "tolist"  [attr-defined]
(alex-ta)Fontinator/NeuralNet/Oli/libs/ModelSerializer.py:96: error: Argument 1 to "open" has incompatible type "Optional[Path]"; expected "Union[str, bytes, int, _PathLike[Any]]"  [arg-type]
Found 14 errors in 4 files (checked 15 source files)

[RRepo](c3nav)c3nav
(c3nav)c3nav/src/c3nav/api/__init__.py: error: Duplicate module named 'api' (also at '/home/bew/archive/typed_project/(c3nav)c3nav/src/c3nav/routing/api.py')  [misc]
Found 1 error in 1 file (checked 86 source files)

[RRepo](w1ll1am23)simplisafe-python
(w1ll1am23)simplisafe-python/tests/test_sensor.py:7: error: Module 'simplipy' has no attribute 'API'  [attr-defined]
(w1ll1am23)simplisafe-python/tests/test_api.py:11: error: Module 'simplipy' has no attribute 'API'  [attr-defined]
(w1ll1am23)simplisafe-python/tests/test_system.py:10: error: Module 'simplipy' has no attribute 'API'  [attr-defined]
(w1ll1am23)simplisafe-python/example.py:9: error: Module 'simplipy' has no attribute 'API'  [attr-defined]
Found 4 errors in 4 files (checked 11 source files)

[RRepo](gjbex)training-material
(gjbex)training-material/DataStorage/Hdf5/PythonSamples/compute_avg.py:10: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 260 source files)

[RRepo](numba)numba
(numba)numba/docs/source/extending/template.py:6: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 399 source files)

[RRepo](project-everest)vale
(project-everest)vale/tools/scripts/collect-fstar-times.py:83: error: Missing parentheses in call to 'print'. Did you mean print("WARNING: Found existing pickled file %s.  No data written.  Consider moving or deleting it." % pickle_file)?  [syntax]
Found 1 error in 1 file (checked 2 source files)

[RRepo](yi-jiayu)bus-eta-bot
Success: no issues found in 2 source files

[RRepo](Tobotimus)Tobo-Cogs
(Tobotimus)Tobo-Cogs/register/register.py:47: error: Unsupported dynamic base class "getattr"  [misc]
(Tobotimus)Tobo-Cogs/filterhelp/formatter.py:58: error: Missing return statement  [return]
(Tobotimus)Tobo-Cogs/welcomecount/welcomecount.py:38: error: Unsupported dynamic base class "getattr"  [misc]
(Tobotimus)Tobo-Cogs/welcomecount/welcomecount.py:170: error: Name 'last_message' already defined on line 168  [no-redef]
(Tobotimus)Tobo-Cogs/welcomecount/welcomecount.py:177: error: "int" has no attribute "delete"  [attr-defined]
(Tobotimus)Tobo-Cogs/docref/types.py:184: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:191: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:192: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:193: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:196: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:197: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:198: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/docref/types.py:199: error: Value of type "Optional[Match[str]]" is not indexable  [index]
(Tobotimus)Tobo-Cogs/reactkarma/reactkarma.py:38: error: Unsupported dynamic base class "getattr"  [misc]
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:53: error: Need type annotation for 'lines'  [var-annotated]
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:55: error: Need type annotation for 'new_lines'  [var-annotated]
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:55: error: Unsupported operand types for - ("None" and "int")  [operator]
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:55: note: Left operand is of type "Optional[int]"
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:62: error: Unsupported operand types for >= ("int" and "None")  [operator]
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:62: note: Right operand is of type "Optional[int]"
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:150: error: "None" has no attribute "delete"  [attr-defined]
(Tobotimus)Tobo-Cogs/errorlogs/reaction_menu.py:154: error: "None" has no attribute "id"  [attr-defined]
(Tobotimus)Tobo-Cogs/updatered/updatered.py:40: error: Unsupported dynamic base class "getattr"  [misc]
(Tobotimus)Tobo-Cogs/errorlogs/errorlogs.py:123: error: Module has no attribute "create_task"  [attr-defined]
Found 22 errors in 8 files (checked 15 source files)

[RRepo](ranisalt)moita-ufsc-crawler
(ranisalt)moita-ufsc-crawler/moita/spiders/cagr.py:9: error: Relative import climbs too many namespaces  [misc]
(ranisalt)moita-ufsc-crawler/moita/spiders/cagr.py:24: error: Need type annotation for 'subject' (hint: "subject: Dict[<type>, <type>] = ...")  [var-annotated]
(ranisalt)moita-ufsc-crawler/moita/spiders/cagr.py:24: error: Need type annotation for 'campus'  [var-annotated]
(ranisalt)moita-ufsc-crawler/moita/spiders/cagr.py:25: error: Need type annotation for 'campi_names'  [var-annotated]
(ranisalt)moita-ufsc-crawler/moita/pipelines.py:25: error: Need type annotation for 'data'  [var-annotated]
Found 5 errors in 2 files (checked 2 source files)

[RRepo](HenriWahl)Nagstamon
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/protocol/structs.py:23: error: Module 'Xlib.protocol' has no attribute 'rq'  [attr-defined]
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/xobject/resource.py:19: error: Module 'Xlib.protocol' has no attribute 'request'  [attr-defined]
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/error.py:23: error: Module 'Xlib.protocol' has no attribute 'rq'  [attr-defined]
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/ext/composite.py:34: error: Module 'Xlib.protocol' has no attribute 'rq'  [attr-defined]
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/ext/composite.py:35: error: Module 'Xlib.xobject' has no attribute 'drawable'  [attr-defined]
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/ext/record.py:20: error: Module 'Xlib.protocol' has no attribute 'rq'  [attr-defined]
(HenriWahl)Nagstamon/Nagstamon/thirdparty/Xlib/ext/xtest.py:20: error: Module 'Xlib.protocol' has no attribute 'rq'  [attr-defined]

[RRepo](seznam)fastrpc
(seznam)fastrpc/python/example/client_example2.py:13: error: invalid syntax  [syntax]
Found 1 error in 1 file (checked 15 source files)

[RRepo](lostatc)codot
(lostatc)codot/codot/commands/role.py:62: error: "None" has no attribute "dir_path"  [attr-defined]
(lostatc)codot/codot/commands/role.py:66: error: "None" has no attribute "get_configs"  [attr-defined]
(lostatc)codot/codot/commands/role.py:73: error: "None" has no attribute "selected"  [attr-defined]
(lostatc)codot/codot/commands/role.py:82: error: "None" has no attribute "get_config_by_name"  [attr-defined]
(lostatc)codot/codot/commands/rm_template.py:79: error: Need type annotation for 'template_identifiers' (hint: "template_identifiers: Set[<type>] = ...")  [var-annotated]
(lostatc)codot/codot/commands/list.py:90: error: List item 0 has incompatible type "Tuple[str]"; expected "Tuple[str, str]"  [list-item]
(lostatc)codot/codot/commands/list.py:92: error: Generator has incompatible item type "Tuple[str]"; expected "Tuple[str, str]"  [misc]
(lostatc)codot/codot/commandbase.py:69: error: Incompatible types in assignment (expression has type "socket", variable has type "None")  [assignment]
(lostatc)codot/codot/commandbase.py:71: error: "None" has no attribute "bind"  [attr-defined]
(lostatc)codot/codot/cli.py:165: error: Return type "None" of "error" incompatible with return type "NoReturn" in supertype "ArgumentParser"  [override]
(lostatc)codot/codot/container.py:59: error: Missing return statement  [return]
(lostatc)codot/codot/container.py:61: error: Value of type "Callable[..., Any]" is not indexable  [index]
(lostatc)codot/codot/container.py:70: error: Value of type "Callable[..., Any]" is not indexable  [index]
(lostatc)codot/codot/container.py:86: error: Name 'last_sync' already defined on line 72  [no-redef]
(lostatc)codot/codot/container.py:113: error: Need type annotation for 'raw_vals' (hint: "raw_vals: Dict[<type>, <type>] = ...")  [var-annotated]
(lostatc)codot/codot/container.py:120: error: Name 'vals' already defined on line 115  [no-redef]
(lostatc)codot/codot/container.py:126: error: Missing return statement  [return]
(lostatc)codot/codot/container.py:147: error: 'None' object is not iterable  [misc]
(lostatc)codot/codot/container.py:207: error: Need type annotation for '_req_keys' (hint: "_req_keys: List[<type>] = ...")  [var-annotated]
(lostatc)codot/codot/container.py:228: error: Name 'vals' already defined on line 220  [no-redef]
(lostatc)codot/codot/container.py:233: error: Missing return statement  [return]
(lostatc)codot/codot/container.py:293: error: Incompatible types in assignment (expression has type "Dict[<nothing>, <nothing>]", variable has type "None")  [assignment]
(lostatc)codot/codot/container.py:297: error: Unsupported target for indexed assignment  [index]
(lostatc)codot/codot/user_files.py:198: error: Need type annotation for 'config_values' (hint: "config_values: Dict[<type>, <type>] = ...")  [var-annotated]
(lostatc)codot/codot/user_files.py:226: error: Argument 1 to "isfile" has incompatible type "Optional[str]"; expected "Union[bytes, str, _PathLike[Any]]"  [arg-type]
(lostatc)codot/codot/utils.py:217: error: The return type of a generator function should be "Generator" or one of its supertypes  [misc]
(lostatc)codot/codot/utils.py:245: error: No overload variant of "next" matches argument type "str"  [call-overload]
(lostatc)codot/codot/utils.py:245: note: Possible overload variant:
(lostatc)codot/codot/utils.py:245: note:     def [_T] next(Iterator[_T]) -> _T
(lostatc)codot/codot/utils.py:245: note:     <1 more non-matching overload not shown>
Found 27 errors in 8 files (checked 12 source files)

[RRepo](pycrystem)pycrystem
(pycrystem)pycrystem/tests/test_signals/test_crystallographic_map.py:177: error: Name 'test_Crystallographic_Map_io' already defined on line 169  [no-redef]
(pycrystem)pycrystem/tests/test_physical/test_orientation_mapping_nonphys.py:41: error: Need type annotation for 'dp_sim_list' (hint: "dp_sim_list: List[<type>] = ...")  [var-annotated]
(pycrystem)pycrystem/tests/test_physical/test_orientation_mapping_nonphys.py:43: error: Need type annotation for 'library' (hint: "library: Dict[<type>, <type>] = ...")  [var-annotated]
(pycrystem)pycrystem/docs/source/conf.py:104: error: Need type annotation for 'exclude_patterns' (hint: "exclude_patterns: List[<type>] = ...")  [var-annotated]
(pycrystem)pycrystem/docs/source/conf.py:262: error: Need type annotation for 'latex_elements' (hint: "latex_elements: Dict[<type>, <type>] = ...")  [var-annotated]
Found 5 errors in 3 files (checked 54 source files)

[RRepo](meng89)wpi
(meng89)wpi/wpi/__init__.py:5: error: Need type annotation for '_modules' (hint: "_modules: Dict[<type>, <type>] = ...")  [var-annotated]
(meng89)wpi/wpi/main.py:21: error: Argument 1 to "join" has incompatible type "Optional[str]"; expected "Union[str, _PathLike[str]]"  [arg-type]
(meng89)wpi/wpi/main.py:416: error: Not all arguments converted during string formatting  [str-format]
Found 3 errors in 2 files (checked 12 source files)

